### ISSUE TITLE
个人简历页是否应该进一步分情况？

### ISSUE THREAD

**Issue by pigsboss** [xueruini/thuthesis#100]
目前thuthesis.dtx中的处理：
...
\ifthu@bachelor
  \newcommand{\thu@resume@title}{在学期间参加课题的研究成果}
\else
    \newcommand{\thu@resume@title}{个人简历、在学期间发表的学术论文与研究成果}
\fi
...
对于博士后研究报告来说，“在学期间”可能不合适，遂改成：
...
\ifthu@bachelor
  \newcommand{\thu@resume@title}{在学期间参加课题的研究成果}
\else
  \ifthu@postdoctor
    \newcommand{\thu@resume@title}{个人简历、发表的学术论文与科研成果}
  \else
    \newcommand{\thu@resume@title}{个人简历、在学期间发表的学术论文与研究成果}
  \fi
\fi
...
这样如何？
参考：http://postdoctor.tsinghua.edu.cn/bsh/UserFiles/File/yj.DOC

**Comment by alick** [comment]
:+1:

**Comment by alick** [comment]
帮忙看看上面的 commit 是否 OK？

**Comment by pigsboss** [comment]
赞！赞速度！
