### ISSUE TITLE
目录subsection的缩进不足两个字符

### ISSUE THREAD

**Issue by salviati6** [xueruini/thuthesis#103]
目录中section的缩进是对的（一个字符），subsection的缩进则不足两个字符，被格式审查老师指出来了，请问这个应该怎么改？虽然我也觉得这个毛病够无聊的……

**Comment by thuFangZhang** [comment]
同问，参见《学位论文写作指南》第2.2.5小节

![qq 20150418114143](https://cloud.githubusercontent.com/assets/11817948/7213825/f0b1e60e-e5bf-11e4-943a-47581cc93a28.png)

**Comment by salviati6** [comment]
发现问题了，应该把`thuthesis.dtx: 2067`改成
~~~latex
\renewcommand*\l@subsection{\@dottedtocline{2}{\ifthu@bachelor 1.6em\else 2.4em\fi}{3em}}
~~~
原来的研究生学位论文目录subsection缩进是2em, 而section缩进是1.2em，相差不到一倍。不知道是不是最近的学位论文格式要求有修订。

**Comment by alick** [comment]
格式要求还是2011年版的吧。听说是要修订，但今年夏天毕业应该还是沿用旧的。

**Comment by alick** [comment]
指南里说的二级节标题缩进2个字符，但给的word目录示例里只缩进了1.5个字符...

**Comment by alick** [comment]
我比较好奇的是为什么一个汉字和两个汉字对应 1.2em 和 2.4em。一般不是用 1em 和 2em 么？

**Comment by salviati6** [comment]
我感觉是因为“第 1 章”的“第”和“1”之间有空白，1em的话section编号就紧贴在“第”的右下方而不是上面的“1”对齐，视觉效果不好

**Comment by alick** [comment]
On 04/19/2015 09:20 AM, Fang Zhang wrote:
> 我感觉是因为“第 1 章”的“第”和“1”之间有空白，1em的话section编号就紧贴在“第”的右下方而不是上面的“1”对齐，视觉效果不好
> 

嗯，不过现在版本里也没有完全对齐。而word示例里也没对齐。我觉得可能还是得按 1em 来。@xueruini 薛神给点背景信息和意见？

**Comment by xueruini** [comment]
我觉得可以参考ctex的\ccwd，\CTEXindent定义。

2015-04-20 13:08 GMT+08:00 Alick Zhao <notifications@github.com>:

**Comment by xueruini** [comment]
https://github.com/xueruini/ctex-kit/blob/master/ctex/ctex.dtx#L1269
https://github.com/xueruini/ctex-kit/blob/master/ctex/ctex.dtx#L5042



2015-04-20 13:17 GMT+08:00 Ruini Xue <xueruini@gmail.com>:

**Comment by alick** [comment]
换用 `\ccwd`，见 #111，看一下效果？
