### ISSUE TITLE
theorem环境标题应为黑体

### ISSUE THREAD

**Issue by salviati6** [xueruini/thuthesis#104]
按照代码里面的说明(`thuthesis.dtx: 1694`)，定理字样使用黑体，正文使用宋体，thuthesis说明文档里看上去也是这样（3.7节）。但是目前版本（v4.8.1）的thuthesis编译出来的标题（“定理”、“引理”、“证明”等）不是黑体而是宋体的。把`thuthesis.dtx: 1698-1699`里面的两个`\rmfamily`删掉就好了：
```latex
\theorembodyfont{\songti\rmfamily}
\theoremheaderfont{\heiti\rmfamily}
```

MWE:
```latex
% !TeX program = pdflatex
\documentclass[doctor]{thuthesis}
\begin{document}
\begin{theorem}
这是一个测试。
\end{theorem}
\end{document}
```
测试环境：Windows 7 SP1 x64 + TeXlive 2014, pdflatex/xelatex

**Comment by alick** [comment]
测试一下上面的提交吧。`\rmfamily` 会影响中英文字体，`\heiti` 只影响中文字体。

**Comment by salviati6** [comment]
这一版没问题了~

还有就是“定理1.1：”既然里面有冒号了，后面最好就不要再附加空白了，现在看起来像是
```
定理1.1：  这是一个定理。
```
不是很好看。“证明”后面没有空格，后面的空白还是应该保留的。

**Comment by alick** [comment]
@salviati6 空白的问题，你再开个issue吧……
