### ISSUE TITLE
ntheorem相关的一个奇怪问题

### ISSUE THREAD

**Issue by alick** [xueruini/thuthesis#107]
当前版本的 thuthesis 示例文件编译是没有问题的。但是，当把 main.tex 里 \include{data/chap01} 一行注释掉后，重新编译，就会出现神秘的：

```
) [6] (./data/ack.tex [7]) [8] (./data/appendix01.tex

! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.36 \begin{mpdef}
                  
? 
```

[这里][gg]是一个相关的问题，但 thuthesis 木有用到 mathtools

[gg]: https://groups.google.com/forum/#!topic/comp.text.tex/qDU4Nz9s2z8

**Comment by beefable** [comment]
对，我也遇到过这个问题。

**Comment by alick** [comment]
进一步测试发现，当注释掉 main.tex 里  \include{data/chap01} 以及 附录的三行后，报同样的错误，但报错位置转移到 resume.tex 处。把 resume.tex 里 enumerate 环境删除后编译可以通过。


```
) [6] (./data/ack.tex [7]) [8] (./data/resume.tex

! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.14   \item
             Yang Y, Ren T L, Zhang L T, et al. Miniature microphone with si...

? 
```

**Comment by xueruini** [comment]
我好像不能重现这个问题。我用的是master HEAD。

**Comment by alick** [comment]
我刚把自己的 TeX Live 2014 升级到最新（frozen了，也不会有更新了），还是有这个问题。xelatex, Linux 下编译 master HEAD。

@xueruini 的环境是？

**Comment by alick** [comment]
哦，问题和上面错误信息之前的空参考文献警告有关。当我在 chap02.tex 里 `\cite{tex}` 制造个参考文献条目后，编译就正常了。看上去很像：

https://tex.stackexchange.com/questions/99404/using-references-to-a-bib-file-when-using-ieeetran

**Comment by alick** [comment]
所以不是模板的BUG……不过最好加一个友情提示吧
