### ISSUE TITLE
请问xelatex支持什么图片的格式

### ISSUE THREAD

**Issue by beefable** [xueruini/thuthesis#109]
我正在使用ThuThesis写论文，由于我的.jpg格式图片较多，所以有如下问题：

1. xelatex能支持.jpg图片吗？还是只支持.eps格式图片？如果是后者，有什么好的方式
转化格式吗，因为据我以前用visio图片转PDF再转eps图片的经验，.eps格式的图片往往非常大，不知道有什么较好的方法。

2. 如果只能使用pdflatex的话，我注意到ThuThesis说明文档中提到了中文字体配置会出现问题，但是我好像使用pdflatex编译过模板，并没有出什么问题。所以，对于这个问题我比较迷惑。

谢谢各位~

**Comment by xueruini** [comment]
2015-04-22 16:40 GMT+08:00 beefable <notifications@github.com>:

> 我正在使用ThuThesis写论文，由于我的.jpg格式图片较多，所以有如下问题：
>
>    1.
>
>    xelatex能支持.jpg图片吗？还是只支持.eps格式图片？如果是后者，有什么好的方式
>    转化格式吗，因为据我以前用visio图片转PDF再转eps图片的经验，.eps格式的图片往往非常大，不知道有什么较好的方法。
>
>
xelatex支持jpg。

**Comment by beefable** [comment]
谢谢~
1.能支持.jpg就好了；
2.ctex是基于MikTex加入中文支持的套装吧，我是下载的texlive2014套装，也装好了吗？

**Comment by alick** [comment]
1. xelatex 原生支持 JPG、PDF、PNG 等格式图片，新版本 tex 发行版通过自动引用 epstopdf 支持 EPS 图片
2. 是的。TeX Live 2014 中文支持也没问题。
