### ISSUE TITLE
Get userguide compiled.

### ISSUE THREAD

**Issue by xueruini** [xueruini/thuthesis#113]
- Find the required figures.
- Remove explicit `CJK` requirement.

**Comment by xueruini** [comment]
@alick 
xelatex编译powerdot有问题，格式全部错乱。可以用这个小例子试一下：

```latex
\documentclass{powerdot}
\usepackage{ctex}

\begin{document}
\begin{slide}{Slide 1}
  Contents. 中国
\end{slide}

\section{Introduction}
\begin{slide}{Slide 2}
  More content.
\end{slide}
\end{document}
```

现在要想编译userguide，得用早先的中文字体配置的套路，我手头已经没有环境了。要么，我们就切换到beamer。

**Comment by alick** [comment]
我觉得可以切换到 beamer。beamer 有一定程度的 powerdot 兼容设置，可以减少代码迁移成本。

2015-05-02 11:38 GMT+08:00 Ruini Xue <notifications@github.com>:

**Comment by xueruini** [comment]
那就先放在这里吧，慢慢弄成beamer。

**Comment by alick** [comment]
@bigeagle

**Comment by xueruini** [comment]
转换的工作量还是不小。

**Comment by xueruini** [comment]
thuthesis.pdf is adequate.

**Comment by alick** [comment]
哦。当时的想法是有个幻灯片形式的方便在图书馆讲座讲😅

**Comment by xueruini** [comment]
orz。。。没想到这个用途



Best

-- ruini

**Comment by alick** [comment]
现在讲座用的是这个：https://github.com/tuna/thulib-latex-talk 其实从原版里“借”了很多东西。以后的讲稿基于它演进也好。

**Comment by xueruini** [comment]
excellet!
