### ISSUE TITLE
参考文献中逗号过多的问题

### ISSUE THREAD

**Issue by beefable** [xueruini/thuthesis#115]
我在使用bibtex编译参考文献的时候出现了如下问题：
Too many commas in name 1 of "Georg T. Becker,Francesco Regazzoni,Christof Paar,Wayne P. Burleson" for entry Georg-Stealthy
说逗号过多，请问下大家遇到过这种问题吗？是怎么解决的呢？

**Comment by alick** [comment]
分割作者名用and，不是逗号
2015年5月3日 下午6:04于 "beefable" <notifications@github.com>写道：

**Comment by beefable** [comment]
明白了，谢谢~
