### ISSUE TITLE
询问一下使用模板写的论文的查重问题

### ISSUE THREAD

**Issue by beefable** [xueruini/thuthesis#116]
因为是用latex写的，所以查重的时候，如果遇到需要粘贴内容的，有点不方便。

请问各位是怎么查重的呢？

**Comment by alick** [comment]
“需要粘贴内容的”是什么东西？

**Comment by alick** [comment]
查重时就交 PDF 吧？

**Comment by beefable** [comment]
很多数据库，比如万方和PaperPass都需要粘贴内容，如果是word写的就比较方便。

恩，学校统一查重是交PDF，我是想自己先测试一下。

如果是用中国知网查重的话好像可以交PDF，但是这种的比较贵。

我已经粘贴完测过了。。。。

**Comment by tl3shi** [comment]
pdf用word打开把识别的内容粘贴查重就行吧~

**Comment by beefable** [comment]
能用word打开PDF？

**Comment by alick** [comment]
有一些（可能收费的）应用可以将 PDF 格式转成 Word 格式，不保证格式完全一致，但对于复制粘贴应该足够。

还有工具提取 PDF 中的文字转成文本文件（TXT），对于复制粘贴可能也够用。

我个人感觉没必要花钱自行查重。

2015-05-04 11:34 GMT+08:00 beefable <notifications@github.com>:

**Comment by beefable** [comment]
OK，了解

**Comment by tl3shi** [comment]
@beefable 我记得2010的office就可以吧~  至少我本机装的2013的office，是可以直接打开编译好的pdf的，部分公式识别有问题，一般文字描述是没有问题的。
