### ISSUE TITLE
构造三线表时出现问题

### ISSUE THREAD

**Issue by beefable** [xueruini/thuthesis#119]
出现的问题是：

chap4.tex
623
Extra alignment tab has been changed to \cr.
<recently read> \endtemplate 
                             
l.623       {\heiti 操作} & {\heiti $V_{SG}$} &

我的代码是：
\begin{table}[htb]
  \centering
  \begin{minipage}[t]{0.8\linewidth} 
  \caption{编程和读取操作时的参数}
  \label{tab:ParametersForPandR}
    \begin{tabular*}{\linewidth}{lp{10cm}}{lcccc}
      \\\toprule[1.5pt]
      {\heiti 操作} & {\heiti $V_{SG}$} & {\heiti $V_{CG}$} & {\heiti $V_{D}$} & {\heiti $V_{S}$} \\\midrule[1pt]
      Program & 16 & 0 & 15.5 & Hiz \\
      Read & 3.3 & 1.8 & BL & 0\\
      \bottomrule[1.5pt]
    \end{tabular*}
  \end{minipage}
\end{table}

这个问题似乎是指列数有问题，但是不知道怎么解决，求助。

**Comment by beefable** [comment]
解决问题了，但是我不清楚原因，可能和minipage等环境有关，其实用简单的表格环境，加上\toprule，\midrule等指令就行了。下面是我改好后的代码：

\begin{table}[htbp]
\centering
\caption{编程和读取操作时的参数}
\label{tab:ParametersForPandR}

\begin{tabular}[c]{lcccc}
\toprule[1.5pt]
{\heiti 操作} & $V_{SG}$ & $V_{CG}$ & $V_{D}$ & $V_{S}$ \\ \midrule[1pt]
Program & 16& 0 & 15.5 &Hiz \\ 
Read    & 3.3 & 1.8 &BL & 0   \\ 
\bottomrule[1.5pt]
\end{tabular}
\end{table}

**Comment by alick** [comment]
> `begin{tabular}{\linewidth}{lp{10cm}}{lcccc}`

你是想用 tabularx 吧？
