### ISSUE TITLE
编译出来的pdf中的中文字符不能正常复制

### ISSUE THREAD

**Issue by Garfee0o0** [xueruini/thuthesis#120]
RT，生成的文档中除了标题，所有中文字符都不能复制。
所以论文查重系统认不得 ┑(￣Д ￣)┍……
用的win8系统，编辑器TexStudio，UTF-8编码。
另外赵涛让我附上字体文件 zhfonts.txt: http://ur1.ca/kci5g

**Comment by alick** [comment]
带文件路径的列表：http://paste.fedoraproject.org/220948/14210921/

**Comment by alick** [comment]
应该是有两个中易宋体导致的问题。试着删除 simsum_0.ttc

**Comment by alick** [comment]
原来不只的两个，还有第三个（D: 盘的 simsun.ttf）。删除了就好了 :)
