### ISSUE TITLE
paralist -> enumitem?

### ISSUE THREAD

**Issue by alick** [xueruini/thuthesis#123]
看起来 enumitem 可定制性更好些，paralist 的段内列表、compact列表 enumitem 现在也都支持了。考虑将宏包依赖切到 enumitem?

**Comment by xueruini** [comment]
没问题，搞之。

btw，`enumitem`最新版是2011年发布的，`paralist`是2013年。

**Comment by alick** [comment]
enumitem 维护者看起来（在 tex.sx 上）还活跃

**Comment by xueruini** [comment]
这两个现在都用到了： https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx#L1177-L1178

这里把paralist的更换一下就可以：
https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx#L1572-L1577

**Comment by alick** [comment]
所言极是

2015-11-15 22:44 GMT-06:00 Ruini Xue <notifications@github.com>:

> 这两个现在都用到了：
> https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx#L1177-L1178
>
> 这里把paralist的更换一下就可以：
> https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx#L1572-L1577
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xueruini/thuthesis/issues/123#issuecomment-156914323>.
>



-- 
Regards,
Alick
