### ISSUE TITLE
texlive 2015 不能通过编译

### ISSUE THREAD

**Issue by dongfengweixiao** [xueruini/thuthesis#126]
texlive 2015 不能通过编译

**Comment by alick** [comment]
嘛错误信息？

texlive 2015 还没正式发布呢。

**Comment by dongfengweixiao** [comment]
最近在测试texlive2015

\ifCTEX@nofonts

这个和ctex升级到2.0有关。

**Comment by alick** [comment]
与 ctex 2.0 兼容性已经修复了 #92 。请用最新版本(master HEAD)测试下。

**Comment by hotpxl** [comment]
同样表示不能编译

> ! Illegal unit of measure (pt inserted).
> <to be read again>
>                    \global
> l.61 \chapter{hh}

正文第一个`\chapter`就会这样

**Comment by hotpxl** [comment]
已经确定是`thuthesis.dtx:1580`的问题。。奈何不会写latex不知道怎么fix。。。

**Comment by hotpxl** [comment]
忘了说环境。。。mactex 2015。。

**Comment by dongfengweixiao** [comment]
话说我倒是想要帮忙修补来着，但是只能说thuthesis的模板写的实在是太鬼斧神工。

**Comment by hotpxl** [comment]
+1

**Comment by dongfengweixiao** [comment]
其实理论上说thuthesis倒是不应该因为texlive的升级导致太大的问题：thuthesis本身使用了大量的tex的代码，所以对于很多的宏包的依赖都很少。可是，它就是那么真实的发生了。。。。

**Comment by hotpxl** [comment]
貌似是从perpage里拿的代码 而perpage也挂了。

**Comment by xueruini** [comment]
干掉这部分代码，直接\RequirePackage{perpage}
保留\MakePerPage{footnote}，看看能过么

**Comment by hotpxl** [comment]
赞 解决了。但是之前用\usepackage{perpage}并没有什么卵用..不过行首缩进以及缩进长度好像也挂了，现在是手动搞的

**Comment by MaskRay** [comment]
texlive 2015
```! Illegal unit of measure (pt inserted).
<to be read again> 
                   \global 
l.6 \chapter{引言}
```
注释 c721bb880d9bdaf9397e41d516a12f9241f34b7d (6月7日) 1577~1591行可以编译通过，但会出现 @hotpxl 的结果，行首缩进长度出问题。

回退到 texlive 2014，可以正常编译。

**Comment by alick** [comment]
试试把 perpage 相关行换成 \RequirePackage[perpage]{footmisc}？

perpage 影响行首缩进感觉也挺诡异的。建议在不使用 thuthuesis 模板类的情况下（例如在使用article与ctexart文档类时）也测试下。

texlive 2015 正式发布了，我最近升级下。

**Comment by xueruini** [comment]
我也升级一下

2015-06-16 16:13 GMT+08:00 Alick Zhao <notifications@github.com>:

**Comment by alick** [comment]
hotfix: alick@556a24

1. footmisc is actually used by default, so I just use it.
2. 行首缩进的问题来自于 ctex 2.0 兼容性，与无法编译的问题应该无关。

**Comment by mengfl05** [comment]
1. 行首缩进距离的问题是因为 nocap 选项含义变掉了，相当于设置了 scheme=plain 变成了英文版式，加上 scheme=chinese 就好了
2. 首段缩进的问题不知道为啥 ctex 宏包没搞定，按理说是可以的，而且在 thuthesis.cls 里面写上和 ctex 宏包一样的代码就能用，不知道为啥宏包里面的代码没起作用
3. 而且，章标题后面的首段是正常的，节标题后面的不对

**Comment by alick** [comment]
@mengfl05 首行缩进问题是 ctex 2.0 的一个（有意的）不兼容情况 https://github.com/CTeX-org/ctex-kit/issues/194

**Comment by mengfl05** [comment]
@alick 谢谢~你这个提醒我了，确定就是 ctex 没有载入 indentfirst，现在的行为都是 \@startsection 这个决定的，参考一下我在水木上发的帖子~

但是这个也还是怪怪的，按照这里 [2994585](https://github.com/CTeX-org/ctex-kit/commit/2994585e3863c5323ede3ca8064dd0d7d53b5e6d) 以及 ctex 随 texlive 2015 发布版本的手册的说法，indentfirst 在 scheme=chinese 及标准文档类公用的时候，是会载入的...

**Comment by mengfl05** [comment]
@alick 呃，折腾一番之后的结果，应该就是 ctexbook 并没有载入 indentfirst 宏包，这时候是否首段缩进是 \@startsection 命令中的 beforeskip 参数的正负控制的，在后面的 \section 等命令的定义那里改改也就好了

ctex 宏包现在貌似并不喜欢载入 indentfirst 宏包，而是使用上面的做法，现在我也晕晕的不知道它到底什么时候会载入...不过反正觉得没有载入的话就去改 beforeskip 或者手动载入就好了...更多的参见水木的帖子...
http://www.newsmth.net/nForum/article/TeX/324095?s=324095

**Comment by alick** [comment]
> thuthesis 这里是不是也可以参考这种做法，修改一下 \section 几个命令的定义就好了，不一定要引入 indentfirst 宏包

感觉这是个好主意。还能保留和 ctex 旧版本（也意味着 TeX Live 2014）的兼容性。

长远来看，用 ctex 2.0 的 `\ctexset` 更好。

**Comment by alick** [comment]
谁有空的话把我的那个 hotfix: alick/thuthesis@556a24f 合并了吧。#149, #153 都是这个 issue 的 duplicate

**Comment by alick** [comment]
hotfix 未完成的东西：弃用 indentfirst 宏包，改为直接修改 section 系列命令的 skip

或者，现在兼容 TeX Live 2014 的必要性也不大了，直接用 `\ctexset` 也行。

**Comment by xueruini** [comment]
给个PR吧，呵呵。

**Comment by alick** [comment]
看谁有工夫吧。我的话可能得到周末了。

On Thu, Nov 12, 2015 at 9:57 PM, Ruini Xue <notifications@github.com> wrote:
> 给个PR吧，呵呵。
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Regards,
Alick
