### ISSUE TITLE
LaTeX编译不了，在字体处出现undefined control sequence

### ISSUE THREAD

**Issue by edcwconan** [xueruini/thuthesis#127]
在latex main的命令时出现这种，XeLaTeX可以正常编译，但是无法生成dvi文件，字数统计就很困难

**Comment by alick** [comment]
请贴一下 undefined control sequence 附近的输出信息（错误信息）。

字体统计可以用：

1. `texcount -ch -inc main.tex`
2. pdf 转换成 txt/rtf/word，然后统计字数。

**Comment by edcwconan** [comment]
!Undefiend control sequence.
<recently read>\lishu
l.38 \makecover
?

**Comment by alick** [comment]
没有 `\lishu` 隶书字体命令。系统里有隶书字体 simli.ttf 吗？操作系统什么版本？

2015-05-19 10:23 GMT+08:00 edcwconan <notifications@github.com>:

**Comment by edcwconan** [comment]
Win7，有这个
不仅仅是这里，编译忽略这一error之后其他字体像\heiti这些也报类似的error。
基本上LaTeX编译就是中文字体的error

**Comment by alick** [comment]
有些奇怪。ctex 宏包版本？
编译一个简单的中文测试文件会报错吗？参考 http://www.newsmth.net/nForum/#!article/TeX/282515
中问题9回答

2015-05-19 15:05 GMT+08:00 edcwconan <notifications@github.com>:

**Comment by edcwconan** [comment]
之前我发现ctex版本太旧xecjk支持比较差就卸了换成TeXLive。
我刚才latex了一篇开题时候的文献翻译，是可以成功编译的，里面用的应该是ctex宏包而且没有指定字体。xecjk的没有尝试过

**Comment by alick** [comment]
中文处理目前推荐的还是 xelatex 编译。不过 latex+dvipdfmx 的方式应该也是支持的。

我这里用latex+dvipdfmx方式编译master分支上最新的 main.tex 是可以得到 pdf 的。环境是 Linux (Fedora 20), TeX Live 2014.

你可能需要花些工夫得到一个最小示例文件，让其他人能重现问题。

**Comment by edcwconan** [comment]
好的，我尝试一下，我是Win7下的TeXLive2014

**Comment by edcwconan** [comment]
修改了一下，把nofonts改成winfonts就能编译通过了，但是有些xelatex上没有的bad box出现了

**Comment by alick** [comment]
@edcwconan 我怀疑你在使用某个旧版本thuthesis。github里master分支的最新版是不需要指定nofonts/winfonts 选项的（指定了也没效果）。

**Comment by edcwconan** [comment]
我用的是CTAN提供的，Git上的没试过，但是我试过在ShareLaTeX上在线编译，也能通过。。。TeXLive2014的pdflatex死活过不了，但是一改fonts就能过了。。。

**Comment by alick** [comment]
CTAN 上是 4.8.1，github上有不少更新了。
pdflatex, latex+dvipdfmx 下只能用 （ctex文档类的） winfonts 选项，这是 thuthesis 依赖的ctex文档类决定的。

**Comment by edcwconan** [comment]
我再去试试。。。

**Comment by edcwconan** [comment]
本科生对附录A里的文献调研部分的字体字号的要求好像没有体现。。。

**Comment by alick** [comment]
嗯，是一个已知问题，不过貌似忘了报issue。有空的话新开个issue？

**Comment by edcwconan** [comment]
还是感谢师兄做了这么方便的模板。。。

**Comment by alick** [comment]
主要还是要谢 @xueruini 神
