### ISSUE TITLE
dvipdfmx 方式编译得到的pdf里子图位置不对

### ISSUE THREAD

**Issue by alick** [xueruini/thuthesis#128]
子图跑偏了。

**Comment by mengfl05** [comment]
图片是用的 eps 文件？

**Comment by xueruini** [comment]
已经很久没用dvi2xxx 系列来生成pdf了。

**Comment by alick** [comment]
I'm OK for dropping support of dvipdfmx.

**Comment by xueruini** [comment]
> I'm OK for dropping support of dvipdfmx.

提了几个PR，帮忙扫一眼。都是小修改。

**Comment by alick** [comment]
drop 掉吧，然后就可以关了。
