### ISSUE TITLE
zhfonts.py prompt order of different font families varys across different runs

### ISSUE THREAD

**Issue by alick** [xueruini/thuthesis#132]
I think it might seem weird to users...

**Comment by xueruini** [comment]
I am afraid they are sorted before printing.

**Comment by alick** [comment]
Ah... the order is fixed with Python 2, and random with Python 3 here.

**Comment by xueruini** [comment]
> the order is fixed with Python 2, and random with Python 3 here.
why?

**Comment by alick** [comment]
I guess we need OrderedDict, rather than regular dict.

https://docs.python.org/3/library/collections.html#collections.OrderedDict

https://docs.python.org/2/library/collections.html#collections.OrderedDict

2015-06-02 7:46 GMT+08:00 Ruini Xue <notifications@github.com>:
