### ISSUE TITLE
本科生附录A（文献调研或文献翻译）格式未设定

### ISSUE THREAD

**Issue by edcwconan** [xueruini/thuthesis#135]
appendix环境下没有设定，另外由于调研或者翻译在开题过程已经完成，所以可能直接input进来比较好

**Comment by edcwconan** [comment]
能不能现提供一下手动设定的方案？
--------------------------------------------------------------------------------------------------------------------------------
附录A：为外文资料的调研阅读报告或书面翻译。调研阅读报告需附参考文献；书面翻译需注明外文资料原文的索引。标题为“外文资料的调研阅读报告或书面翻译”，用黑体小三号字，段前30pt，段后20pt，行距20pt。内容部分采用宋体小四号字，行距用固定值20pt，段前后0pt。
调研阅读报告的参考文献（或书面翻译对应的外文资料的原文索引）标题用宋体小四号字，段前20pt，段后6pt，行距20pt。内容用宋体五号字，取固定行距17pt，段前后3pt。

**Comment by xueruini** [comment]
你的意思是不是：给翻译/调研报告生成自己的参考文献？

**Comment by edcwconan** [comment]
不是，那个我在别的issue上看到过，用一些chaperbib什么的包可以或者手动item。
段前段后这些环境设置反倒比较麻烦

**Comment by xueruini** [comment]
那你的意思是：模板当前appendix的格式跟规定不一致？

**Comment by edcwconan** [comment]
是的吧。
因为appendixA和appendixB的要求不一致，但是只有统一的appendix格式，所以应该是有未实现的环境。

**Comment by alick** [comment]
我当年手工写的，暂供参考

```
\chapter{外文资料的书面翻译}

%TITLE need adjustments
\vspace*{5bp}
{\centering \song\xiaosi 用于多小区多天线无线系统的协作波束成形

}
\vspace*{-10bp}

\section*{摘要}
```

**Comment by edcwconan** [comment]
谢谢~
