### ISSUE TITLE
感谢章节的查重问题

### ISSUE THREAD

**Issue by zhou13** [xueruini/thuthesis#138]
感谢 \thuthesis，它的存在让我的论文写作轻松自在了许多，让我的论文格式规整漂亮
    了许多。

这一内容在毕业论文中重复无数次，建议添加警告提示修改以避免在论文查重上出现不必要的麻烦。

**Comment by xueruini** [comment]
这个被学校查到也不错 :smile:

**Comment by ahyangyi** [comment]
哈哈哈哈哈哈哈，赞！

**Comment by edcwconan** [comment]
师兄这个只能忍痛删掉了啊。。。手动感谢。。。
