### ISSUE TITLE
本科生毕业论文封面与授权说明另起一页？

### ISSUE THREAD

**Issue by wuuuuuud** [xueruini/thuthesis#140]
现在用xelatex编译后，封面和授权说明都不会空一面，双面打印时需要分开打印，不知道是本身设计成这样还是我的配置有问题？

**Comment by alick** [comment]
thuthesis 配置如此，学校给的 word 示例也是如此。

在 2015年6月23日 下午12:24，wuuuuuud <notifications@github.com>写道：

**Comment by wuuuuuud** [comment]
嗯，明白了。
不过没有留空白页确实不太方便，算了我自己改自己的模板吧。

**Comment by alick** [comment]
嗯，打印时得（告诉打印店）手工处理一下。

你看不麻烦的话，给模板加个 printready 选项（默认不启用），启用时加上空白页？欢迎发 Pull Request

2015-06-23 14:15 GMT+08:00 wuuuuuud <notifications@github.com>:
