### ISSUE TITLE
本科生论文中插图索引和表格索引的行间距不正确

### ISSUE THREAD

**Issue by Suniver** [xueruini/thuthesis#144]
根据《本科生综合论文训练指南》，插图索引与表格索引的要求是固定行距20pt，段前6pt，段后0pt。然而Thuthesis排版出来的间距明显偏小，大概缺了那段前6pt的距离。

        上午给赵师兄发邮件后，他建议在thuthesis.cls中做如下修改：

修改模板(cls)文件中的
\renewcommand*\l@figure{\@dottedtocline{1}{0em}{4em}}
一行为
\renewcommand*\l@figure{\vspace*{6bp}\@dottedtocline{1}{0em}{4em}}

        具体是不是6bp，这个还有待调整。然而这样做之后，会出现索引页无法正常分页的情况，插图索引的文字内容会一直延伸到页面最底端，遮住页码，完全超出了档心部分。

        这个问题还没有得到解决。

        本想用图片说明，但我是github新手，传图总是失败，不知道为什么。

**Comment by Suniver** [comment]
![2](https://cloud.githubusercontent.com/assets/13075622/8391518/b8f8f4f8-1cf8-11e5-90f7-2b90d62eeb52.png)
上图中，左侧是正确的行距示例，右侧是thuthesis排版出来的效果。

![1](https://cloud.githubusercontent.com/assets/13075622/8391522/d1bbfbb6-1cf8-11e5-838b-0b5f3a403609.png)
上图显示的是文字溢出档心的问题。

**Comment by fengzee-me** [comment]
我还注意到一个问题，似乎索引里面没有能够正确地自动产生中英文之间的空格（我自己习惯在源码里也加空格了，所以自己的论文里没有发现问题）。

（另说句题外话，以我的排版审美，我觉得目前 ThuThesis 产生的行间距更漂亮呢。反正本科格式审查老师也远远注意不到这么细节的地方，至少我们系是这样……）

**Comment by aixlx** [comment]
这么巧。。我也在搞这个问题，也是给 Alick 发了邮件。。见这个：

https://github.com/xueruini/thuthesis/compare/master...alick:fix-bachelor-lists

**Comment by Suniver** [comment]
我也认为20磅的行距会更漂亮一些。

我们系教务的老师大概是从太上老君的炉子里钻出来的吧。

**Comment by Suniver** [comment]
据反馈，aixlx提到的方法不存在索引文字溢出档心的问题了。
赛高！

**Comment by xueruini** [comment]
> 似乎索引里面没有能够正确地自动产生中英文之间的空格

你是`xelatex`么？正文里面至少的有个space或者~。

**Comment by xueruini** [comment]
> 这么巧。。我也在搞这个问题，也是给 Alick 发了邮件。。见这个：

改`\dottedtocline`可能更好一些。

**Comment by alick** [comment]
你们调整具体数值吧，把调好通过审查的反馈回来，多谢。

**Comment by Suniver** [comment]
\addvspace{6pt} 的数值应该没问题，至少目前审核通过了，我的肉眼也看不出问题来。
另外，bp是什么单位？

**Comment by alick** [comment]
WORD 里的 6pt 对应 TeX 里的 6bp。参见：
https://tex.stackexchange.com/questions/20208/latex-commands-for-a-specific-page-format/20215#20215

在 2015年6月30日 下午4:23，Suniver <notifications@github.com>写道：

**Comment by alick** [comment]
@xueruini 从语义上讲，可能改 `\l@X` (X=figure,table) 比 `\dottedtocline` 好，tocloft 宏包也是改的 `\l@X`。

**Comment by alick** [comment]
PR: #141

**Comment by xueruini** [comment]
> @xueruini 从语义上讲，可能改 \l@X (X=figure,table) 比 \dottedtocline 好，tocloft 宏包也是改的 \l@X。

你是对的，我开始想错了，`\dottedline`影响面有点大，不如`\addvspace`灵活。

**Comment by aixlx** [comment]
这个问题好像之前就提到过，https://github.com/xueruini/thuthesis/issues/68

**Comment by alick** [comment]
@aixlx 赞。我都忘了这事儿了……
