### ISSUE TITLE
封面综合论文训练需要加粗。

### ISSUE THREAD

**Issue by aixlx** [xueruini/thuthesis#145]
封面的“综合论文训练”需要加粗。

教务所给的模板：
![cover](https://cloud.githubusercontent.com/assets/7615494/8391710/6139bf62-1cfe-11e5-9d02-045568cc8d33.png)

我是在 thuthesis.dtx 2437行加了\textbf
```
      %{\xiaochu\heiti\ziju{0.5}\thu@bachelor@subtitle}
      \textbf{{\xiaochu\heiti\ziju{0.5}\thu@bachelor@subtitle}}
```

不知道是不是不同系的模板不一样？我是工物系···

**Comment by xueruini** [comment]
黑体加粗其实没什么意义。

**Comment by aixlx** [comment]
是的。。。不过我的导师给我看论文格式的时候说：你这个。。没有论文示例中“黑”啊···冏

**Comment by alick** [comment]
我觉得黑体加粗很难看……

**Comment by mengfl05** [comment]
这...字体没有设置加粗的黑体的话，textbf 也没什么效果的呀...

**Comment by aixlx** [comment]
但确实有效果呀。。上 没加粗 下 加粗
![no](https://cloud.githubusercontent.com/assets/7615494/8395987/49558748-1dc4-11e5-8c59-bab209fdcb07.PNG)
![yes](https://cloud.githubusercontent.com/assets/7615494/8395988/495587a2-1dc4-11e5-991d-2f5b65d1561a.PNG)

**Comment by mengfl05** [comment]
这是哪个发行版编译的？

**Comment by aixlx** [comment]
开发版。。一直在用开发版。。。
Win7 64 + Texlive2014 + PDFtexify(WinEdt)

**Comment by mengfl05** [comment]
...SimHei 和 AdobeHeiti 还可以这样么...

**Comment by mengfl05** [comment]
试了试，应该是 xeCJK 和 ctex 宏包做了一定的伪粗体或者加载其他字体的支持，以下代码就没有效果，这时候应该是单纯的只用了两种字体

\documentclass{article}

\usepackage{xeCJK}

\setCJKmainfont{simsun.ttc}
\setCJKsansfont{simhei.ttf}

%\setCJKmainfont{SimSun}

\begin{document}
  汉字汉字
  
  \textbf{汉字汉字}
  
  \textsf{汉字汉字}
  
  \textsf{\textbf{汉字汉字}}
\end{document}

**Comment by lich1288** [comment]
论文电子版因为这六个字未加粗而不通过。。。

**Comment by zepinglee** [comment]
windows 下 ctex 默认配置的中易黑体没有粗体字重，即使 `\sffamily\bfseries` 也没有粗体效果，所以解决方案有：
1. 手动配置有粗体字重的黑体（或者换到 Mac 下编译）
2. 中易黑体启用伪粗

@xueruini 要不要考虑后者

**Comment by xueruini** [comment]
> 中易黑体启用伪粗
> @xueruini 要不要考虑后者

指南有没有联系方式？兼容这种诡异的要求就是在吃苍蝇
