### ISSUE TITLE
Readme中的一个小错误。

### ISSUE THREAD

**Issue by aixlx** [xueruini/thuthesis#146]
https://github.com/xueruini/thuthesis/blob/master/README.md 

Readme中的一个小错误。
![cover](https://cloud.githubusercontent.com/assets/7615494/8391733/14557136-1cff-11e5-8b25-93a3519018c0.png)

**Comment by alick** [comment]
眼好尖！

**Comment by aixlx** [comment]
发现好久了···强迫症，因为刚接触摸板时复制进去运行不成功···

**Comment by xueruini** [comment]
:+1:
