### ISSUE TITLE
TexLive2015 编译 thuthesis 模板出错

### ISSUE THREAD

**Issue by jiangning198511** [xueruini/thuthesis#149]
各位大牛，我最近用Texlive 2015（WIN-8 系统） 编译thuthesis(从Git上下载的最新版本) 模板，发现一直报错无法通过，希望大家能够解答一下。
1. 用pdfLatex 编译，报错信息为：
!undefined control sequence
\setmainfont{Times New Roman}
我的理解是没找到字体文件(不一定正确)。请问应该如何解决？

2. 用XeLatex 编译，报错信息为：

!undefined control sequence
\ifCTEX@nofonts

这个问题在网上有人提过，是与CTEX库有关，但网上写的我没看懂，不知道如何修改，能否详细讲一下修改过程。

再次感谢

软件：TexLive 2015 
系统：Win-8
模板：thuthesis

**Comment by jiangning198511** [comment]
我下载了最新的模板，上面的第二个问题解决了，但出现了新的报错，不知道能否解答一下。谢谢

\EU1/FangSong(0)/m/n/16.06 系 别

Underfull \hbox (badness 10000) detected at line 37
\EU1/FangSong(0)/m/n/16.06 专 业

Underfull \hbox (badness 10000) detected at line 37
\EU1/FangSong(0)/m/n/16.06 姓 名
[1] [2] [1] [2] (./main.toc) (./data/denotation.tex [3] [4]) [5]
(./data/chap01.tex
! Illegal unit of measure (pt inserted).
<to be read again> 
                   \global 
l.7 \chapter{带 English 的标题}
                                   
?

**Comment by xueruini** [comment]
用 `xelatex` 编译看看。

不知道会不会是新版本ctex的兼容性问题。

**Comment by jiangning198511** [comment]
我是用的XELATEX编译的，

**Comment by jiangning198511** [comment]
\EU1/FangSong(0)/m/n/16.06 系 别

Underfull \hbox (badness 10000) detected at line 37
\EU1/FangSong(0)/m/n/16.06 专 业

Underfull \hbox (badness 10000) detected at line 37
\EU1/FangSong(0)/m/n/16.06 姓 名
[1] [2] [1] [2] (./main.toc) (./data/denotation.tex [3] [4]) [5]
(./data/chap01.tex
! Illegal unit of measure (pt inserted).
<to be read again> 
                   \global 
l.7 \chapter{带 English 的标题}
                                   
? 

这是PDFLATEX的错误

**Comment by jiangning198511** [comment]
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\\' on input line 37.

! Undefined control sequence.
<recently read> \lishu 
                       
l.37 
     
? 

这是PDFLATEX 的错误

**Comment by xueruini** [comment]
> 我是用的XELATEX编译的，

编译错误是什么？

**Comment by jiangning198511** [comment]
Package hyperref Warning: old toc file detected, not used; run LaTeX again.

(./data/denotation.tex [3] [4]) [5] (./data/chap01.tex
! Illegal unit of measure (pt inserted).
<to be read again> 
                   \global 
l.7 \chapter{带 English 的标题}
                                   
?

**Comment by jiangning198511** [comment]
Underfull \hbox (badness 10000) detected at line 37

\EU1/FangSong(0)/m/n/16.06 专 业


Underfull \hbox (badness 10000) detected at line 37

\EU1/FangSong(0)/m/n/16.06 姓 名

[1] [2] [1] [2] (./main.toc) (./data/denotation.tex [3] [4]) [5]

(./data/chap01.tex

! Illegal unit of measure (pt inserted).

<to be read again>

\global

l.7 \chapter{带 English 的标题}

?

2015-08-17 15:04 GMT+08:00 Ruini Xue <notifications@github.com>:

**Comment by mengfl05** [comment]
看这里 [123](https://github.com/xueruini/thuthesis/issues/126) 关于 footmisc 的部分

**Comment by jiangning198511** [comment]
感谢回复，用了修改的模板，通过了编译，再次感谢

**Comment by mcf171** [comment]
我也碰到这个错误
! Illegal unit of measure (pt inserted).

\global 
l.7 \chapter{带 English 的标题}
用了修改的模板是什么意思？
