### ISSUE TITLE
图形名称变成了黑体，应该在哪里改正回来？

### ISSUE THREAD

**Issue by zhangchao06** [xueruini/thuthesis#150]
我之前运行时，图形名称文字都是好好的，但是不知道昨天晚上动了哪里，导致现在画出的图形下面的名称字体不对。不知道修改哪里可以改正好？

![image](https://cloud.githubusercontent.com/assets/10230543/9702011/14bf4aa6-547d-11e5-810b-0aefbfd58be4.png)
![image](https://cloud.githubusercontent.com/assets/10230543/9702013/239f3ae0-547d-11e5-91b1-35d730a4a140.png)

**Comment by xueruini** [comment]
diff 一下？

2015-09-06 9:53 GMT+08:00 chao zhang <notifications@github.com>:

**Comment by zhangchao06** [comment]
恩，发现了。是因为我加了：
\usepackage{multicap}
把这个注释掉就好了，虽然不知道为啥加了这个包就会造成这种结果....

**Comment by alick** [comment]
因为这个包也是定制图片/表格标题的……

**Comment by alick** [comment]
你想用这个包实现什么效果？看看能不能用其他方法来做。
