### ISSUE TITLE
Latexmk: Bad options specified

### ISSUE THREAD

**Issue by bloodmoon1988** [xueruini/thuthesis#151]
Hello, 

我编译遇到了一个问题：

OS: Fedora 15
安装了tex-live, latexmk. 错误信息如下：

[root@ExpServer thuthesis-master]# make all
latexmk -xelatex thuthesis.dtx
Latexmk: -xelatex bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
make: *** [thuthesis.pdf] Error 10
[root@ExpServer thuthesis-master]#

我应该怎么解决呢？谢谢！

**Comment by xueruini** [comment]
latexmk --help 看看有哪些选项。你的texlive是哪一版本？

**Comment by bloodmoon1988** [comment]
WOW, 很多选项，如下：

texlive是刚刚安装的，应该是2015版吧。

[root@ExpServer thuthesis-master]# latexmk --help
Latexmk 4.30a: Automatic LaTeX document generation routine

Usage: latexmk [latexmk_options] [filename ...]

  Latexmk_options:
   -aux-directory=dir or -auxdir=dir
                 - set name of directory for auxiliary files (aux, log)
                 - Currently this only works with MiKTeX
   -bibtex       - use bibtex when needed (default)
   -bibtex-      - never use bibtex
   -bibtex-cond  - use bibtex when needed, but only if the bib files exist
   -bm <message> - Print message across the page when converting to postscript
   -bi <intensity> - Set contrast or intensity of banner
   -bs <scale> - Set scale for banner
   -commands  - list commands used by latexmk for processing files
   -c     - clean up (remove) all nonessential files, except
            dvi, ps and pdf files.
            This and the other clean-ups are instead of a regular make.
   -C     - clean up (remove) all nonessential files
            including aux, dep, dvi, postscript and pdf files
            and file of database of file information
   -CA     - clean up (remove) all nonessential files.
            Equivalent to -C option.
   -CF     - Remove file of database of file information before doing
            other actions
   -cd    - Change to directory of source file when processing it
   -cd-   - Do NOT change to directory of source file when processing it
   -dependents or -deps - Show list of dependent files after processing
   -dependents- or -deps- - Do not show list of dependent files
   -deps-out=file - Set name of output file for dependency list,
                    and turn on showing of dependency list
   -dF <filter> - Filter to apply to dvi file
   -dvi   - generate dvi
   -dvi-  - turn off required dvi
   -e <code> - Execute specified Perl code (as part of latexmk start-up
               code)
   -f     - force continued processing past errors
   -f-    - turn off forced continuing processing past errors
   -gg    - Super go mode: clean out generated files (-CA), and then
            process files regardless of file timestamps
   -g     - process regardless of file timestamps
   -g-    - Turn off -g
   -h     - print help
   -help - print help
   -jobname=STRING - set basename of output file(s) to STRING.
            (Like --jobname=STRING on command line for many current
            implementations of latex/pdflatex.)
   -l     - force landscape mode
   -l-    - turn off -l
   -latex=<program> - set program used for latex.
                      (replace '<program>' by the program name)
   -new-viewer    - in -pvc mode, always start a new viewer
   -new-viewer-   - in -pvc mode, start a new viewer only if needed
   -nobibtex      - never use bibtex
   -nodependents  - Do not show list of dependent files after processing
   -norc          - omit automatic reading of system, user and project rc files
   -output-directory=dir or -outdir=dir
                  - set name of directory for output files
   -pdf   - generate pdf by pdflatex
   -pdfdvi - generate pdf by dvipdf
   -pdflatex=<program> - set program used for pdflatex.
                      (replace '<program>' by the program name)
   -pdfps - generate pdf by ps2pdf
   -pdf-  - turn off pdf
   -ps    - generate postscript
   -ps-   - turn off postscript
   -pF <filter> - Filter to apply to postscript file
   -p     - print document after generating postscript.
            (Can also .dvi or .pdf files -- see documentation)
   -print=dvi     - when file is to be printed, print the dvi file
   -print=ps      - when file is to be printed, print the ps file (default)
   -print=pdf     - when file is to be printed, print the pdf file
   -pv    - preview document.  (Side effect turn off continuous preview)
   -pv-   - turn off preview mode
   -pvc   - preview document and continuously update.  (This also turns
                on force mode, so errors do not cause latexmk to stop.)
            (Side effect: turn off ordinary preview mode.)
   -pvc-  - turn off -pvc
   -quiet    - silence progress messages from called programs
   -r <file> - Read custom RC file
               (N.B. This file could override options specified earlier
               on the command line.)
   -recorder - Use -recorder option for (pdf)latex
               (to give list of input and output files)
   -recorder- - Do not use -recorder option for (pdf)latex
   -rules    - Show list of rules after processing
   -rules-   - Do not show list of rules after processing
   -silent   - silence progress messages from called programs
   -time     - show CPU time used
   -time-    - don't show CPU time used
   -use-make - use the make program to try to make missing files
   -use-make- - don't use the make program to try to make missing files
   -v        - display program version
   -verbose  - display usual progress messages from called programs
   -version      - display program version
   -view=default - viewer is default (dvi, ps, pdf)
   -view=dvi     - viewer is for dvi
   -view=none    - no viewer is used
   -view=ps      - viewer is for ps
   -view=pdf     - viewer is for pdf
   filename = the root filename of LaTeX document

-p, -pv and -pvc are mutually exclusive
-h, -c and -C override all other options.
-pv and -pvc require one and only one filename specified
All options can be introduced by '-' or '--'.  (E.g., --help or -help.)

**Comment by xueruini** [comment]
但你的latexmk的确没有-xelatex

这个是我的：

Latexmk 4.43a: Automatic LaTeX document generation routine

Usage: latexmk [latexmk_options] [filename ...]

  Latexmk_options:
   -aux-directory=dir or -auxdir=dir
                 - set name of directory for auxiliary files (aux, log)
                 - Currently this only works with MiKTeX
   -bibtex       - use bibtex when needed (default)
   -bibtex-      - never use bibtex
   -bibtex-cond  - use bibtex when needed, but only if the bib files exist
   -bm <message> - Print message across the page when converting to
postscript
   -bi <intensity> - Set contrast or intensity of banner
   -bs <scale> - Set scale for banner
   -commands  - list commands used by latexmk for processing files
   -c     - clean up (remove) all nonessential files, except
            dvi, ps and pdf files.
            This and the other clean-ups are instead of a regular make.
   -C     - clean up (remove) all nonessential files
            including aux, dep, dvi, postscript and pdf files
            and file of database of file information
   -CA     - clean up (remove) all nonessential files.
            Equivalent to -C option.
   -CF     - Remove file of database of file information before doing
            other actions
   -cd    - Change to directory of source file when processing it
   -cd-   - Do NOT change to directory of source file when processing it
   -dependents or -deps - Show list of dependent files after processing
   -dependents- or -deps- - Do not show list of dependent files
   -deps-out=file - Set name of output file for dependency list,
                    and turn on showing of dependency list
   -dF <filter> - Filter to apply to dvi file
   -dvi   - generate dvi
   -dvi-  - turn off required dvi
   -e <code> - Execute specified Perl code (as part of latexmk start-up
               code)
   -f     - force continued processing past errors
   -f-    - turn off forced continuing processing past errors
   -gg    - Super go mode: clean out generated files (-CA), and then
            process files regardless of file timestamps
   -g     - process regardless of file timestamps
   -g-    - Turn off -g
   -h     - print help
   -help - print help
   -jobname=STRING - set basename of output file(s) to STRING.
            (Like --jobname=STRING on command line for many current
            implementations of latex/pdflatex.)
   -l     - force landscape mode
   -l-    - turn off -l
   -latex=<program> - set program used for latex.
                      (replace '<program>' by the program name)
   -latexoption=<option> - add the given option to the (pdf)latex command
   -logfilewarninglist or -logfilewarnings
               give list of warnings after run of (pdf)latex
   -logfilewarninglist- or -logfilewarnings-
               do not give list of warnings after run of (pdf)latex
   -M     - Show list of dependent files after processing
   -MF file - Specifies name of file to receives list dependent files
   -MP    - List of dependent files includes phony target for each source
file.
   -new-viewer    - in -pvc mode, always start a new viewer
   -new-viewer-   - in -pvc mode, start a new viewer only if needed
   -nobibtex      - never use bibtex
   -nodependents  - Do not show list of dependent files after processing
   -norc          - omit automatic reading of system, user and project rc
files
   -output-directory=dir or -outdir=dir
                  - set name of directory for output files
   -pdf   - generate pdf by pdflatex
   -pdfdvi - generate pdf by dvipdf
   -pdflatex=<program> - set program used for pdflatex.
                      (replace '<program>' by the program name)
   -pdfps - generate pdf by ps2pdf
   -pdf-  - turn off pdf
   -ps    - generate postscript
   -ps-   - turn off postscript
   -pF <filter> - Filter to apply to postscript file
   -p     - print document after generating postscript.
            (Can also .dvi or .pdf files -- see documentation)
   -print=dvi     - when file is to be printed, print the dvi file
   -print=ps      - when file is to be printed, print the ps file (default)
   -print=pdf     - when file is to be printed, print the pdf file
   -pv    - preview document.  (Side effect turn off continuous preview)
   -pv-   - turn off preview mode
   -pvc   - preview document and continuously update.  (This also turns
                on force mode, so errors do not cause latexmk to stop.)
            (Side effect: turn off ordinary preview mode.)
   -pvc-  - turn off -pvc
   -quiet    - silence progress messages from called programs
   -r <file> - Read custom RC file
               (N.B. This file could override options specified earlier
               on the command line.)
   -recorder - Use -recorder option for (pdf)latex
               (to give list of input and output files)
   -recorder- - Do not use -recorder option for (pdf)latex
   -rules    - Show list of rules after processing
   -rules-   - Do not show list of rules after processing
   -showextraoptions  - Show other allowed options that are simply passed
               as is to latex and pdflatex
   -silent   - silence progress messages from called programs
   -time     - show CPU time used
   -time-    - don't show CPU time used
   -use-make - use the make program to try to make missing files
   -use-make- - don't use the make program to try to make missing files
   -v        - display program version
   -verbose  - display usual progress messages from called programs
   -version      - display program version
   -view=default - viewer is default (dvi, ps, pdf)
   -view=dvi     - viewer is for dvi
   -view=none    - no viewer is used
   -view=ps      - viewer is for ps
   -view=pdf     - viewer is for pdf
   -lualatex     - use lualatex for processing files to pdf
                   and turn pdf mode on, dvi/ps modes off
*   -xelatex      - use xelatex for processing files to pdf*
*                   and turn pdf mode on, dvi/ps modes off*

   filename = the root filename of LaTeX document

-p, -pv and -pvc are mutually exclusive
-h, -c and -C override all other options.
-pv and -pvc require one and only one filename specified
All options can be introduced by '-' or '--'.  (E.g., --help or -help.)

In addition, latexmk recognizes many other options that are passed to
latex and/or pdflatex without interpretation by latexmk.  Run latexmk
with the option -showextraoptions to see a list of these

Report bugs etc to John Collins <jcc8 at psu.edu>.

**Comment by bloodmoon1988** [comment]
hmmm, 奇怪了，xelatex明明已经安装了。。

[root@ExpServer thuthesis-master]# xelatex
This is XeTeXk, Version 3.141592-2.2-0.996 (Web2C 7.5.6)
 %&-line parsing enabled.
**

**Comment by xueruini** [comment]
http://users.phys.psu.edu/~collins/software/latexmk-jcc/versions.html

从4.37才开始支持 -xelatex

**Comment by bloodmoon1988** [comment]
Sorry,  我重新check了一下发现fedora的源里的texlive是2007版的，我卸载后重新安装了texlive2015. 之前的问题不存在了。但是出了个新的问题，如下，应该是是有些中文字体未安装？

我不知道引用的字体的目录在哪儿，这应该怎么处理呢？


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
!
! The font "SimSun" cannot be found.
!
! See the fontspec documentation for further information.
!
! For immediate help type H <return>.
!...............................................

l.5 ...ldFont={SimHei},ItalicFont={KaiTi}]{SimSun}

**Comment by alick** [comment]
Your fedora version is too old. Consider upgrading if you can.

Tex live in Fedora rpm repo might not be recent enough. You can install Tex
live from tug/CTAN directly.

Thuthesis requires some Chinese fonts from Windows Chinese edition. Link or
copy them to Linux's fonts directory e.g. ~/.fonts/ or /usr/share/fonts/ .
2015年9月7日 上午11:02，"bloodmoon1988" <notifications@github.com>写道：

**Comment by bloodmoon1988** [comment]
Hello, Ruini and alick,

Thanks for your replies.

I tried with TexLive 2015 on Fedora 15, after I fixed the Chinese fonts issues, more font errors came out, even the "times new roman" font was missing. So I guess Fedora 15 is much too old for this latex template, but I would rather not update it. I gave up fedora.

Then I tried with Miktex on Windows7, it required me to install "lisu" and "youyuan" fonts. After this, I passed compilation with Xelatex. Now I'm good.

Note: for those who use CTex suite 2.9, you need to update MikTex first because MikTex is pretty old in CTex, refer to this post http://bbs.ctex.org/forum.php?mod=viewthread&tid=75608.

**Comment by mengfl05** [comment]
Linux 下面就是要自己处理各种字体的，宋体什么的和 Times New Roman 都是有版权的，Linux 一般都没有，装上字体也就好了

win 下用个 TeXLive 2015 也挺好的

**Comment by bloodmoon1988** [comment]
@liuml07  是的，如果一开始在win下装TexLive 2015就没这么多问题了。以前一直都用Miktex挺好的，这次被坑了一次。

**Comment by bloodmoon1988** [comment]
Hello, guys

If you don't have further comments, I will close this issue. Thanks~ 

;-)

**Comment by alick** [comment]
Ah you are right. Times new Roman etc English fonts are also required to
copy or link on Linux or Mac.
2015年9月8日 下午8:39，"bloodmoon1988" <notifications@github.com>写道：
