### ISSUE TITLE
关于一些警告和 Bad Box

### ISSUE THREAD

**Issue by mengfl05** [xueruini/thuthesis#152]
最近两天花时间折腾了一下模板现在报的警告什么的，过来报告一下~供参考
1. \thu@setup@pdfinfo 和 \makecover 中需要插入 pdf 中的内容包含了不少的控制字符，主要是 \thu@ctitle 和 \thu@ckeywords 两个。
    我的思路本来是想把 \ctitle 改成和 \section 命令一样的 \section[...]{...} 格式，后来还是偷懒图方便 \thu@define@term{ctitleshort} 和 \thu@parse@keywords{ckeywordsshort} 了，主要是关键词那个命令看起来不太好改...
2. 博士论文封面里面使用 \thu@put@title 命令添加“培养单位”等等的信息，命令里面用了 \@ht@xb，但是盒子都不满，然后会报一堆 Underfull \hbox。
    本来想是不是填几个 \hfill 就可以，后来调了调还是放弃了，去掉了 \thu@put@title 命令直接用 \ziju 命令调一下字距...
3. 博士论文里面页面设置有 \setlength{\headsep}{0.2cm}，但是后面 \setlength{\headheight}{20pt}，前面那个是否改成 0.8cm-20pt。
4. \ps@thu@headings 命令中 \@oddhead 和 \@evenhead 定义中使用了 \vbox，但是填充不满，导致有页眉的页面每页都会出现 Underfull \vbox 的问题。
    我直接在 \vbox 里面内容的最下面加了一个 \vfill，这样是否合适。
5. 博士论文里面，目录中的章标题是汉字使用黑体，英文使用衬线的 Times，我看 \l@chapter 里面是特意这样设置的，是否改成都用无衬线字体。
关注 {\ifthu@bachelor\sffamily\else\csname thu@toc@font\endcsname\fi\heiti #1} 这行。

**Comment by xueruini** [comment]
box的warning的确不少，不过没功夫一一跟进

**Comment by mengfl05** [comment]
主要就是上面我报的  1、2、4 条啊，具体原因和位置都写了（不知道是不是说清楚了）...我这里自己动手改了改，除了一个 hyperref 里面的 warning 消不掉之外，其他的都能解决

**Comment by xueruini** [comment]
那就给一个PR吧 :)

Best

-- ruini

2015-11-16 15:51 GMT+08:00 Smoulder <notifications@github.com>:

**Comment by xueruini** [comment]
> 1. \thu@setup@pdfinfo 和 \makecover 中需要插入 pdf 中的内容包含了不少的控制字符，主要是 \thu@ctitle 和 \thu@ckeywords 两个。

这个命令实际没有使用

> 我的思路本来是想把 \ctitle 改成和 \section 命令一样的 \section[...]{...} 格式，后来还是偷懒图方便 \thu@define@term{ctitleshort} 和 \thu@parse@keywords{ckeywordsshort} 了，主要是关键词那个命令看起来不太好改...

现在看到的hyperref的warning应该是.out, .lof, .toc里面的非pdf string，比如“第~3~章”的~。

> 2. 博士论文封面里面使用 \thu@put@title 命令添加“培养单位”等等的信息，命令里面用了 \@ht@xb，但是盒子都不满，然后会报一堆 Underfull \hbox。
> 本来想是不是填几个 \hfill 就可以，后来调了调还是放弃了，去掉了 \thu@put@title 命令直接用 \ziju 命令调一下字距...

封面上没有几个，还好。改成 

```latex
\def\thu@put@title#1{\makebox[\thu@title@width][s]{#1}}
```
不知道是否能自动撑满？

> 4. \ps@thu@headings 命令中 \@oddhead 和 \@evenhead 定义中使用了 \vbox，但是填充不满，导致有页眉的页面每页都会出现 Underfull \vbox 的问题。
> 我直接在 \vbox 里面内容的最下面加了一个 \vfill，这样是否合适。

这个效果最明显。

**Comment by mengfl05** [comment]
这个...咋搞成上面的回复的样子捏...

1. \thu@setup@pdfinfo 这个是在 main.tex 里面用了的，thuthesis.cls 里面是没有用的

2. 我这里后面的章节都还没写，搞定 \thu@setup@pdfinfo 和 \makecover（这里面有一个 \pdfbookmark）之后就基本没有了，只剩下一个是写 pdfproducer 项的，这个看了看宏包代码，貌似搞不定...我这里现在的编译就只剩下这一个 warning 了

3. 在 5.0 版本下试了一下，貌似并没有效果...报的坏盒子是 badness 10000，估计不是没撑满的问题，后面超出的报的长度就是正常的长度

自己的代码改得比较随意，就不拿上来 pr 了（其实也还不太熟悉 git）...

**Comment by xueruini** [comment]
除了hyperref的，其它基本都fix了。
