### ISSUE TITLE
inlinecite 是不是比 onlinecite 更常用？ 

### ISSUE THREAD

**Issue by xavieryao** [xueruini/thuthesis#155]
>  `\onlinecite` 感觉怪怪的     

@bigeagle  在图书馆 LaTeX 讲座上如是说

**Comment by xueruini** [comment]
any proposal?

Best

-- ruini

**Comment by bigeagle** [comment]
maybe `\inlinecite` ?

**Comment by xueruini** [comment]
这个名字不错。如果没意见，我就改一下。

**Comment by bigeagle** [comment]
要不 alias 一下？不破坏兼容性感觉好点

**Comment by bigeagle** [comment]
哈看到 #156 了

**Comment by xueruini** [comment]
closed by #156.
