### ISSUE TITLE
KaiTi找不到怎么办啊

### ISSUE THREAD

**Issue by romeph** [xueruini/thuthesis#158]
windows下texlive 2015运行最新版thuthesis。在用xelatex编译学位论文模板的thuthesis.dtx得到用户手册时或用xelatex编译main.tex时，都说找不到楷体，错误是： 
fontspec error:"font-not-found" 
The font "KaiTi" cannot be found. 
已安装说明拷了字体，cache过，也把thufonts.def中的KatTi和FangSong改为KaiTi_GB2312和FangSong_GB2312，可还是不行。
但是在运行如下测试文件时
\documentclass{ctexart}
\begin{document}
你好，TeX Live 2010！\\
{\songti 这是宋体}\\
{\heiti 这是黑体}\\
{\fangsong 这是仿宋}\\
{\kaishu 这是楷书}\\
{\lishu 这是隶书}\\
{\youyuan 这是幼圆}\\
\end{document}
却可以得到正确的字体，也没有错误。这个问题已经困扰我两个多星期了，求大神解答。

**Comment by xueruini** [comment]
fc-list 看看系统里面的是KaiTi还是Kaiti_GB2312.

如果有python的话，可以跑一下zhefonts.py来设置字体。

Best

-- ruini

2015-12-06 14:42 GMT+08:00 romeph <notifications@github.com>:

**Comment by romeph** [comment]
![7](https://cloud.githubusercontent.com/assets/16016259/11618962/e3e036ea-9cdc-11e5-90ea-9500973b378d.jpg)
![1](https://cloud.githubusercontent.com/assets/16016259/11618961/e3dfac8e-9cdc-11e5-8fc4-4c226ff1a5ca.jpg)
![2](https://cloud.githubusercontent.com/assets/16016259/11618964/e3e8f028-9cdc-11e5-981a-7303b8f158b9.jpg)
![3](https://cloud.githubusercontent.com/assets/16016259/11618963/e3e72428-9cdc-11e5-909f-967ffff66a9e.jpg)
![4](https://cloud.githubusercontent.com/assets/16016259/11618965/e3ea11b0-9cdc-11e5-8c2f-0bed539072fc.jpg)
![5](https://cloud.githubusercontent.com/assets/16016259/11618966/e3eccd38-9cdc-11e5-8291-fe2ff96774ff.jpg)
![6](https://cloud.githubusercontent.com/assets/16016259/11618967/e4090cdc-9cdc-11e5-9c0e-957d7ac48493.jpg)
fc-list之后，就这样，找不到Kaiti和Kaiti_GB2312，可能是汉字乱码的缘故吧，我也不知道怎么才能不让它乱码

**Comment by xueruini** [comment]
fc-list -f '%{family}' ':lang=zh'

Best

-- ruini

**Comment by romeph** [comment]
fc-list -f '%{family}' ':lang=zh'没反应，fc-list :lang=zh之后就变成，这回又KaiTi_GB2312l了
![360 20151207223638500](https://cloud.githubusercontent.com/assets/16016259/11629480/6846ff80-9d33-11e5-8497-2978b7b277ba.jpg)

**Comment by alick** [comment]
You have two KaiTi (KaiTi.TTF, simkai.ttf) that may cause problems.
Besides, note the letter case `KaiTi` (not `Kaiti`).

On Mon, Dec 7, 2015 at 8:40 AM, romeph <notifications@github.com> wrote:

> fc-list -f '%{family}' ':lang=zh'没反应，fc-list
> :lang=zh之后就变成，这回又KaiTi_GB2312l了
> [image: 360 20151207223638500]
> <https://cloud.githubusercontent.com/assets/16016259/11629480/6846ff80-9d33-11e5-8497-2978b7b277ba.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xueruini/thuthesis/issues/158#issuecomment-162543659>.
>



-- 
Regards,
Alick

**Comment by alick** [comment]
To avoid weird Chinese characters on Windows, redirect the command output
to a file:

    fc-list :lang=zh > FILENAME.txt

And then use a text editor that understands UTF-8 encoding (e.g. the one
included in TeX distro (WinEdt or Texworks), Notepad++, GVim) to open it.

On Mon, Dec 7, 2015 at 11:42 AM, Alick Zhao <alick9188@gmail.com> wrote:

> You have two KaiTi (KaiTi.TTF, simkai.ttf) that may cause problems.
> Besides, note the letter case `KaiTi` (not `Kaiti`).
>
> On Mon, Dec 7, 2015 at 8:40 AM, romeph <notifications@github.com> wrote:
>
>> fc-list -f '%{family}' ':lang=zh'没反应，fc-list
>> :lang=zh之后就变成，这回又KaiTi_GB2312l了
>> [image: 360 20151207223638500]
>> <https://cloud.githubusercontent.com/assets/16016259/11629480/6846ff80-9d33-11e5-8497-2978b7b277ba.jpg>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xueruini/thuthesis/issues/158#issuecomment-162543659>
>> .
>>
>
>
>
> --
> Regards,
> Alick
>



-- 
Regards,
Alick

**Comment by romeph** [comment]
还是不行啊~~~~(>_<)~~~~

**Comment by alick** [comment]
你做了什么操作？还有什么问题？

**Comment by romeph** [comment]
我就是按你说的，把simkai删掉了，然后用xelatex运行thuthesis.dtx，还是说找不到KaiTi。用xelatex运行main.tex也是一样过不去，图如下：
![360 20151208135742750](https://cloud.githubusercontent.com/assets/16016259/11648942/139d043a-9db4-11e5-9f73-5ace6d17e67e.jpg)

是不是我没有把KaiTi真正安到texlive里啊？我只是把它拷到C:\texlive\2015\texmf-dist\fonts里，并fc-cache了一下。

**Comment by xueruini** [comment]
alick说的是注意大小写。

Best

-- ruini

**Comment by romeph** [comment]
是啊，我也注意了，可还是不行

**Comment by romeph** [comment]
在texstudio里错误是这样的
![360 20151208184142718](https://cloud.githubusercontent.com/assets/16016259/11653772/85876c8a-9ddb-11e5-94c1-5c53d6648763.jpg)

**Comment by alick** [comment]
亲，你的字体叫 `KaiTi_GB2312` 不是 `KaiTi`。改一下再试试？

On Tue, Dec 8, 2015 at 4:43 AM, romeph <notifications@github.com> wrote:

> 在texstudio里错误是这样的
> [image: 360 20151208184142718]
> <https://cloud.githubusercontent.com/assets/16016259/11653772/85876c8a-9ddb-11e5-94c1-5c53d6648763.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xueruini/thuthesis/issues/158#issuecomment-162845825>.
>



-- 
Regards,
Alick

**Comment by romeph** [comment]
alick亲，我改哪儿啊，thuthesis里也没找到可以改的地方啊，windows系统中的字体也改不名啊，在外面是KaiTi，一粘贴到fonts文件夹里面就自动变成楷体_GB2312了。

**Comment by xueruini** [comment]
thufonts.def

不行的话就装个python，跑一下zhfonts.py脚本，会帮你自动修改。

Best

-- ruini

2015-12-09 19:44 GMT+08:00 romeph <notifications@github.com>:

**Comment by romeph** [comment]
thufonts.def已经改过了，改成KaiTi_GB2312了，还是不行。我装了python2.3.5，新版本的装不上，可是打开python后，也不知道怎么跑zhfonts.py啊，直接输入它，显示的是没定义。~~~~(>_<)~~~~

**Comment by xueruini** [comment]
python zhfonts.py

Best

-- ruini

2015-12-09 23:11 GMT+08:00 romeph <notifications@github.com>:

**Comment by alick** [comment]
Python 只能装 2.3 版本？安装姿势不对？还是 XP 系统只能到这儿了？还真没测试过 zhfonts.py 能否在 2.3 版本的
pyhton 上跑😅

请逐步确保如下：

1. 系统有且只有一个楷体 fc-cache 命令检查
1. 升级 TeX 发行版/套装到最新，更新全部宏包
1. 简单中文文档测试 ctexart 文档类下楷体可用
1. 从 GitHub 下载最新版 thuthesis 压缩包，解压到新目录，编译测试。

**Comment by romeph** [comment]
Python换成了3.4.4rc1版本，在python.exe中输入python zhfonts.py，运行后显示的结果是
File "<stdin>"，line 1
python zhfonts.py
SyntexError：invalid syntax

alick列的4个步骤我均已验证，问题还是一样的KaiTi找不到。
多谢二位的热心帮助，尽管我的问题没有解决，但还是学到了很多新东西。我决定先放弃了，否则真的疯掉了。谢啦！

**Comment by xueruini** [comment]
2015-12-10 13:03 GMT+08:00 romeph <notifications@github.com>:

> Python换成了3.4.4rc1版本，在python.exe中输入python zhfonts.py，运行后显示的结果是
>
这个不对，是打开一个命令行窗口，切换到zhfonts.py所在目录，输入命令，大约这个样子：

x:\abc\def\thuthesis > python zhfonts.py

哪位有xp的系统，帮忙生成一个zhfonts.def贴一下吧

**Comment by romeph** [comment]
终于成功了，是我改thufonts.def改的不彻底，只把texlive里自带的thuthesis里的改了，而没有改我用的文件夹中的。从11月23日起到12月10，困扰了我半个多月的字体问题终于解决了。虽然走了很多弯路，但也学到了很多，O(∩_∩)O哈哈~   大榭薛师兄，还有alick亲

**Comment by alick** [comment]
Don't bother to modify the one from tex distro/ CTAN.
