### ISSUE TITLE
will release v4.8.2 (or v4.9?) before the coming new year

### ISSUE THREAD

**Issue by xueruini** [xueruini/thuthesis#165]
A draft release notes: https://github.com/xueruini/thuthesis/releases

#125 is not fixed yet.

**Comment by alick** [comment]
Good news!

If old documents cannot be directly compiled with the new version, maybe let's make it 5.0? (ctex jumps to 2.x and we are now only compatible with 2.2+(?))

About inserting scanned PDF pages, I have a few usage notes in comments. cf. https://github.com/xueruini/thuthesis/pull/136/files

**Comment by xueruini** [comment]
please checkout the master HEAD.

Let's enjoy v5.0!
