### ISSUE TITLE
有两个问题~

### ISSUE THREAD

**Issue by yangbowu** [xueruini/thuthesis#169]
问题1：示例文档需要安装哪些字体才能避免warning.
问题2：
这种warning是由什么原因导致的？
```
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\spacefactor' on input line 30.
```

**Comment by xueruini** [comment]
> 问题1：示例文档需要安装哪些字体才能避免warning.

Times new roma 没有samll caps，而\thuthesis用到了，warning基本都是这儿来的。如果你不用small caps，不用管。

> 问题2：
> 这种warning是由什么原因导致的？

hyperref的bookmark中要把一些(la)tex命令过滤掉。
