### ISSUE TITLE
deprecate dvipdfmx/texi2dvi?

### ISSUE THREAD

**Issue by alick** [xueruini/thuthesis#177]
I guess we can:

- deprecate dvipdfmx in favor of xelatex/pdflatex
- deprecate texi2dvi in favor of latexmk

This should simplify Makefile and tests.

**Comment by xueruini** [comment]
Actually, I only tested xelatex for the latest releases. Good idea to
simplify the compiling process.

Best

-- ruini

**Comment by alick** [comment]
:+1:
