### ISSUE TITLE
关于模板字体修改

### ISSUE THREAD

**Issue by yangbowu** [xueruini/thuthesis#178]
您好。我想基于thuthesis做一些小的修改。比如我现在想要把图表标题设定为小四号宋体加重。而thuthesis.cls里的设定是
`\DeclareCaptionLabelFormat{thu}{{\dawu[1.5]\songti #1~\rmfamily #2}}
\DeclareCaptionLabelSeparator{thu}{\hspace{1em}}
\DeclareCaptionFont{thu}{\dawu[1.5]}
\captionsetup{labelformat=thu,labelsep=thu,font=thu}`

字号改为\xiaosi[1.5],那字体如何加重呢？

**Comment by xueruini** [comment]
\bfseries 吧

Best

-- ruini

2016-02-06 12:33 GMT+08:00 yangbowu <notifications@github.com>:

**Comment by yangbowu** [comment]
还有一个问题，是关于目录那部分的代码。   \l@chapter的两个参数的含义是什么？
` \renewcommand*\l@chapter[2]{%
\ifnum \c@tocdepth >\m@ne
\addpenalty{-\@highpenalty}%
 \vskip 4bp \@plus\p@
\setlength\@tempdima{4em}%
\begingroup
\parindent \z@ \rightskip \@pnumwidth
\parfillskip -\@pnumwidth
\leavevmode
\advance\leftskip\@tempdima
\hskip -\leftskip
{\ifthu@bachelor\sffamily\else\csname thu@toc@font\endcsname\fi\heiti #1} % numberline is called here, and it uses \@tempdima
\leaders\hbox{$\m@th\mkern \@dotsep mu\hbox{.}\mkern \@dotsep mu$}\hfill
\nobreak{\normalfont\normalcolor #2}\par
\penalty\@highpenalty
\endgroup
\fi}`

**Comment by xueruini** [comment]
`\l@chapter` 跟 `\l@section` 类似，参数相同。通过 `\@section` 来理解 `\l@chapter` 更容易。`\l@sectoin` 本质上是 `\@dottedtocline`，比如 `book.cls` 默认定义：

```latex
\newcommand*\l@section{\@dottedtocline{1}{1.5em}{2.3em}}
```

根据 LaTeX 文档：

![image](https://cloud.githubusercontent.com/assets/1863/13025414/d71eb9a0-d241-11e5-9168-c0d0698a4a68.png)
![image](https://cloud.githubusercontent.com/assets/1863/13025416/ddaf3a60-d241-11e5-8dbf-5fe115611213.png)

可知，`#1` 和 `#2` 正好是

**Comment by yangbowu** [comment]
@xueruini book.cls的这个说明文档要在哪里获取呀？ 我尝试找了很久，但是找不到。能指点下我么？

**Comment by zepinglee** [comment]
@yangbowu texdoc classes
