### ISSUE TITLE
zhfonts.py 在 macos 默认不能运行

### ISSUE THREAD

**Issue by xueruini** [xueruini/thuthesis#179]
ref: https://github.com/xueruini/thuthesis/issues/6#issuecomment-182904184

**Comment by xueruini** [comment]
应该指明给xelatex用的

**Comment by zepinglee** [comment]
刚刚看到一办法是用
```
ls ~/Library/Fonts/;
ls /Library/Fonts/;
ls /System/Library/Fonts/
```

**Comment by 09star** [comment]
hi 刚在 mac 下 texpad 使用XeLaTex 直接编译 会遇到一些错误
如： CJKspace.sty:39: LaTeX Error: Environment CJK* undefined.
由于是新手，有什么需要注意和额外配置的地方么？ 感谢

**Comment by xueruini** [comment]
怎么像fc-list那样显示字体信息呢？

**Comment by zepinglee** [comment]
@09star 把 ctex-fontset-thuthesis.def 改成这样
```
\ProvidesFile{ctex-fontset-thuthesis.def}

\setCJKmainfont[BoldFont=STHeiti,ItalicFont=STKaiti]{STSong}
\setCJKsansfont[BoldFont=STHeiti]{STXihei}
\setCJKmonofont{STKaiti}
\setCJKfamilyfont{zhsong}{STSong}
\setCJKfamilyfont{zhhei}{STXihei}
\setCJKfamilyfont{zhkai}{STKaiti}
\setCJKfamilyfont{zhfs}{STFangsong}
\setCJKfamilyfont{zhli}{Libian} % 有报隶和隶变两种隶书
\setCJKfamilyfont{zhyou}{STSong} % Mac 系统没有自带幼圆，从其它地方下载

\newcommand*{\songti}{\CJKfamily{zhsong}}
\newcommand*{\heiti}{\CJKfamily{zhhei}}
\newcommand*{\kaishu}{\CJKfamily{zhkai}}
\newcommand*{\fangsong}{\CJKfamily{zhfs}}
\newcommand*{\lishu}{\CJKfamily{zhli}}
\newcommand*{\youyuan}{\CJKfamily{zhyou}}

\endinput
```

**Comment by zepinglee** [comment]
没有办法……

**Comment by 09star** [comment]
安装[ xquartz](http://www.xquartz.org/)  就可以在mac上使用 fc-list 命令了 ， [参考](http://www.comdyn.cn/cn/from-web/latex/192-mactex-2010-xelatex)

**Comment by xueruini** [comment]
@zepinglee 一开始提这个issue的前提是没装 fc-list..

Best

-- ruini

**Comment by alick** [comment]
似乎也[没有替代][se] fc-list 的方案诶。也许只能建议用户去安装 XQuartz。

[se]: https://apple.stackexchange.com/questions/35852/list-of-activated-fonts-with-shell-command-in-os-x
