### ISSUE TITLE
main.tex 编译不通过

### ISSUE THREAD

**Issue by sunf71** [xueruini/thuthesis#180]
Command Line:   bibtex.exe "main"
Startup Folder: E:\Projects\Thesis\thuthesis-master\thuthesis-master

This is BibTeX, Version 0.99d (MiKTeX 2.9)
The top-level auxiliary file: main.aux
I found no \citation commands---while reading file main.aux
I found no \bibdata command---while reading file main.aux
I found no \bibstyle command---while reading file main.aux
(There were 3 error messages)

Command Line:   texify.exe --pdf --tex-option=--interaction=errorstopmode --tex-option=--synctex=-1 "E:\Projects\Thesis\thuthesis-master\thuthesis-master\main.tex"
Startup Folder: E:\Projects\Thesis\thuthesis-master\thuthesis-master

This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9)
entering extended mode
(E:/Projects/Thesis/thuthesis-master/thuthesis-master/main.tex
LaTeX2e <2016/02/01>
Babel <3.9n> and hyphenation patterns for 69 languages loaded.
(thuthesis.cls
Document Class: thuthesis 2016/02/01 5.2.2 Tsinghua University Thesis Template
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\oberdiek\kvoptions.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\graphics\keyval.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\oberdiek\ltxcmds.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\oberdiek\kvsetkeys.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\oberdiek\infwarerr.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\oberdiek\etexcmds.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\oberdiek\ifluatex.sty"))))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ctex\ctexbook.cls"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\l3kernel\expl3.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\l3kernel\expl3-code.tex")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\l3kernel\l3pdfmode.def"))
Document Class: ctexbook 2016/02/02 v2.3 Chinese adapter for class book (CTEX)
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\l3packages\xparse\xparse.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\l3packages\l3keys2e\l3keys2e.sty
") ("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ctex\ctexhook.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ctex\ctexpatch.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\fix-cm.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\ts1enc.def"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ms\everysel.sty")
("C:\Program Files (x86)\CTEX\CTeX\tex\latex\ctex\cfg\ctexopts.cfg")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\book.cls"
Document Class: book 2014/09/29 v1.4h Standard LaTeX document class
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\bk12.clo"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ctex\engine\ctex-engine-pdftex.d
ef" ("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\cjk\CJKutf8.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\oberdiek\ifpdf.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\inputenc.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\utf8.def"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\t1enc.dfu")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\ot1enc.dfu")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\omsenc.dfu")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\ts1enc.dfu")))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\cjk\CJK.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\cjk\mule\MULEenc.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\cjk\CJK.enc"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\fontenc.sty"))
("C:\Program Files (x86)\CTEX\CTeX\tex\latex\CJKpunct\CJKpunct.sty"
("C:\Program Files (x86)\CTEX\CTeX\tex\latex\CJKpunct\CJKpunct.spa"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\cjk\CJKspace.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ctex\ctexspa.def")
("C:\Program Files (x86)\CTEX\CTeX\tex\latex\CJK\CJKfntef.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\cjk\CJKulem.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ulem\ulem.sty"))))
("C:\Program Files (x86)\CTEX\UserData\tex\latex\zhnumber\zhnumber.sty"
("C:\Program Files (x86)\CTEX\UserData\tex\latex\zhnumber\zhnumber-utf8.cfg"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ctex\scheme\ctex-scheme-plain-bo
ok.def") ("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ctex\ctex-cs4size.clo")
) ("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ctex\config\ctex.cfg")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\etoolbox\etoolbox.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\ifxetex\ifxetex.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\amsmath\amsmath.sty"
For additional information on amsmath, use the `?' option.
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\amsmath\amstext.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\amsmath\amsgen.sty"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\amsmath\amsbsy.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\amsmath\amsopn.sty"))
("C:\Program Files (x86)\CTEX\UserData\tex\latex\newtx\newtxtext.sty"
`newtxtext' v1.465, 2016/01/31 Text macros taking advantage of TeX-Gyre Termes 
fonts (msharpe)
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fontaxes\fontaxes.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\xkeyval\xkeyval.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\xkeyval\xkeyval.tex"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\xkeyval\xkvutils.tex")))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\fontenc.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\t1enc.def"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\textcomp.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\ts1enc.def")) 
Babel
("C:\Program Files (x86)\CTEX\UserData\tex\latex\newtx\t1ntxtlf.fd"))
("C:\Program Files (x86)\CTEX\UserData\tex\latex\newtx\newtxmath.sty"
`newtxmath' v1.465, 2016/01/31 Math macros based on txfonts (msharpe)
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\binhex\binhex.tex"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\tex-gyre\tgcursor.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\graphics\graphicx.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\graphics\graphics.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\graphics\trig.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\00miktex\graphics.cfg")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\pdftex-def\pdftex.def")))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\caption\subcaption.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\caption\caption.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\caption\caption3.sty")))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\pdfpages\pdfpages.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\base\ifthen.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\tools\calc.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\eso-pic\eso-pic.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\oberdiek\atbegshi.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\xcolor\xcolor.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\00miktex\color.cfg")))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\pdfpages\pppdftex.def"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\enumitem\enumitem.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\environ\environ.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\trimspaces\trimspaces.sty"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\footmisc\footmisc.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\pclnfss\arial.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\ntheorem\ntheorem.sty"
Style `ntheorem', Version 1.33 <2011/08/15>
) ("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\tools\array.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\tools\longtable.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\booktabs\booktabs.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\natbib\natbib.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\hyperref\hyperref.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\oberdiek\hobsub-hyperref.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\oberdiek\hobsub-generic.sty"))
 ("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\oberdiek\auxhook.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\hyperref\pd1enc.def")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\00miktex\hyperref.cfg")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\hyperref\puenc.def")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\url\url.sty"))

Package hyperref Message: Driver (autodetected): hpdftex.

("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\hyperref\hpdftex.def"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\oberdiek\rerunfilecheck.sty"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\geometry\geometry.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\geometry\geometry.cfg"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fancyhdr\fancyhdr.sty"))
(thuthesis.cfg) (thuthesis.sty
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\multirow\multirow.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\tools\tabularx.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\diagbox\diagbox.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\pict2e\pict2e.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\00miktex\pict2e.cfg")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\pict2e\p2e-pdftex.def"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp.sty"
`Fixed Point Package', Version 0.8, April 2, 1995 (C) Michael Mehlich
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\defpattern.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp-basic.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp-addons.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp-snap.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp-exp.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp-trigo.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp-pas.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp-random.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp-eqn.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp-upn.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\fp\fp-eval.sty")))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\float\float.sty"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\cjk\UTF8\UTF8.bdg")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\cjk\UTF8\UTF8.enc")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\cjk\UTF8\UTF8.chr") (main.aux)
("C:\Program Files (x86)\CTEX\UserData\tex\latex\newtx\omlntxmi.fd")
("C:\Program Files (x86)\CTEX\UserData\tex\latex\newtx\omsntxsy.fd")
("C:\Program Files (x86)\CTEX\UserData\tex\latex\newtx\untxexa.fd")
ABD: EverySelectfont initializing macros
("C:\Program Files (x86)\CTEX\MiKTeX\tex\context\base\supp-pdf.mkii"
[Loading MPS to PDF converter (version 2006.09.02).]
) ("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\caption\ltcaption.sty")
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\oberdiek\pdflscape.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\graphics\lscape.sty"))
("C:\Program Files (x86)\CTEX\MiKTeX\tex\latex\hyperref\nameref.sty"
("C:\Program Files (x86)\CTEX\MiKTeX\tex\generic\oberdiek\gettitlestring.sty"))
(main.out) (main.out)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(data/cover.tex)

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\\' on input line 27.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                \kern -2.00792pt
(hyperref)                removed on input line 27.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\lower' on input line 27.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\hbox' on input line 27.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                \kern -1.50562pt
(hyperref)                removed on input line 27.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\spacefactor' on input line 27.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\@m' on input line 27.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\\' on input line 28.

LaTeX Font Warning: Font shape `T1/mhv/m/n' undefined
(Font)              using `T1/cmr/m/n' instead on input line 28.

! Undefined control sequence.
<argument> ...nter} \yihao [1.2]{\sffamily \heiti 
                                                  \thu@ctitle }\par \par \vs...
l.28 
     
? 

Process has been terminated ...

**Comment by xueruini** [comment]
手动试一下：

xelatex main
bibtex main
xelatex main
xelatex main

或者把xelatex替换成pdflatex

Best

-- ruini

**Comment by sunf71** [comment]
谢谢，xelatex通过了，peflatex还是不行，还是错误：
! Undefined control sequence.
...nter} \yihao [1.2]{\sffamily \heiti 
\thu@ctitle }\par \par \vs...
l.28
