### ISSUE TITLE
File `ctexhook.sty' not found.

### ISSUE THREAD

**Issue by 09star** [xueruini/thuthesis#181]
hi 我又来了，编译（mac xelatex） 遇到 ! LaTeX Error: File `ctexhook.sty' not found. 

> This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./main.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.
(./thuthesis.cls
Document Class: thuthesis 2016/01/18 5.2.1 Tsinghua University Thesis Template
(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/kvoptions.sty (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/keyval.sty) (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ltxcmds.sty) (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/infwarerr.sty) (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/etexcmds.sty (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ifluatex.sty)))) (/usr/local/texlive/2015/texmf-dist/tex/latex/ctex/ctexbook.cls (/usr/local/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3.sty (/usr/local/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3-code.tex) (/usr/local/texlive/2015/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))
Document Class: ctexbook 2016/02/02 v2.3 Chinese adapter for class book (CTEX)
(/usr/local/texlive/2015/texmf-dist/tex/latex/l3packages/xparse/xparse.sty) (/usr/local/texlive/2015/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
! LaTeX Error: File `ctexhook.sty' not found.

**Comment by zepinglee** [comment]
`tlmgr install --reinstall ctex`

**Comment by 09star** [comment]
感谢，更新完之后 解决啦~
