### ISSUE TITLE
建议在thuthesis.cls中加入 RequirePackage ...

### ISSUE THREAD

**Issue by 02015678** [xueruini/thuthesis#182]
\RequirePackage{l3kernel}
\RequirePackage{l3packages}
\RequirePackage{fontspec}
\RequirePackage{xeCJK}

**Comment by mengfl05** [comment]
没必要，ctex 宏包在 xelatex 下面会自动加载这些宏包

**Comment by xueruini** [comment]
> \RequirePackage{l3kernel}
> \RequirePackage{l3packages}

这些包没有直接调用，为啥要加呢？

说实话，expl3的语法太诡异了，没有了tex的味道。
