### ISSUE TITLE
请问如何修改公式和正文之间的间距

### ISSUE THREAD

**Issue by YingShen-1027** [xueruini/thuthesis#185]
模板输出的公式和正文间距是10pt，太大了，想要改为6pt
使用下面的方法，有些公式的间距缩小了，但有些不变，不清楚问题在哪，求指导~
\begin{equation}
\label{equ1}
\setlength{\abovedisplayskip}{6pt}
\setlength{\belowdisplayskip}{6pt}
    c=a+b,
\end{equation}

**Comment by mengfl05** [comment]
这东西，最靠谱的改法是去模板里面找 \normalsize 和 \large（或者是 \small，记不清了）这两个字体尺寸命令的定义，看到定义你就知道了
印象里应该是两个字号定义里面有这个
不过 10pt 挺好的呀...6 估计太小了

**Comment by YingShen-1027** [comment]
学校的论文要求里面写的是：公式的行距为单倍行距，段前空6磅，段后空6磅。
所以我想改\abovedisplayskip 和 \belowdisplayskip 为6pt

**Comment by mengfl05** [comment]
学校那个要求是按照 word 里面的设置给的，和 latex 里面的设置方式还不一样，可以对比一下现在模板的效果和学校 word 样例的效果...那个段前段后和这两个 skip 不是对应的

不知我理解错了没有，这两个尺寸就是在字体尺寸命令里面设置的
http://tex.stackexchange.com/questions/67133/font-size-selection-how-multiple-of-normalsize

**Comment by YingShen-1027** [comment]
嗯嗯，确实和word的设置不太一样，我明白了~非常感谢您的回答~~
