### ISSUE TITLE
Mac下编译main文件报错The key 'ctex/chapter/afterindent' is unknown and is being ignored.

### ISSUE THREAD

**Issue by ranio** [xueruini/thuthesis#186]
Mac下编译main文件报错The key 'ctex/chapter/afterindent' is unknown and is being ignored.
似乎没有影响main.pdf的生成，terminal中xelatex main后发现该错误，并且详细信息是：
'''''''''''''''''''''''''''''''''''''''''''''''
| The module 'ctex/section' does not have a key called
| ctex/section/afterindent'.
| Check that you have spelled the key name correctly.
|...............................................
初涉Latex，不知道这个错会不会对编译文件有影响，还是忽略就可以？
谢谢各位！

**Comment by xueruini** [comment]
更新package ctex

Best

-- ruini

**Comment by ranio** [comment]
非常感谢thuthesis，更新了下好多包都太old了XD
