### ISSUE TITLE
CJK 模式字体设置不对

### ISSUE THREAD

**Issue by leo-liu** [xueruini/thuthesis#187]
目前版本 bcaf42d71e4541762706980e12031dfc14e8ee2e 的 `thuthesis.dtx` 中对 `ctexbook` 传递的字体配置信息是 `fontset=none`，而在下面用如下语句定义的字体：
```latex
\ifxetex
  \def\CJK@null{\kern\CJKnullspace\Unicode{48}{7}\kern\CJKnullspace}
  \defaultfontfeatures{Mapping=tex-text}
  \IfFileExists{ctex-fontset-thuthesis.def}%
    {\ctexset{fontset=thuthesis}}%
    {\ctexset{fontset=windows}}
\else
  \RequirePackage{CJKspace}
  \ifthu@arial
    \IfFileExists{arial.sty}%
                 {\RequirePackage{arial}}%
                 {\ClassWarning{thuthesis}{arial.sty is not availiable!}}
  \fi
\fi
```
对 XeTeX 的情形正确设置了字体，但对 pdfTeX 等其他引擎则没有。导致 pdflatex 编译会出错。

建议的修改方式是，在 `ctex-fontset-thuthesis.def` 文件中探测编译引擎，用不同的方式设置字体。然后把
```latex
  \IfFileExists{ctex-fontset-thuthesis.def}%
    {\ctexset{fontset=thuthesis}}%
    {\ctexset{fontset=windows}}
```
整体拿到 `\ifxetex` 的外面。

事实上，这里整个 `\ifxetex` 判断都可以想办法去掉。对 `ctex` 2.x 来说，pdfTeX 引擎下 `CJKspace` 总是自动载入的。

**Comment by xueruini** [comment]
这样来看生成thuthesis的配置文件还不如让大家安装字体。

Best

-- ruini

2016-03-20 11:06 GMT+08:00 Liu Haiyang <notifications@github.com>:

**Comment by leo-liu** [comment]
如果只是宋体仿楷，那默认设置下 `ctex` 的自动配置也够了。Windows 会调用中易字体，Mac OS 调用华文字体，Linux 下用 Fandol 字体，效果都没什么问题。

不过我你们还要用到隶书、圆体，这个就非常无奈了。

**Comment by leo-liu** [comment]
啊我仔细又看了看，圆体在类文件中实际没使用到。

那就只有隶书——隶书这玩意儿没免费的啊，Windows 都不自带。然后再仔细看，隶书只在一个地方用到，即学士论文封面中打印“清华大学”四个字的校名：
```latex
    \ifthu@bachelor
      \vskip0.45cm
      {\yihao\lishu\ziju{0.3846}\thu@schoolname}
      \par\vskip1.5cm
      {\xiaochu\heiti\ziju{0.5}\thu@bachelor@subtitle}
% ......
```
所以完全也可以干掉。大不了用图片解决。

这样就可以直接用默认字体设置不用多虑了，哈哈。

**Comment by xueruini** [comment]
good catch!

Best

-- ruini

2016-03-20 15:45 GMT+08:00 Liu Haiyang <notifications@github.com>:

**Comment by samos123** [comment]
For me Fandol wasn't working as default on ArchLinux. I had to hardcode ctex option to use fontset=ubuntu. For reference: https://github.com/samos123/thuthesis/commit/66a1257cd2c05e2e344da990bf285ac5f10fb65c

**Comment by xueruini** [comment]
good idea, we might need to provide an option to allowe customized fontset.

Best

-- ruini

**Comment by samos123** [comment]
最后通过 @leo-liu 的帮助解决了问题。我的PDF Reader无法显示Fandol字体。装完了poppler-data就没问题。
