### ISSUE TITLE
\thu@apply 偏左

### ISSUE THREAD

**Issue by toubun** [xueruini/thuthesis#191]
编译环境：XeLaTeX，TeX Live 2015 on Windows 10 + CTeX 2.3 + xeCJK 3.3.4。
![left](https://cloud.githubusercontent.com/assets/18029370/13985597/b1db188a-f138-11e5-9849-86a7e60037c7.png)
解决方法：
https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx
第 2370 行

    \def\thu@apply{（申请清华大学\thu@cdegree 学位论文）}

改为

    \def\thu@apply{\mbox{}（申请清华大学\thu@cdegree 学位论文）\mbox{}}

![center](https://cloud.githubusercontent.com/assets/18029370/13987770/1d12f392-f144-11e5-8e40-41ba52b4a91d.png)

**Comment by xueruini** [comment]
赞细致！

加个 \noindent 看看？

Best

-- ruini

**Comment by mengfl05** [comment]
赞细致！

试了试，在 .cls 里面插入这行字的代码
    \xiaoer[1] \textrm{\thu@apply}
后面加上 % 去掉空格也有效果的

**Comment by xueruini** [comment]
行尾的空格实在是容易被漏掉。。。

Best

-- ruini

**Comment by xueruini** [comment]
是不是这个意思：

[image: Inline image 1]

Best

-- ruini

**Comment by mengfl05** [comment]
看了看以前的论文，也不是所有的论文封面都有这个问题
我还了解一些这几本论文的写作过程，我猜可能跟 xeCJK 自动加 \glue 有关系...
没有时间仔细验证了...至少暂时能先解决...
