### ISSUE TITLE
\thu@put@title 基线偏低

### ISSUE THREAD

**Issue by toubun** [xueruini/thuthesis#192]
编译环境：XeLaTeX，TeX Live 2015 on Windows 10 + CTeX 2.3 + xeCJK 3.3.4。
![low](https://cloud.githubusercontent.com/assets/18029370/13989033/96fbb11c-f149-11e5-948e-ade6ea7f0587.png)
解决方法：
https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx
第 2443 行

    \begin{CJKfilltwosides}{#1}#2\end{CJKfilltwosides}}

改为

    \begin{CJKfilltwosides}[b]{#1}#2\end{CJKfilltwosides}}

![normal](https://cloud.githubusercontent.com/assets/18029370/13989200/42c63b98-f14a-11e5-87ff-422041eac3ef.png)

**Comment by xueruini** [comment]
赞啊，给个PR吧，这是你的credit。

Best

-- ruini

**Comment by mengfl05** [comment]
点赞
