### ISSUE TITLE
文献引用支持(author, year)格式

### ISSUE THREAD

**Issue by xueruini** [xueruini/thuthesis#195]
`natbib`去掉`numbers`选项还不行，因为：
![image](https://cloud.githubusercontent.com/assets/1863/14045389/d89913bc-f2d4-11e5-9d1f-b241fd292ab5.png)

目前的`thuthesis.bst`是根据原生`unsrt.bst`改过来的，不行。需要基于`unsrtnat.bst`移植一下。

**Comment by zepinglee** [comment]
清华是用的 GB/T 714-2015 嘛？
我正在写一个基于 unsrtnat.bst 的 GB/T 714-2015，放在 https://github.com/ustctug/gbt-7714-2015，可以相互借鉴一下

**Comment by xueruini** [comment]
在关注这个bst，跟学校要求好像有点不同。

**Comment by zepinglee** [comment]
清华目前用的是 GB/T 7714-2005 吧？

**Comment by xueruini** [comment]
> 清华目前用的是 GB/T 7714-2005 吧？

基本是，但有些不同。谁给比对一下，呵呵。其实学校自己定义这种格式也实属不必要。

**Comment by zepinglee** [comment]
那边已经完成啦，你可以 diffmerge

**Comment by xueruini** [comment]
👍

Best

-- ruini

**Comment by alick** [comment]
清华的《研究生学位论文写作指南》中有一节写到：

> 3.5.1
> 参考文献著录只有一个标准
> 现行有效的关于参考文献著录的国家标准只有一个,即《文后参考文献著
> 录规则》
> (GB/T 7714—2005),这是一个基础性的国家标准,适用于各个学科、
> 各种类型的出版物。本指南就是根据该国家标准制订的。我校研究生学位论文
> 的参考文献著录和在正文中的标注方式不区分理工科和人文社科,统一按照国
> 家标准的规定,在“顺序编码制”和“著者-出版年制”两种方法中任选其一。

我的理解是就是按标准来的意思。并没有专门要不一样的意思。

目前的写作指南里还是 GB/T 2005？2015 版相对做了哪些改动？学校是不是该把基准改到 2015 了？

**Comment by alick** [comment]
感谢 @zepinglee 做了新版标准的 bst 样式文件，而且许可证是 LPPL！我觉得如果 @zepinglee 把 bst 作为一个包推到 CTAN 上的话，thuthesis 也可以考虑直接将其作为依赖，而不用再拷贝一份。

**Comment by alick** [comment]
呃，还真被我遇到一处清华指南和标准不一样的：关于中文的学位论文，清华指南要求方括号内标注”硕士学位论文“等，但标准里无论中英文都是只标字母 D

**Comment by xueruini** [comment]
是的。维护自己的bst没有必要。

Best

-- ruini

2016-06-12 12:23 GMT+08:00 Alick Zhao <notifications@github.com>:

**Comment by FinnLin** [comment]
请教一下，用CTAN上的thuthesis包编译，\citeauthor{}可以通过编译，但显示是author?，提示Package natbib Warning: Author undefined for citation`Anily1994'(natbib)。这个问题如何解决呢？
谢谢！

**Comment by alick** [comment]
这个感觉是您的 bib 数据库里 Anily1994 这一项没有写 author 是谁。

Regards,
Tao

**Comment by zepinglee** [comment]
我可以做一个修订版的

**Comment by LechorksMoshel** [comment]
所以现在应该怎样引用（作者年份）的格式呢？把\bibliographystyle{thuthesis}换成那个GB-7714-2015的bst文件吗？尝试了没有成功

**Comment by zepinglee** [comment]
我还正在写，估计两天内会搞定

**Comment by zepinglee** [comment]
我改好了，放在 https://github.com/zepinglee/gbt-7714-2015/tree/thu 。

**Comment by zepinglee** [comment]
@xueruini 你可以先设计一下接口嘛？
1. 两个bst怎么命名？
2. 用户怎样调用两种风格？（文档类参数？手动\bibliographystyle？）

然后我把东西加进去给你发pull request

**Comment by xueruini** [comment]
赞！

> 两个bst怎么命名？

如果这样的话，我想把以前的样式叫做：thuthesis-number.bst，新的叫 thuthesis-author-year.bst。

> 生成 bst 的 dtx 代码要不要加进 thuthesis.dtx？

我觉得不加了。独立 bst 用编辑器处理起来方便。

> 用户怎样调用两种风格？（文档类参数？手动\bibliographystyle？）

bibliographystyle 可能更符合习惯，改样式就换 style。

> 然后我把东西加进去给你发pull request

**Comment by zepinglee** [comment]
1. 我建议用 thuthesis-numerical.bst，这样跟 natbib 的命名更加对应。
3. 主要是 citation style 也要相应设置，而且要在`\cite` 设置（不能跟 `\bibliographystyle` 写在一起）

**Comment by LechorksMoshel** [comment]
现在切换bibliographystyle仍然是上标方框式的，没有变成authoryear。设置\setcitestyle也一点用都没有

**Comment by zepinglee** [comment]
```
\citestyle{authoryear}
\bibliographystyle{thuthesis-author-year}
```

**Comment by LechorksMoshel** [comment]
还是不行。确定不用调整其它的地方？

**Comment by zepinglee** [comment]
\citestyle{authoryear} 要在 \cite 前设置

**Comment by LechorksMoshel** [comment]
原来是因为这个。。之前和citestyle和bibliographystyle一起都放在main.tex的末尾了，怪不得怎么调都没变化

**Comment by fengduole** [comment]
我把以下两行放在了\begin{document}之后，编译依然无法做到Author-Year，请问一下是怎么回事呀
```
\citestyle{authoryear}
\bibliographystyle{thuthesis-author-year}
```

**Comment by fengduole** [comment]
```
\bibpunct{(}{)}{,}{a}{,}{;}
\setcitestyle{authoryear}
\bibliographystyle{thuthesis-author-year}
```
我是通过这个来达到Author-Year的引用的，但是参考文献需要悬挂缩进，不知道怎么处理，还望指点

**Comment by xueruini** [comment]
> 我是通过这个来达到Author-Year的引用的，但是参考文献需要悬挂缩进，不知道怎么处理，还望指点

1. 要改 thebibliography 的定义，根据 citestyle 选择不同样式。
2. 改你本地的 dtx 文件，生成的 cls 会被优先调用。
3. 修改好了放个 PR 出来，造福大家 :)

**Comment by fengduole** [comment]
首行悬挂2个字符的要求话`\setlength{\itemindent}{0pt}`改为`\setlength{\itemindent}{-2em}`似乎就对了，我是直接改的cls文件。

**Comment by xueruini** [comment]
> 首行悬挂2个字符的要求话\setlength{\itemindent}{0pt}改为\setlength{\itemindent}{-2em}似乎就对了，我是直接改的cls文件。

用 ccwd。贴个 diff 出来

**Comment by fengduole** [comment]
`\setlength{\itemindent}{0pt}`改为`\setlength{\itemindent}{-2\ccwd}`
我不知道怎么在comment里贴diff诶
