### ISSUE TITLE
目录中的附录条目，中文无法显示

### ISSUE THREAD

**Issue by BrieflyX** [xueruini/thuthesis#196]
生成目录后，appendix标题里的中文在目录里无法显示了，是我字体没有配置好么？

**Comment by xueruini** [comment]
应该没问题吧。你把截图和相关正文贴一下

Best

-- ruini

**Comment by BrieflyX** [comment]
目录输出的效果是这样

![image](https://cloud.githubusercontent.com/assets/7720233/14064090/b29261a2-f426-11e5-88ca-7dafb3e585ed.png)

正文
``` latex
%%% Local Variables: 
%%% mode: latex
%%% TeX-master: "../main"
%%% End: 

\chapter{Realloc 利用实例: Memo}
\section{程序源码}
\label{sec:memo-src}
...
```

**Comment by xueruini** [comment]
模板版本是？怎么编译的？

**Comment by BrieflyX** [comment]
使用的模板版本是4.5.1，使用的texmaker进行编译的，没有使用makefile
编译的命令
``` bash
latex -interaction=nonstopmode %.tex
pdflatex -synctex=1 -interaction=nonstopmode %.tex
```

如果input模版中自带的appendix01则可以正常显示.......非常奇怪........

**Comment by BrieflyX** [comment]
经过排查，貌似如果我在文中使用了\begin{lstlsting}来贴代码就导致标题无法在目录中显示，去掉所有的lstlisting的代码就可以了........

**Comment by xueruini** [comment]
模板也有点老了，用最新的吧。



Best

-- ruini
