### ISSUE TITLE
Texlive 2015 + xelatex生成的PDF书签章节目录显示不正确

### ISSUE THREAD

**Issue by li-long** [xueruini/thuthesis#197]
PDF书签章节目录后面多添了一个零。
例如，第1章显示为第1零章。section显示正常。
请问需要如何修改？
谢谢

**Comment by xueruini** [comment]
version?

Best

-- ruini

**Comment by li-long** [comment]
不好意思，之前是操作某些地方改错了，现在已正常工作。
