### ISSUE TITLE
本科论文，封面无法修改学校

### ISSUE THREAD

**Issue by DarcySail** [xueruini/thuthesis#198]
您好，我将“thuthesis.cfg"中的\def\thu@schoolname{清华大学}修改为\def\thu@schoolname{××大学}，将"main.tex"中的选项选为\documentclass[type=master]{thuthesis}，编译出来的封面，是正常的××大学。
但将\documentclass[type=master]{thuthesis}修改为\documentclass[type=bachelor]{thuthesis}之后，封面却变成了“清华大学”了。确定不是编译中间文件的问题，我有专门git clone一个新的thuthesis之后，进行过测试。

**Comment by xueruini** [comment]
这个故事说来话长。。。

本来都是在cfg里面写的，后来发现隶书只有在某个type中封面用了一下，为了减少对隶书的依赖，就把这个字做成了图片。而其他的type封面都是黑体，依然用文字，就出现了你说的情况。

https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx#L2493

Best

-- ruini

2016-04-19 11:48 GMT+08:00 DarcySail <notifications@github.com>:

**Comment by DarcySail** [comment]
谢谢您的回复。
