### ISSUE TITLE
main.tex编译无法通过

### ISSUE THREAD

**Issue by Fiendinx** [xueruini/thuthesis#200]
主要报错为，Class thuthesis Error: You have to specify one of thesis options: bachelor, master or doctor.. ...is options: bachelor, master or doctor.}{}
但是main.tex开头确实有
\documentclass[type=master]{thuthesis}

**Comment by xueruini** [comment]
你是不是用的老模板？老模板直接写类型，没有type=

Best

-- ruini

**Comment by byMyWay** [comment]
报错main.tex:325: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! [  subparagraph/afterindent=true}，使用xelatex编译

**Comment by xueruini** [comment]
请更新ctex红包。

Best

-- ruini

**Comment by Fiendinx** [comment]
并不是，去掉前面的"type="后会报错让我加回来
另，本文件用MikTeX和TexLive编译会产生区别么？我用TexLive编译时会直接报：
main.tex:1: Undefined control sequence. [\documentclass]

**Comment by Fiendinx** [comment]
在TexLive下用xelatex编译可以通过，用pdflatex编译时会出现以上的报错信息

**Comment by mengfl05** [comment]
看看是不是 main.tex 里面有 BOM

**Comment by mengfl05** [comment]
无法重现...倒是报了一堆其他错误

能用 xelatex 就用这个吧

**Comment by xueruini** [comment]
提供一下模板版本号，tex发行版及其版本等信息。

**Comment by byMyWay** [comment]
模板版本，5.3.1,tex版本texlive 2015 ，某次执行tlmgr update all 后正常编译，但xelatex 编译不了以前写的文档，故重装，重装后执行tlmgr update all 依然无法编译发自网易邮箱大师
            在2016年05月23日 09:14，Ruini Xue 写道:提供一下模板版本号，tex发行版及其版本等信息。

**Comment by xueruini** [comment]
> main.tex:1: Undefined control sequence. [\documentclass]

这个应该不是模板的问题。现在用xelatex跑是什么错？

pdflatex跑不行，要装中文字体。
