### ISSUE TITLE
Mac下texlive2015无法编译通过

### ISSUE THREAD

**Issue by Hubertzhang** [xueruini/thuthesis#201]
!
! Critical ctex error: "fontset-unavailable"
! 
! CTeX fontset `mac' is unavailable in current mode.
! 
! See the ctex documentation for further information.
! 
! For immediate help type H .
!...............................................

**Comment by Hubertzhang** [comment]
更新包之后发现没有问题。。

**Comment by tangjie1992** [comment]
怎么解决的，更新了什么包？

**Comment by tangjie1992** [comment]
不用pdflatex就没有问题，我用xelatex编译通过了
