### ISSUE TITLE
maintext编译出现ctex问题

### ISSUE THREAD

**Issue by yangyuji12** [xueruini/thuthesis#202]
Package hyperref Message: Driver (autodetected): hxetex.

(/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hxetex.def
(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/stringenc.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/local/texlive/2015/texmf-dist/tex/latex/geometry/geometry.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "kernel/key-unknown"
! 
! The key 'ctex/chapter/afterindent' is unknown and is being ignored.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.329   subparagraph/afterindent=true}
                                      
?

**Comment by xueruini** [comment]
ctex包版本太旧。

Best

-- ruini

**Comment by yangyuji12** [comment]
以下两个命令，解决。
tlmgr update --self 
tlmgr update --all

**Comment by wangg12** [comment]
@xueruini 哪里可以找到最新版本的ctex包?

**Comment by wangg12** [comment]
我用的ctex 2.9.164(好像很久不更新了), 之前因为找不到miktex package manager. 查了一下，在命令行输入mpm就可以了。参考:http://blog.sina.com.cn/s/blog_62ef85c201014sv1.html
