### ISSUE TITLE
提示找不到字体

### ISSUE THREAD

**Issue by liuxiang94** [xueruini/thuthesis#203]
下载最新的模板，make all，出现错误

Transcript written on mfput.log.
grep: OT.log: 没有那个文件或目录
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input OT' failed to make OT.tfm.
kpathsea: Appending font creation commands to missfont.log.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "FangSong" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

latex环境：fedora23，texlive2015

**Comment by xueruini** [comment]
缺仿宋字体。

Best

-- ruini

**Comment by liuxiang94** [comment]
看来又得把windows上的字体文件给复制到linux下了

**Comment by sunyukai1** [comment]
解决了吗,如何安装字体

**Comment by liuxiang94** [comment]
两个解决方法：
一个是把把windows系统的C:\Windows\Fonts目录下的仿宋字体复制到Linux系统的/usr/share/fonts目录下
还有一种方法是只执行make thesis，不生成书脊就不需要仿宋字体

**Comment by ahyangyi** [comment]
不需要/usr/share/fonts，${HOME}/.fonts/应该也行且不需要sudo。

**Comment by jeasinema** [comment]
补充一个解决方法.

如果 Mac 上安装了 MS Word, 那么在以下路径`/Applications/Microsoft Word.app/Contents/Resources/DFonts` 可以找到`Fangsong.ttf`文件. 双击打开后选择安装即可.

以上方法在 macOS Mojave 上测试可用.
