### ISSUE TITLE
Overleaf template

### ISSUE THREAD

**Issue by bigeagle** [xueruini/thuthesis#206]
Hi there,

I created an onverleaf template for ThuThesis at https://www.overleaf.com/latex/templates/tsinghua-university-thesis-template/wrjmnybpzbhw

one issue is that there is no fangsong font on overleaf server, so I use song instead.

Cheers,

**Comment by nanmu42** [comment]
你的License有问题，[The LaTeX Project Public License](The LaTeX Project Public License)没法转到CC 4.0上。 @bigeagle

**Comment by bigeagle** [comment]
已经提交新版，审核后就是 LPPL 了。

**Comment by nanmu42** [comment]
点个赞，别忘了按照LPPL协议Credits.

**Comment by xueruini** [comment]
great!

Best

-- ruini
