### ISSUE TITLE
授权页中加粗的问题

### ISSUE THREAD

**Issue by Brilliant** [xueruini/thuthesis#209]
word中，
![image](https://cloud.githubusercontent.com/assets/1525785/15429558/0c4f461a-1ed4-11e6-8fec-125e72e9ccd7.png)

当前版本中，
![image](https://cloud.githubusercontent.com/assets/1525785/15429577/1eb69420-1ed4-11e6-8ab3-821c76b94086.png)

[thuthesis.dtx](https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx) 中的2687行` \textbf{\thu@authorizationaddon}\par`失效。

应该[dcd8297d](https://github.com/xueruini/thuthesis/commit/dcd8297de8e3309d088006475898cfbf5ad46179)后导致对宋体使用`textbf`会失效？

编译环境：XeLaTeX，TeX Live 2015 on Ubuntu 14.04

**Comment by xueruini** [comment]
应该显示为黑体了

Best

-- ruini

**Comment by Brilliant** [comment]
理论上应该是黑体，但是实际上没有变。

我同学在Windows 7下用CTeX编译也是没有变成黑体。

@xueruini 可否把你的环境贴一下？

**Comment by xueruini** [comment]
刚才试了一下，果然\textbf, \bfseries都没效果了。

Best

-- ruini

**Comment by xueruini** [comment]
\RequirePackage{tgcursor}

这一句导致的

Best

-- ruini

**Comment by xueruini** [comment]
@Brilliant 请看 #212.

**Comment by xueruini** [comment]
是不是直接用\RequirePackage{courier}得了，现在的写法太丑。
