### ISSUE TITLE
在非公式环境下希腊字母显示不出来

### ISSUE THREAD

**Issue by liuxiang94** [xueruini/thuthesis#210]
代码为：脉冲宽度在μs量级
输出为：脉冲宽度在 s 量级

**Comment by Brilliant** [comment]
脉冲宽度在`$\mu s$`量级

**Comment by nanmu42** [comment]
试试upgreek宏包。

Brilliant <notifications@github.com>于2016年5月22日周日 下午7:46写道：

**Comment by liuxiang94** [comment]
我是想在正文环境下显示希腊字母，不是在公式环境下
xelatex里面如果为希腊字母以及斯拉夫字母指定Times New Roman字体是可以直接显示出来的，但是我不知道怎么在模板里面指定Times New Roman字体

**Comment by nanmu42** [comment]
1. 使用upgreek，直立体希腊字母，印象中正文模式是可用的
2. 如果说要显示单位，有SIUnitx这种杀器可以用，直接，便捷。
两个宏包都有完备的文档。
建议使用模板之前先学习一下LaTeX，磨刀不误砍柴工。

liuxiang94 <notifications@github.com> 於 2016年5月23日週一 09:53 寫道：

**Comment by CareF** [comment]
遇到类似问题了, 就是用 SIUnitx 时无法正常显示 \mu. (如\SI{1000}{\us})

**Comment by nanmu42** [comment]
请看siunitx文档，搜索micro，专门有一个小标题写到了这个。

L.M. (CareF) <notifications@github.com> 於 2016年5月31日週二 19:17 寫道：

**Comment by liuxiang94** [comment]
我是这么处理的，在导言区插入
\newfontfamily\roman{Times New Roman} 
然后在正文里直接这么写
\roman{μs}
就可以显示希腊字母了

**Comment by CareF** [comment]
并没有找到小标题, 只找到了这两端看上去相关的: 

> In the case of the micro symbol (μ), siunitx provides a suitable
> low-level definition for the symbol. Depending on the fonts available, this may need to
> be replaced by an alternative by the user.

和

> When using X ETEX or LuaTEX, if fontspec is loaded these options are redefined to
> use UTF-8 characters directly.

@nanmu42

**Comment by nanmu42** [comment]
很高兴你找到了解决方案。

另：
文档版本20160301，第69页。

L.M. (CareF) <notifications@github.com> 於 2016年6月1日週三 10:07 寫道：

**Comment by nanmu42** [comment]
现在手头有电脑啦，这是一个解决方案，你可以试试，导言区适当位置插入以下代码：
```
%si单位支持
\RequirePackage{siunitx}
\RequirePackage{upgreek}
\ifxetex
\sisetup{%
	math-micro = {\upmu},
	text-micro = {\textmu},
}%\sisetup
```
@CareF
