### ISSUE TITLE
本科论文用英文写

### ISSUE THREAD

**Issue by math222** [xueruini/thuthesis#213]
RT，该怎么改设置，比如“第几章”，索引之类的设置成英文

**Comment by xueruini** [comment]
not supported yet.

**Comment by math222** [comment]
gg

**Comment by nanmu42** [comment]
看本地的`thuthesis.cfg`文件，祝你好运。

math222 <notifications@github.com>于2016年5月24日周二 下午6:23写道：

**Comment by xueruini** [comment]
good idea.

Best

-- ruini
