### ISSUE TITLE
文献调研报告参考文献问题

### ISSUE THREAD

**Issue by liboyue** [xueruini/thuthesis#214]
请问附录的文献调研报告的引用如何处理？难道只能手打吗。。。

**Comment by xueruini** [comment]
似乎是

Best

-- ruini

**Comment by liboyue** [comment]
好吧
还好不多。。

**Comment by liboyue** [comment]
@xueruini 如果用`biblatex`，就可以用`refsection`环境解决这个问题
然而折腾半天还是并不会改模板
