### ISSUE TITLE
封面，日期与辅导教师间的间隔不对

### ISSUE THREAD

**Issue by sangy12** [xueruini/thuthesis#215]
本科论文封面，日期紧挨着辅导教师一栏，没有留出空白。环境为ubuntu texlive 2015。

main.tex \makecover 处有warning：Font shape `EU1/FandolSong-Regular(0)/b/n' undefined(Font) using `EU1/FandolSong-Regular(0)/m/n' instead

xelatex编译过程中还看到* fontspec warning: "script-not-exist" Font 'Fandol xxx -Regular' does not contain script 'CJK'.

请问是什么问题，如何解决？非常感谢。

**Comment by xueruini** [comment]
应该有多大的空白？

**Comment by liboyue** [comment]
字体不对，最后拿别人的windows生成一下得了
`~`是空格

**Comment by xueruini** [comment]
贴一下正确的截图

Best

-- ruini

**Comment by sangy12** [comment]
![2016-05-25 15 54 46](https://cloud.githubusercontent.com/assets/13275801/15532199/0eb64668-2291-11e6-8a3d-1cc1a5bc21bb.png)

**Comment by sangy12** [comment]
![2016-05-25 15 57 50](https://cloud.githubusercontent.com/assets/13275801/15532295/a08f42ce-2291-11e6-97ac-3ffd1711a918.png)

**Comment by liboyue** [comment]
csupervisor={XXX~~~~教授}

**Comment by xueruini** [comment]
#216.
