### ISSUE TITLE
bibtex出错引起全文错误

### ISSUE THREAD

**Issue by bigeagle** [xueruini/thuthesis#218]
目前的实现中，必须有至少一篇有效的参考文献，最近遇到一些情况
- 一开始忘了加，之后必须删掉所有aux才能重新编译成功
- bibtex 出错（比如bib写得不对），全文都会跪掉

由于 thuthesis 绝大多数用户都是不知道 bibtex 是什么的纯新手，这个设定太复杂了。

**Comment by xueruini** [comment]
有啥好办法？

**Comment by bigeagle** [comment]
(没有呢，有就发PR而不是issue了……

**Comment by alick** [comment]
这其实是 latex+bibtex 的“问题”，不是 thuthesis 独有的。

我能想到的 walkaround 是：

1. 在示例文档里加注释说明，要使用 `\bibXXX` 必须有 `\cite`。
2. 写一条 FAQ...

**Comment by bigeagle** [comment]
我前几天帮湿弟调的结果是，如果任意时刻忘了加`\cite`，之后即使再加回来，也必须先把 aux 之类的删了，彻底重来一遍。
有没有可能在 main.tex 里强制先加一条…… 然后文档里写上「交论文之前把这条删了」

**Comment by alick** [comment]
赫然发现我已经在 main.tex 里加了一条提示了……

可以在 `\bibXXX` 之前加一个 `\nocite{KEY}`，然后注释”请确认你已经 cite 过了或者真的不需要 cite 后删除该行“。。。

**Comment by xueruini** [comment]
> 可以在 \bibXXX 之前加一个 \nocite{KEY}，然后注释”请确认你已经 cite 过了或者真的不需要 cite 后删除该行“。。。

例子太长了，要求太多了，大家都看不到。

**Comment by bigeagle** [comment]
的确是的，第一次帮湿弟debug的时候我都没注意到。
话说不妨直接加个 ThuThsis 的引用，反正大家都会在致谢里写 :)

**Comment by xueruini** [comment]
呵呵，good idea

Best

-- ruini
