### ISSUE TITLE
本科论文定理正文字体

### ISSUE THREAD

**Issue by math222** [xueruini/thuthesis#219]
学校有规定是宋体吗？这样定理在哪里结束都不知道。
ctexart的定理正文是另一种字体

**Comment by mengfl05** [comment]
定理环境后面应该有一段垂直间距作间隔的吧，本科的规定没有仔细关注，但是看看样例里面的定理是不是也是宋体

**Comment by xueruini** [comment]
\qed很早是有的，后来好像去掉了。可以加回来。

Best

-- ruini

**Comment by math222** [comment]
样例里没有定理。。。写作指南里也没提到定理的格式要求
\qed是放在证明结尾的吧。。。
是不是有必要向教务处反应一下增加定理环境的格式要求。
