### ISSUE TITLE
图表索引中不同章之间行间距偏大

### ISSUE THREAD

**Issue by clumsy456** [xueruini/thuthesis#220]
可以看到，1.1和2.1之间的距离比2,1和2.2以及2.2和2.3之间的距离大
![default](https://cloud.githubusercontent.com/assets/19684295/15706836/2f080ef0-2828-11e6-8666-8b5a61de96aa.PNG)

看到.lof文件里每章之间多了一句\addvspace {10\p@ }

**Comment by xueruini** [comment]
good catch!

**Comment by clumsy456** [comment]
谢谢，但是好像没有变化

**Comment by xueruini** [comment]
.lof里还有addvspace么？

Best

-- ruini

**Comment by clumsy456** [comment]
是的，还是有这一句

2016-06-02 14:02 GMT+08:00 Ruini Xue <notifications@github.com>:

**Comment by xueruini** [comment]
应该可以了。
