### ISSUE TITLE
博士后出站报告密级留白

### ISSUE THREAD

**Issue by yeqibin** [xueruini/thuthesis#222]
如果在文档选项里加上secret，把cover里的secretlevel和secretyear注释掉，编译后出现
       ``密  级2016年 ``

怎么能在密级后留白
     ``密 级_____``
或者紧跟着‘‘公开’’
    ``密 级 公开``

谢谢！

**Comment by xueruini** [comment]
level和year留白就行了。

Best

-- ruini

**Comment by yeqibin** [comment]
用了个笨方法，修改thuthesis.cfg文件：
     ``\def\thu@secretyear{}``
      `` \thu@secretyear  ``

**Comment by xueruini** [comment]
\secretlevel{}
\secretyear{}

就可以。

Best

-- ruini

**Comment by yeqibin** [comment]
必须去掉文档选项secret，然后
\secretlevel{密级} 
\secretyear{}

**Comment by yeqibin** [comment]
否则加secret选项而level和year留白会出现：
密级 二字消失，只留横线

**Comment by yeqibin** [comment]
加secret选项，密级后出现 “年“字

**Comment by xueruini** [comment]
奥
