### ISSUE TITLE
名字“喆”乱码，如何解决？>.<

### ISSUE THREAD

**Issue by lbx6z** [xueruini/thuthesis#223]
环境：Ubuntu
![1](https://cloud.githubusercontent.com/assets/6837297/15812201/587a7754-2be4-11e6-95d0-ae941b469736.png)

**Comment by xueruini** [comment]
仿宋字体似乎没有这个字。可以这样 {\songit 喆}

Best

-- ruini

**Comment by xueruini** [comment]
我这里不改字体的截图：
![image](https://cloud.githubusercontent.com/assets/1863/15817359/42ec871c-2c0a-11e6-829d-64c9bf874d66.png)

这是用了\songti的：
![image](https://cloud.githubusercontent.com/assets/1863/15817396/6c8441be-2c0a-11e6-9c31-a9a4a700105a.png)

**Comment by bigeagle** [comment]
这个原因就是 ubuntu 的 fandol 字体字不够。

**Comment by lbx6z** [comment]
@bigeagle 所以该咋解决？

**Comment by bigeagle** [comment]
找个带「喆」的仿宋字体装上，然后
```
\setCJKfamilyfont{zhfs}{the fangsong u just installed, e.g. 仿宋}
```

这问题在哪儿都很常见，我名字里也带生僻字，各种人做的带我名字的ppt，字体都不对。

**Comment by bigeagle** [comment]
@xueruini 所以说为什么一定要有个用户上手就能改的custom-font文件

**Comment by xueruini** [comment]
字体配置话题太广泛，这句话：

\setCJKfamilyfont{zhfs}{the fangsong u just installed, e.g. 仿宋}

的参数也需要工具获取。


Best

-- ruini

**Comment by bigeagle** [comment]
@xueruini 参数让用户自己设置嘛，现在从文档到样例，没有一个地方能告知如何设置字体的，完全依赖ctex，而ctex在非windows下又依赖fandol半成品……

而且fandol黑体和中易黑体差别很明显，一些院系（电子系）格式检查直接不过，这让非windows用户怎么办？

我不认为以前用python脚本生成配置文件是个好办法，那时候脚本运行不成功，则thuthesis无法编译；

我只是说，有一个开箱即用的默认配置(ctex)，必要的时候，让用户看文档，有一个现成的简单的配置文件可以改，这样才是友好的。

**Comment by bigeagle** [comment]
no offence, 现在题主就需要仿宋字体，把「喆」打出来，用户怎么做比较合适？
难道是去```/path/to/texlive/2015/texmf-dist/tex/latex/ctex/fontset```里把 ```ctex-font-windows.def``` 拷贝出来，按照自己的配置改了，然后再改 ```thuthesis.cls`` ?

**Comment by lbx6z** [comment]
好了，感谢！！！

**Comment by xueruini** [comment]
> no offence, 现在题主就需要仿宋字体，把「喆」打出来，用户怎么做比较合适？
> 难道是去/path/to/texlive/2015/texmf-dist/tex/latex/ctex/fontset里把 ctex-font-windows.def 拷贝出来，按照自己的配置改了，然后再改 thuthesis.cls?

开箱即用在fontset并不容易。如果不熟悉ctex-font-xxx.def格式，即便提供了例子文件也不知如何改。同时，例子最好严格按照def的格式，以兼容不同的编译方式。

因此，我觉得写一篇基于ctex的字体配置wiki，详细解释def中各项配置是什么，相关参数如何获取，更有效。 #217 的comment也是这个意思。
