### ISSUE TITLE
附录外文文献翻译原文索引

### ISSUE THREAD

**Issue by math222** [xueruini/thuthesis#224]
附录中的文献书面翻译要加个原文索引，如何实现？
![image](https://cloud.githubusercontent.com/assets/19402510/15823169/148a9298-2c2c-11e6-94ba-c5188aee40ae.png)

**Comment by xueruini** [comment]
例子里面有：

https://github.com/xueruini/thuthesis/blob/master/data/appendix01.tex#L175-L180

**Comment by math222** [comment]
嗯，主要是“参考文献”这个标题，用section的话会靠左，怎么改成居中呢？

**Comment by xueruini** [comment]
必须要居中么？自己拼一个居中，加粗，特定字号的文字。

**Comment by math222** [comment]
中文的参考文献应该都是居中的。所以现在就是要调节章节标题了？又得学习一个了

**Comment by xueruini** [comment]
```latex
\noindent\begin{center}\heiti\sihao 参考文献\end{center}
```

**Comment by math222** [comment]
谢谢，建议放进例子的附录B中。

**Comment by DingkunLiu** [comment]
![image](https://user-images.githubusercontent.com/19831868/41816029-604f9010-77ad-11e8-8b7b-12a47108c980.png)
目前对参考文献的格式要求是这样的，请问该怎么实现？

**Comment by cyz14** [comment]
@DingkunLiu 我试着用 vspace 调了一下间距。标题的段前似乎还不太对，其他看起来还行。
```
\vspace{20pt}
\noindent\begin{center}{\songti\xiaosi 书面翻译对应的原文索引}\end{center}
\vspace{-13pt}
\begin{translationbib}
    \item Donald E. Knuth. The \TeX book. Addison-Wesley, 1984. ISBN: 0-201-13448-9
\end{translationbib}
```
