### ISSUE TITLE
请问如何解决hyperref的warning?

### ISSUE THREAD

**Issue by klory** [xueruini/thuthesis#225]
[1] Package hyperref Warning:Token not allowd in a PDF string (Unicode): ...

[2] pdfTeX warning (ext4): destination with the same identifier (name{page.I}) has been already used, duplicate ignored...

[3] pdfTeX warning (ext4): destination with the same identifier (name{equation.A.1.1}) has been already used, duplicate ignored

模板是最新的v5.3.1，TexLive 2015, pdfLatex, 使用WinEdt 10.1编译的。

**Comment by xueruini** [comment]
> [1] Package hyperref Warning:Token not allowd in a PDF string (Unicode): ...

可以不管，有些 TeX 指令不影响。 

> [2] pdfTeX warning (ext4): destination with the same identifier (name{page.I}) has been already used, duplicate ignored...
> 
> [3] pdfTeX warning (ext4): destination with the same identifier (name{equation.A.1.1}) has been already used, duplicate ignored

默认是不会出这个问题的，是不是加了什么包？

**Comment by klory** [comment]
我就是直接编译的main.tex，就出了这个问题……是不是这3种警告都没什么影响？

**Comment by klory** [comment]
我就是直接编译的main.tex，就出了这个问题……是不是这3种警告都没什么影响？

**Comment by xueruini** [comment]
我看了一下，默认编译只有第一个warning，后两个是没有的。

第一个warning不影响。

**Comment by klory** [comment]
那我再仔细研究下，我的还是有……

**Comment by nanmu42** [comment]
第一个貌似是因为比较特殊的文字造成的，比如化学式，ccwd这一类。
创建pdf书签时，hyperref 会先给出warning再用替代字符替代特殊文字。
比如化学式的下标变正文，ccwd变普通空格。
这个好像是可以定制的，上下标好像是定义了一款字符，可以用在pdf书签里的。

klory <notifications@github.com> 於 2016年6月15日週三 10:59 寫道：

**Comment by klory** [comment]
谢谢两位
