### ISSUE TITLE
关于索引和目录的一些问题

### ISSUE THREAD

**Issue by liuxiang94** [xueruini/thuthesis#227]
找教务老师查了一下格式，老师说不要让附录里面的公式、图片和表格出现在文末的公式索引、图片索引和表格索引中。

同时附录里面的章节标题也不要出现在目录中，也就是说直接是这种结构
附录A xxx
附录B xxx

而不要做成包含附录章节的这种结构
附录A xxx
  A.1 xxx
  A.2 xxx
附录B xxx
  B.1 xxx
  B.2 xxx

不知道有没有高手能够提供好的解决方案？多谢

**Comment by nanmu42** [comment]
似乎可以在`\backmatter`那里做点文章。

**Comment by math222** [comment]
附录不出现在索引里作者在thuthesis.pdf里专门提到了吧，可以去看看

**Comment by liuxiang94** [comment]
thuthesis.pdf上面写的是
“如果的确想让其编号，但又不想出现在索引中的话，目前模板暂不支持。”
@math222

**Comment by xueruini** [comment]
> thuthesis.pdf上面写的是
> “如果的确想让其编号，但又不想出现在索引中的话，目前模板暂不支持。”

哈哈

**Comment by nanmu42** [comment]
薛老师，别这样…… :P

Ruini Xue <notifications@github.com>于2016年6月23日周四 下午3:31写道：

**Comment by nanmu42** [comment]
:+1:

**Comment by MegaThomas** [comment]
\thu@chapter 编译时提示 ! Undefined control sequence.

**Comment by knwng** [comment]
可以在附录里把\section换成\section*，chapter和subsection同理，就可以不在目录里显示了
