### ISSUE TITLE
Mac Error Cannot Find "FangSong" @ "make shuji"

### ISSUE THREAD

**Issue by songpeng** [xueruini/thuthesis#229]
1. 系统及软件版本:
   Mac: 10.11.6 EI Captan
   Texlive: 2016 (Use MacTex)
2. 编译过程的情况
    make doc OK
    make thuthesis OK
    make shuji Error @ FangSong not found.
3. 尝试
    Run zhfont.py 按照Issue中的修改建议修改了pyhton脚本，运行可以选择字体选项，最后输出错误：缺少宋体，黑体和楷体。。。
    shuji.tex  中ifxetex 后有选择FangSong的，可否修改为其他呢。
4. 杂问：
    zhfont.py 不在repository是不推荐了么？
    我的doc及thuthesis编译正常，是不是我还是有宋体等字体的？修改shuji中的字体配置是不是不好，或修改的话有推荐么？
谢谢！初次用thuthesis，平时用latex也是多用模板，没有理解里面的机制，问题如有不当，请指出。
松鹏

**Comment by mengfl05** [comment]
直接改 shuji.tex 里面那个 FangSong 的设置，改成你系统里面的仿宋就好，Mac 是不是华文仿宋

**Comment by songpeng** [comment]
mac 里面有华文仿宋，但我不知道怎么具体修改参数。。。

**Comment by mengfl05** [comment]
直接把那个 FangSong 换成 STFangsong 试试

**Comment by xueruini** [comment]
> mac 里面有华文仿宋，但我不知道怎么具体修改参数。。。

```shell
$ fc-list | grep -i fangsong
/Library/Fonts/华文仿宋.ttf: STFangsong:style=常规体,標準體,Ordinær,Normal,Regular,Normaali,Regolare,レギュラー,일반체,Regulier,Обычный
/Users/xueruini/Library/Fonts/仿宋_GB2312.ttf: 仿宋_GB2312,FangSong_GB2312:style=Regular
/Users/xueruini/Library/Fonts/AdobeFangsongStd-Regular.otf: Adobe 仿宋 Std,Adobe Fangsong Std,Adobe Fangsong Std R,Adobe 仿宋 Std R:style=R,Regular
/Library/Fonts/Microsoft/Fangsong.ttf: 仿宋,FangSong:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,Arrunta
/Users/xueruini/Library/Fonts/simfang.ttf: 仿宋_GB2312,FangSong_GB2312:style=Regular
```

第一个冒号后面的str，STFangsong

**Comment by songpeng** [comment]
@mengfl05  @xueruini  谢谢你们，改为STFangsong已经可以。
另外，grep -i 应该是Fangsong, 而不是fangsong，后者没有结果，但这个是小事情。
谢谢~
