### ISSUE TITLE
longtable with tabularx

### ISSUE THREAD

**Issue by songpeng** [xueruini/thuthesis#230]
你好，
我想加入long table 到附录，到需要用到tabularx的 X的设置。给的例子用longtable 无法识别X。
求教怎么设置呢？
谢谢~
松鹏

**Comment by songpeng** [comment]
我用了tabu包解决了。看起来还可以。

**Comment by xueruini** [comment]
> 我用了tabu包解决了。看起来还可以

这个 package 看着很 fancy 啊

**Comment by nanmu42** [comment]
tabu是很全能的一个包。
就是文档写得太花哨（各种意义上的），每次读都有奇特的感觉。:smile:

Ruini Xue <notifications@github.com> 於 2016年10月21日 週五 上午9:54 寫道：

**Comment by songpeng** [comment]
你们好，
我想顺便问下，我今天在插入三个子图按照列的方式时，前两个子图的题注都被盖住了。这怎么调整呢？我让图变小也不行。基本的代码是
```
\begin{figure}
\begin{subfigure}{\linewidth}
\centering
\includegraphics[width=0.8\linewidth]{fig}
\end{subfigure}
... (2次)
\end{figure}
```

**Comment by xueruini** [comment]
eps图？

**Comment by songpeng** [comment]
不，就是PDF的
