### ISSUE TITLE
中文部分的注释是乱码

### ISSUE THREAD

**Issue by c30268056** [xueruini/thuthesis#231]
如题，不知道为啥，不会是因为macos吧？改成utf-8encoding或者中文简体，也一样是乱码。build出来ok

**Comment by c30268056** [comment]
好吧，把IDE从TexShop换成TexStudio就ok了

**Comment by nanmu42** [comment]
有可能是字体方面的原因吗？检查下相关设置？

c30268056 <notifications@github.com> 於 2016年11月8日 週二 下午12:38 寫道：

**Comment by c30268056** [comment]
然后现在不管用哪个编译器，都说missing option:bachelor, master or doctor 但是明明定义了type=master。。。。不知道为什么

**Comment by xueruini** [comment]
> 然后现在不管用哪个编译器，都说missing option:bachelor, master or doctor 但是明明定义了type=master。。。。不知道为什么

不会是用错标点符号了吧？type=master, 这里是英文逗号

**Comment by c30268056** [comment]
并不是呀…
\documentclass[type=master]{thuthesis}
\documentclass[type=[master]]{thuthesis}
都不行 后面加,或者.也不行

**Comment by nanmu42** [comment]
编译下示例文档，如果出现问题更新下发行版。
没出现问题的话直接把示例文档的那行拿过来。

**Comment by c30268056** [comment]
我知道问题了，我没有先更新thuthesis.ins，要拿到了cls和cfg，就不会编译出错。现在到了ctex那一步错误了，我应该要更新一下ctex

**Comment by c30268056** [comment]
开发版还是编译不通，发行版，windows可以了，但是mac还是不行，说什么mac mode不能开启？应该是字体问题，但是我按照设置把字体添加进去了以后，还是不行。已经更行成2016版，也更新到ctex。。。。

**Comment by xueruini** [comment]
贴错误消息

**Comment by c30268056** [comment]
Critical ctex error: "fontset-unavailable" CTeX fontset `mac' is unavailable in current mode. For immediate help type H <return>. }

**Comment by Liam0205** [comment]
@c30268056 
Mac 模式的字体使用华文字体，在 pdfLaTeX 模式下不可用，换成 XeLaTeX 就可以了。
