### ISSUE TITLE
thusetup未定义的命令？

### ISSUE THREAD

**Issue by wozy13** [xueruini/thuthesis#235]
提示的错误是\thusetup, undefined control sequence
我的版本是ctex2.9.2，虽然不适宜编译，但是我手动添加了ctex2.2宏包和thuthesis.cls文件，最后出现了cover.tex里面的\thusetup未定义的问题，请问是什么原因呢？

**Comment by xueruini** [comment]
模板哪个版本？

**Comment by wozy13** [comment]
多谢版主的帮助，我现在已经换到了Ubuntu上，用texlive成功编译了，正在进行综合论文训练的写作。
