### ISSUE TITLE
Window下最新版本的CTex编译不通过

### ISSUE THREAD

**Issue by guohengkai** [xueruini/thuthesis#236]
CTex 2.9.2，Win 8下，编译提示：
! Undefined control sequence.
l.212 \ctexset
              {%

无论是pdflatex还是xelatex都一样。

**Comment by mengfl05** [comment]
ctex 宏包太老了，给 ctex 和相关宏包升个级
简单粗暴的话直接升级所有宏包，或者换成 texlive 2016（学校有镜像，网络安装或者下载 iso 都可以）

**Comment by guohengkai** [comment]
@mengfl05 谢谢！换成texlive并更新ctex到2.2之后就能编译了。
