### ISSUE TITLE
File 'newtxtext.sty' not found

### ISSUE THREAD

**Issue by btp10** [xueruini/thuthesis#238]
win7， texlive，ctex版本2.4.7。
用xelatex或pdflatex编译main报错：File 'newtxtext.sty' not found。
用kpsewhich newtxtext.sty查确实没找到，但是安装路径D:\texlive\2016\texmf-dist\tex\latex\newtx\下确实存在文件newtxtext.sty。请问是怎么回事？如果需要重装的话，如何手动重装newtxtext.sty？

**Comment by mengfl05** [comment]
ctex 2.4.7 什么鬼...确认下是用 texlive 编译的，然后试试 mktexlsr 重建一下文件索引，看行不行....

**Comment by nanmu42** [comment]
他说的是CTeX宏包的版本……
尝试使用TeX Live Manager查找newtxtext宏包并安装，另外，在Manager里可以重建文件索引。
如果以上方法都不奏效，还可以考虑到论文模板宏包源文件里注释掉newtxtext的引入语句，应该只有一句。

Smoulder <notifications@github.com> 於 2017年2月20日 週一 下午6:43 寫道：

**Comment by mengfl05** [comment]
ctex 宏包版本都这么高了....
注释宏包还是不要了吧，不然正文的 Times 字体不是掉了，还得换别的，按理说重建文件索引应该就可以了

**Comment by nanmu42** [comment]
万不得已的办法，系统会自己Fallback。

Smoulder <notifications@github.com> 於 2017年2月20日 週一 下午8:24 寫道：

**Comment by btp10** [comment]
多谢两位。试 了mktexlsr，没有用。
想问一下newtxtext所在的宏包名字就是newtxtext么？我在TeX Live Manager里只找到了newtx, newtxsf和newtxtt。我更新了这三个包，也没用。
另附编译错误如下：
......
(D:\CTEX\MiKTeX\tex\latex\ams\math\amsmath.sty
For additional information on amsmath, use the `?' option.
(D:\CTEX\MiKTeX\tex\latex\ams\math\amstext.sty
(D:\CTEX\MiKTeX\tex\latex\ams\math\amsgen.sty))
(D:\CTEX\MiKTeX\tex\latex\ams\math\amsbsy.sty)
(D:\CTEX\MiKTeX\tex\latex\ams\math\amsopn.sty))

! LaTeX Error: File `newtxtext.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 

用clt+c关掉后显示
! Emergency stop.
<read *> 
         
l.84 \RequirePackage
                    {newtxmath}

这里的宏包newtxmath我在TeX Live Manager里也没有找到。

**Comment by xueruini** [comment]
> 想问一下newtxtext所在的宏包名字就是newtxtext么？我在TeX Live Manager里只找到了newtx, newtxsf和newtxtt。我更新了这三个包，也没用。

是 `newtx`，texhash 都不管用，猜不出来为啥。。。如果着急用可以把 newtx 的几个 sty 放在当前目录

**Comment by btp10** [comment]
把 newtx*.sty放在当前目录确实不报错了。多谢薛神。
