### ISSUE TITLE
能否推出一个英文版的模版

### ISSUE THREAD

**Issue by Shuoming** [xueruini/thuthesis#239]
导师是歪果仁。。。。。
或者我怎么能够把目录正文附录文献等全部改成英文？
cover等程序性内容依然中文。

**Comment by emiapwil** [comment]
Try out [this fork?](https://github.com/xueruini/thuthesis/pull/232)

**Comment by zepinglee** [comment]
基本上只用修改 thuthesis.cfg 即可

**Comment by xueruini** [comment]
#232
