### ISSUE TITLE
paralist宏包与inparaenum环境

### ISSUE THREAD

**Issue by ekaradon-Alexander** [xueruini/thuthesis#240]
自己添加paralist宏包会与THUThesis里预装载的宏包产生冲突吗？

**Comment by xueruini** [comment]
no

**Comment by ekaradon-Alexander** [comment]
在实例文档中导入宏包`\usepackage{paralist}`，`\makecover`命令后报错：

> You can't use `\relax' after \the.
> Undefined control sequence.

**Comment by xueruini** [comment]
似乎的确有点冲突，不过我这里看到的错误跟你不一样

```
(/usr/local/texlive/2016/texmf-dist/tex/latex/newtx/ts1ntxtlf.fd)
! Undefined control sequence.
\enit@enditemize ->\enit@after
                               \endlist \ifx \enit@series \relax \else \ifnu...
l.29
```

**Comment by bigeagle** [comment]
可以使用 `enumitem` 宏包的 `itemize*`, `enumerate*` 环境，不过 thuthesis 没有给 `enumitem` 加入 `inline` 选项，需要在 `\documentclass` 之前加一句 `\PassOptionsToPackage{inline}{enumitem}`。

**Comment by mfs6174** [comment]
可以重复@xuruini 所说的问题, 同时@bigeagle的替代方案是好用的, 感谢
