### ISSUE TITLE
编译出错：zxxr17z字体缺失

### ISSUE THREAD

**Issue by sc071139** [xueruini/thuthesis#241]
工作在win7系统下，MikTeX版本2.9.6200，CTeX版本2.4.7，Texmaker版本4.5，使用XeLaTeX对thuthesis v5.3.1中的main.tex直接进行编译。编译失败后miktex-makemf.log文件显示（省略时间戳，下同）

> FATAL miktex-makemf - The zxxrl7z source file could not be found

而在xelatex.log中显示
> FATAL xelatex - Invalid argument
> FATAL xelatex - Info: 
> FATAL xelatex - Source: libraries\miktex\texandfriends\include\miktex\c4p\C4P.h
> FATAL xelatex - Line: 606

**Comment by xueruini** [comment]
weird
