### ISSUE TITLE
如何在正文部分为奇偶页设置不同的页眉

### ISSUE THREAD

**Issue by bitxue** [xueruini/thuthesis#245]
比如：
奇数页为“作者  论文题目”
偶数页为“第*章  章节标题”

模板上好像奇偶页是一样的。有办法设置吗？
谢谢！

**Comment by mengfl05** [comment]
模板加载了 fancyhdr 宏包，直接在导言区改就行，直接看宏包手册或者网上随便找找，简单的使用资料挺多的，比方说这种 http://blog.sina.com.cn/s/blog_5e16f1770100g46l.html，找本入门的教材应该也会讲

另外，要改这个的话，看看学校的论文规范里面是不是明确规定了页眉的内容吧

**Comment by bitxue** [comment]
我是外校的，论文规范里明确规定了奇偶页页眉不同。我再试试吧，多谢~ @mengfl05

**Comment by nanmu42** [comment]
请参阅CQUThesis的用户手册的实现细节部分，解决了一样的需求。
https://github.com/nanmu42/CQUThesis

Junjie XUE <notifications@github.com> 於 2017年3月31日 週五 上午12:46 寫道：

**Comment by bitxue** [comment]
谢谢！
最后用了中科院大学的ucasthesis，应该是参考thuthesis的，默认设置了奇偶页不同页眉。
