### ISSUE TITLE
模板文档中的代码部分出现乱码

### ISSUE THREAD

**Issue by Stone-Zeng** [xueruini/thuthesis#246]
更新至 v5.3.2 后，发现模板文档 `thuthesis.pdf` 中的示例代码和宏包代码都出现乱码。

（图片传不了，好尴尬……）

**Comment by Stone-Zeng** [comment]
`main.pdf` 的封面（姓名、导师什么的）也是如此。

复制出来都是正常的，似乎是华文仿宋的问题。是不是用了繁体版的字体？

**Comment by xueruini** [comment]
编译出来的pdf是乱码还是 editor 打开 tex 文件是乱码？

**Comment by Stone-Zeng** [comment]
CTAN 上面下载的 pdf，不是我编译的。
用 Adobe Acrobat DC 和 SumatraPDF v3.1.2 打开都是乱码，但用 Chrome 和 Edge 浏览器打开都是正常。

**Comment by xueruini** [comment]
这个。。。

**Comment by Stone-Zeng** [comment]
为了发个图还要逼我翻墙。。。

这两张是 SumatraPDF 打开的：
![1](https://cloud.githubusercontent.com/assets/18233088/24834115/b36a9c9a-1d0e-11e7-8749-e2ee8ccc39d4.PNG)
![2](https://cloud.githubusercontent.com/assets/18233088/24834116/b36e23ec-1d0e-11e7-94ec-e5fc94441fa9.PNG)

这一张是 Adobe Acrobat 打开的：
![3](https://cloud.githubusercontent.com/assets/18233088/24834124/febf6ae0-1d0e-11e7-867d-9326bccf4c06.PNG)

**Comment by xueruini** [comment]
![image](https://cloud.githubusercontent.com/assets/1863/24853063/563af048-1e0c-11e7-888d-0819eb38ab93.png)

可能是字体，我是 mac 下编译的

**Comment by toubun** [comment]
STFangsong 未嵌入子集

**Comment by bigeagle** [comment]
的确是字体问题，今天讲课遇到了……
于是重编译一份出来搞定。

**Comment by Stone-Zeng** [comment]
v5.4.0 仍然有这个问题，同样是 STFangsong 没有嵌入子集。

**Comment by zepinglee** [comment]
在 #323 中一起修复了

**Comment by Stone-Zeng** [comment]
目前 v5.4.4 里面显示是正常的。
