### ISSUE TITLE
博士生，英文参考文献除了首字母全部小写，不应该小写如何解决

### ISSUE THREAD

**Issue by guojian6616** [xueruini/thuthesis#247]
@article{zhang2016shandong,
  title={The Shandong Shidao Bay 200 MW e High-Temperature Gas-Cooled Reactor Pebble-Bed Module (HTR-PM) Demonstration Power Plant: An Engineering and Technological Innovation},
  author={Zhang, Zuoyi and Dong, Yujie and Li, Fu and Zhang, Zhengming and Wang, Haitao and Huang, Xiaojin and Li, Hong and Liu, Bing and Wu, Xinxin and Wang, Hong and others},
  journal={Engineering},
  volume={2},
  number={1},
  pages={112--118},
  year={2016},
  publisher={Elsevier}
}

效果如下
<img width="806" alt="2017-04-07 1 18 27" src="https://cloud.githubusercontent.com/assets/15259582/24767045/3861970e-1b30-11e7-88f2-ce269a99273f.png">
如何原样插入参考文献？

**Comment by mengfl05** [comment]
不希望被 bibtex 处理的部分用大括号括起来，这样

title = {LaTeX {LaTeX}}
