### ISSUE TITLE
一个定理环境字体设置的问题

### ISSUE THREAD

**Issue by mengfl05** [xueruini/thuthesis#251]
.dtx 的 1745 和 1746 两行，特别是 1745 设置定理环境体的字体用了 \songti，会导致环境体里面用 \textbf{...} 命令（或者之类的命令，\bfseries、\textit{...} 什么的）的时候去找加粗的宋体，和 \setCJKmainfont 的设置不太一致，是否只用 \rmfamily 就可以？另外模板里面多处字体设置都是这么做的，是否需要修改？

另外，这两行放在了 .cls 里面，这里面也没有其他定理环境相关的设置了，是否和其他定理环境设置一起放在 .cfg 里面更好些？

**Comment by xueruini** [comment]
> .dtx 的 1745 和 1746 两行，特别是 1745 设置定理环境体的字体用了 \songti，会导致环境体里面用 \textbf{...} 命令（或者之类的命令，\bfseries、\textit{...} 什么的）的时候去找加粗的宋体，和 \setCJKmainfont 的设置不太一致，是否只用 \rmfamily 就可以？另外模板里面多处字体设置都是这么做的，是否需要修改？

good idea!

> 
> 另外，这两行放在了 .cls 里面，这里面也没有其他定理环境相关的设置了，是否和其他定理环境设置一起放在 .cfg 里面更好些？

make sense.

Will you create a PR? 😄

**Comment by mengfl05** [comment]
好吧呀，我尽量弄一下，状况好的话过两天五一弄出来，状况不好的话....呃....
