### ISSUE TITLE
请教关于“单倍行距”的定义

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#253]
我注意到\thu@def@fontsize定义的字号默认为“单倍行距”，我理解的“[单倍行距](http://bbs.ctex.org/forum.php?mod=viewthread&tid=56766)”应该是相邻两行字之间的空白是 1 倍的字号大小。换成LaTeX的语言，就是两行的基线距离是字号的 2 倍。但是
```
\def\thu@def@fontsize#1#2{%
  \expandafter\newcommand\csname #1\endcsname[1][1.3]{%
    \fontsize{#2}{##1\dimexpr #2}\selectfont}}
```
这里默认设置 1.3 倍，再加上 ctex 的默认 \linspread{1.3}，所以实际是 1.69 倍的字号大小。
所以想请教下你们？

**Comment by xueruini** [comment]
> 这里默认设置 1.3 倍，再加上 ctex 的默认 \linspread{1.3}，所以实际是 1.69 倍的字号大小。
> 所以想请教下你们？

凑 word 的效果。

**Comment by zepinglee** [comment]
原来是这样……
