### ISSUE TITLE
导师职称需要两端对齐

### ISSUE THREAD

**Issue by shengzhangdexiaozouzi** [xueruini/thuthesis#255]
如果指导老师有两个或者有联合指导老师，并且当两个导师的职称不同的时候，需要将职称两端对齐，这个需要怎么改

**Comment by aixlx** [comment]
目前的模板中， csupervisor、cassosupervisor、ccosupervisor是将姓名和职称放在一起的，暂不能做到导师姓名、职称分别对齐，作为临时解决方案，可以添加 \hspace*{1pt} 手动对齐，比如：
```
# cover.tex
csupervisor={某某某\hspace*{24pt}副研究员},
ccosupervisor={某某某\hspace*{24pt}研\hspace*{24.5pt}究\hspace*{24.5pt}员}, % 联合指导老师
```
![image](https://cloud.githubusercontent.com/assets/7615494/25889058/18f4945e-359b-11e7-885a-a04622c448ee.png)

**Comment by xueruini** [comment]
像你这样自己拼盒子就挺好的 :)

不然就得把老师姓名和职称拆分成两个变量存。

**Comment by zepinglee** [comment]
可以使用 \makebox[6em][s]{研究员}，s 参数可以两端对齐

**Comment by xueruini** [comment]
> 可以使用 \makebox[6em][s]{研究员}，s 参数可以两端对齐

还是手动处理，模板里就不切分了
