### ISSUE TITLE
求教，将main.tex文件编译后出现这种问题，该如何解决？

### ISSUE THREAD

**Issue by asasasw1234** [xueruini/thuthesis#256]
使用windows系统mixtex进行编写

![17 05 10 2045_1](https://cloud.githubusercontent.com/assets/28591424/25899255/b21436e6-35c1-11e7-9d1c-77725cd04c08.png)
Runaway argument?
21:33:50\relax  \ProvidesExplClass {ctexbook} {\ExplFileDate }{2.4.9}\ETC.
! Paragraph ended before \GetIdInfoAuxSVN was complete.
<to be read again> 
                   \par 
l.725     \par

所使用的ctex版本以更新至2.4.9，实在不清楚该如何解决，还请薛老师帮忙看一下，谢谢！

**Comment by asasasw1234** [comment]
![17 05 10 2104_1](https://cloud.githubusercontent.com/assets/28591424/25899926/458877f0-35c4-11e7-91ce-8636b39cdb89.png)
ctex宏包版本业已最新

**Comment by xueruini** [comment]
xelatex main?

**Comment by asasasw1234** [comment]
是用pdflatex的，刚去试了一下xelatex，也是一样的问题。

**Comment by Stone-Zeng** [comment]
试一试把 `l3kernel` 更新一下，或者干脆更新所有宏包。
