### ISSUE TITLE
eqnarray公式最后一个标号无法对齐

### ISSUE THREAD

**Issue by btp10** [xueruini/thuthesis#257]
使用eqnarray写多行公式，然后最后一行公式的标号后会多出1个字符。
例如在第一章写如下公式
\begin{eqnarray}
min~x^2+y^2 \\\\
s.t. x + y \ge 10\\\\
x - y \le 2
\end{eqnarray}
对应的编译效果三行标号分别是(1-1)(1-2)和(1-3)
其中(1-1)和(1-2)完全右对齐，(1-3)没有完全对齐，其右侧多了1个字符或者说标号整体左移了一个字符。
求问各位大神该如何解决？

**Comment by Stone-Zeng** [comment]
用 `align` 环境，不要用 `eqnarray`。不用 `eqnarray` 的原因可以看 [tugboat 33:1](http://tug.org/TUGboat/tb33-1/tb103madsen.pdf)。

**Comment by btp10** [comment]
多谢@Stone-Zeng
