### ISSUE TITLE
在图表标题中出现文献引用的问题

### ISSUE THREAD

**Issue by chaonan99** [xueruini/thuthesis#258]
如果在图表标题中出现文献引用，插图和表格索引中也会带上引用，这样科学吗？有没有办法取消插图索引标题里的引用，只在原标题出现，并且也不换行呢？（用\caption*{}包起来会换一行）

**Comment by zepinglee** [comment]
`\caption` 的内容会原封不动地写到 `\listoffigures`，这个没法阻止，除非你自己把 `\caption` 重新实现。
你可以换种写法，比如在正文 `\ref` 引述图的地方 `\cite`。

**Comment by mengfl05** [comment]
试试 \caption[abc]{abc\cite{xxx}} 这样的写法？

**Comment by chaonan99** [comment]
> 试试 \caption[abc]{abc\cite{xxx}} 这样的写法？

Works like magic!!!

**Comment by mengfl05** [comment]
\section{}、\subsection{} 之类的命令都有类似的写法，\caption{} 可以参考下 caption 宏包手册，看起来是 caption 宏包实现的
