### ISSUE TITLE
符号表能否加入对nomencl包的支持或者加入自动排序功能？

### ISSUE THREAD

**Issue by teancake** [xueruini/thuthesis#259]
xueruini 您好，非常感谢您开发了这么好一个模板，想请教一下，能否在符号对照表中加入对nomencl包的支持或者加入自动排序功能呢？谢谢您！

**Comment by xueruini** [comment]
nomencl 看起来很不错啊，样式上调整一下似乎就可以

**Comment by zepinglee** [comment]
@xueruini 这个 issue 居然有一年多历史了……
`nomencl` 宏包会强制进行排序，可能有同学不需要这个功能，所以我用 `ctexhook` 的功能在检测到调用 `nomencl` 宏包时会自动配置格式。

**Comment by xueruini** [comment]
> @xueruini 这个 issue 居然有一年多历史了……
> `nomencl` 宏包会强制进行排序，可能有同学不需要这个功能，所以我用 `ctexhook` 的功能在检测到调用 `nomencl` 宏包时会自动配置格式。

PR 里看到了，实际上用这个包挺好的，用的更加规范

**Comment by zepinglee** [comment]
我觉得灵活性也很重要，像这本书（https://github.com/goodfeli/dlbook_notation/blob/master/notation.tex ）就是用的 `tabular` 环境
