### ISSUE TITLE
调整 author-year refs 样式

### ISSUE THREAD

**Issue by xueruini** [xueruini/thuthesis#260]

**Comment by zepinglee** [comment]
《写作指南》 3.3 节要求：
> 采用“著者-出版年制”组织参考文献时，每条文献不必加序号。采用悬挂格式， 悬挂缩进 2 个汉字符或 4 个字符。

3.4.2节有个例子：
![screen shot 2017-05-20 at 12 49 57 pm](https://cloud.githubusercontent.com/assets/12290822/26273091/f13802e4-3d5a-11e7-8227-47dc7b128eb3.png)

看起来是首行缩紧两字（同 numerical ），悬挂缩进再多两字。

**Comment by JazzeYoung** [comment]
可以使用makebst.tex自己生成吗？能给个选项的选择示意吗？

**Comment by zepinglee** [comment]
不能，我手写的 bst；
这个 issue 与 bst 无关；

**Comment by JazzeYoung** [comment]
大概找到了，但还是不太符合，需要帮忙……在thuthesis.dtx里面添加这些，可以生成，但格式比较奇怪，我不太熟悉latex，希望能帮忙调整一下：
![122](https://user-images.githubusercontent.com/11983806/26956065-ca213f5c-4ced-11e7-9a32-7a205d3d177c.PNG)
