### ISSUE TITLE
文献格式标识

### ISSUE THREAD

**Issue by hlltc** [xueruini/thuthesis#262]
文献格式标识如何自动生成，例如 [J] [D] [M]

**Comment by zepinglee** [comment]
在 BibTeX style （bst 文件）里面生成的

**Comment by hlltc** [comment]
@zepinglee 谢谢回复。可是我最终生成的pdf论文没有这些标识。是在bib文件里做什么处理吗？

**Comment by zepinglee** [comment]
如果你使用了 master 分支的版本，应该不需要

**Comment by hlltc** [comment]
非常感谢，我用了最新的模版以及-numerical.bst后有标识了。有个新的小问题，因为有些参考文献没有出版地，怎么处理 生成的 [S.l.: s.n.] 问题呢？

**Comment by zepinglee** [comment]
我也觉得很丑，但是按照学校的规定就应该这么写。

@xueruini 这里要不要擅自修改一下？

**Comment by hlltc** [comment]
@zepinglee 你好，refs.bib中没有专利文献的样例，不知道有没有支持？

**Comment by zepinglee** [comment]
@patent

详情见 https://github.com/zepinglee/gbt-7714-2015
