### ISSUE TITLE
文献的直接和间接引用，以及一些小问题

### ISSUE THREAD

**Issue by chaonan99** [xueruini/thuthesis#263]
刚去论文格式审查跪了，，，总结一些论文格式的问题（针对本科生中文论文）

1. 学校要求文献要分直接和间接引用，例如：
  * 直接引用不用上标：文献[15]表明。。。
  * 间接引用用上标：Li F. 等人^[15] 提出了。。。
这个如何实现呢？
2. 除了标题都要首行缩进，如`\paragraph`, 以及各种定理引理例子等环境。应该如何缩进？
3. `enumerate` 环境也要求首行缩进并且后文不缩进，如何改变设置？

谢谢！

**Comment by chaonan99** [comment]
1 的解决方法
https://tex.stackexchange.com/questions/94178/temporarily-disable-superscript-in-citation

2 的解决方法
https://tex.stackexchange.com/questions/321373/indent-only-first-line-of-newtheorem
thuthesis.cfg 28行改为`\theoremheaderfont{\hspace*{\parindent}\bfseries}`

3 的解决方法
https://tex.stackexchange.com/questions/268609/indent-only-first-line-in-customized-enumerate

**Comment by zepinglee** [comment]
1. 有 `\cite{⟨key⟩}` 和 `\inlinecite{⟨key⟩}`，使用前要看说明文档
