### ISSUE TITLE
windows下改成新的bst和cls文件后编译不过。

### ISSUE THREAD

**Issue by YaoXinatTHU** [xueruini/thuthesis#265]
改回原来的bst和cls文件就能编译。。。

**Comment by zepinglee** [comment]
报的的什么错？能不能提供一下相关的 bib entry？

**Comment by YaoXinatTHU** [comment]
![image](https://cloud.githubusercontent.com/assets/20432547/26480434/5f7459aa-420c-11e7-9a6c-f1a7824368ab.png)

**Comment by zepinglee** [comment]
我看不出这个和 bst 有什么关系

**Comment by xueruini** [comment]
我这里都能编译

用 xelatex
