### ISSUE TITLE
加粗的宋体如何设置？

### ISSUE THREAD

**Issue by chaonan99** [xueruini/thuthesis#266]
格式审查的老师说 直接用\textbf{} 或 \bfseries 好像是黑体？那么加粗的宋体应该怎么写呢？

我写
```
{\bfseries \songti balabala}
```
报了warning:
> LaTeX Font Warning: Font shape `TU/SimSun(1)/bx/n' undefined(Font) using `TU/SimSun(1)/m/n' instead on input line 80.

然后并没有加粗中文（英文加粗了）

**Comment by Stone-Zeng** [comment]
中易宋体（SimSun）是没有对应粗体的。

如果你用的是 XeLaTeX 编译，可以使用伪粗体：
``` TeX
\setCJKmainfont{SimSun}[ItalicFont = KaiTi, AutoFakeBold = true]
```
这里面的 `ItalicFont = KaiTi` 确保宋体对应的斜体是（中易）楷体（跟 `ctex` 宏集保持一致）。

当然也可以换一个自带粗体的宋体，比如 FandolSong（如果已经安装了宏包 `fandol` 的话）：
``` TeX
\setCJKmainfont{FandolSong}[ItalicFont = FandolKai]
```
不出意外的话粗体是自动解析的。

使用的话用正常用 `\textbf` 或者 `\bfseries` 就可以了。
