### ISSUE TITLE
应当使用黑体而不是雅黑

### ISSUE THREAD

**Issue by MegaThomas** [xueruini/thuthesis#271]
在Windows 10, MikTex, XeLaTeX编译的情况下，正文中标题使用了雅黑字体。格式审查不幸被认为不合格。通过增加自定义的`ctex-fontset-⟨name⟩.def`文件强行解决了。

还有更优雅的解决办法么？

**Comment by zepinglee** [comment]
ctex 默认会在 windows 10 调用微软雅黑，所以只能手动改了。

但是，微软雅黑不是黑体？白马不是马？

**Comment by mengfl05** [comment]
这里黑体一般特指原来 Win 系统带的那套中易的黑体吧，至少用个长得比较像的，雅黑这个差的太远了

**Comment by zepinglee** [comment]
我知道是这个意思；不过，很多人说微软雅黑不适合作为印刷的字体来使用

**Comment by MegaThomas** [comment]
呃我这个被认为不合格可能是个例，运气不好吧。总之还是把解决方法贴一下吧：

1. 找到`ctex-fontset-⟨name⟩.def`的路径，复制一个`ctex-fontset-windowsnew.def`并重命名，比如`ctex-fontset-hehehe.def`
2. 打开`ctex-fontset-hehehe.def`，将其中的`msyh`，`Microsoft~YaHei`等换成`SimHei`。我用的是XeLaTeX，所以只替换了对应的`if`块里的雅黑，也就是95~107行里的。
3. 刷新文件索引（MiKTeX的settings里点Refresh FNDB）
4. `thuthesis.cls`里将
```latex
\LoadClass[a4paper,openany,UTF8,zihao=-4,scheme=plain]{ctexbook}
```
改为
```latex
\LoadClass[a4paper,openany,UTF8,zihao=-4,scheme=plain,fontset=none]{ctexbook}
```
5. 再在`main.tex`导言区中增加
```latex
\ctexset{fontset=hehehe}
```

**Comment by zepinglee** [comment]
不知道 fontset=windowsold 行不行

**Comment by alick** [comment]
根据 ctex 文档，我猜  thuthesis 指定 `fontset=windowsold`，提醒用户系统上需要有中易字体即可。

**Comment by Stone-Zeng** [comment]
直接用 `\setCJKsansfont{SimHei}` 之类的不可以吗？

**Comment by alick** [comment]
应该也是可以的。我是说模板本身就应该设置好这些。

Regards,

**Comment by xueruini** [comment]
> 根据 ctex 文档，我猜 thuthesis 指定 fontset=windowsold，提醒用户系统上需要有中易字体即可。

现在没指定字体，可以写在例子里

**Comment by xueruini** [comment]
e6c0ff9989035f4e4670a8f70f4eb1213698d2fd
