### ISSUE TITLE
博士后封面与学校样式不一致

### ISSUE THREAD

**Issue by yaojyilx** [xueruini/thuthesis#274]
博士后报告的封面和题名页与学校的要求不一致，
我不太会改，能否更新一下？
非常感谢

学校要求文件：
http://postdoctor.tsinghua.edu.cn/upload_files/file/20170425/1493097422004056634.doc

**Comment by xueruini** [comment]
看哪位有功夫给个 PR 吧

**Comment by dizhang** [comment]
这个issue能否修改下？

**Comment by dizhang** [comment]
@zepinglee 这个问题更重要些，几个同学因为这个问题用了别的模板。

**Comment by zepinglee** [comment]
ok，我提高一些这个 issue 的 priority。

用了别的模板？如果格式符合要求的话直接整合过来就好了，可以给个链接吗？

**Comment by dizhang** [comment]
> ok，我提高一些这个 issue 的 priority。
> 
> 用了别的模板？如果格式符合要求的话直接整合过来就好了，可以给个链接吗？

有人用了sistthesis（别人直接分享给我过，我也没找到比较新的版本），只是首页满足要求，其他的并不满足需求。不过博士后的报告对于格式要求相对于学位论文来说没有那么严。所以满足首页要求的基本前提达到，其他的没有那么严格。

**Comment by dizhang** [comment]
> ok，我提高一些这个 issue 的 priority。
> 
> 用了别的模板？如果格式符合要求的话直接整合过来就好了，可以给个链接吗？

可以参考下：https://github.com/sslchi/SISTThesis/

**Comment by xueruini** [comment]
> 可以参考下：https://github.com/sslchi/SISTThesis/

这不是 thu 的吧？

**Comment by dizhang** [comment]
> > 可以参考下：https://github.com/sslchi/SISTThesis/
> 
> 这不是 thu 的吧？

对，这个不是thu的。不过它的博士后模板的首页跟现在学校给出的word差不多。

**Comment by zepinglee** [comment]
我基本改出了一版封面，不过还有几个问题：

1. “博士后”的英文似乎很少使用“postdoctor”，一般用“postdoc”或者“postdoctoral”。
2. 单独分出的 cfg 文件有什么作用？我觉得像 `\def\thu@postdoctor@report@title{博士后研究工作报告}` 这样没有必要暴露给用户，而且使得写 `\thu@first@titlepage` 时需要反复跟 cfg 的内容进行比对，有点不太方便。

**Comment by xueruini** [comment]
> 2\. 单独分出的 cfg 文件有什么作用？我觉得像 `\def\thu@postdoctor@report@title{博士后研究工作报告}` 这样没有必要暴露给用户，而且使得写 `\thu@first@titlepage` 时需要反复跟 cfg 的内容进行比对，有点不太方便。

你的意思是 cfg 文件可以直接植入在 cls 里？这个有点历史原因，cfg 是 atendofclass 时加载，当时为了兼容 cjk 包。后来一直也没动。现在都是 utf8 的确没有必要存在了

**Comment by zepinglee** [comment]
对，有些标题名称有中英文两个版本的可以集中放在一起，有些封面的标题只用到一次的，直接写在在封面的代码里就可以了

**Comment by xueruini** [comment]
> 对，有些标题名称有中英文两个版本的可以集中放在一起，有些封面的标题只用到一次的，直接写在在封面的代码里就可以了

LGTM. Go ahead!
