### ISSUE TITLE
参考文献目录中中文学位论文会多一对[]

### ISSUE THREAD

**Issue by kraikonnen** [xueruini/thuthesis#277]
环境为TeXLive 2017。

生成样式如：

猪八戒. 论流体食物的持久保存[[硕士学位论文]]. 北京: 广寒宫大学, 2005.
沙和尚. 论流沙河的综合治理[[博士学位论文]]. 北京: 清华大学, 2005.

尝试修改.bst文件，将其中的\thuphdbib{}和\thumasterbib{}分别替换成对应的汉字，问题解决，虽然原因并没搞懂。。。

**Comment by zepinglee** [comment]
1. 最新的 master 分支编译没有问题呀
2. thuphdbib 的定义就是
```
\def\thumasterbib{\ifthu@bachelor D\else 硕士学位论文\fi}
\def\thuphdbib{\ifthu@bachelor D\else 博士学位论文\fi}
```
好像没问题呀
