### ISSUE TITLE
设置英文字体的问题

### ISSUE THREAD

**Issue by fengduole** [xueruini/thuthesis#279]
我想把英文字体(正文和数学)改为默认的Computer Modern的话应该怎么操作呢？
`\setmainfont{CMU Serif}`
能让英文字体都改为CM，但是所有的加粗(textbf)、斜体(textit)就都失效了，请问一下这个该怎么处理呢？

**Comment by zepinglee** [comment]
要求 Times New Roman 吧

**Comment by fengduole** [comment]
> 要求 Times New Roman 吧
嗯，好像是要求TNR，但是写的时候看起来不习惯，所以想改了，然后到最后提交到数据库的时候再换回TNR。
如果确实不方便用CM就只好这样啦

**Comment by zepinglee** [comment]
我记得是调用 newtx 来使用（一个山寨的）TNR 的，注释掉就可以

**Comment by fengduole** [comment]
```
%\RequirePackage[defaultsups]{newtxtext}
%\RequirePackage{newtxmath}
```

这两行我注释掉了，的确得到了CM字体，效果和`\setmainfont{CMU Serif}`一样，但它们都存在的问题是\textbf，\textit均没有效果了。

**Comment by xueruini** [comment]
注释掉 newtxmath 就恢复了，textbf, it 我试了一下没发现受影响。

**Comment by fengduole** [comment]
> 注释掉 newtxmath 就恢复了，textbf, it 我试了一下没发现受影响。

不知道是我操作有问题还是怎么没搞对，我`main.tex`目录下的`thuthesis.dtx`和`C:\texlive\2017\texmf-dist\source\latex\thuthesis\thuthesis.dtx`都注释掉了`newtxmath`和`newtxtext`两行，但是仍旧是TNR字体，是我哪里没操作对？

与此同时，如果在`main.tex`中加入`\setmainfont{CMU Serif}`，可以变为CM字体，但textbf和it失效，望求解

**Comment by Stone-Zeng** [comment]
改 dtx 文件没有用的，要改 cls 文件。dtx 文件是模板编写者所写的源文件，之后需要用它生成 cls（文档类）、sty（宏包）等文件，分别用在 `\documentclass` 和 `\usepackage` 中。

**Comment by fengduole** [comment]
原来是这样，我的锅，现在对了。
感谢感谢 @Stone-Zeng
