### ISSUE TITLE
thuthesis论文类型参数名称应为type

### ISSUE THREAD

**Issue by Hanyuz1996** [xueruini/thuthesis#286]
下载的main文档中的参数degree = master无法成功编译，将参数名改为type后成功.

**Comment by xueruini** [comment]
你没用新版本 cls 吧

**Comment by Hanyuz1996** [comment]
我是V5.4.3那里一起下下来的...

**Comment by xueruini** [comment]
不能够啊，我刚又下载了 5.4.3，直接编译的没问题。也检查了打包的 cls 是对的。

**Comment by YxjAnly** [comment]
我也痛出现了这个问题，把degree改成type才能编译成功

**Comment by xueruini** [comment]
你们是不是直接从 releases 下载的 source code？那里面是没有 cls 的，如果没有 make cls，实际会用系统中的 cls，很有可能系统里是未更新的，于是就错了。

我在 release 里放了个完整的 zip，应该没问题了。ctan 上是对的。
