### ISSUE TITLE
不兼容 empheq 包

### ISSUE THREAD

**Issue by anamewing** [xueruini/thuthesis#288]
测试用例
```
\documentclass[degree=doctor]{thuthesis}
\usepackage{amsmath}
\usepackage{empheq}

\begin{document}

\begin{empheq}[left=\empheqlbrace]{align*}
a
\end{empheq} 
	
\end{document}
```
log 文件显示对`\end{empheq}`一行报错`! Undefined control sequence.`
文类换为`ctexbook`是可以正常编译的。

**Comment by Stone-Zeng** [comment]
因为 `thuthesis` 调用了 `ntheorem` 宏包，所以要这样写：`\usepackage[ntheorem]{empheq}`。

**Comment by anamewing** [comment]
十分感谢！
另，这种问题一般应该如何排查…在log文件说明不甚清晰时？

**Comment by Stone-Zeng** [comment]
@anamewing 这也没什么好办法 😭 。我先去文档看了看有没有什么不兼容宏包的说明，正好有 `ntheorem`；然后测试一下，就 OK 了。

如果文档没写，就只好看代码了。看 `empheq` 代码的话（在 `empheq.dtx` 文件里面看），你去搜一下 `\SetOnlyEndMark` （就是报 `! Undefined control sequence` 的命令），他这里明确提到了跟 `ntheorem` 有关，所以也能猜个八九不离十了。

一般情况出现这种问题，基本就是凭经验了……

**Comment by anamewing** [comment]
再次感谢指导。第二段解决办法对我来说很有用~
