### ISSUE TITLE
多个子图/子表格排版问题

### ISSUE THREAD

**Issue by EternalWave23** [xueruini/thuthesis#289]
无论是使用subfigure还是subcaptionbox，当子图数量多到要换行时，就会出现行间距过小，从而第二行的图片和第一行的标题重叠的现象。如下：

\begin{figure}[h]
  \centering%
  \subcaptionbox{第一个小图形\label{fig:subfig1}}[3cm]{\includegraphics[height=3cm]{thu-fig-logo}}\hspace{4em}%
  \subcaptionbox{第二个小图形，注意这个图略矮些。如果标题很长的话，它会自动换行\label{fig:subfig2}}{\includegraphics[height=2cm]{thu-text-logo}}
  \subcaptionbox{第一个小图形\label{fig:subfig1}}[3cm]{\includegraphics[height=3cm]{thu-fig-logo}}\hspace{4em}%
  \subcaptionbox{第二个小图形，注意这个图略矮些。如果标题很长的话，它会自动换行\label{fig:subfig2}}{\includegraphics[height=2cm]{thu-text-logo}}
  \caption{包含子图形的大图形(subcaptionbox示例)}
  \label{fig:big1-subcaptionbox}
\end{figure}

结果为：

![1519890158](https://user-images.githubusercontent.com/10924641/36832629-34312dae-1d67-11e8-9620-150c18f40acd.png)

**Comment by Stone-Zeng** [comment]
可以把 subcaption 的 `belowskip` 调大一点：

```tex
\begin{figure}[h]
  \centering
  \captionsetup[sub]{belowskip={20bp-\intextsep}}
  \subcaptionbox{\CAPA}[3cm]{\FIGA} \hspace{2em}
  \subcaptionbox{\CAPB}{\FIGB}      \hspace{2em}
  \subcaptionbox{\CAPA}[3cm]{\FIGA}
  \subcaptionbox{\CAPB}{\FIGB}
  \caption{包含子图形的大图形(subcaptionbox 示例)}
  \label{fig:big1-subcaptionbox}
\end{figure}
```

![default](https://user-images.githubusercontent.com/18233088/36842393-8636a7e0-1d86-11e8-8a6d-8b86f4513c4f.PNG)

但与此同时，整体的 caption 上面空白也会较大。可以把前三个图连同设置一起放在一个分组里面：

```tex
\begin{figure}[h]
  \centering
  \begingroup
    \captionsetup[sub]{belowskip={24bp-\intextsep}}
    \subcaptionbox{\CAPA}[3cm]{\FIGA} \hspace{2em}
    \subcaptionbox{\CAPB}{\FIGB}      \hspace{2em}
    \subcaptionbox{\CAPA}[3cm]{\FIGA}
  \endgroup
  \captionsetup[sub]{belowskip={16bp-\intextsep}}
  \subcaptionbox{\CAPB}{\FIGB}
  \caption{包含子图形的大图形(subcaptionbox 示例)}
  \label{fig:big1-subcaptionbox}
\end{figure}
```

![2](https://user-images.githubusercontent.com/18233088/36842526-e04fd760-1d86-11e8-955a-67defaaf11f6.PNG)

当然如果要严格按照标准

> 段前空 6 磅，段后空 12 磅

只需要把第二个 `\captionsetup` 删去。只是我个人觉得这样不太好看。

注：代码里的 `\FIGA` 等是为了方便定义的：

```tex
\def\FIGA{\includegraphics[height=3cm]{thu-fig-logo}}
\def\FIGB{\includegraphics[height=2cm]{thu-text-logo}}
\def\CAPA{小图形，注意这个图略矮些。}
\def\CAPB{\CAPA\CAPA\CAPA}
```

**Comment by rrenjie** [comment]
我是通过在要换行的subfigure后加命令\par\bigskip命令解决的（谷歌搜到的方法）：

...
\end{subfigure}
\par\bigskip
\begin{subfigure} ...
