### ISSUE TITLE
中文字符的问题

### ISSUE THREAD

**Issue by wadesunyang** [xueruini/thuthesis#291]
您好,我是latex小白一个，我安装了texlive2017 ,然后下载了thuthesis,但是在编译main.tex的时候报错说,
KaiTi_GB2312 not found.
我查看了以前的issues,发现thuthesis中的结构和现在不太相同,没有了thufonts.def。

另外百度得知
Windows XP 自带的中文字体叫 KaiTi_GB2312
Windows Vista 以后版本自带的中文字体叫 KaiTi
我电脑中的是KaiTi，所以我应该修改哪里的文件，以及怎么修改？ 谢谢

**Comment by wxcmonkey** [comment]
同学你是怎么解决的？我也碰到这问题了。。

**Comment by wadesunyang** [comment]
下载KaiTi_GB2312安装C:/Windows/fonts中就可以了，提示缺少啥就下载什么字体

**Comment by wxcmonkey** [comment]
好滴，谢谢~
