### ISSUE TITLE
参考文献中inproceeding的格式问题

### ISSUE THREAD

**Issue by wxcmonkey** [xueruini/thuthesis#292]
对于inproceeding类型的参考文献，在会议名称后面会出现[S.1.: s.n.]或者[S.1.]或者[s.n.]这样的字符串
这样是正常的吗？这些字符是什么含义呢？

**Comment by wang-ps** [comment]
我也遇到这个问题，比如：
 Desbrun M, Meyer M, Schröder P, et al. Implicit fairing of irregular meshes using diffusion and
curvature flow[C]//SIGGRAPH. [S.l.: s.n.], 1999: 317–324
能否通过修改不显示 [S.l.: s.n.]？

**Comment by Stone-Zeng** [comment]
这是 GB/T 7714-2015 的新要求，S.l. 表示出版地不详（*sine loco*），s.n. 表示出版者不详（*sine nomine*）。

**Comment by clumsy456** [comment]
学校貌似还是用的2005。不过只要把相关信息填进去就好，例如上面那篇文献可以
```
...
address = {New York, NY, USA},
organization={ACM Press/Addison-Wesley Publishing Co.},
...
```

**Comment by wxcmonkey** [comment]
有没有办法把这部分删掉，还原到2005标准呢？

**Comment by Stone-Zeng** [comment]
这个怕是要请教一下 @zepinglee

**Comment by zepinglee** [comment]
@wxcmonkey 《清华大学研究生学位论文写作指南》第3.5.6节规定：
> (2)无出版地可著录[出版地不详]或[S.l.]，无出版者可著录[出版者不详] 或[s.n.]; 

GB/T 7714-2005 也是这么规定的。

我也觉得这很丑，所以 @xueruini 要不要在这里变通一下？

**Comment by xueruini** [comment]
> 我也觉得这很丑，所以 @xueruini 要不要在这里变通一下？

还是按规则来吧

**Comment by wxcmonkey** [comment]
那先这样吧，丑点就丑点><
谢谢各位~

**Comment by xueruini** [comment]
> 那先这样吧，丑点就丑点><

为啥不把缺的信息补全呢？补全就不丑了

**Comment by xiasummer** [comment]
可以博士论文哪里有什么出版地呢？

**Comment by xueruini** [comment]
```bib
@phdthesis{phdthesis,
  author       = {Peter Joslin}, 
  title        = {The title of the work},
  school       = {The school of the thesis},
  year         = 1993,
  address      = {The address of the publisher},
  month        = 7,
  note         = {An optional note}
}
```
