### ISSUE TITLE
degree=bachlor 后\makecover 一行报错，改degree = master 编译可通过

### ISSUE THREAD

**Issue by TraceyZhong** [xueruini/thuthesis#293]
Errors:
/Users/EngThesis.tex:37: Undefined control sequence. []

EngThesis.tex:

%!TEX program = xelatex
\documentclass[degree=bachelor]{thuthesis}

\usepackage{times}
\usepackage{url}
\usepackage{latexsym}
\usepackage{float,graphicx,tabularx}
\usepackage{amsmath}
\usepackage{csquotes}
\usepackage{xr}
\usepackage{thuthesis}

\graphicspath{{figures/}}
 \def\myname{姓名}

\begin{document}

\frontmatter
\input{data/cover1}
37 \makecover %这一行报错
40 \tableofcontents
...

封面文件：
cover1.tex
\thusetup{
ctitle={社交媒体时代的政治话语：川普推特情感分析},
  cdegree={文学学士},
  cdepartment={外国语言文学系},
  cmajor={英语语言文学},
  cauthor={姓名},
  csupervisor={周允程副教授},
  etitle={Political Communication in Social Media Era: An Empirical Analysis of Sentiments on Trump's Tweets},
  edegree={Bachelor of Arts},
  emajor={Foreign Languages and Literatures},
  eauthor={Zhong Xinyi},
  esupervisor={Professor Zhou Yuncheng},
  eassosupervisor={Chen Wenguang},
  ckeywords={\TeX, \LaTeX, CJK, 模板, 论文},
  ekeywords={\TeX, \LaTeX, CJK, template, thesis}
}

cover.tex的其他部分暂时没有修改过

**Comment by xueruini** [comment]
cover1.tex 完整的贴出来看看

**Comment by TraceyZhong** [comment]
\thusetup{
  %******************************
  % 注意：
  %   1. 配置里面不要出现空行
  %   2. 不需要的配置信息可以删除
  %******************************
  %
  %=====
  % 秘级
  %=====
  % secretlevel={秘密},
  % secretyear={10},
  %
  %=========
  % 中文信息
  %=========
  ctitle={社交媒体时代的政治话语\\：川普推特情感分析},
  cdegree={文学学士},
  cdepartment={外国语言文学系},
  cmajor={英语语言文学},
  cauthor={钟欣艺},
  csupervisor={周允程副教授},
  % cassosupervisor={陈文光教授}, % 副指导老师
  % ccosupervisor={某某某教授}, % 联合指导老师
  % 日期自动使用当前时间，若需指定按如下方式修改：
  % cdate={超新星纪元},
  %
  % 博士后专有部分
  % cfirstdiscipline={计算机科学与技术},
  % cseconddiscipline={系统结构},
  % postdoctordate={2009年7月——2011年7月},
  % id={编号}, % 可以留空： id={},
  % udc={UDC}, % 可以留空
  % catalognumber={分类号}, % 可以留空
  %
  %=========
  % 英文信息
  %=========
  etitle={Political Communication in Social Media Era: An Empirical Analysis of Sentiments on Trump's Tweets},
  % 这块比较复杂，需要分情况讨论：
  % 1. 学术型硕士
  %    edegree：必须为Master of Arts或Master of Science（注意大小写）
  %             “哲学、文学、历史学、法学、教育学、艺术学门类，公共管理学科
  %              填写Master of Arts，其它填写Master of Science”
  %    emajor：“获得一级学科授权的学科填写一级学科名称，其它填写二级学科名称”
  % 2. 专业型硕士
  %    edegree：“填写专业学位英文名称全称”
  %    emajor：“工程硕士填写工程领域，其它专业学位不填写此项”
  % 3. 学术型博士
  %    edegree：Doctor of Philosophy（注意大小写）
  %    emajor：“获得一级学科授权的学科填写一级学科名称，其它填写二级学科名称”
  % 4. 专业型博士
  %    edegree：“填写专业学位英文名称全称”
  %    emajor：不填写此项
  % edegree={Bachelor of Arts},
  % emajor={Foreign Languages and Literatures},
  eauthor={Zhong Xinyi},
  esupervisor={Professor Zhou Yuncheng},
  % eassosupervisor={Chen Wenguang},
  % 日期自动生成，若需指定按如下方式修改：
  % edate={December, 2005}
  %
  % 关键词用“英文逗号”分割
  ckeywords={\TeX, \LaTeX, CJK, 模板, 论文},
  ekeywords={\TeX, \LaTeX, CJK, template, thesis}
}

% 定义中英文摘要和关键字
\begin{cabstract}
  论文的摘要是对论文研究内容和成果的高度概括。摘要应对论文所研究的问题及其研究目
  的进行描述，对研究方法和过程进行简单介绍，对研究成果和所得结论进行概括。摘要应
  具有独立性和自明性，其内容应包含与论文全文同等量的主要信息。使读者即使不阅读全
  文，通过摘要就能了解论文的总体内容和主要成果。

  论文摘要的书写应力求精确、简明。切忌写成对论文书写内容进行提要的形式，尤其要避
  免“第 1 章……；第 2 章……；……”这种或类似的陈述方式。

  本文介绍清华大学论文模板 \thuthesis{} 的使用方法。本模板符合学校的本科、硕士、
  博士论文格式要求。

  本文的创新点主要有：
  \begin{itemize}
    \item 用例子来解释模板的使用方法；
    \item 用废话来填充无关紧要的部分；
    \item 一边学习摸索一边编写新代码。
  \end{itemize}

  关键词是为了文献标引工作、用以表示全文主要内容信息的单词或术语。关键词不超过 5
  个，每个关键词中间用分号分隔。（模板作者注：关键词分隔符不用考虑，模板会自动处
  理。英文关键词同理。）
\end{cabstract}

% 如果习惯关键字跟在摘要文字后面，可以用直接命令来设置，如下：
% \ckeywords{\TeX, \LaTeX, CJK, 模板, 论文}

\begin{eabstract}
   An abstract of a dissertation is a summary and extraction of research work
   and contributions. Included in an abstract should be description of research
   topic and research objective, brief introduction to methodology and research
   process, and summarization of conclusion and contributions of the
   research. An abstract should be characterized by independence and clarity and
   carry identical information with the dissertation. It should be such that the
   general idea and major contributions of the dissertation are conveyed without
   reading the dissertation.

   An abstract should be concise and to the point. It is a misunderstanding to
   make an abstract an outline of the dissertation and words ``the first
   chapter'', ``the second chapter'' and the like should be avoided in the
   abstract.

   Key words are terms used in a dissertation for indexing, reflecting core
   information of the dissertation. An abstract may contain a maximum of 5 key
   words, with semi-colons used in between to separate one another.
\end{eabstract}

\ekeywords{\TeX, \LaTeX, CJK, template, thesis}

**Comment by TraceyZhong** [comment]
\thusetup{
  %******************************
  % 注意：
  %   1. 配置里面不要出现空行
  %   2. 不需要的配置信息可以删除
  %******************************
  %
  %=====
  % 秘级
  %=====
  % secretlevel={秘密},
  % secretyear={10},
  %
  %=========
  % 中文信息
  %=========
  ctitle={社交媒体时代的政治话语\\：川普推特情感分析},
  cdegree={文学学士},
  cdepartment={外国语言文学系},
  cmajor={英语语言文学},
  cauthor={姓名},
  csupervisor={周允程副教授},
  % cassosupervisor={陈文光教授}, % 副指导老师
  % ccosupervisor={某某某教授}, % 联合指导老师
  % 日期自动使用当前时间，若需指定按如下方式修改：
  % cdate={超新星纪元},
  %
  % 博士后专有部分
  % cfirstdiscipline={计算机科学与技术},
  % cseconddiscipline={系统结构},
  % postdoctordate={2009年7月——2011年7月},
  % id={编号}, % 可以留空： id={},
  % udc={UDC}, % 可以留空
  % catalognumber={分类号}, % 可以留空
  %
  %=========
  % 英文信息
  %=========
  etitle={Political Communication in Social Media Era: An Empirical Analysis of Sentiments on Trump's Tweets},
  % 这块比较复杂，需要分情况讨论：
  % 1. 学术型硕士
  %    edegree：必须为Master of Arts或Master of Science（注意大小写）
  %             “哲学、文学、历史学、法学、教育学、艺术学门类，公共管理学科
  %              填写Master of Arts，其它填写Master of Science”
  %    emajor：“获得一级学科授权的学科填写一级学科名称，其它填写二级学科名称”
  % 2. 专业型硕士
  %    edegree：“填写专业学位英文名称全称”
  %    emajor：“工程硕士填写工程领域，其它专业学位不填写此项”
  % 3. 学术型博士
  %    edegree：Doctor of Philosophy（注意大小写）
  %    emajor：“获得一级学科授权的学科填写一级学科名称，其它填写二级学科名称”
  % 4. 专业型博士
  %    edegree：“填写专业学位英文名称全称”
  %    emajor：不填写此项
  % edegree={Bachelor of Arts},
  % emajor={Foreign Languages and Literatures},
  eauthor={Zhong Xinyi},
  esupervisor={Professor Zhou Yuncheng},
  % eassosupervisor={Chen Wenguang},
  % 日期自动生成，若需指定按如下方式修改：
  % edate={December, 2005}
  %
  % 关键词用“英文逗号”分割
  ckeywords={\TeX, \LaTeX, CJK, 模板, 论文},
  ekeywords={\TeX, \LaTeX, CJK, template, thesis}
}

% 定义中英文摘要和关键字
\begin{cabstract}
  论文的摘要是对论文研究内容和成果的高度概括。摘要应对论文所研究的问题及其研究目
  的进行描述，对研究方法和过程进行简单介绍，对研究成果和所得结论进行概括。摘要应
  具有独立性和自明性，其内容应包含与论文全文同等量的主要信息。使读者即使不阅读全
  文，通过摘要就能了解论文的总体内容和主要成果。

  论文摘要的书写应力求精确、简明。切忌写成对论文书写内容进行提要的形式，尤其要避
  免“第 1 章……；第 2 章……；……”这种或类似的陈述方式。

  本文介绍清华大学论文模板 \thuthesis{} 的使用方法。本模板符合学校的本科、硕士、
  博士论文格式要求。

  本文的创新点主要有：
  \begin{itemize}
    \item 用例子来解释模板的使用方法；
    \item 用废话来填充无关紧要的部分；
    \item 一边学习摸索一边编写新代码。
  \end{itemize}

  关键词是为了文献标引工作、用以表示全文主要内容信息的单词或术语。关键词不超过 5
  个，每个关键词中间用分号分隔。（模板作者注：关键词分隔符不用考虑，模板会自动处
  理。英文关键词同理。）
\end{cabstract}

% 如果习惯关键字跟在摘要文字后面，可以用直接命令来设置，如下：
% \ckeywords{\TeX, \LaTeX, CJK, 模板, 论文}

\begin{eabstract}
   An abstract of a dissertation is a summary and extraction of research work
   and contributions. Included in an abstract should be description of research
   topic and research objective, brief introduction to methodology and research
   process, and summarization of conclusion and contributions of the
   research. An abstract should be characterized by independence and clarity and
   carry identical information with the dissertation. It should be such that the
   general idea and major contributions of the dissertation are conveyed without
   reading the dissertation.

   An abstract should be concise and to the point. It is a misunderstanding to
   make an abstract an outline of the dissertation and words ``the first
   chapter'', ``the second chapter'' and the like should be avoided in the
   abstract.

   Key words are terms used in a dissertation for indexing, reflecting core
   information of the dissertation. An abstract may contain a maximum of 5 key
   words, with semi-colons used in between to separate one another.
\end{eabstract}

\ekeywords{\TeX, \LaTeX, CJK, template, thesis}

**Comment by TraceyZhong** [comment]
![screen shot 2018-03-16 at 16 16 14](https://user-images.githubusercontent.com/25614156/37510241-76ce5842-2935-11e8-984f-b47bfdbb95e2.jpg)
以上是报错的截图

**Comment by TraceyZhong** [comment]
![screen shot 2018-03-16 at 16 18 06](https://user-images.githubusercontent.com/25614156/37510318-a3a97a86-2935-11e8-851d-6c678672bff7.jpg)
以上是报错的截图

**Comment by xueruini** [comment]
> ctitle={社交媒体时代的政治话语\：川普推特情感分析},

`\：` ？

**Comment by TraceyZhong** [comment]
我查了原文件发现是\\ (换行) 和 ：（冒号），不知道为什么粘过来少了一个\

**Comment by xueruini** [comment]
方便的话把你的文件打包发邮件给我

**Comment by TraceyZhong** [comment]
非常方便！

**Comment by xueruini** [comment]
> 非常方便！

发了吗？xueruini \at gmail \dot com

**Comment by xueruini** [comment]
收到邮件，编译正常。。。
