### ISSUE TITLE
模板里面用的英文字体和word里面用的Times New Roman字体是有区别的？

### ISSUE THREAD

**Issue by cfanyyx** [xueruini/thuthesis#296]
感觉word中使用的Times New Roman是要粗一些的求问下如何更改模板的英文字体？急！
![default](https://user-images.githubusercontent.com/7723243/37564569-8e356c38-2ad3-11e8-929d-eff538030d6c.png)

**Comment by cfanyyx** [comment]
而且不光是英文字体，中文字体好像也会细一些！

**Comment by Stone-Zeng** [comment]
`thuthesis` 是通过调用 `newtx` 宏包（包括 `newtxtext` 和 `newtxmath`）来使用「Times New Roman」字体的。`newtx` 实际用的是 TeX Gyre Termes，是 Times New Roman 的开源复刻版本，虽然很像，但并不完全一样。

如果一定要使用「Times New Roman」，需要修改 `thuthesis.cls`：

```tex
\RequirePackage[defaultsups]{newtxtext}
```

把这一行（第 84 行附近）删调或注释掉，然后再在导言区里加上

```tex
\setmainfont{Times New Roman}
```

注意必须使用 xelatex 编译。

<br>

**说明**

1. 我不知道您是直接 clone 了 `thuthesis` 的 git 仓库，还是在 TeX Live 或者 MikTeX 里面安装的宏包。如果是后者，不建议直接修改原始文件，通常的做法是复制一份到工作目录（您的论文放置位置）或者 `texmf-local` 树下的相应位置（`texmf-local/tex/latex/thuthesis`）。如果是放在 `texmf-local` 树下，修改之后还需要刷新 ls-R 数据库（命令行中执行 `texhash`）。

2. 字体的粗细还依赖于字体渲染。Word 的渲染结果与 TeX/PDF 的渲染结果大概是不同的，所以即使换成了真的「Times New Roman」，也无法保证效果完全一样。

**Comment by Stone-Zeng** [comment]
另外 @xueruini ，如果是使用 xelatex 编译的话，可否把模板改成不调用 `newtxtext` 宏包，而是直接用 `fontspec` 选择字体？反正 `xeCJK` 也是会调用 `fontspec` 的。

**Comment by cfanyyx** [comment]
@Stone-Zeng 谢谢，按照提供的修改方案修改以后正文字体正常了，但是所有Arial字体均受到了影响，请问该怎么样更改？

**Comment by Stone-Zeng** [comment]
在导言区加上 `\setsansfont{Arial}`。

**Comment by cfanyyx** [comment]
@Stone-Zeng thx~另外想说FandolSong相比SimSun更接近word生成PDF之后的效果！

**Comment by xueruini** [comment]
> 另外 @xueruini ，如果是使用 xelatex 编译的话，可否把模板改成不调用 newtxtext 宏包，而是直接用 fontspec 选择字体？反正 xeCJK 也是会调用 fontspec 的。

用户自己配字体的事情有点啰嗦，之前[讨论过](#270)也没达成一致

**Comment by cfanyyx** [comment]
@Stone-Zeng @xueruini 还想请问一下，下面的warnings该怎么fix：
LaTex Font: Font shape 'TU/TimesNewRoman(0)/m/sc' undefined using 'TU/TimesNewRoman(0)/m/n' instead
LaTex Font: Font shape 'OMS/TimesNewRoman(0)/m/n' undefined using 'OMS/cmsy/m/n' instead

**Comment by Stone-Zeng** [comment]
我这里没有复现这个 warning，您可以提供完整的、能复现问题的最小示例吗？

**Comment by cfanyyx** [comment]
@Stone-Zeng 恩，是这样的，第一个warning会在下面35行这个位置报：
![image](https://user-images.githubusercontent.com/7723243/37653882-54a15aa0-2c7b-11e8-9740-30c1baa297c3.png)
第二个warning是会出现在正文中第一处\footnote的位置（是不是①这个符号报的？）
我尝试过重新clone一份新的模板，然后按照以上步骤替换了TNR字体之后，两个warning均会复现，环境是windows~

**Comment by Stone-Zeng** [comment]
请提供**完整的**示例，包含整个 tex 文档，以及相应的 log（不要使用截图），还有您的系统信息、TeX Live/MikTeX/MacTeX 版本以及宏包版本。您目前给出的信息不足以准确描述出现的问题。

PS:
1. 提问的技巧见 <https://tex.meta.stackexchange.com/q/228/136923>
2. Warning 如果不影响排版效果，可以直接无视。

**Comment by xueruini** [comment]
> LaTex Font: Font shape 'TU/TimesNewRoman(0)/m/sc' undefined using 'TU/TimesNewRoman(0)/m/n' instead

看起来是 small cap 用不上，模板里就 `\thuthesis` 用到了 sc，如果你自己没有可以用的话，可以忽略之。

> LaTex Font: Font shape 'OMS/TimesNewRoman(0)/m/n' undefined using 'OMS/cmsy/m/n' instead

这个有可能是 footnote 中圆圈字里遇到的问题，估计也感知不到

我在本地编译了一下模板，似乎没发现这种问题

**Comment by cfanyyx** [comment]
@xueruini @Stone-Zeng 确实，忽略了，sc用不到，圈圈无所谓了。感谢！
