### ISSUE TITLE
CTex最新版依然报lofskip, lotskip unknow的错误

### ISSUE THREAD

**Issue by b-liu14** [xueruini/thuthesis#297]
操作系统：macos high sierra
tex软件：mactex
CTex版本：v2.4.12

报错如下：
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
./thuthesis.cls:327: LaTeX error: "kernel/key-unknown"
! 
! The key 'ctex/chapter/lofskip' is unknown and is being ignored.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.327   subparagraph/afterindent=true}
                                      

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
./thuthesis.cls:327: LaTeX error: "kernel/key-unknown"
! 
! The key 'ctex/chapter/lotskip' is unknown and is being ignored.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................

**Comment by terro** [comment]
建议在 MacTeX 安装后，使用附带的 TeX Live Utility 把所有包更新到最新版，然后在文章的目录下，删掉除了 bst 之外的所有 thuthesis 文件，使用发行版里自带的即可。

**Comment by b-liu14** [comment]
删除所有的这些吗？
```
thuthesis.cfg
thuthesis.cls
thuthesis.dtx
thuthesis.ins
thuthesis.sty
```

**Comment by terro** [comment]
不如先试一下下面的这个能不能编译：

```
\documentclass[degree=master]{thuthesis}
\usepackage{thuthesis}
\begin{document}
\tableofcontents
\mainmatter
this is a test.
\end{document}
```

**Comment by b-liu14** [comment]
错误并不出现在tex文件里，出现在cls文件里

**Comment by terro** [comment]
应该是你环境的问题，你的 TeX Live 是 2017 么？

**Comment by b-liu14** [comment]
2016和2017都试过了

**Comment by b-liu14** [comment]
应该是我这边的问题，我在找找吧。
