### ISSUE TITLE
中文文献作者超过三个时，若标题存在标点符号，则生成“et al”而非“等”。

### ISSUE THREAD

**Issue by clumsy456** [xueruini/thuthesis#298]
引用中文文献，当作者超过三个时，应该用“等”表示后面的作者。
.bib文件中应该使用`lang = "zh"`表示。
然而我发现，若标题中存在标点符号，则默认用“et al”表示。
```
@article{sunhongbin,
  author =       "孙宏斌 and 郭庆来 and 潘昭光 and 王剑辉",
  title =        "能源互联网：驱动力、评述与展望",
  journal =      "电网技术",
  pages =        "3005--3013",
  volume =       39,
  number =      11,
  year =         2015,
  lang =         "zh",
}

@article{mazhao,
  author =       "马钊 and 周孝信 and 尚宇炜 and 盛万兴",
  title =        "能源互联网概念、关键技术及发展模式探索",
  journal =      "电网技术",
  pages =        "3014--3022",
  volume =       39,
  number =       11,
  year =         2015,
  lang =         "zh",
}
```
结果为
![image](https://user-images.githubusercontent.com/19684295/37747437-2c48512c-2dba-11e8-9d2e-89ea1bd23941.png)
进一步试验发现，顿号和句号会导致这一现象发生，冒号和逗号不会。

以上所指标点符号均为中文标点符号。

**Comment by zhaofeng-shu33** [comment]
Use `language = "chinese"` instead.
If you inspect 'thuthesis-numeric.bst`, you can find it defines the entry `language`, not `lang`. If no language field is provided, then it will tries to guess the language based on the utf-8 encoding and it is possible to make wrong judgement, e.g lang = japanese.

**Comment by clumsy456** [comment]
Thank you. I think the expression should be updated in `refs.bib` and `chap01.tex`. haha

**Comment by xueruini** [comment]
thanks so much for @zhaofeng-shu33's [PR](#301)
