### ISSUE TITLE
使用cite显示xx等人+文章年份

### ISSUE THREAD

**Issue by nicehzj** [xueruini/thuthesis#304]
在文中引用文献时，使用\cite，但是生成的pdf里面，不是想要的[1]这样类型，而是作者+年份
![image](https://user-images.githubusercontent.com/37993309/38182812-89bee674-366e-11e8-8a78-048bed1ee157.png)
而且最后的参考文献部分格式也不对，缩进都是乱的
![image](https://user-images.githubusercontent.com/37993309/38182834-a98ed4a0-366e-11e8-8002-fef1c86dc565.png)
我只是将论文模板编译了一下，没做出任何改动
但是我编译以前的版本就没有问题
麻烦帮忙解决一下问题，急，谢谢了！

**Comment by xueruini** [comment]
main.tex 的说明

```latex
%% 参考文献
% 注意：至少需要引用一篇参考文献，否则下面两行可能引起编译错误。
% 如果不需要参考文献，请将下面两行删除或注释掉。
% 数字式引用
\bibliographystyle{thuthesis-numeric}
% 作者-年份式引用
% \bibliographystyle{thuthesis-author-year}
\bibliography{ref/refs}
```

**Comment by xueruini** [comment]
#303

**Comment by zepinglee** [comment]
请教一下 @xueruini ，这个地方
```
\expandafter\newcommand\csname bibstyle@thuthesis-author-year\endcsname{%
  \bibpunct{(}{)}{;}{a}{,}{,}}
```
这样设置好像就不需要 `\citestyle{thuthesis-author-year}` 了？

**Comment by xueruini** [comment]
> 这样设置好像就不需要 \citestyle{thuthesis-author-year} 了？

这里只是定义 style，还是得用 `\citestyle` 激活一下吧

**Comment by xueruini** [comment]
> 这样设置好像就不需要 \citestyle{thuthesis-author-year} 了？

是的，现在也没有调 `\citestyle` 了

**Comment by zepinglee** [comment]
能不能解释一下这个是为啥啊？我一直不是很懂 `\expandafter`

**Comment by zepinglee** [comment]
噢原来这样啊。那 citation style 是在哪里设置的？

**Comment by xueruini** [comment]
natbib 文档 2.10 

![image](https://user-images.githubusercontent.com/1863/38660802-3000a956-3e61-11e8-8ccc-d514fe3f0ead.png)

**Comment by zepinglee** [comment]
原来如此！感谢！
