### ISSUE TITLE
[目录部分问题]纯英文目录，如何设置章目录字体为arial，其他节目录字体为times new roman

### ISSUE THREAD

**Issue by HuaGuo1992** [xueruini/thuthesis#306]
英文论文，说明手册里找了好久，看到有一个  ‘每章标题⾏前空6磅，后空0 磅。如果使⽤⽬录项中英⽂要使⽤Arial，那么就加上 \sffamily。章节名中英⽂⽤ Arial 字体，页码仍⽤ Times。’  无果。  

后又发现
`% \DescribeOption{arialtoc}
% 目录项（章目录项除外）中的英文是否用 \emph{Arial} 字体。本选项
% 和 \option{arialtitle} 都不用用户干预，模板根据当前论文类型自动设置。`

可这是设置除章目录之外的。

求问如何实现在目录页，章目录字体为arial，其他节目录字体为times new roman

**Comment by xueruini** [comment]
> 页码仍⽤ Times。’

没考虑这个问题

**Comment by xueruini** [comment]
#320 #321
