### ISSUE TITLE
lishu does not exist on linux ?

### ISSUE THREAD

**Issue by zhaofeng-shu33** [xueruini/thuthesis#309]
For bachelor thesis, 
![http://media.leidenschaft.cn/ctexbbs/thuthesis/schoolname.png](http://media.leidenschaft.cn/ctexbbs/thuthesis/schoolname.png)
the following code is processed:
`\lishu\ziju{0.5}\thu@schoolname`

According to ctex doc:
![http://media.leidenschaft.cn/ctexbbs/thuthesis/ctexdoc.png](http://media.leidenschaft.cn/ctexbbs/thuthesis/ctexdoc.png)

It suggests that no lishu font is available for linux ?

Providing `degree=bachelor` to `thuthesis` fails to compile on my machine, Ubuntu 16.04.

**Comment by xueruini** [comment]
> The lishu font is provided by Ubuntu. You can copy this font from Windows to Linux and manually configure the \lishu command as ctex.

this is the only one spot the `\lishu` macro is used. It is a figure originally, and updated at https://github.com/xueruini/thuthesis/commit/3d06bdfe586a84517b327c9c8ccac318941b8069

perhaps we could get back the figure
