### ISSUE TITLE
求问如何使研究生论文中文摘要的关键字在最底部？

### ISSUE THREAD

**Issue by nicehzj** [xueruini/thuthesis#311]
去格式审查的时候老师说中英文摘要都要放在最底部，不太会调，应该如何修改？
谢谢帮助！

**Comment by xueruini** [comment]
#302 
#305 

说只有博士受影响，硕士也要改么？

**Comment by nicehzj** [comment]
我不是很清楚，我是核研院的，研究室办公室老师说要改

**Comment by nicehzj** [comment]
需要如何修改呢？我试了将博士修改的那个把@doctor换成@master好像不好用

**Comment by xueruini** [comment]
> 我不是很清楚，我是核研院的，研究室办公室老师说要改

现在代码针对博士的改了，硕士的麻烦确认一下学校规定，统一改

**Comment by HuaGuo1992** [comment]
同核研院硕士，就按照你这个方法，然后重新编译下模板latex thusis.ins就行。  我这边可以。 我想问下你有遇到引用网页出问题的没

**Comment by nicehzj** [comment]
暂时我还没有遇到，不知道你遇到了什么问题 @HuaGuo1992

**Comment by HuaGuo1992** [comment]
bibitex引用网页 显示不了  不知咋回事  参考文献部分最后只显示编号

**Comment by nicehzj** [comment]
@HuaGuo1992 你可以看一下模板示例里面的refs文件，里面的【19】【20】是引用网页的，你看一下是不是refs里面的格式出了问题
