### ISSUE TITLE
插图和表格目录内的引用问题

### ISSUE THREAD

**Issue by ajane0234** [xueruini/thuthesis#315]
也不知道算不算bug。

插图和表格的标题内有时候会有引用，然而插图和表格目录在论文的最前面，所以文献编号顺序就变成了插图和表格内存在的引用最靠前，这样引用顺序就乱了。

我现在用的版本也不是最新的，不知道这个问题有木有办法修正~

**Comment by shenyp09** [comment]
一不小心用成小号提issue了...

**Comment by zepinglee** [comment]
https://tex.stackexchange.com/questions/227833/cite-references-in-figure-caption

\protect\cite{}

**Comment by shenyp09** [comment]
@zepinglee 不知道为什么不好使，现在暂时引入notoccite包解决了问题，不知道有没有后遗症。

**Comment by shenyp09** [comment]
是排序问题。caption可能在论文的很后面，按照顺序排序的话，caption里引用的文献应该是比如[100]。然而由于表格目录的存在，这篇文献在正文之前就出现了，所以引用变成了[1]，这样顺序就完全乱了。
比如下面这张是正常的图目录（引入了notoccite包），
![image](https://user-images.githubusercontent.com/4045048/38659623-e76ef4ee-3e5c-11e8-92e3-daf8751565a7.png)
如果不引入这个包，就会变成
![image](https://user-images.githubusercontent.com/4045048/38659725-43943f9a-3e5d-11e8-968d-6b0329d757a0.png)

**Comment by xueruini** [comment]
明白了。good question，我想想

**Comment by xueruini** [comment]
试试这个

https://tex.stackexchange.com/questions/36304/ignore-citations-in-captions-in-list-of-figures-when-numbering

**Comment by shenyp09** [comment]
biblatex我试了一下，会冲突。我发现notoccite好使以后就没仔细研究。
![image](https://user-images.githubusercontent.com/4045048/38660938-b20915d2-3e61-11e8-8a95-eef3bf50040f.png)

**Comment by shenyp09** [comment]
biblatex我试了一下，会冲突。我发现notoccite好使以后就没仔细研究。
![image](https://user-images.githubusercontent.com/4045048/38660938-b20915d2-3e61-11e8-8a95-eef3bf50040f.png)

**Comment by xueruini** [comment]
> biblatex我试了一下，会冲突。我发现notoccite好使以后就没仔细研究。

notoccite 好使就行。是不是有必要把它加到模板里？

**Comment by shenyp09** [comment]
我现在没发现引入这个包有什么其他的bug，我觉得有必要放进去。

**Comment by shenyp09** [comment]
或者能否修改一下notoccite包，我觉得应该包含一个content里不出现引用这个选项（比较符合直觉）

**Comment by shenyp09** [comment]
我刚才说的不清楚。我是觉得应该能够自动实现
\caption{abc\cite{d}}->\caption[abc]{abc\cite{d}}
的效果。这样在图目录里就不会出现引用了。

**Comment by xueruini** [comment]
> \caption{abc\cite{d}}->\caption[abc]{abc\cite{d}}

这个方式感觉有点累。你看那个贴子的第二个回答。你加一句

```latex
\usepackage{notoccite}
```

不需要改 caption

**Comment by shenyp09** [comment]
notoccite和\caption{abc\cite{d}}->\caption[abc]{abc\cite{d}}最后实现出来的效果不太相同。

notoccite可以保证文献顺序正确，但是在插图目录里依然会出现"abc[23]"这种引用。

而\caption{abc\cite{d}}->\caption[abc]{abc\cite{d}}在插图目录里是"abc"这样的。

我不知道那种是标准形式。不过要是能够有包能够自动保证和第二种形式一样的插图目录也是很不错的。

**Comment by xueruini** [comment]
> notoccite可以保证文献顺序正确，但是在插图目录里依然会出现"abc[23]"这种引用。

我理解这是理想状态。不需要像下面的方案一个标题维护两套文字

> 而\caption{abc\cite{d}}->\caption[abc]{abc\cite{d}}在插图目录里是"abc"这样的。

**Comment by shenyp09** [comment]
那就没问题了。我使用中没有发现引入notoccite会有什么冲突，建议加进来。

**Comment by xueruini** [comment]
closed by 3cbfb9d2a8bc92749071c8572744d2c9d695c741
