### ISSUE TITLE
书脊的那条虚线该怎么弄出来？

### ISSUE THREAD

**Issue by cfanyyx** [xueruini/thuthesis#316]

**Comment by xueruini** [comment]
哪条虚线？

**Comment by cfanyyx** [comment]
![default](https://user-images.githubusercontent.com/7723243/38679154-91092be0-3e95-11e8-92fb-e3a65fc38255.PNG)

**Comment by xueruini** [comment]
有啥用？

**Comment by cfanyyx** [comment]
不知道，只是发现跟学校的模板不一样。

**Comment by xueruini** [comment]
做书脊应该不需要

**Comment by Sinica1997** [comment]
这个虚线真的没人问吗...我也发现了，怎么设置呢

**Comment by Sinica1997** [comment]
@xueruini 麻烦您解答一下了

**Comment by xueruini** [comment]
这条虚线应该没啥用。装订的时候不应该有
