### ISSUE TITLE
proof环境中插入公式会有奇怪的方框字符出现

### ISSUE THREAD

**Issue by netheril96** [xueruini/thuthesis#327]
环境：macOS High Sierra 10.13.4 (17E199), TeX Live 2017，用xelatex编译

例子：

```tex
\documentclass[type=master]{thuthesis}
\usepackage{thuthesis}

\begin{document}
    \begin{proof}
        如下所示
        \begin{equation}
            W = a * b
        \end{equation}
    \end{proof}
\end{document}
```

编译结果
![image](https://user-images.githubusercontent.com/836839/38764195-eb5b2c7c-3fdc-11e8-9d4b-56c886cef199.png)

去除proof环境后就没有右下角的□了
![image](https://user-images.githubusercontent.com/836839/38764199-134e5024-3fdd-11e8-9f2f-a6edbe86f2c3.png)

**Comment by zepinglee** [comment]
那个符号是 qed，https://en.wikipedia.org/wiki/Q.E.D.

**Comment by netheril96** [comment]
能关掉吗？我觉得没几个人认得这个符号。

**Comment by netheril96** [comment]
而且放置的位置也很奇怪。

**Comment by netheril96** [comment]
好吧，我明白了，这个好像是从AMS继承过来的。

**Comment by netheril96** [comment]
但是我用`\renewcommand{\qedsymbol}{}`并没有效果

**Comment by xueruini** [comment]
> 但是我用\renewcommand{\qedsymbol}{}并没有效果

截个图？

**Comment by netheril96** [comment]
算了，我就留着这个符号好了

**Comment by Stone-Zeng** [comment]
直接在导言区重定义好了：

```tex
\theorembodyfont{\normalfont}
\theoremheaderfont{\normalfont\heiti}
%\theoremsymbol{\ensuremath{\square}}
\theoremsymbol{}
\renewtheorem*{proof}{证明}
```

原来的定义在 `thuthesis.cfg` 中。
