### ISSUE TITLE
书籍引用最后少个句号

### ISSUE THREAD

**Issue by lollloll** [xueruini/thuthesis#328]
![default](https://user-images.githubusercontent.com/5697871/38779809-27aa371c-4100-11e8-8da4-574db36945c5.PNG)

如图，不知道是不是bug

**Comment by zepinglee** [comment]
《写作指南》第 21 页 3.5.6(8)：
> 每条文献结尾可加“.”，图书的文献一般不加。

我也不知道为何要这样要求，但是现在还是照规定做

**Comment by zepinglee** [comment]
奇怪的是，学校的 word 模板也没遵守这个规定
