### ISSUE TITLE
编辑后cover部分有三张空白页该怎么去除？

### ISSUE THREAD

**Issue by mumushanyu** [xueruini/thuthesis#332]
又过来询问了……网上找的\clearpage或\openany 可能是我没用对？还是存在的……

**Comment by xueruini** [comment]
哪个版本模板？能给个例子么

**Comment by mumushanyu** [comment]
额……没找到具体的模板，有些说直接添加这个命令就可以……然后我各种尝试……未果……

**Comment by xueruini** [comment]
`kpsewhich thuthesis.cls` 看一下版本号

先不要在 tex 里加东西，保留一个能复现问题的最小例子发出来

**Comment by mumushanyu** [comment]
刚看了毕业格式，才知道那三张空白页是为单双面打印区别加的，不是额外的空白页，我用的是v5.4.3这个版本。昨晚把你的问题理解错了。
不是模板出状况，太谢谢你了。
