### ISSUE TITLE
当先后引用/section和/subsection时，定义好的段前段后距离和正常格式不一致。

### ISSUE THREAD

**Issue by mumushanyu** [xueruini/thuthesis#333]
![1524228025](https://user-images.githubusercontent.com/38512798/39051417-2c90a160-44db-11e8-8209-bcbb862232da.png)
文字有点说不清楚，我上传了 一个编译好的图片。
不知道怎么去改它，直接被发现了，格式太折磨人了。

**Comment by mumushanyu** [comment]
我在想是不是因为这样
 section={
    afterindent=true,
    beforeskip={\ifthu@bachelor 25bp\else 24bp\fi\@plus 1ex \@minus .2ex},
    afterskip={\ifthu@bachelor 12bp\else 6bp\fi \@plus .2ex},
    format={\thu@title@font\ifthu@bachelor\sihao[1.286]\else\sihao[1.429]\fi},
因为规定了afterindent=true 所以只能在有缩进的内容后有这样的行间距

**Comment by xueruini** [comment]
3.1 只有标题没有正文内容。我理解在正式论文中第一种场景基本不可能出现

**Comment by mumushanyu** [comment]
这样……那我去加点正文，谢谢啦
