### ISSUE TITLE
编译后正文字体是横过来的

### ISSUE THREAD

**Issue by Vargnatt** [xueruini/thuthesis#336]
使用`latexmk -xelatex main`编译后，目录和正文字体是横着的（和书脊一样），但是标题不影响。
 

![1524411115](https://user-images.githubusercontent.com/6397830/39096644-86bfb5bc-4685-11e8-9b15-414efa9cff60.png)
![1524411154 1](https://user-images.githubusercontent.com/6397830/39096645-8a5596c4-4685-11e8-8e1b-af695b4f671b.png)

而且看起来字体也不对，请问相关格式如何配置

**Comment by Vargnatt** [comment]
我发现是因为shuji的问题。但是为什么shuji使用了CJKvert以后对全局有效呢？

**Comment by xueruini** [comment]
> 为main里面加入了/shuji的问题

没看懂。。。这是两个独立的文件？你把他们合并成一个文件了？shuji 里的命令是会全文旋转

**Comment by Vargnatt** [comment]
是的，我之前以为`/NewDocumentCommand`只对它自己的page有效，就在main里面加了`/shuji`
