### ISSUE TITLE
THUthethesis论文模板默认字体变成黑体

### ISSUE THREAD

**Issue by lioucd** [xueruini/thuthesis#341]
Texlive2017+Texstudio编译环境，在下载了缺少的字体Kati-gb2312和Fangsong-gb2312后，用Xelatex跑通了模板，但是出现了模板中默认字体全部变成黑体的情况，论文的正文默认字体应该是宋体，这个应该在哪里配置呢？
@xueruini 
![image](https://user-images.githubusercontent.com/35163277/39794246-ef564570-537b-11e8-8108-81a678bb7d30.png)

**Comment by zepinglee** [comment]
这是我上次取消微软雅黑时的失误。

原来因为 fontset=windowsnew 会使用雅黑字体，我设置成了所有 windows 都自动调用 fontset=windowsold，但是这导致使用 KaiTi_GB2312 和 FangSong_GB2312 （似乎在新版系统中缺失？）

我再开一个 PR，顺便解决最新版 ctex 在 mac 下配置苹方字体的问题。

**Comment by lioucd** [comment]
再开一个PR是什么意思呢？是说重新发布新版本的模板吗？

**Comment by zepinglee** [comment]
Pull request

缺少 Kati-gb2312 和 Fangsong-gb2312 是我上次的失误，但是全文变成黑体就不应该了。

**Comment by lioucd** [comment]
我是在windows10环境下跑的模板，在CTAN上下载的最新版模板V5.4.4，一下载下来原始模板用Xelatex编译出来的所有字体就是黑体，感觉很奇怪。
