### ISSUE TITLE
请问如何取消cmajor

### ISSUE THREAD

**Issue by panranyang** [xueruini/thuthesis#345]
将论文送给老师检查格式时， 老师说现在专硕已经不需要写学科了。 于是我将cover中cmajor那一栏注释了。然而新生成的PDF中 封面还是有学科那一栏选项。

将cmajor用%注释后封面大概是这样：
培养单位： XXXX
学科：
研究生： XXXX
指导老师：XXXX

请问该如何将这一行删掉呢？

**Comment by Stone-Zeng** [comment]
注释掉 `cmajor` 只是不指定这一字段，但输出还是会照常的。所以需要在定义的地方把这一块字段删掉。

可以进行如下 patching 而不伤身体：

```tex
\makeatletter
\patchcmd{\thu@first@titlepage@other}%
  {\thu@put@title{\thu@major@title} & \thu@title@sep & {\ziju{0.1875}\thu@cmajor}\\}{}%
  {}{}
\makeatother
```

放在 `\documentclass[...]{thuthesis}` 之后就好了。

**Comment by xueruini** [comment]
这个字段以前是必选，现在可选了？
