### ISSUE TITLE
关于公式与正文的间隔

### ISSUE THREAD

**Issue by liboaidushu** [xueruini/thuthesis#346]
使用`equation`环境命令来输入公式，发现与正文的间隔（空白）过大。根据格式说明应该是单倍行距，段前6磅，段后6磅。请问模板(master)中是这样设置的吗？如果不是如何只修改`equation`或者`align`部分与正文的间隔。

**Comment by xueruini** [comment]
https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx#L1497-L1500

**Comment by liboaidushu** [comment]
问题就在这里，我在看thuthesis.pdf时就看到关于这的说明。但是这个设置是全局的，如果改动这里，那么正文其他部分的段前后的行距也会受到影响，而目前的设置是与写作标准的正文要求是一致的，只是公式与正文的行距会显得过大，需要只对公式环境修改。

**Comment by xueruini** [comment]
这4个参数只影响公式和正文的间距

**Comment by liboaidushu** [comment]
好的，如下设置完美解决。多谢！
```latex
\renewcommand\normalsize{%
  \@setfontsize\normalsize{12bp}{20bp}%
  \abovedisplayskip=12bp \@plus 2bp \@minus 2bp
  \abovedisplayshortskip=12bp \@plus 2bp \@minus 2bp
  \belowdisplayskip=\abovedisplayskip
  \belowdisplayshortskip=\abovedisplayshortskip}
```

**Comment by xueruini** [comment]
> 好的，如下设置完美解决。多谢！

是不是学校规定更新了？这部分设置很久没有动过了

**Comment by liboaidushu** [comment]
不知道开发thuthesis时是参考的那个格式要求版本，目前我们写作是参考清华大学研究生学位论文写作指南（201109）版本，其中对公式与正文之间的间隔要求设置是单倍行距，段前6磅，段后6磅。目前ththesis.cls的设置出来的效果明显可以看出公式与正文间的空白较大。

**Comment by xueruini** [comment]
那我就统一改成 12bp 吧

**Comment by xueruini** [comment]
https://github.com/xueruini/thuthesis/commit/c75e38d814423ef6e8aa7eb49bc01465ed6485b8

**Comment by huiyiqun** [comment]
我发现就算把这个值改成0在公式前也会有一行的间距，不清楚是怎么造成的。

**Comment by huiyiqun** [comment]
抱歉，这是我的问题，不小心多加了换行。
