### ISSUE TITLE
如何参考文献最后加上 . 号

### ISSUE THREAD

**Issue by fupolarbear** [xueruini/thuthesis#350]
参考文献类型是 Inbook 和 incollection 的后面没有 . (英文句号)。看了看「清华大学研究生学位论文写作指南-2011版」和格式审查老师的要求似乎要求加上…
请问如何加上… bst 文件看不太懂…看到了一些奇怪的规则…

```FUNCTION {fin.entry}
{ type$ "book" =
  type$ "inbook" = or
  type$ "incollection" = or
  type$ "collection" = or
    'skip$
    'add.period$
  if$
  write$
  newline$
}
```

感觉是不是这段的问题啊，请问该如何 patch 才能不伤身体（正经

**Comment by zepinglee** [comment]
《写作指南》第 21 页 3.5.6(8)：
> 每条文献结尾可加“.”，图书的文献一般不加。

我也不知道为何要这样要求，但是现在还是照规定做

**Comment by zepinglee** [comment]
我一直觉得这个规定很蠢……

既然现在格式审查老师要求加上的话， @xueruini 我们是不是统一加上？

**Comment by fupolarbear** [comment]
@zepinglee 我去…写作指南竟然还在后面加补充声明…
再请问 bst 也对 collection/incollection 类型做了这个处理，collection 是「汇编」，请问跟图书一样么？
多谢！

**Comment by zepinglee** [comment]
@fupolarbear 学校《写作指南》没有对“图书”下定义，也没有给出任何一个例子是不带点的。

我的理解是，collection 也应该算作图书的一种，incollection 是“普通图书的析出文献”，也应该算是图书。

**Comment by zepinglee** [comment]
@fupolarbear 你要自己改的话，把
```
  type$ "incollection" = or
  type$ "collection" = or
```
这两行直接去掉就行，

如果你要改成全部都加点:
```
FUNCTION {fin.entry}
{ add.period$
  write$
  newline$
}
```

**Comment by fupolarbear** [comment]
@zepinglee 对，你的理解没有错，搜了搜 incollection 的标号跟普通图书一样都是 M，那么两个应该处理上是一样的。而且指南里的确没有定义，也全部加点但是给出了矛盾的说明，可能写的人自己也晕了吧 anyway。

最后大佬也不吝给出了解决方法，非常感谢。

**Comment by xueruini** [comment]
> 既然现在格式审查老师要求加上的话， @xueruini 我们是不是统一加上？

我觉得先 hold 一下吧，观察一下反馈情况
