### ISSUE TITLE
综合论文训练中题目两字出现在标题上方而非左方

### ISSUE THREAD

**Issue by kaisadadi** [xueruini/thuthesis#352]
如图所示，其他同学也出现了这样的问题，
请问这是sty文件的问题吗？
![1](https://user-images.githubusercontent.com/17382818/40268686-6c967944-5ba4-11e8-8e3b-d3b61cd60cee.png)

**Comment by Stone-Zeng** [comment]
见 #339

**Comment by kaisadadi** [comment]
thanks a lot!
