### ISSUE TITLE
关于参考文献的问题

### ISSUE THREAD

**Issue by daiannan1993** [xueruini/thuthesis#354]
运行之后发现参考文献把bib文件中的所有参考文献都列出来了，有些没有用到的也罗列了出来，并且顺序是按照bib文件中的顺序而非引用的顺序，请问本身就是这样设计的吗还是有什么地方没有设置准确吗？多谢了~

**Comment by zepinglee** [comment]
这是因为你自己在某个地方写了 `\nocite{*}`

**Comment by daiannan1993** [comment]
我仔细检查了一下并没有啊。。之前也看到网上也有给出这个解释的，不过我这里并没有找到。。

**Comment by zepinglee** [comment]
```
grep -ir "nocite" .
```

**Comment by daiannan1993** [comment]
啊因为我起初编译生成了bbl文件，但是更改了正文之后没有删掉bbl文件。现在删除重新生成之后就准确了。
