### ISSUE TITLE
请问参考文献中是否可以不显示url

### ISSUE THREAD

**Issue by jin-li** [xueruini/thuthesis#355]
现在的参考文献格式好像是只要refs.bib中的bibtex中有url字段，打印出来的参考文献中就会显示url。由于bibtex是其他文献管理软件生成的，一般都会带有url，但实际上在论文中打印时没必要把这些url打印出来。请问有没有办法不让这些url显示在参考文献中？

**Comment by jin-li** [comment]
@zepinglee 好的，谢谢~

**Comment by zepinglee** [comment]
@jin-li 好像还会有些问题，虽然设置了不显示 url，但是
1. 文献载体标识还是会自动添加 “/OL”
2. 引用的网页 online 是必须有 url 的，在这种情况下也会不显示 url
之后有心情修复吧
