### ISSUE TITLE
想请问下表格或者图的标题如果有换行的话，那么其文字的对齐方式确定是左对齐么？

### ISSUE THREAD

**Issue by cfanyyx** [xueruini/thuthesis#357]
如题~

**Comment by cfanyyx** [comment]
求大神解答一下！

**Comment by xueruini** [comment]
是

**Comment by cfanyyx** [comment]
@xueruini 还想请问下参考文献的内容如何左对齐？

**Comment by zepinglee** [comment]
@cfanyyx 
> 还想请问下参考文献的内容如何左对齐？

你用的是什么样式？可以给个截图说明一下要怎么对齐？

**Comment by cfanyyx** [comment]
@xueruini @zepinglee 还有一个问题是，写作说明里面要求表格和图的标题中的英文和数字都要使用宋体，请问如何单独设置表格和图标题里面的英文和数字为宋体，包括“图5.3”、“表5.1”这个里面的数字都要使用宋体，急求可以应急解决的方法！

**Comment by zepinglee** [comment]
这不是对齐的问题，这是 url 断行的问题。你试试在导言区加入下面的代码会不会好一点：
```
\makeatletter
\g@addto@macro\UrlBreaks{%
  \do\a\do\b\do\c\do\d\do\e\do\f\do\g\do\h\do\i\do\j%
  \do\k\do\l\do\m\do\n\do\o\do\p\do\q\do\r\do\s\do\t%
  \do\u\do\v\do\w\do\x\do\y\do\z%
  \do\A\do\B\do\C\do\D\do\E\do\F\do\G\do\H\do\I\do\J%
  \do\K\do\L\do\M\do\N\do\O\do\P\do\Q\do\R\do\S\do\T%
  \do\U\do\V\do\W\do\X\do\Y\do\Z%
  \do\1\do\2\do\3\do\4\do\5\do\6\do\7\do\8\do\9\do\0%
}
\makeatother
```

**Comment by cfanyyx** [comment]
@zepinglee 确实变得正常了！谢谢！能不能再帮忙解答一下表格和图标题的宋体问题？

**Comment by zepinglee** [comment]
@xueruini 我看到目前有提到一句“调用 breakurl 宏包”， 但我建议默认处理一下 url 断行的问题，因为默认情况下很容易搞得很丑。

**Comment by xueruini** [comment]
> 还有一个问题是，写作说明里面要求表格和图的标题中的英文和数字都要使用宋体，请问如何单独设置表格和图标题里面的英文和数字为宋体，包括“图5.3”、“表5.1”这个里面的数字都要使用宋体，急求可以应急解决的方法！

现在就是这样的

![image](https://user-images.githubusercontent.com/1863/40931621-40b201b0-685e-11e8-8632-36d3f300eccd.png)

**Comment by xueruini** [comment]
> 我看到目前有提到一句“调用 breakurl 宏包”， 但我建议默认处理一下 url 断行的问题，因为默认情况下很容易搞得很丑。

load breakurl 还是你这个方式？

**Comment by cfanyyx** [comment]
@xueruini 现在的数字和英文是TNR的不是宋体T_T

**Comment by zepinglee** [comment]
@xueruini 我没用过 breakurl，但`\UrlBreaks` 方式基本满足要求，尤其能应对连续字母数字的 url，比如 GB/T 7714 的一个例子：http://www.cnnic.net.cn/hlwfzyj/hlwxzbg/201201/P020120709345264469680 。

**Comment by zepinglee** [comment]
@cfanyyx 西文对应于宋体就是 TNR，中易宋体的西文基本不能用

**Comment by cfanyyx** [comment]
@zepinglee 只是想请教一下图表标题中字体单独变更的方法，我自己用一下，因为自己想根据写作说明中来，求！

**Comment by zepinglee** [comment]
丑得一比，新手还是别乱搞了

**Comment by cfanyyx** [comment]
@zepinglee 但是我们写作指南上是这样规定的，能不能告诉一下设置的方法，我自己用，

**Comment by xueruini** [comment]
> @xueruini 我没用过 breakurl，但\UrlBreaks 方式基本满足要求，尤其能应对连续字母数字的 url，比如 GB/T 7714 的一个例子：http://www.cnnic.net.cn/hlwfzyj/hlwxzbg/201201/P020120709345264469680 。

![image](https://user-images.githubusercontent.com/1863/40949915-ed138ce6-68a2-11e8-9387-610224ad4f7f.png)
![image](https://user-images.githubusercontent.com/1863/40949927-f7c313dc-68a2-11e8-94f1-eb56cb38b913.png)

**Comment by xueruini** [comment]
> http://www.cnnic.net.cn/hlwfzyj/hlwxzbg/201201/P020120709345264469680 。

404

**Comment by Stone-Zeng** [comment]
@cfanyyx 我就假定你用 Windows 好了。

```tex
% 放在导言区
\DeclareCaptionFont{thu}{\dawu[1.5]\normalfont\CJKfamily+{zhsong}}
\DeclareCaptionLabelFormat{thu}{{\dawu[1.5]\normalfont\CJKfamily+{zhsong} #1~#2}}
\captionsetup{labelformat=thu,labelsep=thu,font=thu,skip=6bp}
```

Linux 没有中易宋体，我拿文鼎简报宋代替，可以这么做：

```tex
\setCJKfamilyfont{song}{AR PL SungtiL GB}
\DeclareCaptionFont{thu}{\dawu[1.5]\normalfont\CJKfamily+{song}}
\DeclareCaptionLabelFormat{thu}{{\dawu[1.5]\normalfont\CJKfamily+{song} #1~#2}}
\captionsetup{labelformat=thu,labelsep=thu,font=thu,skip=6bp}
```

![image](https://user-images.githubusercontent.com/18233088/40954890-5d2816ee-68b9-11e8-882b-9c6edb519f96.png)

效果是相当猥琐的。当然和 @zepinglee 一样，强烈不建议使用中易宋体（和文鼎简报宋）的配套西文。它的设计很糟糕，而且完全没有考虑字母的间距处理，应当绝对避免使用。

不过话又说回来，高质量的宋体，比如思源等等，它的配套西文还是相当可靠的。在不用斜体、不考虑和数学字体搭配的情况下，甚至优于直接用其他西文字体（因为做了scale、基线等优化）。

**Comment by zepinglee** [comment]
@xueruini breakurl 虽然灵活，但是它是依赖 hyperref 的，这回导致更多的复杂度，而 `\UrlBreaks` 只需要 url 宏包（hyperref 依赖 url）。

我刚刚稍微研究了一下，即使是 `\usepackage[anythingbreaks]{breakurl}` 似乎也不允许从字母数字之间断行：如图：
<img width="1125" alt="screen shot 2018-06-05 at 3 29 11 pm" src="https://user-images.githubusercontent.com/12290822/40961450-3d7a7d48-68d5-11e8-9dba-4972cb1cbd41.png">

然后我改进了一下 `\UrlBreaks` 的方法：
```
\def\UrlBreaks{%
  \do\a\do\b\do\c\do\d\do\e\do\f\do\g\do\h\do\i\do\j%
  \do\k\do\l\do\m\do\n\do\o\do\p\do\q\do\r\do\s\do\t%
  \do\u\do\v\do\w\do\x\do\y\do\z%
  \do\A\do\B\do\C\do\D\do\E\do\F\do\G\do\H\do\I\do\J%
  \do\K\do\L\do\M\do\N\do\O\do\P\do\Q\do\R\do\S\do\T%
  \do\U\do\V\do\W\do\X\do\Y\do\Z%
  \do\1\do\2\do\3\do\4\do\5\do\6\do\7\do\8\do\9\do\0%
}
\def\UrlBigBreaks{\do\:\do@url@hyp%
  \do\.\do\@\do\\\do\/\do\!\do\_\do\|\do\;\do\>\do\]%
  \do\)\do\,\do\?\do\&\do\'\do+\do\=\do\#}%
```
这样优先从 `\UrlBigBreaks` 断行，`\UrlBreaks` 也允许断行，效果要好很多：
<img width="1042" alt="screen shot 2018-06-05 at 3 33 46 pm" src="https://user-images.githubusercontent.com/12290822/40961687-e02e2102-68d5-11e8-8166-db92c28f3628.png">

**Comment by xueruini** [comment]
直接把你的办法加进去吧，我加你为开发者了

**Comment by cfanyyx** [comment]
@Stone-Zeng 非常非常非常感谢！帮我解决了这个问题。
@xueruini 怕出麻烦，所以我这边单独按照规定来设置。没办法，一纸规定，无可奈何。

**Comment by zepinglee** [comment]
@cfanyyx 有老师要求你这样改嘛？我估计到时候会要求再改回去

**Comment by Stone-Zeng** [comment]
其实可以用方正书宋的，西文部分至少比中易强一点。正常人应该不可能看出来，而且可以免费使用。

**Comment by zepinglee** [comment]
在 9dbf177c4818ad21945d42c9be81dcc66c66c1e1 中处理

**Comment by xueruini** [comment]
@zepinglee https://ctan.org/pkg/xurl

**Comment by zepinglee** [comment]
我试了一下，效果确实比我的方法要好：
![screen shot 2018-06-07 at 10 03 42 pm](https://user-images.githubusercontent.com/12290822/41104785-c71c54b6-6a9e-11e8-8e9e-92d2f511ee5b.png)
至于原理我也没搞太懂……

不过这个宏包实在太新了，好在代码不是很长，建议直接 copy paste 进 thuthesis 里

**Comment by zepinglee** [comment]
已经 push 了 2b7e81a

**Comment by xueruini** [comment]
看到作者就信了这个包

**Comment by cfanyyx** [comment]
@Stone-Zeng 请问一下目前“图 2.1”，“表 1.1”这些label的“图和表字样“与“x.x”之间是有一个空格么？请问该如何去除这个空格？

**Comment by cfanyyx** [comment]
@Stone-Zeng 引用你的这张图：
![40954890-5d2816ee-68b9-11e8-882b-9c6edb519f96](https://user-images.githubusercontent.com/7723243/41204046-17858fec-6d12-11e8-90cb-6215f698faed.png)

**Comment by cfanyyx** [comment]
@Stone-Zeng 引用你的这张图：
![40954890-5d2816ee-68b9-11e8-882b-9c6edb519f96](https://user-images.githubusercontent.com/7723243/41204062-3a5ab2ea-6d12-11e8-8b28-68b9b1beca97.png)

**Comment by Stone-Zeng** [comment]
惯例是在中文字符与西文字符(包括阿拉伯数字)放一个空白，不只是图注如此。建议您还是不要改比较好。

关于混排时的空格，给个知乎链接：<https://www.zhihu.com/question/19587406>

另外最好不要在一个 issue 中讨论不太相关的内容，再开一个会更符合社区规范。不过已经讨论下来这么多，就随意吧。。。

**Comment by xueruini** [comment]
```latex
\DeclareCaptionLabelFormat{thu}{{\dawu[1.5]\normalfont #1~#2}}
```

**Comment by Stone-Zeng** [comment]
@xueruini 这是原来的代码吧？

可以改成
```tex
% 不修改字体
\DeclareCaptionLabelFormat{thu}{{\dawu[1.5]\normalfont #1\hskip0pt#2}}
% 修改西文字体为宋体
\DeclareCaptionLabelFormat{thu}{{\dawu[1.5]\normalfont\CJKfamily+{zhsong} #1\hskip0pt#2}}
```

就是插入一个零宽空格。

**Comment by cfanyyx** [comment]
@Stone-Zeng @xueruini 感谢！
