### ISSUE TITLE
文献中 volume 数字和后面文字的距离感觉有点大

### ISSUE THREAD

**Issue by xueruini** [xueruini/thuthesis#358]
不知道是不是规范如此

![image](https://user-images.githubusercontent.com/1863/40982322-9166c364-690f-11e8-933a-0f5f327a88b2.png)
![image](https://user-images.githubusercontent.com/1863/40982413-ca3bb226-690f-11e8-90d2-78e20a36763b.png)

**Comment by zepinglee** [comment]
这两个都是 “series: volume  booktitle” 的结构

我查了一下， 2005 的规定是：
![screen shot 2018-06-05 at 10 40 49 pm](https://user-images.githubusercontent.com/12290822/40983255-ca0317c0-6911-11e8-9253-f1f29a044fc3.png)

2015 的规定是：
![screen shot 2018-06-05 at 10 32 26 pm](https://user-images.githubusercontent.com/12290822/40983272-d2ce1a58-6911-11e8-8a99-8fea78e85e50.png)

我目前的是按照 2015 实现的，所以输出了一个 `\quad`；之后我会改成 `\ `

**Comment by zepinglee** [comment]
Fixed in aaad7eda68bc095d22aee9518eb78e2e46ae712d .
