### ISSUE TITLE
缺失thuthesis.cls、thuthesis.cfg

### ISSUE THREAD

**Issue by ash799** [xueruini/thuthesis#359]
在5月的一次更新后，文件列表默认缺失thuthesis.cls、thuthesis.cfg。
虽然通过`latex thuthesis.ins`这样手动更新的方式可以解决问题，但是依旧容易出错，建议补上thuthesis.cls和thuthesis.cfg

**Comment by zepinglee** [comment]
啥叫“旧容易出错”？就算有 cls 文件，也是用 `xetex thuthesis.ins` 生成的

**Comment by xueruini** [comment]
没看懂这个问题

**Comment by Stone-Zeng** [comment]
@xueruini 他的意思好像是 CTAN 上下载到的 zip 没有这几个文件：

![image](https://user-images.githubusercontent.com/18233088/41239526-139959f4-6dcb-11e8-9044-28fbe0dd40f5.png)

见 <https://ctan.org/tex-archive/macros/latex/contrib/thuthesis>

**Comment by xueruini** [comment]
ctan 上传的包如果有 `.ins` 就不用川 cls/sty 了，texlive, miktex 等自己会重新组织，代码，文档都是在不同的位置。所以推荐通过包管理系统来更细包，要么就从 github 直接下（这里是打包了 cls/cfg 的）
