### ISSUE TITLE
声明页和授权页替换成扫描的图片

### ISSUE THREAD

**Issue by Ebonnov** [xueruini/thuthesis#36]
本科生论文最终提交的电子版要求声明页和授权页有签字。这产生了把声明页和授权页整替换成扫描的图片的需求。

我看到context/t-thuthesis里有授权页的定义, 但是不清楚这里如何影响到latex/下面内容的生成。求教:)

**Comment by alick** [comment]
基于上面的思路，我用 pdfpages 实现了一下。大家看看？
