### ISSUE TITLE
插入一张较大图片（例如由六张子图组成占据整个页面）会被自动移至章节最后的问题

### ISSUE THREAD

**Issue by rrenjie** [xueruini/thuthesis#360]
使用subfigure插入一张由六张子图组成大图时（此时图片占据整个页面），编译生成pdf之后会自动将该图片放在章节最末端（即本章小结之后），这样带来了两个问题：1）插入图片的文字离图片太远，检索起来不方便；2）在大图之后插入新的图片都会被移到章节最末端。

想请问一下，有没有办法不让大图被移到章节最末端，而是紧邻插入图片的文字下方出现？

**Comment by xueruini** [comment]
`[!h]`

**Comment by rrenjie** [comment]
[!h]不行。我已经找到解决方法了，用[p]，允许整个图片占据一页，这样编译的时候就会将图片作为一整页插入到最近的位置。
