### ISSUE TITLE
西文字体使用严格的 Times New Roman 和 Arial

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#361]
学校要求的是正文西文使用 Times New Roman 和 Arial 字体，目前模板使用 newtx 来配置：
```
\PassOptionsToPackage{no-math}{fontspec}
\RequirePackage[defaultsups]{newtxtext}
\RequirePackage{newtxmath}
```
正如 @Stone-Zeng 在 #296 所讲，newtx 实际用的是 TeX Gyre Termes，严格意义上跟 Times New Roman 是不太一样的。所以要不要考虑使用真正的 Times New Roman 和 Arial？

如果用 fontspec 调用 Times New Roman，可以考律的方案有：
1. 使用默认的 Computer Modern
2. newtxmath 宏包
3. STIX 宏包
3. unicode-math + STIX / STIX2 / XITS / Tex Gyre Termes math

**Comment by Stone-Zeng** [comment]
数学用 Computer Modern 肯定会和 times 系不配的，不如拿 `mathspec`  包去拼一下。就是公式里面字母、数字等用真正的 Times New Roman，符号还是用 newtx，不知道行不行？

**Comment by zepinglee** [comment]
@Stone-Zeng 用 mathspec 调用 STIX 是吧？我之前试过用 fontspec 调用 Times New Roman 配置 newtxmath，但是还有些问题

**Comment by Stone-Zeng** [comment]
stix2 现在有 Unicode math 支持了，和 xits 一样可以用 `unicode-math` 宏包调用。但貌似 Unicode math 仍然远远不是主流。

**Comment by xueruini** [comment]
> 这样正文使用规定的字体，数学使用 Computer Modern Math

直接用 tnr 和 arial 我没问题，主要是跟下面的数学字体不协调

> 缺点是舍弃了 pdflatex 的支持。

很久以来都是只用 xelatex 测试

**Comment by zepinglee** [comment]
我参考了 https://tex.stackexchange.com/questions/394111/math-digits-are-in-cm-with-newtxmath-and-fontspec-lualatex-tex-live-2017 ：
```
\usepackage[upint,slantedGreek]{newtxmath}
\DeclareSymbolFont{operators}{OT1}{ntxtlf}{m}{n}
\SetSymbolFont{operators}{bold}{OT1}{ntxtlf}{b}{n}
\usepackage{bm}

\usepackage[no-math]{fontspec}

\setmainfont{Times New Roman}
\setsansfont{Arial}
\setmonofont{Courier}
```
`\mathrm` 的效果：
![screen shot 2018-06-18 at 12 00 50 pm](https://user-images.githubusercontent.com/12290822/41517714-93a04706-72ef-11e8-8e1e-d5b230900ee3.png)

但是 `\mathrm` 和 `\mathbf` 的希腊字母还不合适，`\mathbf` 的效果：
![screen shot 2018-06-18 at 12 00 54 pm](https://user-images.githubusercontent.com/12290822/41517727-ab5350f0-72ef-11e8-8a80-fda876a69074.png)

**Comment by zepinglee** [comment]
我感觉 unicode-math 太新了，容易有兼容性问题，所以建议用 nfss + newtx 慢慢打磨成合适的样子

**Comment by Stone-Zeng** [comment]
试了一下 `mathspec`，基本上效果是可以了。可能 `fontspec` 的选项会有冲突，需要处理一下，倒也不是什么大问题。

```tex
\documentclass{article}
\usepackage{amsmath,newtxmath,mathspec,etoolbox}
\usepackage{ctex} % 必须在 mathspec 之后

\makeatletter
% 增加 \mathbfit 定义
\expandafter\patchcmd\csname\string\setmathrm\endcsname
  {\DeclareMathAlphabet{\mathbf}{\eu@enc}{\eu@mathrm}{bx}{n}}%
  {\DeclareMathAlphabet{\mathbf}{\eu@enc}{\eu@mathrm}{bx}{n}%
   \DeclareMathAlphabet{\mathbfit}{\eu@enc}{\eu@mathrm}{bx}{it}}%
  {\typeout{Success}}{\typeout{Failure}}
\makeatother

\setmainfont{Times New Roman}
\setmathfont(Digits,Latin,Greek){Times New Roman}
\setmathrm{Times New Roman}
%\setmathsf{TeX Gyre Heros}
\setmathsf{Arial}
%\setmathtt{TeX Gyre Cursor}
\setmathtt{Courier New}

\def\ii{\mathrm{i}}
\def\Latinalphabets{ABCDEFGHIJKLMNOPQRSTUVWXYZ}
\def\latinalphabets{abcdefghijklmnopqrstuvwxyz}
\def\Greekalphabets{%
  \Alpha      \Beta       \Gamma      \Delta      \Epsilon
  \Zeta       \Eta        \Theta      \varTheta   \Iota
  \Kappa      \Lambda     \Mu         \Nu         \Xi
  \Omicron    \Pi         \Rho        \Sigma      \Tau
  \Upsilon    \Phi        \Chi        \Psi        \Omega
}
\def\greekalphabets{%
  \alpha      \beta       \gamma      \delta      \epsilon
  \varepsilon \zeta       \eta        \theta      \vartheta 
  \iota       \kappa      \varkappa   \lambda     \mu
  \nu         \xi         \omicron    \pi         \rho
  \varrho     \sigma      \varsigma   \tau        \upsilon
  \phi        \varphi     \chi        \psi        \omega
}
\def\SHOW#1{\[#1{\Latinalphabets\latinalphabets}\]\[#1{\Greekalphabets\greekalphabets}\]}

\begin{document}

\section{字母表 (Alphabets)}

\texttt{rm (Times New Roman)}       \SHOW{\mathrm}
\texttt{it (Times New Roman)}       \SHOW{\mathit}
\texttt{bf (Times New Roman)}       \SHOW{\mathbf}
\texttt{bfit (Times New Roman)}     \SHOW{\mathbfit}
\texttt{sf (Arial)}                 \SHOW{\mathsf}
\texttt{tt (Courier New)}           \SHOW{\mathtt}
\texttt{normal (Nimbus Rom No 9 L)} \[\mathnormal{\Latinalphabets\latinalphabets}\]
\texttt{cal (txsys)}                \[\mathcal{\Latinalphabets}\]
\texttt{bb (txsyb)}                 \[\mathbb{\Latinalphabets}\]
\texttt{frak (txmia)}               \[\mathfrak{\Latinalphabets\latinalphabets}\]

\section{公式 (Formulas)}

\[
  \ii\hbar \frac{\partial \psi(x)}{\partial t}
  =\big[c\mathbfit{\alpha}\cdot(-\ii\hbar\nabla) + \beta mc^2\big] \psi(x)
\]
\[
  \ii\hbar \gamma^\mu \frac{\partial \psi(x)}{\partial x^\mu} - mc \psi(x) = 0
\]
\[
    \int_0^\pi        \sin x \, \mathrm{d} x
  = \int\limits_0^\pi \sin x \, \mathrm{d} x
  = \cos 0 - \cos\pi + C
  \quad
  \int\limits_0^\infty \int_0^{\text{正无穷大 inf}}
  \sum_{i=1}^\infty \prod_{j=i}^\infty \coprod_{k=i}^\infty
\]

\end{document}
```

![test_ _1](https://user-images.githubusercontent.com/18233088/41701309-95159250-755e-11e8-9103-71353b08dcc0.png)

![test_ _2](https://user-images.githubusercontent.com/18233088/41701329-a3e8cba8-755e-11e8-82d4-57ec0c2859ce.png)

**Comment by Stone-Zeng** [comment]
Times New Roman 并不是专为数学排版所涉及的字体，有些间距未必完美（注意小写的意大利体 f）。个人觉得 `mathspec` 更多算是一种 hackable 的操作，但既然你们学校有这样的~~无理~~要求，这也是一种实现思路。

**Comment by zepinglee** [comment]
@Stone-Zeng 感谢你的方法！Times New Roman 本来也没有数学符号。学校好像没有规定数学字体，但是我跟 xueruini 都觉得数学字体跟西文字体应该协调，所以不能算是“无理要求”吧。

我打算 hack 基于 newtx 的方法，但是现在还没怎么看懂 nfss……

**Comment by Stone-Zeng** [comment]
nfss 确实大坑，希望有生之年能看到 TeX 完全转到 opentype

**Comment by zepinglee** [comment]
嗯，我也赞同，opentype math 以后应该会成为主流

**Comment by xueruini** [comment]
搞个 PR 上来看看？ @zepinglee

**Comment by zepinglee** [comment]
@xueruini 需要些时间，完成后会发 PR

**Comment by zepinglee** [comment]
我试了一下 unicode-math，配置如下：
```LaTeX
\usepackage{amsmath}
\usepackage{unicode-math}
\unimathsetup{
  math-style=ISO,
  % 国标里的 grad, rot, nabla 使用粗正体，所以应该保留正体
  bold-style=upright, 
  mathrm=sym,
  mathbf=sym,
  mathit=sym,
  mathsf=sym,
  mathtt=sym,
  nabla=upright,
  partial=upright,
}

\setmainfont{Times New Roman}
\setsansfont{Arial}
\setmonofont{Courier}

% ss08 使积分号变为正体
\setmathfont[StylisticSet=8]{STIX2Math.otf}

% \mathcal 和 \mathscr 使用不用的 stylistic set
\setmathfont[range={scr,bfscr},StylisticSet=1]{STIX2Math.otf}

% STIX/STIX2 中 \partial (U+02202) 的字形做成了斜体，没有正体，所以用 XITS 的
\setmathfont[range=\partial]{xits-math.otf}

% 积分号的上下限默认置于上下
\removenolimits{%
  \int\iint\iiint\iiiint\oint\oiint\oiiint
  \intclockwise\varointclockwise\ointctrclockwise\sumint
  \intbar\intBar\fint\cirfnint\awint\rppolint
  \scpolint\npolint\pointint\sqint\intlarhk\intx
  \intcap\intcup\upint\lowint
}

% 小于等于号、大于等于号使用倾斜的
\protected\def\le{\leqslant}
\protected\def\ge{\geqslant}

% 国标里的省略号一律在中间
\def\mathellipsis{\cdots}
```

完整的代码在这里 https://gist.github.com/zepinglee/f3ba9d3416c4e6a844648fde1a9acbe1 。

然而还有两个问题：
1. `\mathbfit` 的数字仍为正体，这样就不适合表示“0向量”。
![screen shot 2018-07-04 at 1 46 41 am](https://user-images.githubusercontent.com/12290822/42236047-44a417b0-7f2c-11e8-9a2f-322c5434e771.png)
2. 需要将 `\nabla` 命令设为粗体的字符。

**Comment by xueruini** [comment]
赞持续挖掘的精神！

**Comment by zepinglee** [comment]
我回顾了刘海洋以前的答案（http://bbs.ctex.org/forum.php?mod=viewthread&tid=152494）：
> 正文不建议用 Times New Roman，而是用 \setmainfont 设置 TeX Gyre Termes 或 XITS 对前面对应……上面的原则主要是使用相对成套的字体。

我个人认为，虽然 TNR + STIX 在设计上不是成套的，但是相比之下，替换掉学校规定的特定字体更加不可接受（强迫症）。@xueruini @Stone-Zeng 你们怎么看？

**Comment by xueruini** [comment]
我个人倾向于配套字体，简单的设置方案。但这样的确会造成论文可能过不了，丢掉了模板存在的根基。两害相权取其轻吧

**Comment by Stone-Zeng** [comment]
最好还是可以问一下教务处。如果他们不能区分（或者不在乎） Times New Roman 和其他版本的 Times，那就最好不过了。

另外我挺想知道 @leo-liu 说的不要用 `mathspec` 的理由是什么……虽然这个包确实算是 hack，但如果作者自己不乱改也不会出什么问题吧？

**Comment by zepinglee** [comment]
@Stone-Zeng https://tex.stackexchange.com/questions/118244/what-is-the-difference-between-unicode-math-and-mathspec
> Because TeX does not apply kerning between characters from different fonts, using mathspec has its drawbacks, since you may find places in which the switch from the text font to the math font produces bad spacing

**Comment by Stone-Zeng** [comment]
话说 `thuthesis` 有考虑过支持 LuaTeX 吗？`mathspec` 只支持 XeTeX 的。

**Comment by xueruini** [comment]
> 话说 thuthesis 有考虑过支持 LuaTeX 吗？mathspec 只支持 XeTeX 的。

有愿意搞的可以 PR，等我估计够呛

**Comment by zepinglee** [comment]
我最近测试了一下 `unicode-math` + Times New Roman + STIX2Math，感觉数学字体部分有点太粗了，如图所示：
![screen shot 2018-07-18 at 11 57 38 pm](https://user-images.githubusercontent.com/12290822/42893326-9c3da99e-8ae6-11e8-8bf1-6fdbfc24d964.png)
一眼看过去，文字中的数学符“f”和“g”几乎能被认为是粗体。

另外，`newtx` 的作者 Michael Sharpe 在 stickstoo 宏包中说：
> As of the initial release of STIX2, the math fonts have some problem which make them unsuited to high quality mathematical typesetting...

@xueruini 怎么看？

**Comment by xueruini** [comment]
一个式子里的 f/g 看着是有点粗，后面几个还好

**Comment by zepinglee** [comment]
我失误了，刚刚给的例子的西文字体没设成 Times New Roman，还是 Computer Modern。其实 STIX2Math 在 Times New Roman 中的效果还不错：
![screen shot 2018-07-19 at 10 34 58 pm](https://user-images.githubusercontent.com/12290822/42949329-1bba2752-8ba4-11e8-810f-9faaefd031ec.png)

**Comment by zepinglee** [comment]
@Stone-Zeng 我的 macOS 10.13.6 上的 Times New Roman 是 Version 5.01.3x，有 U+FB01 (fi) 和 U+FB02 (fl) 两个字形，不知道 windows 那边怎么样……

**Comment by zepinglee** [comment]
然而我的 Times New Roman 没这个 feature：
![screen shot 2018-07-20 at 5 27 00 pm](https://user-images.githubusercontent.com/12290822/42994972-31e47c6e-8c42-11e8-8983-f0d7057edffd.png)

**Comment by muzimuzhi** [comment]
> 然而我的 Times New Roman 没这个 feature：
> ![screen shot 2018-07-20 at 5 27 00 pm](https://user-images.githubusercontent.com/12290822/42994972-31e47c6e-8c42-11e8-8983-f0d7057edffd.png)

win 和 macOS，系统自带的 time new roman 字体，是不同版本的。macOS 里的版本，更旧。

**Comment by xueruini** [comment]
连字符说不定会被审查老师给打回来
