### ISSUE TITLE
Windows 上的字体配置

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#367]
根据 @d-li14 反馈，在编译main.tex的时候还是遇到了一个找不到Courier字体的问题，如下
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "Courier" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
```

另外貌似还有一个字体的小问题
```
kpathsea:make_tex: Invalid filename `[STIX2Math', contains '['
```
在Ubuntu上测试也存在会有这个信息

**Comment by zepinglee** [comment]
@d-li14 第二个 STIX2Math 字体的报错比较诡异，我在 mac 上的 TeX Live 2018 测试没问题，travis 上的 TeX Live 2018 也没问题 https://travis-ci.org/xueruini/thuthesis/builds/402524358 ，所以你用的是什么版本的？

**Comment by Stone-Zeng** [comment]
第二个问题见 <https://tex.stackexchange.com/q/419854/136923>，之前我也遇到过，但似乎并不影响，所以就没管了。

**Comment by d-li14** [comment]
@zepinglee 是win10 TexLive2018上出现的，另外Ubuntu 18.04的测试是TexLive17。问题如 @Stone-Zeng 所述，对正常输出文档应该没有影响

**Comment by zepinglee** [comment]
确认 windows 上不能用 courier 嘛？那我打算改成 courier new 了

**Comment by quansilong** [comment]
Windows上编译出现同样的问题，找不到Courier字体的问题

**Comment by zepinglee** [comment]
Fixed in 7cb39259bcf76c0dc8c765279be4a41a1a87b7bd .
