### ISSUE TITLE
Windows编译出现字体问题

### ISSUE THREAD

**Issue by fengduole** [xueruini/thuthesis#368]
Windows 10 1809，TeXLive 2018，xelatex编译遇到如下错误(code clone自本项目)，提示缺少字体“KaiTi_GB2312”，不知何解

> ! fontspec error: "font-not-found"
> !
> ! The font "KaiTi_GB2312" cannot be found.
> !
> ! See the fontspec documentation for further information.
> !
> ! For immediate help type H <return>.

此外还有若干其他和字体相关的问题：

![image](https://user-images.githubusercontent.com/9671744/46644236-07c88880-cbb2-11e8-8dfe-291ac74cdee9.png)

求解答，感谢。

**Comment by zepinglee** [comment]
merge 一下 origin/master？
这个问题早就修复了

**Comment by fengduole** [comment]
感谢感谢, 拉取了最新版本好了.

> xetex thuthesis.ins
得到thuthesis.cls

然后用xelatex编译即可。
