### ISSUE TITLE
feature request: 给模版添加英文字符串

### ISSUE THREAD

**Issue by mattandryc** [xueruini/thuthesis#370]
@xueruini Please add an option/config to generate a thesis using English section titles and labels. 翻译如下：

### path: ./thuthesis.dtx

**line 918**
% \subsubsection{Acknowledgments}

**line 2048**
\ctexset{%
  chapter/name={Chapter,''},
  appendixname=Appendix,
  contentsname={Contents},
  listfigurename=List of Figures,
  listtablename=List of Tables,
  figurename=Figure,
  tablename=Table,
  bibname=References,
  indexname=Appendices,
}
\newcommand\listequationname{List of Equations}
\newcommand\equationname{Equation}
\ifthu@bachelor
  \newcommand{\cabstractname}{中文摘要}
  \newcommand{\eabstractname}{ABSTRACT}
\else

@xueruini 如果有其它字符串需要翻译的话，随时@一下我

**Comment by xueruini** [comment]
thanks for the sharing. There's discussion about English template (#67 #239 #232). Let's push it forward.

**Comment by zepinglee** [comment]
I'll handle this. 

@mattandryc Is there any writing guide for dissertations in English?

@xueruini  BTW, I don't think it necessary to generate a separate `.cfg` file because any modifications with be overwritten if the `.dtx` file is updated to a newer version.

**Comment by zepinglee** [comment]
I've just added an "english" option for the document class but I'm not sure of the translation of "个人简历、在学期间发表的学术论文与研究成果". @xueruini You can review and modify it.

**Comment by mattandryc** [comment]
> I've just added an "english" option for the document class but I'm not sure of the translation of "个人简历、在学期间发表的学术论文与研究成果". @xueruini You can review and modify it.

@zepinglee 个人简历 : Resume

**Comment by zepinglee** [comment]
@mattandryc The full title is "Resume, Publications During School and Research Achievements" and I guess "Resume" is too short. Is there an official document?

**Comment by mattandryc** [comment]
还有“List of Abbreviations”

**Comment by zepinglee** [comment]
你说的“学校给出的模板”是哪个？可以给个链接吗？

**Comment by mattandryc** [comment]
> 你说的“学校给出的模板”是哪个？可以给个链接吗？

没有链接，导师是直接发docx 。怎发给你？

**Comment by zepinglee** [comment]
> > 你说的“学校给出的模板”是哪个？可以给个链接吗？
> 
> 没有链接，导师是直接发docx 。怎发给你？

不妨发到我们两个的邮箱：xueruini@gmail.com , zepinglee@gmail.com 。

**Comment by zepinglee** [comment]
顺便吐槽一下，学校的很多文档都找不到官网，比如本科生毕设的写作指南

**Comment by mattandryc** [comment]
@zepinglee 我记错了，原来导师提供的是英文硕士论文的latex。模版特别老，感觉好几年没人在维护。刚发给你们了。

**Comment by zepinglee** [comment]
这个模板太老了，而且找不到学校官方给的正式模板，我个人觉得不宜在 thuthesis 按这个实现

**Comment by mattandryc** [comment]
同意，我觉得直接用flag，实用英文translation即可

**Comment by xueruini** [comment]
cute list icon

![image](https://user-images.githubusercontent.com/1863/50367896-c9dedc00-05c6-11e9-9143-185643a26b58.png)

**Comment by xueruini** [comment]
> 这个模板太老了，而且找不到学校官方给的正式模板，我个人觉得不宜在 thuthesis 按这个实现

@zepinglee any thoughts? 其实也就是翻译的问题，可以先搞一个出来，到时候被学校打回来就知道正确的是啥了

**Comment by zepinglee** [comment]
有道理，可以先搞一版出来

**Comment by zepinglee** [comment]
暂且译为“Resume, Publications and Research Achievements”，如果不合要求再反馈。

**Comment by xavieryao** [comment]
[英语专业论文写作指南.pdf](https://github.com/xueruini/thuthesis/files/2897740/default.pdf)
[sample_APA.docx](https://github.com/xueruini/thuthesis/files/2897741/sample_APA.docx)
[sample_MLA.docx](https://github.com/xueruini/thuthesis/files/2897742/sample_MLA.docx)

**Comment by zepinglee** [comment]
@xavieryao 有很多跟目前的实现不一致的地方。不过外文系有使用 LaTeX 的需求嘛？
