### ISSUE TITLE
模板改进建议

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#371]
### 行末注释
部分 `\newcommand` 定义的内容没有用 `%` 在行末注释

### Coding style：
- [ ] `\newcommand` 定义的命令不加大括号，同 `\def` 的格式一致
- [ ] 如果配对的大括号不在一行时 `}` 换行，类似 C 的大括号风格
- [ ] 尽量避免在参数重使用空格，除非是使用 key-value 的参数
- [ ] 几个常量宏（比如 `\thu@ack@name`）的命名应该一致

### 精简宏包：
xelatex 的编译速度本来就比较慢，建议精简依赖的宏包以提升编译速度。以下宏包与《写作指南》要求的格式无关，也并非每个人都需要，建议用 `ctexhook` 在载入用户载入宏包后自动进行配置。
- [ ] `subcaption`
- [ ] `pdfpages`
- [ ] `ntheorem`
- [ ] `array`
- [ ] `longtable`
- [ ] `hyperref`
- [ ] ~~`notoccite`~~

另外建议增加以下宏包的配置：
- [ ] `siunitx`
- [x] `nomencl`

### 带圈数字
- [x] 目前带圈数字使用的是 `pifont` 宏包的字体，事实上中易和华文的中文字体都有 1 到 10 的字形，直接使用这些字体的带圈数字更方便。

### 单元测试
- [ ] ~~是否有必要使用 `l3build` 配置单元测试？~~

### EPS 图片
- [x] EPS 格式已经过时，建议删掉模板中的 eps 图片。

**Comment by xueruini** [comment]
> * 几个常量宏（比如 `\thu@ack@name`）的命名应该一致

👍

**Comment by xueruini** [comment]
> xelatex 的编译速度本来就比较慢，建议精简依赖的宏包以提升编译速度。以下宏包与《写作指南》要求的格式无关，也并非每个人都需要，建议用 `ctexhook` 在载入用户载入宏包后自动进行配置

pdfpages 对本科有用。notoccite 是一个 bug report 后添加的。subcaption 并排图形还是有用吧

**Comment by xueruini** [comment]
> * nomencl

可以改造一下符号表的实现，有人反馈过

**Comment by xueruini** [comment]
> ### EPS 图片
> EPS 格式已经过时，建议删掉模板中的 eps 图片。

latex 编译已经好多年没用了

**Comment by zepinglee** [comment]
> > xelatex 的编译速度本来就比较慢，建议精简依赖的宏包以提升编译速度。以下宏包与《写作指南》要求的格式无关，也并非每个人都需要，建议用 `ctexhook` 在载入用户载入宏包后自动进行配置
> 
> pdfpages 对本科有用。notoccite 是一个 bug report 后添加的。subcaption 并排图形还是有用吧

可能我比较追求极简主义把……
1. 现在都可以用电子签名啊，即便用扫描的话，可以在示例里说明自己加载 `pdfpages` 宏包。或者只在本科模板中加载 `pdfpages`。
2. `notoccite` 很短，应该没啥问题。
3. `subcaption` 确实很有用，但不是必需，所以我觉得放在示例文档里更合适些。

**Comment by zepinglee** [comment]
> > 是否有必要使用 `l3build` 配置单元测试？
> 
> 这个没用过，开发维护成本大不大？

可以参考 https://github.com/ustctug/ustcthesis/tree/master/test ，只是每次对格式做出修改时需要 `make save`
