### ISSUE TITLE
TeXlive2018里自带的thuthesis.cls编译不通过

### ISSUE THREAD

**Issue by zhuxiangthu** [xueruini/thuthesis#373]
就是因为奇怪的字体问题编译不过，装上字体后还有别的问题，怎么折腾都不行

用说明中手动更新生成thuthesis.cls，但是
`latex thuthesis.ins`
运行不通。

后来用
`xelatex thuthesis.ins`
就生成正确的thuthesis.cls了，编译也通过了。

建议把这个提示明确一下。

## 编译环境
编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：MacTeX 2018 / TeX Live 2018 / MikTeX 2.9.6753
相关宏包版本：ctex v2.4.14 / unicode-math v0.8m
模板类型： doctor / master / bachelor

## 描述问题
《研究生学位论文写作指南》第 xx 页要求……而模板编译的结果是……

示例代码：
```TeX
\documentclass[degree=master,tocarialchapter]{thuthesis}
\begin{document}
abc
\end{document}
```

截图：

**Comment by zepinglee** [comment]
GitHub 上 master 版本已经修改为“使用 xetex 编译”

Duplicate of issue #362 .
