### ISSUE TITLE
能否更新overleaf上的模板

### ISSUE THREAD

**Issue by archie0431** [xueruini/thuthesis#375]
## 编译环境
编译的系统：Overleaf

## 描述问题
在overleaf上找到了ThuThesis的模板，十分感谢学长的工作。
但是这个版本的模板较老，因为是联合培养项目，论文要英文。
自己试图上传了ThuThesis.zip文件到overleaf，但是会报错。
抱歉LaTex小白啊

**Comment by zepinglee** [comment]
1. 报的什么错？先把问题描述清楚。

2. Overleaf 上的模板（https://www.overleaf.com/latex/templates/tsinghua-university-thesis-template/wrjmnybpzbhw ）似乎是 @bigeagle 上传的，我们也没有权限。

3. 从 github 上下载的模板需要先用 xetex 编译 dtx 文件生成 cls，直接上传到 Overleaf 上会自动调用 TeC Live 2017 发行版里 thuthesis 的 cls，这可能会造成版本冲突。

4. 目前的 latex 模板并不支持“联合培养项目”的论文，你可以提供一份这个的论文的格式要求和模板吗？最好是学校官网的链接。

**Comment by archie0431** [comment]
1. 显示的报错有152条。看的不是太懂，抱歉啊。。

2 .好的，明白了

3. 我先尝试一下将dtx生成cls之后再上传。

4. 联培项目没有特殊说明，和清华英文论文要求一样。

麻烦师兄了，我先尝试一下（3）的方法~

**Comment by zepinglee** [comment]
1. 那也应该把最前面几个报错贴过来或者截图，不要让别人猜。

4. 学校的写作指南（http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=001050603&parentColumnId=0010506&itemSeq=5365 ）并没有提到英文论文要求，如果你了解到相关要求记得发过来。

**Comment by archie0431** [comment]
1. 报错的前四个
![default](https://user-images.githubusercontent.com/46235642/50534358-75af9b00-0b76-11e9-8d31-fe013ee7fe85.PNG)
![image](https://user-images.githubusercontent.com/46235642/50534361-7d6f3f80-0b76-11e9-9e0e-c4b2a14a98fd.png)

2. 格式同清华大学《研究生学位论文写作指南》中的英文论文格式要求。http://www.law.tsinghua.edu.cn/publish/law/7024/20111021165212974587726/6.pdf 
应该与ThuThesis的英文版一样的。

**Comment by zepinglee** [comment]
这个报错是因为没有切换成 xelatex 编译

**Comment by Stone-Zeng** [comment]
可以做一下编译引擎检测，如果不是 xetex 就直接退出，这样可以省掉很多冗余的信息（反正也编译不出来）。

**Comment by zepinglee** [comment]
> 可以做一下编译引擎检测，如果不是 xetex 就直接退出，这样可以省掉很多冗余的信息（反正也编译不出来）。

有道理

**Comment by xueruini** [comment]
> > 可以做一下编译引擎检测，如果不是 xetex 就直接退出，这样可以省掉很多冗余的信息（反正也编译不出来）。
> 
> 有道理

代码里好像还有一些 pdftex 的判断，也都成为历史了

**Comment by archie0431** [comment]
抱歉切换成 xelatex 编译 
![image](https://user-images.githubusercontent.com/46235642/50580794-3216a300-0e8e-11e9-9448-0d67c6e8b07b.png)
报错信息如下
![image](https://user-images.githubusercontent.com/46235642/50580801-3e026500-0e8e-11e9-835a-f62c8e2db360.png)
好像问题还是没有解决 /(ㄒoㄒ)/~~

**Comment by archie0431** [comment]
太棒了 编译通过了( •̀ ω •́ )y
现在只有提醒了
![image](https://user-images.githubusercontent.com/46235642/50581278-48732d80-0e93-11e9-928b-577afebe073a.png)

**Comment by Stone-Zeng** [comment]
这个 hyperref 的 warning 可以不管，需要处理的话，看一下文档（命令行 `texdoc hyperref`）4.1.2 小节。

**Comment by zepinglee** [comment]
@Stone-Zeng 我之前也尝试过去掉实例文档的所有 warning，但是这个地方比较坑的是，摘要关键词里的 `\TeX` 在被写入 pdf meta info 时已经被展开了，所以有这么一大串 warning .

**Comment by zepinglee** [comment]
@xueruini 我建议还是把关键词里的 `\TeX` `\LaTeX` 换成 plain text 吧，这么多 warning 对非程序员或强迫症患者不太友好

**Comment by archie0431** [comment]
明白了 至少现在可以用英文版了
简直太完美
十分感谢各位师兄的帮助 (*^_^*)

**Comment by zepinglee** [comment]
@archie0431 英文版在 dev 分支上还没搞完，之后还需要再更新一下模板

**Comment by archie0431** [comment]
好的 明白了 但是还是太感谢了~

**Comment by xueruini** [comment]
> @xueruini 我建议还是把关键词里的 `\TeX` `\LaTeX` 换成 plain text 吧，这么多 warning 对非程序员或强迫症患者不太友好

我也有这个强迫症，后来发现是 hyperref 的事，就没折腾。

**Comment by zepinglee** [comment]
@xueruini 我加一下 xelatex 的检查，并移除 pdflatex 的代码。另外 Makefile 里的 xelatex method 其实很不方便，也可以删掉。

**Comment by zepinglee** [comment]
去掉了全部 latex 编译的 warning，但是还有 xdvipdfmx 的，我还没搞懂原因。

```
[42][43][44
xdvipdfmx:warning: PDF file is tagged... Ignoring tags.
][45
xdvipdfmx:warning: PDF file is tagged... Ignoring tags.
]
xdvipdfmx:warning: PDF destination "Hfootnote.3" not defined.
xdvipdfmx:warning: PDF destination "Hfootnote.4" not defined.
```

**Comment by zepinglee** [comment]
@xueruini 另外有没有必要维护 overleaf 上的模板啊？

**Comment by Stone-Zeng** [comment]
> 我建议还是把关键词里的 `\TeX` `\LaTeX` 换成 plain text 吧，这么多 warning 对非程序员或强迫症患者不太友好

看了一下，LaTeX 默认情况下 `\TeX` 是用 `\def` 定义的，可以展开；而 `\LaTeX`、`\LaTeXe` 是用 `DeclareRobustCommand` 定义的，因此是被保护起来而不能展开的。

**Comment by zepinglee** [comment]
> > 我建议还是把关键词里的 `\TeX` `\LaTeX` 换成 plain text 吧，这么多 warning 对非程序员或强迫症患者不太友好
> 
> 看了一下，LaTeX 默认情况下 `\TeX` 是用 `\def` 定义的，可以展开；而 `\LaTeX`、`\LaTeXe` 是用 `DeclareRobustCommand` 定义的，因此是被保护起来而不能展开的。
> 
> 可以用一下 `hologo` 包然后把所有 logo 改成 protected 的形式，再用 pdf string 来搞一下。

呃……这个也只是个示例文档，没必要引入额外宏包，我已经改成了 plain text 并 push 到 dev 分支上。

如果你有兴趣的话不妨研究下 xdvipdfmx 的那两个 warning？似乎是跟脚注的 pdf 链接有关

**Comment by zepinglee** [comment]
`xdvipdfmx:warning: PDF file is tagged... Ignoring tags.` 这个 warning 是因为 `\includepdf[pages=-]{scan-record.pdf}` 的 pdf 文件导致的，在示例文件里默认注释掉就好了

**Comment by zepinglee** [comment]
`hyperref` 的文档里说：
> This package can be used with more or less any normal LaTeX document by specifying in the document preamble
`\usepackage{hyperref}`
Make sure it comes *last* of your loaded packages, to give it a fighting chance of not being over-written, since its job is to redefine many LaTeX commands.

不然可能会引起冲突

**Comment by liantze** [comment]
我是Overleaf的工作人员，今天接收到ThuThesis v6.0.0的投稿，查找资料时找到这个repo来了，感谢开发者们的辛苦工作。v6.0的模板已在 https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/tjjttqzttsyv 上线，旧版本v5.3.2的模板页面也会自动跳转到v6.0的模板页面。

**Comment by zepinglee** [comment]
> 我是Overleaf的工作人员，今天接收到ThuThesis v6.0.0的投稿，查找资料时找到这个repo来了，感谢开发者们的辛苦工作。v6.0的模板已在 https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/tjjttqzttsyv 上线，旧版本v5.3.2的模板页面也会自动跳转到v6.0的模板页面。

感谢！

**Comment by xueruini** [comment]
> 我是Overleaf的工作人员，今天接收到ThuThesis v6.0.0的投稿，查找资料时找到这个repo来了，感谢开发者们的辛苦工作。v6.0的模板已在 https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/tjjttqzttsyv 上线，旧版本v5.3.2的模板页面也会自动跳转到v6.0的模板页面。

thx，不过我发现 overleaf 上搜索却没有结果

**Comment by liantze** [comment]
> 一个小反馈： overleaf 上搜索 thuthesis 却没有结果。我是直接设置了 title 的

诶？有的呀 。

![image](https://user-images.githubusercontent.com/1103696/71791276-6a3b5d80-306f-11ea-9136-3b1395685c9b.png)

**Comment by xueruini** [comment]
昨晚看到了，谢谢
