### ISSUE TITLE
示例参考文献信息不全

### ISSUE THREAD

**Issue by dizhang** [xueruini/thuthesis#377]
参考文献缺少信息，会出现[S.l.]，[s.n.]。找了下才发现主要是缺少address和publisher信息。

**Comment by zepinglee** [comment]
请阅读《研究生学位论文写作指南》

**Comment by dizhang** [comment]
还想报告个小错误呢，已经被close了。linux下部分字体加粗之后仍然是宋体。windows编译的是黑体。比如算法的标题。

**Comment by zepinglee** [comment]
@dizhang 抱歉我刚没注意到你是博士后，似乎博士后的模板要求参考文献格式的是 87 年的标准？

**Comment by Stone-Zeng** [comment]
> 还想报告个小错误呢，已经被close了。linux下部分字体加粗之后仍然是宋体。windows编译的是黑体。比如算法的标题。

因为 Windows 下面的 SimSun 没有粗体；而 Linus 下面用 Fandol，它有粗体。这里的字体配置继承自 `ctex` 宏集，`thuthesis` 只是做了一些修改。

**Comment by zepinglee** [comment]
这个宋体加粗的问题同 #376
