### ISSUE TITLE
English模版顺序与中文不对称

### ISSUE THREAD

**Issue by mattandryc** [xueruini/thuthesis#379]
最好跟中文论文模版的顺序保持一致。按我去年写的论文（计算机系）顺序和/section名称应该如下：

目前contents页上的内容的order/titles: 
> [Chapters...]
> List of Figures
> List of Tables
> List of Equations
> Bibliography 
> Acknowledgments 
> 声明
> [Appendices...]
> 个人简历、在学期间发表的学术论文与研究成果

2018年被图书馆认可的order/titles（来自于contents页面）：
> List of Abbreviations (目前写的是Nomenclature)
> [Chapters...] 
> References  (目前写的是Bibliography)
> Acknowledgments
> [Appendices...]
> Resume

**Comment by xueruini** [comment]
这些顺序都可以在 `main.tex` 里自己调，不是写死的
