### ISSUE TITLE
可能不算bug，不过subfigure的caption如何缩小字体呢？

### ISSUE THREAD

**Issue by xiasummer** [xueruini/thuthesis#380]
我在嵌入一个3*3的图形时，遇到的问题，caption被遮挡了，如果caption很短的话，同样是遮挡了一半的字体。于是我想找办法去缩小subfigure caption的字体，但是找到的方法不知道如何写入，直接在main中引入package和设置似乎也没用。
![image](https://user-images.githubusercontent.com/8190676/52762962-c90d7800-3054-11e9-9e26-6ff3c1c9d58d.png)

**Comment by xueruini** [comment]
#237 #289
