### ISSUE TITLE
中英文文献排序的问题

### ISSUE THREAD

**Issue by zhengkai0919** [xueruini/thuthesis#381]
能否让中文的参考文献都出现在英文参考文献后面？

**Comment by zepinglee** [comment]
我看了一下写作指南，似乎这样也是允许的，需要修改 bst 文件。

我稍后改进一下代码，提供一个更方便的接口供修改语言的顺序。

**Comment by LiuRuiQi** [comment]
and why would you like that?

**Comment by zhengkai0919** [comment]
> and why would you like that?

 easier to look up reference in alphabetic order？

**Comment by zepinglee** [comment]
Fixed in 63bb44f .

**Comment by zhengkai0919** [comment]
感谢！
