### ISSUE TITLE
如何在thuthesis中使用bibitem这种格式的引用？谢谢

### ISSUE THREAD

**Issue by LiuRuiQi** [xueruini/thuthesis#383]
## 编译环境
编译的系统： Windows 7
TeX 发行版： TeX Live 2018 

## 描述问题
我在之前写英文论文时参考文献用的都是文中

For instance, the length of the preamble of Chinese DTMB systems is chosen from 420 bits, 595 bits or 945 bits \cite{DTV_1}\cite{DTV_2}.

最后：
\begin{thebibliography}{1}
\bibitem{new}
J. Yang, X. Wang, M. J. Rahman, S. I. Park, H. M. Kim and Y. Wu, ``A New Positioning System Using DVB-T2 Transmitter Signature Waveforms in Single Frequency Networks,'' \textit{IEEE Transactions on Broadcasting}, vol. 58, no. 3, pp. 347-359, Sept. 2012.

\bibitem{DTV_1}
J. Song, Z. Yang, L. Yang, K. Gong, C. Pan, J. Wang, Y. Wu, "Technical review on Chinese digital terrestrial television broadcasting standard and measurements on some working modes", IEEE Trans. Broadcasting, vol. 53, no. 1, pp. 1-7, Mar. 2007.

\bibitem{DTV_2}
J. Song and C. Zhang, "Technical Review on DTMB-Advanced (DTMB-A) Standard," 2016 International Conference on Engineering and Telecommunication (EnT), Moscow, 2016, pp. 128-133.

\end{thebibliography}

这样的。不知道如何在thuthesis模板中用这种？这样我直接复制粘贴会更容易。现在的Bibtex我也会用，只不过都再从IEEE上重新导出。
谢谢！

**Comment by zepinglee** [comment]
这个格式不符合学校的要求，如果你更喜欢手动调整格式的话，可以用 `\begin{thebibliography}{1} ... \end{thebibliography}` 替换掉 `main.tex` 中的 `\bibliography{ref/refs}`

**Comment by LiuRuiQi** [comment]
> 
> 
> 这个格式不符合学校的要求，如果你更喜欢手动调整格式的话，可以用 `\begin{thebibliography}{1} ... \end{thebibliography}` 替换掉 `main.tex` 中的 `\bibliography{ref/refs}`

OK，谢谢！我看我师兄发给我的他去年的word版本里，就是按照我那种格式引用的…… 估计这方面的检查不严格？那我再看看吧，谢谢！
