### ISSUE TITLE
bump a new release?

### ISSUE THREAD

**Issue by xueruini** [xueruini/thuthesis#384]
@zepinglee for the new graduates?

**Comment by zepinglee** [comment]
我觉先不急吧，The TeX Live 2018 已经 freeze 了，所以即使新版本也没法通过 `tlmgr` 更新。

**Comment by xueruini** [comment]
> 我觉先不急吧，The TeX Live 2018 已经 freeze 了，所以即使新版本也没法通过 `tlmgr` 更新。

good point
