### ISSUE TITLE
模板更新后运行报错

### ISSUE THREAD

**Issue by bones0822** [xueruini/thuthesis#385]
## 编译环境
编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：MacTeX 2018 / TeX Live 2018 / MikTeX 2.9.6753
相关宏包版本：ctex v2.4.14 / unicode-math v0.8m
模板类型： doctor / master / bachelor

## 描述问题
从CTAN上下载了最新的模板后替换原目录中的cls、cfg文件后，运行main报错，提示如下：
!Latex error: File 'newtxtex.sty' not found.
确认发现网上更新的模板中确实没有这个文件

**Comment by zepinglee** [comment]
用 GitHub 上最新的版本

**Comment by bones0822** [comment]
我也下了一个GitHub的v5.4.5，运行也报错，还是上面的问题

**Comment by zepinglee** [comment]
请使用 GitHub 上的 master 版分支

**Comment by bones0822** [comment]
我也下了，运行结果为，
！Underfined control sequence.
1.193 \IfFontExistsTF
                            {STIX2Math.otf}{

**Comment by zepinglee** [comment]
所以你用的是那个版本？一开始的表是需要你填的

**Comment by bones0822** [comment]
什么表格？

**Comment by zepinglee** [comment]
![Screen Shot 2019-03-13 at 1 08 15 PM](https://user-images.githubusercontent.com/12290822/54254994-123be380-4591-11e9-8601-f0be27da2dbf.png)

**Comment by zepinglee** [comment]
@xueruini 这么看来还是有必要 bump new version，v 5.4.5 以来已经 36 个 commits 了，而且改动比较大（unicode-math），还有一些用户似乎不知道怎么找最新版

**Comment by xueruini** [comment]
> @xueruini 这么看来还是有必要 bump new version，v 5.4.5 以来已经 36 个 commits 了，而且改动比较大（unicode-math），还有一些用户似乎不知道怎么找最新版

恩。很多人都是直接从例子文档开始写，所以自己下载到本目录最方便。ctan 上更多是个占位，直接用其实有门槛。

**Comment by zepinglee** [comment]
@xueruini 我之前的表达不是太准确，我的意思是似乎很多用户不会（或者怕不稳定而不敢？）直接用 github 上 master 的版本，所以多搞些 release 版本方便用户使用？

另外我觉得最好在 README.md 或者文档里注明一下支持的 TeX Live 版本，
```
！Underfined control sequence.
1.193 \IfFontExistsTF
{STIX2Math.otf}{
```
这个报错应该是因为用了 TeX Live 2016 或更低的版本

**Comment by xueruini** [comment]
> @xueruini 我之前的表达不是太准确，我的意思是似乎很多用户不会（或者怕不稳定而不敢？）直接用 github 上 master 的版本，所以多搞些 release 版本方便用户使用？

的确会有这个情况，甚至也不知道到底哪个分支能用。

> 另外我觉得最好在 README.md 或者文档里注明一下支持的 TeX Live 版本

是个好主意，不过怎么快速测试验证呢

**Comment by zepinglee** [comment]
我本地有个 TeX Live 2016，所以我的 ustcthesis 会在 tl2016 上测试一下；如果还有问题就靠其他人的反馈了
