### ISSUE TITLE
怎样使 conference 和 book 的名称以斜体的形式显示？

### ISSUE THREAD

**Issue by sangjeedondrub** [xueruini/thuthesis#387]
## 编译环境
编译的系统：macOS 10.14
TeX 发行版：MacTeX 2018
模板类型： doctor

## 描述问题

请问：

参考文献中，怎样使 conference 和 book 的名称以斜体的形式显示？
我注意到 `bst` 中有 `  italic.jounal` 配置项，如何为 conference 和book也添加类似的选项？

谢谢！

**Comment by zepinglee** [comment]
这是方便其他学校定制的配置接口，我们学校要求的 conference 和 book 都是正体
