### ISSUE TITLE
公式中使用\bm得到数学粗体报错

### ISSUE THREAD

**Issue by ycydsxy** [xueruini/thuthesis#389]
已使用\usepackage{bm}，编译时报错：
```
! Extended mathchar used as mathchar (14799939).
<to be read again> 
                   \relax 
l.33 \bm{P}
           =-p\bm{I}+[2\mu\bm{S}-\frac{2}{3}\mu(\nabla\cdot\bm{U})\bm{I}]
A mathchar number must be between 0 and "7FFF.
I changed this one to zero.
```

**Comment by ycydsxy** [comment]
又试了一下，换成\mathbold不会报错（但希腊字母不能加粗），\mathsymbol报同样的错误。

**Comment by ycydsxy** [comment]
貌似是unicode-math下我不应该再使用\bm命令？ 

我看到这里有一个回答：[Error “Extended mathchar used as mathchar” when using \bm](https://tex.stackexchange.com/questions/431013/error-extended-mathchar-used-as-mathchar-when-using-bm)

**Comment by zepinglee** [comment]
模板用了 `unicode-math` 宏包，不兼容 `bm`，不过模板已经对 `\bm` 命令作了兼容处理，所以不要调用 `bm` 宏包，直接用 `\bm` 命令即可

**Comment by zepinglee** [comment]
文档里好像没提到这一个，稍后补充一下

**Comment by ycydsxy** [comment]
@zepinglee 多谢，不调用bm宏包可以正常编译。
