### ISSUE TITLE
单独使用thuthesis.cls文件无法编译生成pdf。

### ISSUE THREAD

**Issue by ladyrick** [xueruini/thuthesis#390]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2018
模板类型： master

## 描述问题
使用`xetex thuthesis.ins`生成`thuthesis.cls`文件后，把它复制到新的文件夹，用来编译pdf，编译失败。
还需要把`thuthesis-numeric.bst`，`thuthesis-bachelor.bst`，`thuthesis-author-year.bst`这三个文件也复制过去才可以编译成功。

这些不本质，本质的是，从ctan安装的版本里面，就没有这三个文件。
因此，从ctan安装的thuthesis，一直在报错。

截图：
![2019-03-29_174952](https://user-images.githubusercontent.com/10379994/55224249-13386a80-524b-11e9-82e4-f5b6c4ae18e6.png)

**Comment by zepinglee** [comment]
不要用 CTAN 上的版本，直接用 github 上 master 的版本
