### ISSUE TITLE
参考文献为专著，其著录格式末尾有句点，而模板编译的结果是则没有句点

### ISSUE THREAD

**Issue by caijun** [xueruini/thuthesis#391]
## 编译环境
编译的系统：macOS 10.14
TeX 发行版：MacTeX 2018
模板类型： doctor

## 描述问题
《研究生学位论文写作指南》第 13页要求参考文献为专著，其著录格式末尾有句点，而模板编译的结果则没有句点。

截图：
![image](https://user-images.githubusercontent.com/2522593/55632918-df7eb700-57ed-11e9-8772-39aaf27e27de.png)

![image](https://user-images.githubusercontent.com/2522593/55632929-e4436b00-57ed-11e9-8ed7-0b7052a724a2.png)

**Comment by zepinglee** [comment]
《写作指南》第 21 页有句：
> 每条文献结尾可加“.”，图书的文献一般不加。

**Comment by zepinglee** [comment]
我觉得这条很奇怪， @xueruini 这个应该视作《写作指南》前后自相矛盾吧，所以没必要严格按照 21 页这条规定

**Comment by caijun** [comment]
研究院提供的word模板选择每条文献后都加”.“，都加显得比较统一。

**Comment by zepinglee** [comment]
嗯我同意

**Comment by xueruini** [comment]
现在的方式并不算违反规则，不过的确统一点好

**Comment by xueruini** [comment]
@zepinglee 这个 issue 处理了之后发个版本如何

**Comment by zepinglee** [comment]
嗯，我 push 到 dev 分支了
