### ISSUE TITLE
几个调整

### ISSUE THREAD

**Issue by xueruini** [xueruini/thuthesis#393]
原先的例子其实是要 label，但是不出现在索引。修改之后 label 也消失了。虽然这个例子有点奇葩，不过的确是个情形，应保留原样为好
![image](https://user-images.githubusercontent.com/1863/55809170-06075f80-5b18-11e9-9aba-25a4ddb25e07.png)

**Comment by xueruini** [comment]
我简单写了一下 changelog，你看看

- font: use `unicode-math` for math fonts.
- spacing: fix spacing between float caption and text.
- postdoc: fix titlepage for post doc.
- denoation: support `nomencl`
- lang: added English thesis template.
- cfg: merge `thuthesis.cfg` into `thuthsis.cls`
- ref: list English references first and then Chinese ones.
- ref: add period for all reference items.
- ref: add language aware special words in refs, like `et.al`, `s.n`, and `Anon` etc.
- build: only `xetex` is supported.
- build: upgrade to `gulp-4.0`
- biuld: refactor travis-ci

**Comment by zepinglee** [comment]
> 这个虽然作用比较小，也是个惯例
> ![image](https://user-images.githubusercontent.com/1863/55809896-4ddab680-5b19-11e9-86c6-9ed867a6feed.png)

`doc` 文档：
> While \CharacterTable and \CheckSum have been important features in the
early days of the public internet when doc was written as the mail gateways back then were rather unreliable and often mangled files they are these days more a nuisance than any help. They are therefore now fully optional and no longer recommended for use with new files.

现在都是用 git 了，这些其实没啥用

**Comment by xueruini** [comment]
> 主要还是 Times New Roman 没有 small capital，所以即便用了也没有效果，反而多一条 warning

恩，也可以。文档里有 sc 就可以了。

**Comment by xueruini** [comment]
这样来看，也就是 secret 文档不一致，其它都没问题。changlog 仔细看看，直接在上面改

**Comment by zepinglee** [comment]
1. font: use `unicode-math` and `stix2` for math fonts.

2. > bst: list English references first and then Chinese ones.

其实我只是增加了一个接口供自定义，这条不是很重要，不提也没关系。

3. > bst: add language aware special words in refs, like et.al, s.n, and Anon etc.

这个以前就有，不是 new feature

4. bst: update to GB/T 7714-2015 for bachelors

5. 版本号？5.5 或 6.0 都可以吧
