### ISSUE TITLE
关于公式和符号的疑问

### ISSUE THREAD

**Issue by lookforlgf** [xueruini/thuthesis#394]
编译环境
编译的系统：macOS 10.14 
TeX 发行版：MacTeX 2018
模板类型： doctor

疑问：
用5.4.5版本模板显示正常的公式和符号（比如偏微分符号，下标的m和p，积分符号等）
用最新的master模板编译后，出现了如图所示问题，\rm环境的符号还是斜体。这是为什么呢？

截图：
![2019-04-10_00-39-19](https://user-images.githubusercontent.com/39450308/55819398-3dcbd280-5b2b-11e9-9638-d299896f9abc.jpg)

**Comment by alick** [comment]
首先，公式里直立的字母用 `\text{}` 或 `\mathrm{}` 不要用 `\rm{}`。楼主试试用 `\text{}` 有没有同样的问题？如果还有，猜测是字体的问题（两边的积分号长的不一样），可能和 unicode-math 有关？

**Comment by lookforlgf** [comment]
> 首先，公式里直立的字母用 `\text{}` 或 `\mathrm{}` 不要用 `\rm{}`。楼主试试用 `\text{}` 有没有同样的问题？如果还有，猜测是字体的问题（两边的积分号长的不一样），可能和 unicode-math 有关？

谢谢，用 `\text{}` 或 `\mathrm{}`解决了斜体字母直立的问题。
符号长的不一样，真可能是字体的问题。劳烦作者解释一下，谢谢啦！

**Comment by stone-zeng** [comment]
现在 thuthesis 中的数学字体由 `unicode-math` 宏包负责处理，实际使用的字体是 xits-math 或 stix2，默认使用直立积分号，且上下限置于正上/下方。

**Comment by lookforlgf** [comment]
> 现在 thuthesis 中的数学字体由 `unicode-math` 宏包负责处理，实际使用的字体是 xits-math 或 stix2，默认使用直立积分号，且上下限置于正上/下方。

谢谢，我是觉得直立的偏微分号有点丑，不如斜体的好看。p.s.头像有点意思

**Comment by lookforlgf** [comment]
我理解错了，应该是xits-math 或 stix2字体的某些符号不如原先字体的美观

**Comment by xueruini** [comment]
partial 可以改成歪的，积分符号没看到参数

![image](https://user-images.githubusercontent.com/1863/55849030-c2e1d680-5b81-11e9-8570-8c0a4673aef0.png)

![image](https://user-images.githubusercontent.com/1863/55849005-a6459e80-5b81-11e9-8991-dcaf4e1e0c86.png)

**Comment by stone-zeng** [comment]
积分号是这一个决定的：`\setmathfont[range={cal,bfcal},StylisticSet=1]{xits-math.otf}`，把 `StylisticSet=1` 删去（但似乎只能改 cls 了）。

**Comment by xueruini** [comment]
> 积分号是这一个决定的：`\setmathfont[range={cal,bfcal},StylisticSet=1]{xits-math.otf}`，把 `StylisticSet=1` 删去（但似乎只能改 cls 了）。

改 cls 倒是问题不大，这部分我不熟悉，是否会引入其它问题

**Comment by lookforlgf** [comment]
> 积分号是这一个决定的：`\setmathfont[range={cal,bfcal},StylisticSet=1]{xits-math.otf}`，把 `StylisticSet=1` 删去（但似乎只能改 cls 了）。

删去了`StylisticSet=1`，积分号没变化，还是直立的

**Comment by stone-zeng** [comment]
抱歉是我搞错了，`StylisticSet=8` 是 Upright Integrals，你把相关的选项都修改掉吧（直接删除即可）。

**Comment by zepinglee** [comment]
> > 现在 thuthesis 中的数学字体由 `unicode-math` 宏包负责处理，实际使用的字体是 xits-math 或 stix2，默认使用直立积分号，且上下限置于正上/下方。
> 
> 谢谢，我是觉得直立的偏微分号有点丑，不如斜体的好看。p.s.头像有点意思

《撰写手册》第 10 页：
> 要严格执行国家技术监督局 1993 年 12 月 27 日批准的、1994 年 7 月 1 日 开始实施的国家标准 GB3100-3102—1993 有关量和单位的规定。

你可以去翻阅 GB 3102.11-1993 （现在改成 GB/T 了），积分号和 `\partial` 都是直立的。所以建议不要乱改

**Comment by zepinglee** [comment]
我也觉得 stix2 的一些字形不太好看，之前打算修改 stix2 （比如引入 `newtx` 的一些字形），不过一直鸽了

**Comment by xueruini** [comment]
dx 的 d 是歪的还是正的？https://tex.stackexchange.com/questions/14821/whats-the-proper-way-to-typeset-a-differential-operator

**Comment by zepinglee** [comment]
> dx 的 d 是歪的还是正的？https://tex.stackexchange.com/questions/14821/whats-the-proper-way-to-typeset-a-differential-operator

国标和 ISO 是正的，但是英美国家的一些人习惯写成斜的，参考 https://github.com/latexstudio/ChinaThesis/wiki/GB-math

**Comment by lookforlgf** [comment]
现在没问题了，感谢各位大佬！

**Comment by zepinglee** [comment]
@xueruini 我忘记当时为何会选择 STIX 2 Math 了，但是小写希腊字母的字形实在有点奇怪，所以把数学字体换成 XITS Math 怎么样？

**Comment by xueruini** [comment]
没问题，xits 的看着的确更舒服一点
