### ISSUE TITLE
5.5.0版本中，公式hat/tilde与mathbf连在一起会出错

### ISSUE THREAD

**Issue by yuanzhigang10** [xueruini/thuthesis#395]
## 编译环境

编译的系统：macOS 10.14
TeX 发行版：TeX Live 2017
模板类型： doctor

## 描述问题

更新至5.5.0 release之后，定位到出错的问题是：
`$\hat{\mathbf{x}}$` 报错，显示`! Internal error: bad native font flag in map_char_to_glyph`
换成 `$\mathbf{\hat{x}}$`后，编译没问题，但x上面符号不显示。
类似的，`$\tilde{\mathbf{x}}$`也出现了这个问题。

求帮助，谢谢！

**Comment by zepinglee** [comment]
TeX Live 2018 上无法复现你的问题

**Comment by zepinglee** [comment]
可能是 texlive 2017 里 `unicode-math` 的 bug

**Comment by yuanzhigang10** [comment]
@zepinglee 好的，谢谢。那我直接升级2018试试吧，查了好多方案似乎都不行。

**Comment by yuanzhigang10** [comment]
更新：
升级到TeX Live2018后问题解决。

但奇怪的是，把整个project上传到Overleaf时同样编译失败（5.4.5的可以编译），难道Overleaf用的还是早期版本……

**Comment by stone-zeng** [comment]
> 难道Overleaf用的还是早期版本……

感谢你猜对了！惊不惊喜，意不意外？（他们表示之前忙于和  sharelatex 的合并，一直没时间处理，可能今年会升级）

**Comment by zepinglee** [comment]
@yuanzhigang10 比较可行的办法是把新版 `unicode-math` 的 4 个文件（`unicode-math-luatex.sty`, `unicode-math-xetex.sty`, `unicode-math-table.tex`, `unicode-math.sty`）往 overleaf 上传一份
