### ISSUE TITLE
5.5.0 版本的 \theta 的字体有点异样

### ISSUE THREAD

**Issue by yzlnew** [xueruini/thuthesis#399]
## 编译环境
编译的系统：Windows 10
TeX 发行版：MikTeX 2.9.6941
相关宏包版本：ctex v2.4.15 / unicode-math v0.8o
模板类型： master

## 描述问题
更新用了 unicode-math 之后，数学环境下 `$\theta$` 的字体问题。

示例代码：
```TeX
\begin{equation}
    c_L \sin \theta_{L} = c_S \sin \theta_{S}
\end{equation}
```

截图：
现在：
![image](https://user-images.githubusercontent.com/4904877/56220001-46c42300-609a-11e9-90cb-f1504f2177c6.png)
之前版本：
![image](https://user-images.githubusercontent.com/4904877/56220024-50e62180-609a-11e9-9067-3707a82b5482.png)

[UPDATE]
原来是因为使用了 stix2 作为数学环境的字体，考虑换成 lm-math.

**Comment by zepinglee** [comment]
5.5.0 用了 `unicode-math` 宏包和 `stix2` 字体，原来的讨论见 #361 。

我个人也觉得 stix2 的一些字形有点“异样”，不过符号比较齐全。

另外 `lm-math` 跟西文字体 Times New Roman 不是很搭。

**Comment by stone-zeng** [comment]
你们要的 Times：

![image](https://user-images.githubusercontent.com/18233088/56268790-d0b8ce00-6124-11e9-969c-84d4d4149562.png)

**Comment by yzlnew** [comment]
STIX2 的 Greek letters 怎么这么另类呢，即使不关心数学环境字体的也能看出与前面8种的不同

**Comment by xueruini** [comment]
STIX2 的确有点另类

**Comment by zepinglee** [comment]
可以在 https://github.com/stipub/stixfonts/issues 反馈问题。不过还是更期待 @stone-zeng 大佬能做一版

**Comment by zepinglee** [comment]
准确滴说应该是希腊字母的 angle of contrast 跟拉丁字母不一致，参考 http://designwithfontforge.com/en-US/What_Is_a_Font.html

**Comment by stone-zeng** [comment]
可以参考 [Designing Greek typefaces](https://medium.com/@gerryleonidas/designing-greek-typefaces-eac0de7767cc)。
