### ISSUE TITLE
! Package kvsetkeys Error: Undefined key `postdocstartdate'.

### ISSUE THREAD

**Issue by james20141606** [xueruini/thuthesis#400]
## 编译环境
编译的系统：macOS 10.14
TeX 发行版：MacTeX 2018
相关宏包版本：ctex v2.4.14
模板类型： bachelor english version

## 描述问题
我在使用dev版本的english模板时遇到了! Package kvsetkeys Error: Undefined key `postdocstartdate'.的问题

代码：
```TeX
\documentclass[degree=bachelor,language=english,tocarialchapter]{thuthesis}
```
而且同时会有warning:
\documentclass[degree=bachelor,language=english,tocarialchapter]{thuthesis}

**Comment by zepinglee** [comment]
1. 你的目录有没有生成 `cls` 文件？
2. 本科生允许使用英文撰写吗？

**Comment by zepinglee** [comment]
刚刚 fix 了英文的一个 bug，你需要从 dev 分支再 pull 一下

**Comment by james20141606** [comment]
> 刚刚 fix 了英文版的一个 bug，你需要从 dev 分支再 pull 一下

pull 了新版之后没有问题啦，本科生学堂班/外文系都有英文写作的需求的。以及我比较好奇的是英文版和中文版对用户来说有什么区别？是不是设置好language=english之后就用英文写作即可，不需要其他额外的设置？

**Comment by zepinglee** [comment]
> 我比较好奇的是英文版和中文版对用户来说有什么区别？

你可以找 `\ifthu@chinese` 判断语言的代码。

> 是不是设置好language=english之后就用英文写作即可，不需要其他额外的设置？

我没有找到学校对本科生用英文写作的格式要求，所以目前的英文版只是根据中文版进行了简单的修改。

**Comment by zepinglee** [comment]
@james20141606 如果你有学校的格式要求或者模板不妨发个链接

**Comment by james20141606** [comment]
> > 我比较好奇的是英文版和中文版对用户来说有什么区别？
> 
> 你可以找 `\ifthu@chinese` 判断语言的代码。
> 
> > 是不是设置好language=english之后就用英文写作即可，不需要其他额外的设置？
> 
> 我没有找到学校对本科生用英文写作的格式要求，所以目前的英文版只是根据中文版进行了简单的修改。

这样呀，我明白啦~如果后续拿到英文写作的格式要求我可以post到这里~非常感谢！

**Comment by james20141606** [comment]
> @james20141606 如果你有学校的格式要求或者模板不妨发个链接

[外语论文要求.docx](https://github.com/xueruini/thuthesis/files/3101312/default.docx)
我这里有外文系的本科格式要求。

**Comment by zepinglee** [comment]
最好发教务处的链接，这样学弟学妹可以检查模板依照的格式要求是不是最新版

**Comment by zepinglee** [comment]
目前没问题的话我先关啦

**Comment by james20141606** [comment]
> 目前没问题的话我先关啦

看起来还有一点问题，就是选择bachelor的话，会出现论文标题无法换行，且没有英文信息页的问题，master的参数下是正常的。

**Comment by xueruini** [comment]
> 看起来还有一点问题，就是选择bachelor的话，会出现论文标题无法换行，且没有英文信息页的问题，master的参数下是正常的。

我这里看到是正常的
