### ISSUE TITLE
公式环境中大写希腊字母默认为斜体

### ISSUE THREAD

**Issue by WuSiren** [xueruini/thuthesis#404]
## 编译环境
编译的系统：Windows 10 
TeX 发行版：TeX Live 2018
相关宏包版本：？
模板类型： doctor

## 描述问题
公式环境下输入大写希腊字母默认为斜体，比如我要输入Δ_t_，按照学术规范，其中Δ应为正体，而t应为斜体，相应的latex代码为$\Delta t$，而模板中两者均为斜体。

示例代码：
```TeX
\documentclass[degree=doctor,tocarialchapter]{thuthesis}
\begin{document}
$\Delta t$
\end{document}
```

截图：

**Comment by xueruini** [comment]
模板现在用的是 ISO 模式，所以是歪的

![image](https://user-images.githubusercontent.com/1863/57363237-414a8c00-71b3-11e9-93b5-928bd30fde9e.png)

**Comment by stone-zeng** [comment]
本来 `\Delta`（U+1D6E5，&#x1D6E5;）就是作为字母、变量使用的，比如二次方程判别式。作为增量的 Delta，Unicode 里面定义了专门的 U+2206（&#x2206;），使用的话就是 `\increment`（目前模版已经转为了 `unicode-math` 应该是可以用的）。

**Comment by WuSiren** [comment]
> 模板现在用的是 ISO 模式，所以是歪的
> 
> ![image](https://user-images.githubusercontent.com/1863/57363237-414a8c00-71b3-11e9-93b5-928bd30fde9e.png)

谢谢薛老师。

**Comment by WuSiren** [comment]
> 本来 `\Delta`（U+1D6E5，𝛥）就是作为字母、变量使用的，比如二次方程判别式。作为增量的 Delta，Unicode 里面定义了专门的 U+2206（∆），使用的话就是 `\increment`（目前模版已经转为了 `unicode-math` 应该是可以用的）。

谢谢，您的回答正中我的下怀。

**Comment by mindest** [comment]
> 本来 `\Delta`（U+1D6E5，𝛥）就是作为字母、变量使用的，比如二次方程判别式。作为增量的 Delta，Unicode 里面定义了专门的 U+2206（∆），使用的话就是 `\increment`（目前模版已经转为了 `unicode-math` 应该是可以用的）。

谢谢，码了一堆字正准备发布 issue，看到了这个
