### ISSUE TITLE
本科生论文英文封面及英文标题

### ISSUE THREAD

**Issue by h-zhen** [xueruini/thuthesis#406]
## 编译环境
编译的系统：Overleaf
模板类型： bachelor

# 问题描述
按照命令
```TeX
\documentclass[degree=bachelor,language=english]{thuthesis}
```
的本科生论文只显示中文封面，没有英文封面。

如果本科生论文不提供英文封面的话，是否有办法在英文摘要上方添加英文标题呢？

谢谢！

**Comment by zepinglee** [comment]
据我了解本科生毕设论文是不允许使用英文的，所以你能不能提供一份关于英文格式的官方文件？

**Comment by h-zhen** [comment]
数学系老师说可以用英文写，但没有提供官方格式。感觉现在的模板调到 language=english 就够用了，如果能有办法添加英文标题就更好了

**Comment by zepinglee** [comment]
那最好问一下你们系负责审核论文格式的老师。如果我搞一个封面/扉页导致审查不通过就麻烦了

**Comment by zhaoyq15** [comment]
同求。前排插眼。

**Comment by zepinglee** [comment]
@zhaoyq15 给一份格式要求或者样例啊

**Comment by zhaoyq15** [comment]
> @zhaoyq15 给一份格式要求或者样例啊

在问了，档案馆负责论文的老师出差了，下周一再继续问。。。

**Comment by zhaoyq15** [comment]
> @zhaoyq15 给一份格式要求或者样例啊

院系负责老师邮件原文：

> 本来英文论文就不是规则里面的，所以也不会有模板。你可以参考过往国际学生的论文格式。如果有找不到，去图书馆问。理论上图书馆会提供所有非涉密的论文。

**Comment by zhaoyq15** [comment]
1. 问了图书馆，因为系统故障，图书馆暂时无法查询往年本科生（优秀）论文，所以目前没有往年样例
2. 问了学校教务，学校教务口头表示本科生英文毕业论文今年没有也不会有官方的、正式的、书面的格式要求和样例，但仍需要有中文论文的全部组件，即封面、中文（长）摘要、英文摘要、正文、索引、参考文献、致谢、声明和附录，声明仍需使用学校官方正式的中文版
3. 学校教务口头推荐使用中文封面

**Comment by zepinglee** [comment]
ok，那我还是做一个英文封面吧，用户自己选择是否使用

**Comment by zepinglee** [comment]
我觉得还是写在 `ctitle` 里面吧
