### ISSUE TITLE
another bibstyle command

### ISSUE THREAD

**Issue by james20141606** [xueruini/thuthesis#408]
## 编译环境
编译的系统：macOS 10.14
TeX 发行版：MacTeX 2018
相关宏包版本：ctex v2.4.14
模板类型： bachelor

## 描述问题
插入引文直接编译不通过，需要删除main.aux中的其中一种bibstyle才可以通过。

示例代码：
Running 'bibtex  "main"'
------------
This is BibTeX, Version 0.99d (TeX Live 2018)
The top-level auxiliary file: main.aux
A level-1 auxiliary file: data/chap01.aux
A level-1 auxiliary file: data/chap02.aux
A level-1 auxiliary file: data/chap03.aux
The style file: thuthesis-numeric.bst
Illegal, another \bibstyle command---line 49 of file main.aux
 : \bibstyle
 :          {thuthesis-author-year}
I'm skipping whatever remains of this command
A level-1 auxiliary file: data/ack.aux
Database file #1: ref/refs.bib
(There was 1 error message)
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  bibtex main: Bibtex errors: See file 'main.blg'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
make: *** [Makefile:61: main.pdf] Error 12

直接适用make thesis时由于main.aux中同时存在bibstyle
\bibstyle{thuthesis-numeric}
\bibstyle{thuthesis-author-year}
此时步骤bibtex main会有上述报错，在手动删除main.aux中的两个bibstyle中的其中一个后可以继续编译

**Comment by zepinglee** [comment]
main.tex 里的两个 \bibliographystyle 要注释掉其中一个

**Comment by james20141606** [comment]
> main.tex 里的两个 \bibliographystyle 要注释掉其中一个
> […](#)
> On May 21, 2019, at 12:18 AM, Chen Xupeng ***@***.***> wrote: 编译环境 编译的系统：macOS 10.14 TeX 发行版：MacTeX 2018 相关宏包版本：ctex v2.4.14 模板类型： bachelor 描述问题 插入引文直接编译不通过，需要删除main.aux中的其中一种bibstyle才可以通过。 示例代码： Running 'bibtex "main"' This is BibTeX, Version 0.99d (TeX Live 2018) The top-level auxiliary file: main.aux A level-1 auxiliary file: data/chap01.aux A level-1 auxiliary file: data/chap02.aux A level-1 auxiliary file: data/chap03.aux The style file: thuthesis-numeric.bst Illegal, another \bibstyle command---line 49 of file main.aux : \bibstyle : {thuthesis-author-year} I'm skipping whatever remains of this command A level-1 auxiliary file: data/ack.aux Database file #1: ref/refs.bib (There was 1 error message) Latexmk: Errors, so I did not complete making targets Collected error summary (may duplicate other messages): bibtex main: Bibtex errors: See file 'main.blg' Latexmk: Use the -f option to force complete processing, unless error was exceeding maximum runs of latex/pdflatex. make: *** [Makefile:61: main.pdf] Error 12 直接适用make thesis时由于main.aux中同时存在bibstyle \bibstyle{thuthesis-numeric} \bibstyle{thuthesis-author-year} 此时步骤bibtex main会有上述报错，在手动删除main.aux中的两个bibstyle中的其中一个后可以继续编译 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

非常感谢~感觉是不是可以在main.pdf里稍微提一句，第一次用的话可能找不到在哪里，搜报错的关键词\bibstyle也搜不到main.tex的相关内容里。

**Comment by zepinglee** [comment]
嗯，有道理。
