### ISSUE TITLE
本科生论文参考文献序号缺失，正文直接显示作者名，而非文献序号

### ISSUE THREAD

**Issue by ZhangShuTHU** [xueruini/thuthesis#410]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
相关宏包版本：ctex v2.4.14
模板类型： bachelor

## 描述问题
使用2019.5.22的github版本，采用本科论文参考文献格式，生成的pdf中参考文献序号缺失，正文直接显示作者名，而非文献序号

示例代码：
开始 : xelatex.exe -synctex=1 -interaction=nonstopmode "main".tex
完成
开始 : bibtex.exe "main"
This is BibTeX, Version 0.99d (TeX Live 2019/W32TeX)
The top-level auxiliary file: main.aux
A level-1 auxiliary file: data/chap01.aux
A level-1 auxiliary file: data/chap02.aux
A level-1 auxiliary file: data/chap03.aux
A level-1 auxiliary file: data/chap04.aux
A level-1 auxiliary file: data/chap05.aux
A level-1 auxiliary file: data/chap06.aux
The style file: thuthesis-bachelor.bst
Database file #1: ref/refs.bib
完成
开始 : xelatex.exe -synctex=1 -interaction=nonstopmode "main".tex
完成
开始 : xelatex.exe -synctex=1 -interaction=nonstopmode "main".tex
完成
开始 : xelatex.exe -synctex=1 -interaction=nonstopmode "main".tex
完成

截图：
![image](https://user-images.githubusercontent.com/38218229/58305705-9f21d980-7e2b-11e9-91d9-c4d95f8c2e19.png)
![image](https://user-images.githubusercontent.com/38218229/58305723-b6f95d80-7e2b-11e9-836b-ab3c22a2f650.png)

**Comment by zepinglee** [comment]
在 d32e35c 中已经修复
