### ISSUE TITLE
章节标题中使用$\cdot$会报错，以及如何在数学模式中使用正体的Times New Roman字体？

### ISSUE THREAD

**Issue by zhaoyq15** [xueruini/thuthesis#411]
\subsection{$balabala\cdot balabala$}会报错且无法往下编译，\subsection{$balabala\textperiodcentered balabala$}则会正常，
而$\cdot$在正文中可以正常使用。
以及如何在数学模式中使用正体而非斜体的Times New Roman字体？

![image](https://user-images.githubusercontent.com/14362223/58349065-e3958f80-7e94-11e9-9c50-d9385e89e427.png)
不明觉厉

**Comment by zepinglee** [comment]
在 d32e35c 中已经修复

**Comment by stone-zeng** [comment]
如果是某一个字母要用正体，可以用 `\symrm{x}` 或者 `\mathrm{x}`（推荐前者）；如果是要全部改为正体，这种属于乱来，请不要这么做。

**Comment by zhaoyq15** [comment]
> 如果是某一个字母要用正体，可以用 `\symrm{x}` 或者 `\mathrm{x}`（推荐前者）；如果是要全部改为正体，这种属于乱来，请不要这么做。

1. 我需要写行间的化学反应方程式，其中有各种上下标，确实有这种的需求。。。
2. \mathrm{}还是Times New Roman字体吗？

**Comment by stone-zeng** [comment]
1. 如果你用写化学方程式，推荐使用 [`mhchem`](https://ctan.org/pkg/mhchem) 宏包，不要自己依靠数学环境来实现。
2. 在默认配置下，`\symrm{x}` 是 XITS Math，`\mathrm{x}` 是 Times New Roman，不过我打赌你看不出来。相关讨论见 #361、#399。

**Comment by zepinglee** [comment]
对，就像国际单位最好用 `siunitx` 一样

**Comment by zhaoyq15** [comment]
> 1. 如果你要写化学方程式，推荐使用 [`mhchem`](https://ctan.org/pkg/mhchem) 宏包，不要自己依靠数学环境来实现。
> 2. 在默认配置下，`\symrm{x}` 是 XITS Math，`\mathrm{x}` 是 Times New Roman，不过我打赌你看不出来。相关讨论见 #361、#399。

好的。谢谢。
