### ISSUE TITLE
renewcommand\vec 建议去掉

### ISSUE THREAD

**Issue by WenyinWei** [xueruini/thuthesis#412]
## 编译环境
编译的系统：Windows 10 
TeX 发行版： TeX Live 2018 
相关宏包版本：amsmath
模板类型： master 

## 描述问题

```Tex
% 后来在chap01的535行找到了这个,我建议不要再模板里面加入这个内容.
\renewcommand\vec{\symbf}
\newcommand\mat{\symbf}
```
建议不要在模板内将数学符号重新命名,似乎我这里所有的矢量符号 \vec{} 都无法通过编译.

示例代码：
```TeX
\begin{equation}
\label{equ:chap2:bayes}
p(y|\vec{x}) = \frac{p(\vec{x},y)}{p(\vec{x})}=
\frac{p(\vec{x}|y)p(y)}{p(\vec{x})}
\end{equation}
```

截图：
![image](https://user-images.githubusercontent.com/33152225/58382937-2b3a2980-8003-11e9-9536-93e8bf7ef2cb.png)

**Comment by stone-zeng** [comment]
这个修改是在 ba4c2c4090bdee569d427ade03e5eac7602822a7 中做的。请确保模版本身（`.cls`）和示例文件（`.tex`）是同一个版本的。从 GitHub 下载并使用 master 的话，需要先运行释放出模版，而不能直接运行示例。

**Comment by zepinglee** [comment]
@stone-zeng 我刚发现 `unicode-math` 里也用了 `\vec` 命令，感觉这里把它重定义一番作为示例不太合适。

不过我很不喜欢 `\vec` 这个命令的设计，因为它本身表达的是语义信息（向量 vector），但是却被用来表示具体的格式；而且像在向量的格式上，国标、ISO（粗斜体）跟 LaTeX 习惯（粗正体）并不一致。所以最好有一个表达语义的命令表示“向量”语义。

**Comment by stone-zeng** [comment]
我自己写东西一般是先定义一个 `\def\V#1{\sumbf{#1}}` 这种……

**Comment by zepinglee** [comment]
我觉得可以把 https://github.com/goodfeli/dlbook_notation/blob/master/math_commands.tex 借鉴过来
