### ISSUE TITLE
本科英文论文标题无法换行

### ISSUE THREAD

**Issue by james20141606** [xueruini/thuthesis#413]
## 编译环境
编译的系统：macOS 10.14
TeX 发行版：MacTeX 2018
相关宏包版本：ctex v2.4.14
模板类型： bachelor

## 描述问题
运行dev分支的英文版代码，选择\documentclass[degree=bachelor,language=english,tocarialchapter]{thuthesis}后，发现标题无法换行。
原因大概是这样的，如果是bachelor的话，cover.tex下面的那段etitle似乎是无法涵盖的，因此只能在ctitle里填写英文标题，但是无法实现换行功能。英语专业及英语双学位要求英文题目1号黑体字，1.2倍行距。如果我在ctitle内手动换行并不符合要求

**Comment by james20141606** [comment]
> ## 编译环境
> 编译的系统：macOS 10.14
> TeX 发行版：MacTeX 2018
> 相关宏包版本：ctex v2.4.14
> 模板类型： bachelor
> 
> ## 描述问题
> 运行dev分支的英文版代码，选择\documentclass[degree=bachelor,language=english,tocarialchapter]{thuthesis}后，发现标题无法换行。
> 原因大概是这样的，如果是bachelor的话，cover.tex下面的那段etitle似乎是无法涵盖的，因此只能在ctitle里填写英文标题，但是无法实现换行功能。英语专业及英语双学位要求英文题目1号黑体字，1.2倍行距。如果我在ctitle内手动换行并不符合要求

因为要求的是标题是英文，其他信息填写中文，所以最好可以增加一个ctitle也支持英文输入换行？或者允许中文信息部分插入etitle

**Comment by james20141606** [comment]
另外能否允许注释掉中文摘要呢？如果只需要英文摘要的话

**Comment by zepinglee** [comment]
> ## 编译环境
> 编译的系统：macOS 10.14
> TeX 发行版：MacTeX 2018
> 相关宏包版本：ctex v2.4.14
> 模板类型： bachelor
> 
> ## 描述问题
> 运行dev分支的英文版代码，选择\documentclass[degree=bachelor,language=english,tocarialchapter]{thuthesis}后，发现标题无法换行。
> 原因大概是这样的，如果是bachelor的话，cover.tex下面的那段etitle似乎是无法涵盖的，因此只能在ctitle里填写英文标题，但是无法实现换行功能。英语专业及英语双学位要求英文题目1号黑体字，1.2倍行距。如果我在ctitle内手动换行并不符合要求

1. 可以用 `\\` 手动换行。
2. “英语专业及英语双学位要求英文题目1号黑体字，1.2倍行距。”能不能让我看下官方的文件？

**Comment by zepinglee** [comment]
@xueruini 目前的模板是在 `cabstract` 环境中将摘要存到 `\thu@cabstract`，然后用 `\makecover` 命令连封面一起输出。

我觉得可以改成像 `article` 的 `abstract` 环境一样直接输出，这样更加灵活，另外摘要也不是封面的一部分。

**Comment by zepinglee** [comment]
另外 `\makecover` 这个命令跟标准文档类的接口 `\maketitle` 还不太一致

**Comment by zepinglee** [comment]
还有 `ctitle` 和 `etitle` 这些 key 有点太丑，我觉得像 [stone-zeng/fduthesis](https://github.com/stone-zeng/fduthesis/blob/d2ae24f805baf27c30639ced7cadfbde46b3e990/docs/fduthesis-template.tex#L160) 这样的接口更优雅一些。

**Comment by xavieryao** [comment]
我现在的解决方案是，用 `soulutf8` 宏包，使用 `\ul\thu@etitle` 命令生成标题，效果还不错。

**Comment by xueruini** [comment]
> 还有 `ctitle` 和 `etitle` 这些 key 有点太丑，我觉得像 [stone-zeng/fduthesis](https://github.com/stone-zeng/fduthesis/blob/d2ae24f805baf27c30639ced7cadfbde46b3e990/docs/fduthesis-template.tex#L160) 这样的接口更优雅一些。

是的，这些名字都是历史上遗留下来的，叫法有点土。可以改。
