### ISSUE TITLE
多行子图的caption出现重叠的问题

### ISSUE THREAD

**Issue by dutry** [xueruini/thuthesis#414]
## 编译环境
编译的系统：Overleaf
模板类型： master 

## 描述问题
这一问题在[stack exchange和他人讨论](https://tex.stackexchange.com/questions/492665/multiline-subfigure-caption-cannot-be-shown-fully/493080#493080)已经获得确认是bug问题（详细讨论参见指向stack exchange的超链接），现在需要对模板pull一个修改。

**Comment by zepinglee** [comment]
无法复现你的问题，可能你需要升级一下 thuthesis 的版本
