### ISSUE TITLE
本科学位论文参考文献格式

### ISSUE THREAD

**Issue by yanghtr** [xueruini/thuthesis#415]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
thuthesis版本：releases v5.5.2
模板类型： bachelor

## 描述问题
《参考文献著作格式》第 2 页要求学位论文参考格式为：“[文献类型标志/文献载体标识]”，比如：
[1] 张志祥. 间断动力系统的随机扰动及其在守恒律方程中的应用[D]. 北京: 北京大学数学学院，1998: 5-10.
而模板编译的结果是“[硕士学位论文]”

截图：使用v5.5.2版本编译得到的结果
![image](https://user-images.githubusercontent.com/30250600/58534312-80ea1e00-821d-11e9-9c9c-1126590f4e3d.png)

**Comment by zepinglee** [comment]
你需要在 \bibliographystyle 处选择本科生的样式
