### ISSUE TITLE
mac编译后字体和预期不符

### ISSUE THREAD

**Issue by yangyuji12** [xueruini/thuthesis#416]
## 编译环境
编译的系统：macOS 10.11.6
TeX 发行版：TeX Live 2019
模板类型： master

## 描述问题
按照模板使用TexStudio或者TexPad编译后，发现和别人的字体明显不同。例如标题，别人的标题更粗一些，像是黑体中等；而我的标题就细一些，像是黑体细体。

我朋友的标题（部分）：
<img width="168" alt="屏幕快照 2019-05-31 12 39 05" src="https://user-images.githubusercontent.com/16333419/58681901-25e13400-83a1-11e9-94f0-f35b93d9b924.png">

字体集中的中等字体：
<img width="329" alt="屏幕快照 2019-05-31 12 32 50" src="https://user-images.githubusercontent.com/16333419/58681817-b703db00-83a0-11e9-82c2-3f4b63c401b4.png">

我的标题（部分）：
<img width="132" alt="屏幕快照 2019-05-31 12 39 13" src="https://user-images.githubusercontent.com/16333419/58681915-2bd71500-83a1-11e9-8486-cae3013caf10.png">

字体集中的细体字体
<img width="350" alt="屏幕快照 2019-05-31 12 32 39" src="https://user-images.githubusercontent.com/16333419/58681816-b703db00-83a0-11e9-8f6f-191b3a737279.png">

我测试了Adobe四种字体的编译结果，
```
\documentclass{ctexart}  
\begin{document}  
你好，TeX Live 2019！  
{\songti 这是宋体}  
{\heiti 这是黑体}  
{\fangsong 这是仿宋}  
{\kaishu 这是楷书}  
\end{document}
```

结果如下：
<img width="374" alt="屏幕快照 2019-05-31 12 43 46" src="https://user-images.githubusercontent.com/16333419/58682134-fc74d800-83a1-11e9-9c58-6a3fbb8844ec.png">
感觉里面出现的还是细体的黑体。

问题：如何设置我的字体呢？现在编译出来的论文看起来比较弱弱的，不太好看。

log文件中无报错，[main.log](https://github.com/xueruini/thuthesis/files/3239738/main.log)

**Comment by zepinglee** [comment]
没啥问题，就是这样。你同学应该是在 Windows 上编译的，所以用的中易黑体略粗一点。

**Comment by yangyuji12** [comment]
> 没啥问题，就是这样。你同学应该是在 Windows 上编译的，所以用的中易黑体略粗一点。

不不，我朋友也是mac系统。如果我想变成中等黑体，应该在哪里如何设置吗？

**Comment by zepinglee** [comment]
> 不不，我朋友也是mac系统。如果我想变成中等黑体，应该在哪里如何设置吗？

你要是把 Heiti SC Medium 设成默认的，黑体就没有粗体了，只能开启伪粗。

你上面截图的两个标题分别是用什么命令生成的？

**Comment by yangyuji12** [comment]
> 你要是把 Heiti SC Medium 设成默认的，黑体就没有粗体了，只能开启伪粗。
> 你上面截图的两个标题分别是用什么命令生成的？

我和我朋友的操作都是一样的：1.下载thuthesis模板；2.填写正文；3.Texstudio中用xelatex一键编译生成pdf。没有其他多余的操作，但是生成的pdf却是不一样的。

我系统的字体册中有很多黑体：
<img width="204" alt="屏幕快照 2019-06-01 11 52 06" src="https://user-images.githubusercontent.com/16333419/58743442-d1eb5380-8463-11e9-88ce-c9b9936d8f8c.png">

我使用
`avail_font_names = [f.name for f in matplotlib.font_manager.fontManager.ttflist]`
得到了系统中的字体列表：

> ['DejaVu Sans Mono', 'STIXGeneral', 'DejaVu Sans', 'DejaVu Serif', 'STIXSizeThreeSym', 'DejaVu Serif', 'DejaVu Sans', 'STIXGeneral', 'STIXSizeThreeSym', 'cmex10', 'DejaVu Sans Mono', 'STIXNonUnicode', 'DejaVu Sans Mono', 'cmb10', 'STIXNonUnicode', 'STIXNonUnicode', 'STIXSizeTwoSym', 'cmsy10', 'STIXSizeTwoSym', 'STIXSizeOneSym', 'DejaVu Serif', 'cmmi10', 'STIXGeneral', 'cmss10', 'cmr10', 'DejaVu Serif', 'DejaVu Serif Display', 'STIXSizeOneSym', 'STIXSizeFourSym', 'STIXGeneral', 'STIXSizeFourSym', 'STIXSizeFiveSym', 'STIXNonUnicode', 'DejaVu Sans Mono', 'DejaVu Sans', 'cmtt10', 'DejaVu Sans Display', 'DejaVu Sans', 'Estrangelo Nisibin', 'Bitstream Vera Sans Mono', 'Luxi Serif', 'Luminari', 'STIXGeneral', 'STIXIntegralsD', 'Euclid Math One', 'Serto Jerusalem', 'Skia', 'Bodoni 72 Smallcaps', 'Bitstream Vera Sans', '.Keyboard', 'HeadLineA', 'Verdana', 'Luxi Sans', 'STIXIntegralsSm', 'East Syriac Adiabene', 'STIXIntegralsSm', 'STIXSizeFourSym', 'STIXVariants', 'Serto Mardin', 'STIXIntegralsUpSm', 'System Font', 'Georgia', 'Arial Unicode MS', 'Verdana', 'InaiMathi', 'LiSong Pro', 'Goha-Tibeb Zemen', 'System Font', 'STHeiti', 'System Font', 'Estrangelo Nisibin Outline', 'Georgia', 'Tahoma', 'Arial Narrow', 'Gurmukhi MT', 'Apple Braille', 'Ayuthaya', 'STIXSizeOneSym', 'Serto Jerusalem', 'Estrangelo Quenneshrin', 'PCMyungjo', 'AppleMyungjo', 'Webdings', 'System Font', 'STIXNonUnicode', 'System Font', 'STIXVariants', 'msbm10', 'STIXSizeOneSym', 'Brush Script MT', 'Serto Jerusalem Outline', 'Bitstream Vera Sans', 'Courier New', 'Verdana', 'Luxi Sans', 'Plantagenet Cherokee', 'Andale Mono', 'Luxi Serif', 'SignPainter', 'Courier New', 'Comic Sans MS', 'STIXIntegralsD', 'STIXSizeTwoSym', 'Symbol', 'Bitstream Vera Serif', 'Bitstream Vera Sans', 'Verdana', 'System Font', 'STIXIntegralsUpD', 'System Font', 'Serto Malankara', 'Arial', 'Estrangelo Edessa', 'Arial', 'modstmary10', 'STIXSizeTwoSym', 'Comic Sans MS', 'Estrangelo Midyat', 'Bitstream Vera Sans Mono', 'STIXSizeFiveSym', 'System Font', 'Bradley Hand', 'YuGothic', 'Impact', 'Hoefler Text', 'Zapf Dingbats', 'Yuppy SC', 'System Font', 'System Font', 'Trebuchet MS', 'Bitstream Vera Sans Mono', 'Estrangelo TurAbdin', 'System Font', 'TeamViewer13', 'System Font', 'Arial Narrow', 'Courier New', 'Yuppy TC', 'Kokonor', 'System Font', 'Bitstream Vera Sans Mono', 'Microsoft YaHei', 'Arial Narrow', 'Serto Mardin', 'TeamViewer12', 'System Font', 'System Font', 'LiHei Pro', 'System Font', 'System Font', 'Bodoni Ornaments', 'Estrangelo Antioch', 'Tahoma', 'Times New Roman', 'System Font', 'System Font', 'Apple Braille', 'System Font', 'Luxi Mono', 'Luxi Mono', 'Sathu', 'Apple Braille', 'System Font', 'Wawati SC', 'Lao Sangam MN', 'Farisi', 'Herculanum', 'STIXNonUnicode', 'Trebuchet MS', 'System Font', 'Big Caslon', 'Wingdings', 'Weibei SC', 'Zapfino', 'System Font', 'Georgia', 'System Font', 'STFangsong', 'System Font', 'Luxi Mono', 'Mishafi', 'Times New Roman', 'STIXNonUnicode', 'STHeiti', 'Bitstream Vera Serif', 'Silom', 'System Font', 'Bitstream Vera Sans', 'Trattatello', 'System Font', 'Mishafi Gold', 'Serto Jerusalem', 'Weibei TC', 'Apple Braille', 'Goha-Tibeb Zemen', 'Arial Black', 'Luxi Sans', 'Arial', 'Serto Kharput', 'Luxi Sans', 'STIXIntegralsUp', 'Luxi Serif', 'STIXSizeThreeSym', 'Arial Rounded MT Bold', 'DIN Condensed', 'msam10', 'PilGi', 'Wingdings 2', 'System Font', 'Apple Chancery', 'STIXIntegralsUpSm', 'STIXGeneral', 'STIXGeneral', 'Courier New', 'DIN Alternate', 'Khmer Sangam MN', 'STIXIntegralsUp', 'Serto Batnan', 'YuGothic', 'Osaka', 'Diwan Thuluth', 'Trebuchet MS', 'Wingdings 3', 'System Font', 'Serto Urhoy', 'System Font', 'Arial', 'Trebuchet MS', 'STIXSizeThreeSym', 'Microsoft Sans Serif', 'STIXIntegralsUpD', 'SimHei', 'System Font', 'Luxi Serif', 'Estrangelo Talada', 'Serto Urhoy', 'STIXSizeFourSym', 'STIXGeneral', 'Times New Roman', 'Apple Braille', 'Arial Narrow', 'Krungthep', 'Chalkduster', 'GungSeo', 'East Syriac Ctesiphon', 'Georgia', 'Times New Roman', 'Luxi Mono', 'AppleGothic', 'Osaka', 'Wawati TC', 'System Font', 'Serto Batnan', 'Verdana', 'System Font', '.LastResort', 'STHeiti', 'STIXNonUnicode']

列表里有三个'STHeiti'，没有'Heiti SC'。是因为我缺少某个在程序中被设置为最高优先级的黑体字体吗？

**Comment by zepinglee** [comment]
下载模板后要用 `xetex` 编译 `thuthesis.ins` 生成 `thuthesis.cls` 文件。

**Comment by yangyuji12** [comment]
使用`xetex thuthesis.ins`命令生成了新的cls等文件，再次编译成pdf仍然还是细体。
`xetex thuthesis.ins`日志如下：

> This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xetex)
>  restricted \write18 enabled.
> entering extended mode
> (./thuthesis.ins
> (/usr/local/texlive/2019/texmf-dist/tex/latex/base/docstrip.tex
> Utility: `docstrip' 2.5g <2018/05/03>
> English documentation    <2018/05/03>
> 
> **********************************************************
> * This program converts documented macro-files into fast *
> * loadable files by stripping off (nearly) all comments! *
> **********************************************************
> 
> ********************************************************
> * No Configuration file found, using default settings. *
> ********************************************************
> 
> )
> 
> Generating file(s) thuthesis.cls thuthesis.cfg dtx-style.sty
> 
> Processing file thuthesis.dtx (cls) -> thuthesis.cls
>                               (cfg) -> thuthesis.cfg
>                               (dtx-style) -> dtx-style.sty
> File thuthesis.dtx ended by \endinput.
> Lines  processed: 3499
> Comments removed: 2256
> Comments  passed: 0
> Codelines passed: 1173
> 
> ***********************************************************
> *
> * To finish the installation you have to move the following
> * files into a directory searched by TeX:
> *
> * The recommended directory is TEXMF/tex/latex/thuthesis
> *
> *   thuthesis.cls
> *   thuthesis.cfg
> *   thuthesis-author-year.bst
> *   thuthesis-numeric.bst
> *
> * To produce the documentation run the files ending with
> * `.dtx' through LaTeX.
> *
> * Happy TeXing!
> ***********************************************************
>  )
> No pages of output.
> Transcript written on thuthesis.log.
> ➜  硕士毕业论文-thuthesis-v5.4.5 xetex thuthesis.ins
> This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xetex)
>  restricted \write18 enabled.
> entering extended mode
> (./thuthesis.ins
> (/usr/local/texlive/2019/texmf-dist/tex/latex/base/docstrip.tex
> Utility: `docstrip' 2.5g <2018/05/03>
> English documentation    <2018/05/03>
> 
> **********************************************************
> * This program converts documented macro-files into fast *
> * loadable files by stripping off (nearly) all comments! *
> **********************************************************
> 
> ********************************************************
> * No Configuration file found, using default settings. *
> ********************************************************
> 
> )
> 
> Generating file(s) thuthesis.cls thuthesis.cfg dtx-style.sty
> 
> Processing file thuthesis.dtx (cls) -> thuthesis.cls
>                               (cfg) -> thuthesis.cfg
>                               (dtx-style) -> dtx-style.sty
> File thuthesis.dtx ended by \endinput.
> Lines  processed: 3499
> Comments removed: 2256
> Comments  passed: 0
> Codelines passed: 1173
> 
> ***********************************************************
> *
> * To finish the installation you have to move the following
> * files into a directory searched by TeX:
> *
> * The recommended directory is TEXMF/tex/latex/thuthesis
> *
> *   thuthesis.cls
> *   thuthesis.cfg
> *   thuthesis-author-year.bst
> *   thuthesis-numeric.bst
> *
> * To produce the documentation run the files ending with
> * `.dtx' through LaTeX.
> *
> * Happy TeXing!
> ***********************************************************
>  )
> No pages of output.
> Transcript written on thuthesis.log.

**Comment by stone-zeng** [comment]
话说什么时候用 `\sffamily` 什么时候用 `\heiti`？看了下代码感觉挺混乱的，而且效果确实也是不一样的吧 @zepinglee

**Comment by zepinglee** [comment]
> 话说什么时候用 `\sffamily` 什么时候用 `\heiti`？看了下代码感觉挺混乱的，而且效果确实也是不一样的吧 @zepinglee

这部分代码应该是 @xueruini 早期的代码，不是我的锅😂

**Comment by zepinglee** [comment]
> 使用`xetex thuthesis.ins`命令生成了新的cls等文件，再次编译成pdf仍然还是细体。

给段代码复现问题啊

**Comment by yangyuji12** [comment]
> > 使用`xetex thuthesis.ins`命令生成了新的cls等文件，再次编译成pdf仍然还是细体。
> 
> 给段代码复现问题啊

使用`xetex thuthesis.ins`命令生成了新的cls等文件，再次编译成pdf仍然还是细体。
命令行输出为：

> This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xetex)
>  restricted \write18 enabled.
> entering extended mode
> (./thuthesis.ins
> (/usr/local/texlive/2019/texmf-dist/tex/latex/base/docstrip.tex
> Utility: `docstrip' 2.5g <2018/05/03>
> English documentation    <2018/05/03>
> 
> **********************************************************
> * This program converts documented macro-files into fast *
> * loadable files by stripping off (nearly) all comments! *
> **********************************************************
> 
> ********************************************************
> * No Configuration file found, using default settings. *
> ********************************************************
> 
> )
> 
> Generating file(s) thuthesis.cls thuthesis.cfg dtx-style.sty
> 
> Processing file thuthesis.dtx (cls) -> thuthesis.cls
>                               (cfg) -> thuthesis.cfg
>                               (dtx-style) -> dtx-style.sty
> File thuthesis.dtx ended by \endinput.
> Lines  processed: 3499
> Comments removed: 2256
> Comments  passed: 0
> Codelines passed: 1173
> 
> ***********************************************************
> *
> * To finish the installation you have to move the following
> * files into a directory searched by TeX:
> *
> * The recommended directory is TEXMF/tex/latex/thuthesis
> *
> *   thuthesis.cls
> *   thuthesis.cfg
> *   thuthesis-author-year.bst
> *   thuthesis-numeric.bst
> *
> * To produce the documentation run the files ending with
> * `.dtx' through LaTeX.
> *
> * Happy TeXing!
> ***********************************************************
>  )
> No pages of output.
> Transcript written on thuthesis.log.

[thuthesis.log](https://github.com/xueruini/thuthesis/files/3243621/thuthesis.log)

**Comment by zepinglee** [comment]
> 使用`xetex thuthesis.ins`命令生成了新的cls等文件，再次编译成pdf仍然还是细体。
> 命令行输出为：

跟 `xetex thuthesis.ins` 没关系，这个只是确认你的 `cls` 是最新版的。我需要的是 

![](https://user-images.githubusercontent.com/16333419/58681915-2bd71500-83a1-11e9-8486-cae3013caf10.png)

所对应的代码

**Comment by yangyuji12** [comment]
抱歉，误解了。

main.tex代码如下：
```
\documentclass[degree=master,tocarialchapter,pifootnote]{thuthesis}

% 选项

%   degree=[bachelor|master|doctor|postdoctor], % 必选，学位类型
%   secret,                % 可选（默认：关闭），是否有密级
%   tocarialchapter,       % 可选（默认：关闭），章目录中使用黑体（这项表示同时打开下面两项）
%   tocarialchapterentry,  % 可选（默认：关闭），单独控制章标题在目录中使用黑体
%   tocarialchapterpage,   % 可选（默认：关闭），单独控制章页码在目录中使用黑体
%   pifootnote,            % 可选（默认：关闭），页脚编号采用 pifont 字体符号，建议打开
%fontset=custom, 自定义字体
% 所有其它可能用到的包都统一放到这里了，可以根据自己的实际添加或者删除。
\usepackage{thuthesis}

\usepackage{amsmath}
\usepackage{amsfonts}

\usepackage{tabularx}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{subcaption}
\usepackage{booktabs}
\usepackage{url}
\usepackage{array}
\usepackage{multirow}
\usepackage{algorithm}
\usepackage{algorithmic}

\usepackage[margin=0.2cm]{caption}
% 定义所有的图片文件在 figures 子目录下
\graphicspath{{figures/}}

% 可以在这里修改配置文件中的定义。导言区可以使用中文。
% \def\myname{薛瑞尼}

\begin{document}

%%% 封面部分
\frontmatter
\input{data/cover_1}
% 如果使用授权说明扫描页，将可选参数中指定为扫描得到的 PDF 文件名，例如：
% \makecover[scan-auth.pdf]
\makecover

%% 目录
\tableofcontents

%% 符号对照表
%\input{data/denotation}


%%% 正文部分
\mainmatter
%\include{data/chap01}
%\include{data/chap02}
%\include{data/chap03}
%\include{data/chap04}
%\include{data/chap05}
%\include{data/chap06}


%%% 其它部分
\backmatter

%% 本科生要这几个索引，研究生不要。选择性留下。
% 插图索引
%\listoffigures
% 表格索引
%\listoftables
% 公式索引
%\listofequations


%% 参考文献
% 注意：至少需要引用一篇参考文献，否则下面两行可能引起编译错误。
% 如果不需要参考文献，请将下面两行删除或注释掉。
% 数字式引用
\bibliographystyle{thuthesis-numeric}
% 作者-年份式引用
% \bibliographystyle{thuthesis-author-year}
\bibliography{ref/refs}


%% 致谢
\include{data/ack}

%% 附录
%\begin{appendix}
%\input{data/appendix01}
%\end{appendix}

%% 个人简历
\include{data/resume}

%% 本科生进行格式审查是需要下面这个表格，答辩可能不需要。选择性留下。
% 综合论文训练记录表
%\includepdf[pages=-]{scan-record.pdf}
\end{document}
```

cover.tex代码如下：

```
\thusetup{
  %******************************
  % 注意：
  %   1. 配置里面不要出现空行
  %   2. 不需要的配置信息可以删除
  %******************************
  %
  %=====
  % 秘级
  %=====
  secretlevel={秘密},
  secretyear={10},
  %
  %=========
  % 中文信息
  %=========
  ctitle={AAA关系抽取方法研究},
  cdegree={工学硕士},
  cdepartment={计算机科学与技术系},
  cmajor={计算机科学与技术},
  cauthor={X XX},
  csupervisor={Y YY 副教授},
%  cassosupervisor={陈文光教授}, % 副指导老师
%  ccosupervisor={某某某教授}, % 联合指导老师
  % 日期自动使用当前时间，若需指定按如下方式修改：
  % cdate={超新星纪元},
  %
  % 博士后专有部分
  cfirstdiscipline={计算机科学与技术},
  cseconddiscipline={系统结构},
  postdoctordate={2009年7月——2011年7月},
  id={编号}, % 可以留空： id={},
  udc={UDC}, % 可以留空
  catalognumber={分类号}, % 可以留空
  %
  %=========
  % 英文信息
  %=========
  etitle={English Title},
  % 这块比较复杂，需要分情况讨论：
  % 1. 学术型硕士
  %    edegree：必须为Master of Arts或Master of Science（注意大小写）
  %             “哲学、文学、历史学、法学、教育学、艺术学门类，公共管理学科
  %              填写Master of Arts，其它填写Master of Science”
  %    emajor：“获得一级学科授权的学科填写一级学科名称，其它填写二级学科名称”
  % 2. 专业型硕士
  %    edegree：“填写专业学位英文名称全称”
  %    emajor：“工程硕士填写工程领域，其它专业学位不填写此项”
  % 3. 学术型博士
  %    edegree：Doctor of Philosophy（注意大小写）
  %    emajor：“获得一级学科授权的学科填写一级学科名称，其它填写二级学科名称”
  % 4. 专业型博士
  %    edegree：“填写专业学位英文名称全称”
  %    emajor：不填写此项
  edegree={Master of Science},
  emajor={Computer Science and Technology},
  eauthor={X XX},
  esupervisor={Associate Professor Y YY},
%  eassosupervisor={Chen Wenguang},
  % 日期自动生成，若需指定按如下方式修改：
  % edate={December, 2005}
  %
  % 关键词用“英文逗号”分割
  ckeywords={关系},
  ekeywords={relations}
}

% 定义中英文摘要和关键字
\begin{cabstract}
	这是中文摘要。

\end{cabstract}

% 如果习惯关键字跟在摘要文字后面，可以用直接命令来设置，如下：
% \ckeywords{}

\begin{eabstract}
This is the English abstract.
\end{eabstract}
```

这两个tex文件和生成的pdf文件，我打成一个包，
[latex_test.zip](https://github.com/xueruini/thuthesis/files/3243661/latex_test.zip)

**Comment by zepinglee** [comment]
1. 标题的粗细没问题，你同学编译的应该有问题
2. 你的模板版本较低

**Comment by yangyuji12** [comment]
首先，我之前的版本是5.4.5，刚才换成了5.5.2，得到的还是细体的黑体。模板版本对字体粗细没有影响。
其次，我还看了其他2位师兄的字体，感觉也是和我朋友的一致，和我的不一致。如下图，前3个是从师兄和朋友的论文里截图得到的，最后一个是我论文里的，对比很明显。

![屏幕快照 2019-06-01 19 29 47](https://user-images.githubusercontent.com/16333419/58747887-d2a3da00-84a3-11e9-9d10-2dfbdcf6680e.png)
![屏幕快照 2019-06-01 19 29 52](https://user-images.githubusercontent.com/16333419/58747880-bd2eb000-84a3-11e9-8215-f3d980c8de4f.png)
![屏幕快照 2019-06-01 19 30 01](https://user-images.githubusercontent.com/16333419/58747881-c029a080-84a3-11e9-8d67-3368eb933c4e.png)
![屏幕快照 2019-06-01 19 30 09](https://user-images.githubusercontent.com/16333419/58747884-c28bfa80-84a3-11e9-921a-0664d6203cef.png)

最后，究竟如何做可以把标题和各章节的小标题改成粗体呢？

**Comment by zepinglee** [comment]
学校给的 Word 版示例的标题就是黑体不加粗，所以你是要遵守学校的规定，还是要跟你师兄保持一致？

**Comment by yangyuji12** [comment]
我想跟师兄保持一致，谢谢！

**Comment by zepinglee** [comment]
你换 windows 系统编译应该就可以了，或者把 windows 的字体拷贝过来，在 `\documentclass` 加上 `fontset=windows` 参数

**Comment by yangyuji12** [comment]
我觉得我的字体是有问题的。
看了学校给的模板里的标题，确实是“黑体”不加粗，但是这个粗细和师兄的是一致的，和我的是不一致的。
下图是学校的模板中的一个例子：
<img width="279" alt="屏幕快照 2019-06-01 19 58 21" src="https://user-images.githubusercontent.com/16333419/58748214-be61dc00-84a7-11e9-9b6a-379591f9d5f7.png">

下图是我的标题中的部分：
![屏幕快照 2019-06-01 19 30 09](https://user-images.githubusercontent.com/16333419/58748225-dd606e00-84a7-11e9-9bdb-8083e0993044.png)

学校要求确实是黑体不加粗，我的论文里的标题应该是黑体习细体。换系统编译或者找别人帮我都是可行的方法，但是我觉得本质原因应该是代码后台调字体的时候有个什么逻辑，没有找到我的黑体正常的字体。我想在您的帮助下，把这个原因找到给解决掉。
我检查了我的字体，之前发现没有Adobe的黑体，我安装了之后还是不管用。
下图是我的所有包含黑体的字体列表：
<img width="520" alt="屏幕快照 2019-06-01 20 05 19" src="https://user-images.githubusercontent.com/16333419/58748280-af2f5e00-84a8-11e9-85af-8c7500aaaf94.png">

**Comment by yangyuji12** [comment]
通过笨方法一个一个试，把"黑体-简-细体"禁用，就好了。

<img width="685" alt="屏幕快照 2019-06-01 20 32 12" src="https://user-images.githubusercontent.com/16333419/58748504-6bd6ee80-84ac-11e9-9b3b-837b293df734.png">

得到的新标题：

<img width="112" alt="屏幕快照 2019-06-01 20 33 00" src="https://user-images.githubusercontent.com/16333419/58748518-a04aaa80-84ac-11e9-8c10-b122d103a9f3.png">

原来的旧标题：

![屏幕快照 2019-06-01 19 30 09](https://user-images.githubusercontent.com/16333419/58748529-c4a68700-84ac-11e9-96ac-1c8720ace129.png)

**Comment by stone-zeng** [comment]
在你不知道自己做什么的情况下，强烈不建议修改系统的默认行为，比如把某个系统字体禁掉。

Adobe 的黑体是根本不会用到的，不知道你为什么回想到用它呢？（在哪里看到的，我们要过去批判一番）

**Comment by stone-zeng** [comment]
@zepinglee  按照现在模版里面的写法：

https://github.com/xueruini/thuthesis/blob/cfeb2c833635d75ab4356539b5ef2b8e85a5db75/thuthesis.dtx#L1463-L1478

确实是会用到细体的黑体-简。是不是可以考虑默认就调 medium 然后更粗的靠 fakebold？（虽然我也不知道为什么 mac 就没有自带粗体）

**Comment by zepinglee** [comment]
我觉得用 Heiti SC Light 也没啥问题，首先 Songti SC 默认也是 Light，其次 ctex 配置的 macnew fontset 的 zhhei 也是 Heiti SC Light。

我觉得与其用 fakebold 不如用苹方。另外苹方也没有 Bold

> @zepinglee 按照现在模版里面的写法：
> 
> https://github.com/xueruini/thuthesis/blob/cfeb2c833635d75ab4356539b5ef2b8e85a5db75/thuthesis.dtx#L1463-L1478
> 
> 确实是会用到细体的黑体-简。是不是可以考虑默认就调 medium 然后更粗的靠 fakebold？（虽然我也不知道为什么 mac 就没有自带粗体）

**Comment by yangyuji12** [comment]
Heiti SC Light 可能确实没啥问题，我之前也觉得没啥影响，虽然和别人的不太一样。但是前几天导师审论文的时候说你这个字体和别人的不一样，别人的更好看，你这个标题看起来弱弱的。

所以如果在学校要求的标准之内的话，我肯定是要用medium的。谢谢@stone-zeng， 我改一下代码好了，修改系统行为确实会有隐患。
