### ISSUE TITLE
本科生英文参考文献

### ISSUE THREAD

**Issue by d-li14** [xueruini/thuthesis#417]
## 编译环境
编译的系统： Windows 10
TeX 发行版：TeX Live 2018 
模板类型： bachelor

## 描述问题
请问本科生论文如何加入英文文献，我目前编译出来是中文参考文献的格式

示例代码：
```TeX
\bibliographystyle{thuthesis-bachelor}     % 本科生参考文献的著录格式
\bibliography{ref/refs}
```

截图：
![image](https://user-images.githubusercontent.com/25176159/58743135-c5b0c780-845e-11e9-9bc4-ff78b7fb17e1.png)

**Comment by zepinglee** [comment]
你看一下 #374 是不是要求这个格式？

**Comment by d-li14** [comment]
@zepinglee 

谢谢，我之前看到《参考文献的著录格式》的要求了，我理解里面的意思是区分中文和英文文献，中文文献是GB\T7714-2015的规范，对应`\bibliographystyle{thuthesis-bachelor}`，而英文是APA/Chicago等格式，对应`\bibliographystyle{apalike} %或\bibliographystyle{chicago}`。

所以是不是应该区分两种style？我添加的参考文献多数为英文文献，但是像截图中那样，也被`\bibliographystyle{thuthesis-bachelor}`统一成GB\T7714-2015的规范输出了。

**Comment by stone-zeng** [comment]
同一篇文章肯定只能用一种格式，如果你的论文主要用中文写，那就用所谓「中文文献」的格式；否则再考虑 Chicago 或者 APA 或者 MLA。可以看到给出的 [样例](https://github.com/xueruini/thuthesis/files/2708535/2019.docx) 中，也有这样的条目（它的标点是有问题的……）

> [3] CRAWFPRD W，GORMAN M．Future libraries：dreams，madness， reality[M]．Chicago：American Library Association，1995.

**Comment by zepinglee** [comment]
@d-li14 @stone-zeng 《格式》的意思是正文用 GB/T 7714-2015，“外文资料的调研阅读报告或书面翻译”的参考文献用 APA 或 Chicago，不过这个还没有在模板里正式支持，见讨论 #343 。

**Comment by d-li14** [comment]
OK，所以正文的参考文献还是用`\bibliographystyle{thuthesis-bachelor}`这个style就对了。
我自己查重的时候参考文献很多被标重了，可能是参考文献都当做正文检查了，所以才怀疑是引用格式上有错误。

**Comment by zepinglee** [comment]
嗯，我也收到一些反馈说参考文献被标重了，还是研究中

**Comment by ArayCHN** [comment]
> 嗯，我也收到一些反馈说参考文献被标重了，还是研究中

根据其他同学的描述，论文格式如果某个条目没有年份，后面的条目均会被查重系统认为是正文。（但我目前没有验证的渠道，你们有办法验证吗？）
