### ISSUE TITLE
本科生论文表格题目应在表格上方

### ISSUE THREAD

**Issue by ZhangShuTHU** [xueruini/thuthesis#418]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
模板类型： bachelor

## 描述问题
本科生论文表格题目应在表格上方

示例代码：

截图：
![image](https://user-images.githubusercontent.com/38218229/58746787-e1cf5b80-8494-11e9-9843-4f2ea92703c6.png)

[本科综合论文训练论文写作指南.docx](https://github.com/xueruini/thuthesis/files/3243647/default.docx)

**Comment by zepinglee** [comment]
这个只能手动将 `\caption` 放到 `tabular` 上面

**Comment by zepinglee** [comment]
话说这份《本科综合论文训练论文写作指南》有没有教务处官方的链接？

**Comment by ZhangShuTHU** [comment]
http://www.sss.tsinghua.edu.cn/publish/sss/8359/20130608091332916105100/1.pdf


------------------
              张枢/ZHANG Shu      
                                                                                                                          
             清华大学电机工程与应用电子技术系                   
 
                                             Department of Electrical Engineering                          
                              Tsinghua University                          
                              Beijing,                                           100084                                           , P.R.CHINA                            
                          
 
               Mobile：                      +86-13717599330                                    
         Email：shu-zhang@qq.com          
 


 




------------------ 原始邮件 ------------------
发件人: "Zeping Lee"<notifications@github.com>;
发送时间: 2019年6月1日(星期六) 下午5:51
收件人: "xueruini/thuthesis"<thuthesis@noreply.github.com>;
抄送: "张枢/ZHANG Shu"<shu-zhang@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [xueruini/thuthesis] 本科生论文表格题目应在表格上方 (#418)




话说这份《本科综合论文训练论文写作指南》有没有教务处官方的链接？
