### ISSUE TITLE
本科生毕业论文两个指导老师如何写封面？

### ISSUE THREAD

**Issue by zhaoyq15** [xueruini/thuthesis#419]
想写成“指导教师：XXX （换行）（空格） XXX”的形式，请问应该如何编写呢？谢谢。尝试了\\和\protect\\，结果对齐出现了问题。

**Comment by xueruini** [comment]
单项里恐怕写不了。有个联合指导老师设置

**Comment by DaitTHU** [comment]
一个不太优雅的方法是把supervisor={}写成：
xxx, 教授\\5个全角空格+xxx+1个全角空格+教授
跟多行标题的处理差不多，全角是为了对齐
