### ISSUE TITLE
关于贵系教学办“参考文献格式不对”的问题

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#421]
> 各位同学：大家的论文基本都是用的latex模版，但是这个模版的参考文献格式不对，请大家不要用latex的参考文献模版。[计算机系教学办][清华大学]

> 刚刚打电话问过了，还是那个出版地不详和出版社不详，sl sn的问题，老师也建议，未知的东西不要显示就好

**Comment by xueruini** [comment]
审查者多是只看例子，不读规范。没见过的就判定为错。

**Comment by yangyuji12** [comment]
通过dblp或者会议期刊主页把address好epublisher信息补全就行了

**Comment by zepinglee** [comment]
《写作指南》第 20 页说：
> 无出版地可著录[出版地不详]或[S.l.]，无出版者可著录[出版者不详] 或[s.n.]；

这里就理解为，也可以不著录吧。

**Comment by xueruini** [comment]
sl/sn 是合规的，自己的论文还是要 proofread，看到 sl/sn 自然要补一下。我反而觉得应该保留 sl/sn，是一个很好的提醒机制。

**Comment by b-z** [comment]
软院的情况是，老师看这个sl什么的不爽，但确实是**符合写作规范**的。
个人觉得如果原始信息里没有提供出版地，那么不放感觉好看一点。

**Comment by xueruini** [comment]
> 个人觉得如果原始信息里没有提供出版地，那么不放感觉好看一点。

如果引用的都是近年的资料，应该还是能查到地点的，比如 @yangyuji12 提到的 dblp

**Comment by b-z** [comment]
> > 个人觉得如果原始信息里没有提供出版地，那么不放感觉好看一点。
> 
> 如果引用的都是近年的资料，应该还是能查到地点的，比如 @yangyuji12 提到的 dblp

感谢回复。我是用的dblp，但当时为了统一格式，把booktitle里的地点都去掉了。加回来之后发现确实可以啦!

**Comment by xueruini** [comment]
@zepinglee 我建议把删除 sl/sn 的 commit revert。文档里可以加相应的提醒。

**Comment by zepinglee** [comment]
我觉得还是方便大家更重要，因为这个到教学办折腾一趟不太值。另外一些会议的出版社还是有点难找的。
