### ISSUE TITLE
目录章节页码要求Times，编译为arial

### ISSUE THREAD

**Issue by knwng** [xueruini/thuthesis#422]
## 编译环境
编译的系统：macOS 10.14
TeX 发行版：TeX Live 2019
模板版本：v5.5.2
模板类型：bachelor

## 描述问题
教务要求目录中chapter页码要和section的页码字体相同，为Times，但默认编译出来的结果貌似和chapter标题一样为arial

截图：
![image](https://user-images.githubusercontent.com/26247277/58865359-01f75880-86e9-11e9-9b57-4d3ac59b1866.png)

**Comment by zepinglee** [comment]
tocarialchapter

**Comment by x-zheng16** [comment]
我也遇到这个问题，目录中的页码被答辩老师着重圈了出来
