### ISSUE TITLE
本科论文参考文献查重

### ISSUE THREAD

**Issue by YuanHaoReginald** [xueruini/thuthesis#423]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2018
模板版本：v5.5.2
模板类型：bachelor

## 描述问题

使用 v5.5.2 release 版本编译的结果，今天提交查重的时候整个参考文献几乎全部被标红（然后重复率炸了……），其中“参考文献”四个标题只显示出了一个“文”字。使用文献格式是 `\bibliographystyle{thuthesis-numeric}`（因为5.5.2还没修复thuthesis-bachelor格式丢失序号的问题）

问了一下周围使用latex的朋友，绝大多数使用numeric格式编译，情况很多样化。有的人没出问题，有的包含sl/sn但没出问题，有的部分参考文献出现重复。目前几乎所有参考文献全部重复的情况只发现我一个。

**Comment by YuanHaoReginald** [comment]
目前正在尝试update到最新commit重新编译一版，然后联系教务提交一下……

**Comment by zepinglee** [comment]
别的学校也有 latex 模板的参考文献几乎全被标重的情况，目前原因不明

**Comment by xueruini** [comment]
查重软件真的太牛了，都能够识别参考文献部分

**Comment by zepinglee** [comment]
> 查重软件真的太牛了，都能够识别参考文献部分

是太弱了，没识别出这是参考文献

**Comment by YuanHaoReginald** [comment]
刚才查了一堆页面，然后翻了一下相关的大学thesis，好像大概明白问题在哪了

> 如果你在用 TeX Live 2018 及以前的版本：
> 
> 这是因为 Windows 自带的宋体没有粗体，所以在本模板中使用了伪粗体（config/zjuthesis.cls:\PassOptionsToPackage{AutoFakeBold}{xeCJK}），这样可以保证观感一致性。
> 
> 如果大家有对查重的要求，请删除这一行，并手动指定粗体字体，比如使用楷体作为本模板的‘粗体’，这也是一种常见的解决方案。
> 
> 要想彻底解决这个问题，只能换用有真正粗体版本的字体，目前为止我并没有找到仿宋对应的粗体版本。 当然 Office 对字体伪粗体问题有更好的解决方式，毕竟人家是收钱的嘛……

参见 [https://github.com/TheNetAdmin/zjuthesis](url)

然后我翻了一下，thuthesis是在今年一月份的[https://github.com/xueruini/thuthesis/issues/376]这个issue(url)里面添加的伪粗体支持（如果我犯错记录了麻烦指出），所以能够解释为什么往届没有出现过这个问题。

在我Update到2019版本之后，“参考文献”四个字已经能够正常复制了。原来的版本里面只有“文”字能够复制到txt，剩下的都是方框和乱码。如果我明天二次查重过了的话大概能证明是这个问题。

（所以pmlc是硬匹配“参考文献”四个字的吗……）
（所以都怪我当初犯懒懒得从2018更新到2019……）

**Comment by xueruini** [comment]
> 在我Update到2019版本之后，“参考文献”四个字已经能够正常复制了。原来的版本里面只有“文”字能够复制到txt，剩下的都是方框和乱码。如果我明天二次查重过了的话大概能证明是这个问题。

good luck

> （所以pmlc是硬匹配“参考文献”四个字的吗……）

不知道是如何 match 的，str 匹配感觉太不靠谱了

**Comment by Chris-BAO** [comment]
> 刚才查了一堆页面，然后翻了一下相关的大学thesis，好像大概明白问题在哪了
> 
> > 如果你在用 TeX Live 2018 及以前的版本：
> > 这是因为 Windows 自带的宋体没有粗体，所以在本模板中使用了伪粗体（config/zjuthesis.cls:\PassOptionsToPackage{AutoFakeBold}{xeCJK}），这样可以保证观感一致性。
> > 如果大家有对查重的要求，请删除这一行，并手动指定粗体字体，比如使用楷体作为本模板的‘粗体’，这也是一种常见的解决方案。
> > 要想彻底解决这个问题，只能换用有真正粗体版本的字体，目前为止我并没有找到仿宋对应的粗体版本。 当然 Office 对字体伪粗体问题有更好的解决方式，毕竟人家是收钱的嘛……
> 
> 参见 https://github.com/TheNetAdmin/zjuthesis
> 
> 然后我翻了一下，thuthesis是在今年一月份的这个issue（#376 ）里面添加的伪粗体支持（如果我搞错记录了麻烦指出），所以能够解释为什么往届没有出现过这个问题。
> 
> 在我Update到2019版本之后，“参考文献”四个字已经能够正常复制了。原来的版本里面只有“文”字能够复制到txt，剩下的都是方框和乱码。如果我明天二次查重过了的话大概能证明是这个问题。
> 
> （所以pmlc是硬匹配“参考文献”四个字的吗……）
> （所以都怪我当初犯懒懒得从2018更新到2019……）
啊，我mac的机子，晚上查重也炸了，所有参考文献都重了，太崩溃了。。我发现我的“参考文献“是可以复制的，我用我室友的windows重新编译后，字体居然和mac有差别，然后反而“参考文献”不能正常复制了，然而我又去淘宝查了一次，还没出结果，保佑啊！另外问你，如何学校二次查重呢？

**Comment by Chris-BAO** [comment]
> 刚才查了一堆页面，然后翻了一下相关的大学thesis，好像大概明白问题在哪了
> 
> > 如果你在用 TeX Live 2018 及以前的版本：
> > 这是因为 Windows 自带的宋体没有粗体，所以在本模板中使用了伪粗体（config/zjuthesis.cls:\PassOptionsToPackage{AutoFakeBold}{xeCJK}），这样可以保证观感一致性。
> > 如果大家有对查重的要求，请删除这一行，并手动指定粗体字体，比如使用楷体作为本模板的‘粗体’，这也是一种常见的解决方案。
> > 要想彻底解决这个问题，只能换用有真正粗体版本的字体，目前为止我并没有找到仿宋对应的粗体版本。 当然 Office 对字体伪粗体问题有更好的解决方式，毕竟人家是收钱的嘛……
> 
> 参见 https://github.com/TheNetAdmin/zjuthesis
> 
> 然后我翻了一下，thuthesis是在今年一月份的这个issue（#376 ）里面添加的伪粗体支持（如果我搞错记录了麻烦指出），所以能够解释为什么往届没有出现过这个问题。
> 
> 在我Update到2019版本之后，“参考文献”四个字已经能够正常复制了。原来的版本里面只有“文”字能够复制到txt，剩下的都是方框和乱码。如果我明天二次查重过了的话大概能证明是这个问题。
> 
> （所以pmlc是硬匹配“参考文献”四个字的吗……）
> （所以都怪我当初犯懒懒得从2018更新到2019……）

啊，我mac的机子，晚上查重也炸了，所有参考文献都重了，太崩溃了。。我发现我的“参考文献“是可以复制的，我用我室友的windows重新编译后，字体居然和mac有差别，然后反而“参考文献”不能正常复制了，然而我又去淘宝查了一次，还没出结果，保佑啊！另外问你，如何学校二次查重呢？

**Comment by xueruini** [comment]
据说因为翟天临，今年学术规范检查异常严格。不知道查重系统怎么处理 PDF 的，这样试错大家的成本还是有点高？关键是都是误判

**Comment by zepinglee** [comment]
> 刚才查了一堆页面，然后翻了一下相关的大学thesis，好像大概明白问题在哪了
> 
> > 如果你在用 TeX Live 2018 及以前的版本：
> > 这是因为 Windows 自带的宋体没有粗体，所以在本模板中使用了伪粗体（config/zjuthesis.cls:\PassOptionsToPackage{AutoFakeBold}{xeCJK}），这样可以保证观感一致性。
> > 如果大家有对查重的要求，请删除这一行，并手动指定粗体字体，比如使用楷体作为本模板的‘粗体’，这也是一种常见的解决方案。
> > 要想彻底解决这个问题，只能换用有真正粗体版本的字体，目前为止我并没有找到仿宋对应的粗体版本。 当然 Office 对字体伪粗体问题有更好的解决方式，毕竟人家是收钱的嘛……
> 
> 参见 https://github.com/TheNetAdmin/zjuthesis
> 
> 然后我翻了一下，thuthesis是在今年一月份的这个issue（#376 ）里面添加的伪粗体支持（如果我搞错记录了麻烦指出），所以能够解释为什么往届没有出现过这个问题。
> 
> 在我Update到2019版本之后，“参考文献”四个字已经能够正常复制了。原来的版本里面只有“文”字能够复制到txt，剩下的都是方框和乱码。如果我明天二次查重过了的话大概能证明是这个问题。
> 
> （所以pmlc是硬匹配“参考文献”四个字的吗……）
> （所以都怪我当初犯懒懒得从2018更新到2019……）

似乎跟这个没有关系，ustc 的一个同学也是 mac 编译的炸了。

**Comment by b-z** [comment]
三年前我本科毕业的时候就这样了，我当时邮件问过知网，他们说是清华这边使用API不对，清华的锅。
本科查重很水，把各种无关的公式图片索引、附录、参考文献等等都删掉，只留下正文就好了。
知网会认为重复可能是因为公式图片索引这些部分不是标准的学位论文里的。

**Comment by b-z** [comment]
对于这种显然的系统错误，学院的老师通常会帮你再次申请一次查重，处理之后重新查就好了。
而且本科好像只查一次吧，和最终版不一致也无所谓。

**Comment by b-z** [comment]
> 据说因为翟天临，今年学术规范检查异常严格。不知道查重系统怎么处理 PDF 的，这样试错大家的成本还是有点高？关键是都是误判

我猜查重系统的处理方式是把pdf里的文字直接拷贝出来。然后做文本匹配什么的。
有的人参考文献、目录重复好像是因为复制出来的"参考文献"这几个字有乱码，或者有空格之类的，导致系统没识别出来。

为了避免误判，我查重前都先把文字拷出来看了一下是否有乱码。并且，插入的svg/pdf格式图片里的文字也是能复制出来的，为了避免这部分被查重，查之前我把这些图都删掉了。

**Comment by Chris-BAO** [comment]
> > 据说因为翟天临，今年学术规范检查异常严格。不知道查重系统怎么处理 PDF 的，这样试错大家的成本还是有点高？关键是都是误判
> 
> 我猜查重系统的处理方式是把pdf里的文字直接拷贝出来。然后做文本匹配什么的。
> 有的人参考文献、目录重复好像是因为复制出来的"参考文献"这几个字有乱码，或者有空格之类的，导致系统没识别出来。
> 
> 为了避免误判，我查重前都先把文字拷出来看了一下是否有乱码。并且，插入的svg/pdf格式图片里的文字也是能复制出来的，为了避免这部分被查重，查之前我把这些图都删掉了。

你说的对，我的mac生成的pdf中“参考文献”四个字看似没问题，换到win上字体就明显不对了，我觉得要复制到txt里，如果是黑体，应该就没问题，我后来叫我同学帮我编译了一遍，花钱查重了一次，就过了。

**Comment by YuanHaoReginald** [comment]
之前事情太多了忘了这边了

总之我更新到TexLive2019版本之后，二次查重就通过了，目前估计原因如[https://github.com/xueruini/thuthesis/issues/423#issuecomment-499079128](url)所示，希望能在README里面提醒后来的同学记得更新TexLive到2019版本以上

**Comment by TheNetAdmin** [comment]
还有一种情况可能导致查重出问题。

XeTeX编译出来的pdf似乎默认utf-8编码，但如果采用GBK方式读取，会读出来大量重复字符，比如大量的‘路’字，这个可能导致正文查重出问题。但这个完全是查重系统的问题，并不是LaTeX模板本身出错。

我记得之前科大的LaTeX模板查重时出过这样的问题，可能是他们用的查重系统不支持utf-8。
