### ISSUE TITLE
封面指导教师姓名、职称格式问题

### ISSUE THREAD

**Issue by b-z** [xueruini/thuthesis#424]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MikTeX 2.9.6972
模板版本：最新版
模板类型：master

## 描述问题
《研究生学位论文写作指南》第 5 页要求
> 若不超过 4 个汉字， 作者姓名和导师姓名应等宽， 各自应保持均匀间隔。

而模板编译的结果是，不会默认处理两个字的导师姓名的宽度(需要自己加全角空格)，且职称文字间距过大。指南未对职称文字做要求，但四个字的职称编出来很不好看。使用word的同学这里会好很多，职称是紧凑的。

![snip_20190605_154302](https://user-images.githubusercontent.com/6956659/58939265-6d086400-87a9-11e9-94ee-494d57b34617.png)

**Comment by zepinglee** [comment]
所以你期望的是什么样的？给个图例我去改下

**Comment by b-z** [comment]
感谢。用word的同学写的是这样的:
![image](https://user-images.githubusercontent.com/6956659/58945433-6cc29580-87b6-11e9-9ddd-e6c56e0b59e8.png)

希望出一个可选项之类的吧，如果是"教授"这种两个字的，现在的间距其实还好。

**Comment by zepinglee** [comment]
我刚看了一下，目前的模板是这样的：
<img width="502" alt="Screen Shot 2019-06-07 at 10 41 56 PM" src="https://user-images.githubusercontent.com/12290822/59112385-7d6d3a00-8975-11e9-87c5-e029617b2472.png">

而学校的 word 模板是：

1. 01-博-1-中文3学术型封面（论文题目一行，无副导师）

**Comment by zepinglee** [comment]
我总结一下，这个封面的规则应该是：
1. 姓名与职称空一字；
2. 姓名四字宽，保持均匀间隔；
3. 职称三字宽，保持均匀间隔。

所以在 `\thusetup` 录入信息时，应该将教师姓名和职称分开。

**Comment by zepinglee** [comment]
@stone-zeng 话说在接口的设计上有没有什么建议？我感觉贵校模板的接口设计比较优雅

**Comment by b-z** [comment]
```
  csupervisor={\ziju{0.6875}某　某副\ziju{0}研究员},
```

我暂时这么解决了，效果还不错

![image](https://user-images.githubusercontent.com/6956659/59141881-5e0ef500-89e7-11e9-855f-2da1e70a5bdd.png)

**Comment by zepinglee** [comment]
> ```
>   csupervisor={\ziju{0.6875}某　某副\ziju{0}研究员},
> ```
> 
> 
> 我暂时这么解决了，效果还不错
> 
> 
> ![image](https://user-images.githubusercontent.com/6956659/59141881-5e0ef500-89e7-11e9-855f-2da1e70a5bdd.png)

这个方法没问题，不过我还是在下一个版本中修复这个 bug 吧。

**Comment by xueruini** [comment]
> 2\. 姓名四字宽，保持均匀间隔；

少数名族呢？我感觉学校给的是个例子，而不是规则。学科这个字段应该没有要求吧？各个专业名字长短差别太大

**Comment by zepinglee** [comment]
> > 2. 姓名四字宽，保持均匀间隔；
> 
> 少数名族呢？我感觉学校给的是个例子，而不是规则。学科这个字段应该没有要求吧？各个专业名字长短差别太大

应该改成“不超过四个字时四字宽”，《写作指南》里有规定：

> 若不超过 4 个汉字，作者姓名和导 师姓名应等宽，各自应保持均匀间隔。

最好跟 word 模板保持一致吧

**Comment by zepinglee** [comment]
我正在改写封面的代码，目前初步实现了格式要求：
<img width="440" alt="Screen Shot 2019-06-23 at 2 29 35 PM" src="https://user-images.githubusercontent.com/12290822/59972532-59d7ff80-95c3-11e9-943a-64e92f8fec63.png">

而且接口超级简单：
```
\thusetup{
  cdegree         = {工学硕士},
  cdepartment     = {计算机科学与技术系},
  cmajor          = {计算机科学与技术},
  cauthor         = {薛尼},
  csupervisor     = {某某, 教授},
  cassosupervisor = {某某某, 教授}, % 副指导老师
  ccosupervisor   = {某某某, 研究员}, % 联合指导老师
}
```

**Comment by xueruini** [comment]
估计有人会用中文逗号分隔

**Comment by zepinglee** [comment]
专业型博士的封面跟学术型不太一样，需要加一个 `type=academic/professional` 的文档类选项

**Comment by zepinglee** [comment]
刚发现有一段
```
\def\thu@master@art{Master of Arts}
\def\thu@master@sci{Master of Science}
\def\thu@doctor@phi{Doctor of Philosophy}

\newif\ifthu@professional\thu@professionalfalse
\ifthu@master
  \ifthenelse{\equal{\thu@edegree}{\thu@master@art}}
    {\relax}
    {\ifthenelse{\equal{\thu@edegree}{\thu@master@sci}}
      {\relax}
      {\thu@professionaltrue}}
\fi
\ifthu@doctor
  \ifthenelse{\equal{\thu@edegree}{\thu@doctor@phi}}
    {\relax}
    {\thu@professionaltrue}
```
也就是说是靠 `edegree` 判断是否为专业型学位。我觉得做成一个显式的接口更方便。

**Comment by xueruini** [comment]
隐约记得这部分是潘神加的，哈哈 @frankpzh 

加一个接口也可以，更直观

**Comment by xueruini** [comment]
> 专业型博士的封面跟学术型不太一样，需要加一个 `type=academic/professional` 的文档类选项

硕士好像有这两种类型，博士啥时候也分叉了

**Comment by zepinglee** [comment]
研究生院提供的[封面示例](http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=001050603&parentColumnId=0010506&itemSeq=5365)里有“中文7专业博士封面”：
<img width="618" alt="Screen Shot 2019-07-04 at 2 55 29 PM" src="https://user-images.githubusercontent.com/12290822/60645629-c5478a00-9e6b-11e9-9879-26c19fab5982.png">

我也没见过这种学位，不过为了模板的完备性还是做了吧

**Comment by zepinglee** [comment]
硕士的封面 layout 居然跟博士不一样，而且表格的行都对不齐，简直坑：
<img width="409" alt="Screen Shot 2019-07-05 at 9 33 10 PM" src="https://user-images.githubusercontent.com/12290822/60725768-7f261f80-9f6c-11e9-86b5-83b51ad0a26d.png">
我觉得，硕士封面还是按照博士的 layout 吧（除了个别明显的差异），不过感觉就是在模仿 word 模板的 bug。

**Comment by zepinglee** [comment]
我打算借这个机会重新设计一下整个文档的接口：
```TeX
\thusetup{
  %******************************
  % 注意：
  %   1. 配置里面不要出现空行
  %   2. 不需要的配置信息可以删除
  %******************************
  %
  % 学位类型
  %   doctor | master | bachelor | postdoc;
  %   academic（默认）| professional
  %
  degree-type     = {master, academic},
  %
  % 标题
  %   可使用“\\”命令手动控制换行
  %
  title           = {清华大学学位论文 \LaTeX{} 模板\\使用示例文档 v\version},
  title*          = {An Introduction to \LaTeX{} Thesis Template of Tsinghua
                     University v\version},
  %
  % 中文学位
  %   1. 学术型学位
  %      需注明所属的学科门类，例如：
  %      哲学、经济学、法学、教育学、文学、历史学、理学、工学、农学、医学、
  %      军事学、管理学、艺术学
  %   2. 专业型学位
  %      直接填写专业学位的名称，例如：
  %      金融硕士、应用统计硕士、法律硕士、社会工作硕士、教育博士、体育硕士、
  %      汉语国际教育硕士、新闻与传播硕士、建筑学硕士、工程硕士、工程博士、
  %      风景园林硕士、公共卫生硕士、工商管理硕士、高级管理人员工商管理硕士、
  %      公共管理硕士、会计硕士、工程管理硕士、艺术硕士等
  %   3. 本科生不需要填写
  %
  degree          = {工学硕士},
  %
  % 英文学位
  %   1. 学术型博士
  %      Doctor of Philosophy
  %   2. 学术型硕士
  %      哲学、文学、历史学、法学、教育学、艺术学门类，公共管理学科
  %      填写“Master of Arts“，其它填写“Master of Science”
  %   2. 专业型学位
  %      直接填写专业学位英文名称全称，例如：
  %      Doctor of Education, Master of Engineering
  %   3. 本科生不需要填写
  %
  degree*         = {Master of Science},
  %
  % 培养单位
  %   填写所属院系的全名
  %
  department      = {计算机科学与技术系},
  %
  % 学科
  %   1. 学术型学位
  %      获得一级学科授权的学科填写一级学科名称，其他填写二级学科名称
  %   2. 工程硕士
  %      工程领域名称
  %   3. 其他专业型学位
  %      不填写此项
  %
  field           = {计算机科学与技术},
  field*          = {Computer Science and Technology},
  %
  % 姓名
  %
  author          = {薛瑞尼},
  author*         = {Xue Ruini},
  %
  % 指导教师
  %   中文姓名和职称之间以英文逗号“,”分开，下同
  %
  supervisor      = {郑纬民, 教授},
  supervisor*     = {Professor Zheng Weimin},
  %
  % 副指导教师
  %
  assosupervisor  = {陈文光, 教授},
  assosupervisor* = {Professor Chen Wenguang},
  %
  % 联合指导教师
  %
  cosupervisor    = {某某某, 教授},
  cosupervisor*   = {Professor Mou moumou},
  %
  % 日期
  %   默认为当前时间
  %
  % date            = {2019-07-07},
  %
  % 密级和年限
  %   秘密, 机密, 绝密
  %
  secretlevel     = {秘密},
  secretyear      = {10},
  %
  % 博士后专有部分
  %
  clc             = {分类号},            % 可以留空
  udc             = {UDC},               % 可以留空
  id              = {编号},              % 可以留空
  field-level-1   = {计算机科学与技术},  % 流动站（一级学科）名称
  field-level-2   = {系统结构},          % 专业（二级学科）名称
  startdate       = {2011-07-01},        % 研究工作起始时间
}
```

1. 以上参数以及 `language=english`, `tocarialchapter` 等，都允许在 `\documentclass` 中设置，或者用 `\thusetup` 在导言区或正文的任意位置修改，更加灵活。
2. `\makecover` 拆分为 `\maketitle`, `\copyrightpage`, `\declarationpage`，跟标准文档类的接口尽量接近。
3. 中英文摘要用 `abstract`, `abstract*` 环境生成，跟标准文档类的接口保持一致。
3. `\frontmatter` 用于 `abstract` 前，跟标准文档类的接口保持一致。

@xueruini 有什么意见？

**Comment by xueruini** [comment]
> ```
>   assosupervisor  = {陈文光, 教授},
>   assosupervisor* = {Professor Chen Wenguang},

不如就写全了。`associative-supervisor`?

>   %
>   % 联合指导教师
>   %
>   cosupervisor    = {某某某, 教授},
>   cosupervisor*   = {Professor Mou moumou},

`co-supervisor` like `co-author`?

>   % 密级和年限
>   %   秘密, 机密, 绝密
>   %
>   secretlevel     = {秘密},
>   secretyear      = {10},

secret-level, secret-year

**Comment by xueruini** [comment]
> @xueruini 有什么意见？

完全赞同！这样就清爽多了

**Comment by zepinglee** [comment]
> > ```
> >   assosupervisor  = {陈文光, 教授},
> >   assosupervisor* = {Professor Chen Wenguang},
> > ```
> 
> 
> 不如就写全了。`associative-supervisor`?
> 
> 
> > %
> > % 联合指导教师
> > %
> > cosupervisor    = {某某某, 教授},
> > cosupervisor*   = {Professor Mou moumou},
> 
> 
> `co-supervisor` like `co-author`?
> 
> 
> > % 密级和年限
> > %   秘密, 机密, 绝密
> > %
> > secretlevel     = {秘密},
> > secretyear      = {10},
> 
> 
> secret-level, secret-year

有道理！

**Comment by zepinglee** [comment]
官方英文模板的叫法是 Associate Supervisor，还是写成 associate-supervisor 避免混淆。

另外这里的 “Cooperate Supervisor”
https://github.com/xueruini/thuthesis/blob/0565f4e94ee022bdfca37b225a87f45787456dee/thuthesis.dtx#L2796
完全不合语法啊，应该叫 joint supervisor 或者 co-supervisor，但是官方似乎没有给出例子

**Comment by xueruini** [comment]
我在想这次接口变更要兼容老的文件么？比如用户使用 etitle 进行配置是否还能工作？要不然就彻底一点，不留尾巴，不兼容了

**Comment by zepinglee** [comment]
我也觉得没有必要

**Comment by zepinglee** [comment]
用 `kvsetkeys` 实现起来有点麻烦，@xueruini 有没有兴趣用 latex3？像这段很蛋疼的代码
https://github.com/xueruini/thuthesis/blob/0565f4e94ee022bdfca37b225a87f45787456dee/thuthesis.dtx#L2401-L2411
其实用 `\clist_use` 直接就搞定了

**Comment by xueruini** [comment]
不喜欢 expl3，总感觉不像 tex code

**Comment by zepinglee** [comment]
好吧，那我就硬刚 `kvsetkeys` 了。

PS 其实 `xparse` 也算是 `l3packages` bundle 里的。

**Comment by xueruini** [comment]
> PS 其实 `xparse` 也算是 `l3packages` bundle 里的。

是的，xparse 提供的 API 还是比较舒服

**Comment by zepinglee** [comment]
目前实现得差不多了，还有几个问题：

1. `degree-type     = {master, academic},` 这个 comma list 定义起来略麻烦，改成：
```
degree = master,
degree-type = academic,
degree-name = {工学硕士},
```

2. 目前的导言区是：
```
% 所有其它可能用到的包都统一放到这里了，可以根据自己的实际添加或者删除。
\usepackage{thuthesis}

% 定义所有的图片文件在 figures 子目录下
\graphicspath{{figures/}}

% 可以在这里修改配置文件中的定义。导言区可以使用中文。
% \def\myname{薛瑞尼}
```
调用的宏包、配置和定义的命令写到了 `thuthesis.sty`，这个容易让用户混淆，以为也是模板的一部分。（https://github.com/xueruini/thuthesis/issues/428 ）另外一些用法跟用户接口不太一样（比如 `\RequirePackage`）。我建议换成普通的 `.tex` 文件（比如 `thusetup.tex`？）然后 `\input` 进来就好，还有 cover.tex 的内容也可写在这个里面。

**Comment by xueruini** [comment]
> degree-type = academic,
> degree-name = {工学硕士},

这两个总感觉不直观

**Comment by stone-zeng** [comment]
是不是可以直接合并：

```
degree = doctor[-academic]
         doctor[-professional] (有这个吗)
         master[-academic]
         master[-professional]
         bachelor
         postdoc
```

然后 `-` 不写就默认取一个？

**Comment by zepinglee** [comment]
> 是不是可以直接合并：
> 
> ```
> degree = doctor[-academic]
>          doctor[-professional] (有这个吗)
>          master[-academic]
>          master[-professional]
>          bachelor
>          postdoc
> ```
> 
> 然后 `-xxx` 不写就默认取一个？

这个思路也不错！

PS `doctor-professional` 是有的，比如“教育博士”（似乎跟美国的 EdD 差不多？）：
<img width="549" alt="Untitled" src="https://user-images.githubusercontent.com/12290822/61311559-2a668c80-a829-11e9-823c-d04c285a8ebe.png">


另外参见 [学位授予和人才培养学科目录](http://www.moe.gov.cn/s78/A22/xwb_left/moe_833/201804/t20180419_333655.html)：

**Comment by zepinglee** [comment]
目前打算写一个 `\thu@define@key` 来定义key-value 的接口，这也方便以后增加接口。（参考了 `l3keys`）：
```latex
\newif\ifthu@degree@graduate
\thu@define@key{
  degree = {
    choices = {
      doctor = \thu@degree@graduatetrue,
      master = \thu@degree@graduatetrue,
      bachelor,
    },
    default = doctor,
  },
  associate-professor = {
    % default = {},  % default empty
    name = {associate@professor},  % \thu@associate@professor
  },
}
```
这样会自动定义 `\thu@degree` 和 `\thu@associate@professor`，同时定义 `\ifthu@degree@doctor` 等等。

后续还打算实现
```
\thu@define@key{
  math-style = {
    choices = {
      GB,
      ISO,
      TeX,
    },
    default = GB,
  },
}
```

然而我现在被 TeX 宏展开整得打算去研究编译原理了，先挖个坑留着。

**Comment by zepinglee** [comment]
@xueruini 你看下 https://github.com/xueruini/thuthesis/tree/interface 新改的接口怎么样？
