### ISSUE TITLE
bst文件里参数重复配置

### ISSUE THREAD

**Issue by caijun** [xueruini/thuthesis#426]
## 描述问题
使用过程中发现以下参数重复配置，看着怪怪的。

https://github.com/xueruini/thuthesis/blob/master/thuthesis-numeric.bst#L42-L43

https://github.com/xueruini/thuthesis/blob/master/thuthesis-author-year.bst#L47-L48

https://github.com/xueruini/thuthesis/blob/master/thuthesis-author-year.bst#L50-L51

https://github.com/xueruini/thuthesis/blob/master/thuthesis-author-year.bst#L61-L62

**Comment by zepinglee** [comment]
因为这个是从 https://github.com/CTeX-org/gbt7714-bibtex-style 的 dtx 文件生成，所以这些重复的行是 GB/T 7714-2015 的默认配置 + THU 定制。

这个问题已经在 https://github.com/CTeX-org/gbt7714-bibtex-style/commit/81d0ddea7e6744737b1eeaac2a71934a2f70814c 中修复，只是还没搞到这边来。
