### ISSUE TITLE
附录内的章节标题不列入目录

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#427]
> 部分院系（例如自动化系）有额外的格式要求，附录内的章节标题不列入目录。

> 至少我所在的自动化系的本科毕业论文是明确这么要求的，目录中只出现附录的chapter标题，不出现附录中的section及subsection的标题。

> 我们系有官方文件，但其中没有提及我所述的额外要求（是格式审查的2位老师一致口头要求的）。

_Originally posted by @goldsail in https://github.com/xueruini/thuthesis/pull/425#issuecomment-499569692_

**Comment by weiyx15** [comment]
把\section替换成\section*（\subsection, \subsubsectoin同理），就可以使得章节不在目录中显示了。代价就是章节的数字编号也没有了

**Comment by goldsail** [comment]
> 把\section替换成\section*（\subsection, \subsubsectoin同理），就可以使得章节不在目录中显示了。代价就是章节的数字编号也没有了

#425 提供了解决办法，可以既不列入目录，又保留章节的字母和数字编号。
