### ISSUE TITLE
示例文档 (main.pdf)中，有关表格宏包的加载说明

### ISSUE THREAD

**Issue by Angel-halo** [xueruini/thuthesis#428]
## 编译环境
模板版本：v5.5.2

## 描述问题
示例文档 (main.pdf) 第 2 页，“模板中关于表格的宏包有三个:booktabs、array 和 longtabular……”，而模板“thuthesis.cls”中加载的是……“\RequirePackage{longtable}”……
两者指定要加载的宏包有出入，即“longtabular”和“longtable”。

截图：
示例文档 (main.pdf) 第 2 页
![屏幕快照 2019-06-14 下午3 04 29](https://user-images.githubusercontent.com/45824505/59489824-d37e3800-8eb5-11e9-9dce-d1ecf9878a1e.png)
thuthesis.cls 第 85 行
![屏幕快照 2019-06-14 下午3 06 05](https://user-images.githubusercontent.com/45824505/59489898-f9a3d800-8eb5-11e9-9962-6a532adbfa4e.png)

**Comment by stone-zeng** [comment]
应该是 typo，没有 `longtabular` 这个包。

**Comment by Angel-halo** [comment]
MR. Zeng :
	您好
	非常感谢您的帮助
	另外，GitHub上的Issue 是由代码团队Close，还是由提问人Close，我是新手，不明白规则，还望不吝赐教
	谢谢

Wingeen.Wang

**Comment by stone-zeng** [comment]
> 另外，GitHub上的Issue 是由代码团队Close，还是由提问人Close

都可以（当然，我不是 `thuthesis` 的维护者所以我关不了

**Comment by xueruini** [comment]
改了，多谢

**Comment by Angel-halo** [comment]
首先，非常感谢作者及 Mr. Zeng 的帮助
另，还有两个问题，分述如下：
### 1、在1.3.1节，未给出只使用“thuthesis.cls”中，三个表格宏包的示例，亦或说，在基本表格中，未说明使用了“ tabularx ”宏包
示例文档 (main.pdf)中，第2页，1.3.1 基本表格
![屏幕快照 2019-06-14 下午3 04 29](https://user-images.githubusercontent.com/45824505/59503859-14854500-8ed4-11e9-80dd-f50ab09f2b61.png)

示例文件“chap01.tex”，第 71 行，1.3.1 基本表格及1.3.2 复杂表格，均使用了“ tabularx ”宏包
![屏幕快照 2019-06-14 下午6 11 09](https://user-images.githubusercontent.com/45824505/59502221-d7b74f00-8ecf-11e9-9422-edfd4b60f7ac.png)
### 2、示例文档 (main.pdf)中，未明确指出：main.pdf = "thuthesis.cls" + "thuthesis.sty"，在编译出错时，不容易排查，容易把思路引向 main.pdf = "thuthesis.cls" 
论文模版（thuthesis.pdf）中，第 3 页，“thuthesis.sty   为示例文档加载其它宏包”
thuthesis.sty   为示例文档加载其它宏包
![屏幕快照 2019-06-14 下午6 18 59](https://user-images.githubusercontent.com/45824505/59502750-26b1b400-8ed1-11e9-93c2-c42730437578.png)
示例文档 (main.pdf)中，第3页，“thuthesis.sty：常用的包和命令写在这里，减轻主文件的负 担。”
thuthesis.sty ：常用的包和命令写在这里，减轻主文件的负担
![屏幕快照 2019-06-14 下午6 22 23](https://user-images.githubusercontent.com/45824505/59502854-78f2d500-8ed1-11e9-8fb9-24b0be9c1be2.png)
