### ISSUE TITLE
使用模板，编译失败

### ISSUE THREAD

**Issue by bezier2018** [xueruini/thuthesis#429]
## 编译环境
编译的系统：Windows 10 
TeX 发行版：This is XeTeX, Version 3.1415926-2.3-0.9997.5 (MiKTeX 2.9) (preloaded format=xelatex 2019.7.11) 

## 描述问题
模板编译时报错
```
! Undefined control sequence.
l.193 \IfFontExistsTF
                     {XITSMath-Regular.otf}{
```
在下载并安装了“XITSMath-Regular.otf”之后，仍然报错。

**Comment by zepinglee** [comment]
`\IfFontExistsTF` 是 `fontspec` 宏包的，手动安装一下？

**Comment by xueruini** [comment]
fontspec 默认会没装？

**Comment by stone-zeng** [comment]
miktex 比较难说

**Comment by zepinglee** [comment]
我觉得应该显式地列出依赖的宏包：比如 `ctex` 在用 `xelatex` 编译时会自动依赖 `xeCJK`, `fontspec` 等等，但是在模板中如果使用了 `fontspec` 的命令，就应该显式地写 `\RequirePackage{fontspec}`
