### ISSUE TITLE
编译不结束

### ISSUE THREAD

**Issue by ZhangMingdong** [xueruini/thuthesis#430]
我用的环境是Windows10, texstudio和ctex最新版本。编译模板没有错误，但一直在编译中不结束。

**Comment by zepinglee** [comment]
给个截图？

**Comment by ZhangMingdong** [comment]
![图片](https://user-images.githubusercontent.com/16713153/61991471-17528880-b083-11e9-9f12-243d9f70060f.png)

**Comment by ZhangMingdong** [comment]
开始的时候出错提示缺少字体，然后我从网上下载了XITS字体安装。之后就这样了。不过我后来卸载了这个字体依然这样，也没再报错。

**Comment by zepinglee** [comment]
似乎都没有在编译，建议：

1. 路径不要含空格，这里的 `Paper Writing` 改成 `Paper-Writing` 之类的。
2. 使用最新版的 TeX Live，按理是不会出现 XITS 字体的问题的。

**Comment by ZhangMingdong** [comment]
我该用texlive现在可以了，之前用的CTex不行。非常感谢！

**Comment by ZhangMingdong** [comment]
我重新安装了texlive，现在可以了，之前用的CTex不行。非常感谢！

**Comment by zepinglee** [comment]
https://github.com/xueruini/thuthesis/wiki/FAQ#为什么我使用-ctex-292-套件无法编译
