### ISSUE TITLE
目录的章标题字体

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#431]
目前控制目录中的章标题字体有三个选项：
```
%   tocarialchapter,       % 可选（默认：关闭），章目录中使用黑体（这项表示同时打开下面两项）
%   tocarialchapterentry,  % 可选（默认：关闭），单独控制章标题在目录中使用黑体
%   tocarialchapterpage,   % 可选（默认：关闭），单独控制章页码在目录中使用黑体
```
根据 #334 的实现，这几个选项打开时相应的部分使用 `\sffamily`（中文黑体，西文 Arial），关闭时使用 `\rmfamily`（中文宋体，西文 Times New Roman）。默认全部三个选项关闭。

根据研究生《写作指南》：
> 目录中的章标题行采用黑体小四号字……

另外示例的目录格式是：

<img width="700" alt="Screen Shot 2019-09-10 at 12 10 55" src="https://user-images.githubusercontent.com/12290822/64583564-0d32e200-d3c4-11e9-9ead-77293db90c94.png">

其中章页码使用衬线体，标题的中文部分使用黑体，有争议的部分在于如果章标题含有西文应该用衬线体？注意到“第 2 章”的“2”是用了无衬线体（准确滴说是中易黑体，但是显然 Arial 更合理），可以推测章标题的西文也应该用 Arial 才比较搭配，即统一用 `\sffamily`。

而本科生《写作指南》的要求是：
> 目录从第 1 章开始，每 章标题用黑体小四号字……

某广为流传的示例（《气候变化对冬小麦产量影响的 数值模拟研究》）中：
<img width="702" alt="Screen Shot 2019-09-10 at 12 21 25" src="https://user-images.githubusercontent.com/12290822/64583934-85e66e00-d3c5-11e9-8a2c-7b9748cc7aed.png">
其中章标题的数字是用的衬线体，可以推测如果含有西文也应该用衬线体，只需把中文换成黑体 `\heiti` 即可。
 
所以，我建议取消这三个选项，另设一个类似于 `tocarialchapterentry`，只控制章标题内容的西文部分是否使用衬线体，不含“第 2 章”部分，以防有检测格式的老师的要求跟我的推理不一致。

**Comment by xueruini** [comment]
这三个开关也是当时有反馈说各个部分的字体要求不一样才加的。最恼火都是不同学院检查要求不一样，所以不能根据论文类型内置。于是名字都起的很仓促，机制上也没想到更好的办法。
