### ISSUE TITLE
README 的“博士论文”和“博士哲学论文”

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#433]
![2019-09-22 21 54 00](https://user-images.githubusercontent.com/12290822/65388975-84cd1d80-dd83-11e9-89f7-9541aafca4ed.jpg)

README 的“博士论文”和“博士哲学论文”是一个东西吧？同样英文里的 thesis 和 dissertation 也可以直接合并。

by @stone-zeng

**Comment by stone-zeng** [comment]
thesis 和 dissertation 好像还不完全一样……

**Comment by zepinglee** [comment]
dissertation 特指 phd 的学位论文，所我理解的是 thesis 包含 dissertation

**Comment by xueruini** [comment]
博士论文和哲学论文好像是有一年一个文科同学提上来的，说不一样，只不过当时样式要求碰巧一样。代码里好像也没什么区分

**Comment by zepinglee** [comment]
另外“博后”其实不能算是“学位”，所以 `\thusetup{degree = postdoc}` 严格来说不太准确。

**Comment by zepinglee** [comment]
> 博士论文和哲学论文好像是有一年一个文科同学提上来的，说不一样，只不过当时样式要求碰巧一样。代码里好像也没什么区分

可能是早些年文科的格式是分开的？现在研究生的格式要求也没区分，感觉可以去掉这个表述了

**Comment by xueruini** [comment]
> 另外“博后”其实不能算是“学位”，所以 `\thusetup{degree = postdoc}` 严格来说不太准确。

是的，不过这里也不用那么纠结。用个通用的词（比如 type）还不如 `degree` 清晰

**Comment by xueruini** [comment]
> 可能是早些年文科的格式是分开的？现在研究生的格式要求也没区分，感觉可以去掉这个表述了

应该可以去掉了
