### ISSUE TITLE
Package kvsetkeys Error: Undefined key `postdocstartdate'

### ISSUE THREAD

**Issue by zy19970** [xueruini/thuthesis#436]
## 编译环境
编译的系统： Windows 10 
TeX 发行版：TeX Live 2019
模板版本：v5.5.2
模板类型：doctor / master / bachelor

## 描述问题
初始编译出现这个问题，不清楚该怎么解决。
下载的代码没有进行任何更改
截图：

![image](https://user-images.githubusercontent.com/22004812/66382671-390aad00-e9ee-11e9-8d8a-749b39e2c14d.png)

复现上述问题的代码：
太多了。。。

**Comment by zepinglee** [comment]
复现上述问题的代码把 postdocstartdate 那行给出来呀。

另外最近 `\thusetup` 的接口正在进行大规模调整，建议你先跳过封面/题名页内容，或者按照 interface 分支的格式进行填写。

**Comment by zy19970** [comment]
代码没有做任何修改，就是下载下来直接编译，出现了这种问题。

**Comment by xueruini** [comment]
你从 github 下的么？`make cls` 一下呢
