### ISSUE TITLE
生成文档时提示cls模板有数学字体命令错误。

### ISSUE THREAD

**Issue by chong-rong** [xueruini/thuthesis#437]
## 编译环境
编译的系统：Windows 7
TeX 发行版： MikTeX 2.9.4196
模板版本：v5.5.2
模板类型：bachelor

## 描述问题
  生成文档时，显示cls模板中的字体命令错误! 

截图：
```
Undefined control sequence.
l.193 \IfFontExistsTF
                     {XITSMath-Regular.otf}
? 

复现上述问题的代码：
\unimathsetup{
  math-style = ISO,
  bold-style = ISO,
  nabla      = upright,
  partial    = upright,
}
\IfFontExistsTF{XITSMath-Regular.otf}{
  \setmathfont[
    Extension    = .otf,
    BoldFont     = XITSMath-Bold,
    StylisticSet = 8,
  ]{XITSMath-Regular}
  \setmathfont[range={cal,bfcal},StylisticSet=1]{XITSMath-Regular.otf}
}{
  \setmathfont[
    Extension    = .otf,
    BoldFont     = *bold,
    StylisticSet = 8,
  ]{xits-math}
  \setmathfont[range={cal,bfcal},StylisticSet=1]{xits-math.otf}
}
```

**Comment by zepinglee** [comment]
`\IfFontExistsTF` 是 `fontspec` 宏包在 2017 年才开始提供的，升级一下 `fontspec` 宏包就可以了

**Comment by zepinglee** [comment]
改进：在 `\RequirePackage{fontspec}` 后面添加版本日期

**Comment by chong-rong** [comment]
感谢。在win10下用最新版本的MikTeX测试通过了。在win7的32位系统下，可能是MikTeX版本低了，不能自动升级宏包。手动升级宏包过程较繁琐，还在学习中。在 \RequirePackage{fontspec} 后面添加版本日期的方法没理解，在模块文件中没有找到相关语句，是要自己添加吗？添加版本日期又是指？

**Comment by zepinglee** [comment]
> 感谢。在win10下用最新版本的MikTeX测试通过了。在win7的32位系统下，可能是MikTeX版本低了，不能自动升级宏包。手动升级宏包过程较繁琐，还在学习中。在 \RequirePackage{fontspec} 后面添加版本日期的方法没理解，在模块文件中没有找到相关语句，是要自己添加吗？添加版本日期又是指？

那句话是记录给模板开发者的，你就研究在 miktex 中怎么升级宏包吧
