### ISSUE TITLE
直接运行出现以下问题

### ISSUE THREAD

**Issue by liuJwei** [xueruini/thuthesis#438]
## 编译环境
编译的系统：Windows 10 
TeX 发行版：TeX Live 2019
模板版本：v5.3.2
模板类型：doctor

## 描述问题
未修改模板，直接运行出现一下问题

截图：
![image](https://user-images.githubusercontent.com/29155688/70403203-20138c00-1a71-11ea-8d20-28fc5c27b054.png)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
abc
\end{document}
```

**Comment by zepinglee** [comment]
最新版的已经是 v5.5.2

**Comment by liuJwei** [comment]
最新版本的直接运行出现的问题更多，如下
![image](https://user-images.githubusercontent.com/29155688/70409925-5e687580-1a88-11ea-8a4e-ffeb79d586a9.png)
于是我想到了我两年前已经尝试运行过的版本。

以前的版本会修改电脑的一些配置吗？是否和现在的版本存在冲突？

**Comment by zepinglee** [comment]
1. 模板用 GitHub 上最新版；

2. TeX Live 2017 以上的发行版都可以运行，建议使用最新版；

3. 按照文档的说明运行 `xetex thuthesis.dtx` 在工作目录下生成 `.cls` 文件，否则会调用发行版里旧版本的 `thuthesis.cls`，导致冲突。

**Comment by liuJwei** [comment]
非常感谢，这个问题没有了。我关了
