### ISSUE TITLE
公式字体问题

### ISSUE THREAD

**Issue by liuJwei** [xueruini/thuthesis#439]
请问如何将公式字体更改为默认字体？由于以前写的论文里的公式字体都是LaTeX默认字体，配图里使用的公式、字母也是默认字体，现在这样做不到统一字体。非常感谢

**Comment by zepinglee** [comment]
你说的“公式默认字体”应该是指“Computer Modern Math”，由于 v5.5 版本开始使用 `unicode-math` 宏包和 `XITSMath` 字体，你可以将其切换成 Latin Modern Math，然而这会导致：

1. 数学字体跟西文字体不搭配；
2. 一些数学符号的字形不符合 GB(/T) 3101-93。

**Comment by liuJwei** [comment]
> 你说的“公式默认字体”应该是指“Computer Modern Math”，由于 v5.5 版本开始使用 `unicode-math` 宏包和 `XITSMath` 字体，你可以将其切换成 Latin Modern Math，然而这会导致：
> 
> 1. 数学字体跟西文字体不搭配；
> 2. 一些数学符号的字形不符合 GB(/T) 3101-93。

非常感谢，请问在哪个文件哪处进行更改？

**Comment by zepinglee** [comment]
https://github.com/xueruini/thuthesis/blob/0565f4e94ee022bdfca37b225a87f45787456dee/thuthesis.dtx#L1425-L1439

这一段改成
```
\setmathfont{latinmodern-math.otf}
```

**Comment by qzxuhui** [comment]
请问在新的v7.2.3模板下，应该怎么修改才能变成latex默认的字体呢？谢谢。
