### ISSUE TITLE
数学公式报错 Internal error: bad native font flag in `map_char_to_glyph'

### ISSUE THREAD

**Issue by liuJwei** [xueruini/thuthesis#441]
## 编译环境
编译的系统：Windows 10 
TeX 发行版：TeX Live 2017
模板版本：v5.5.2
模板类型：doctor 

## 描述问题
在没有修改添加参考文献的情况下出现这个错误。我只是添加了很多公式(这些公式本身没有问题，都在以前的论文中实现过)，不知道是哪里出现了冲突，希望能够得到帮助，非常感谢。

截图：
![image](https://user-images.githubusercontent.com/29155688/70623055-2adc4580-1c58-11ea-87b7-307d77b351ae.png)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
abc
\end{document}
```

**Comment by zepinglee** [comment]
生成 `main.aux` 的时候就已经出了问题，但是没有显示出来，估计是公式导致的。显示出来的 bibtex 和 xdvipdfmx 的报错无法定位到真正问题。

建议：

1. 清理掉辅助文件后再编译看看；
2. 可以在终端里编译，报错信息比较完整；
3. 报错信息是文本，应该贴上来而不是截图；
4. issue 模板中无关的信息可以删掉。

**Comment by liuJwei** [comment]
非常感谢，已按建议尝试，报错信息如下：
! Internal error: bad native font flag in `map_char_to_glyph'

xdvipdfmx:fatal: File ended prematurely

**Comment by liuJwei** [comment]
定位到了可能出现冲突的地方，这种组合使用不行
\tilde{\mathbf{u}}
尝试过\hat{\mathbf{u}}也是不行

**Comment by zepinglee** [comment]
### 编译环境
编译的系统：Windows 10 
TeX 发行版：TeX Live 2017
模板版本：v5.5.2
模板类型：doctor

### 复现问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
$\tilde{\mathbf{u}}$
$\hat{\mathbf{u}}$
\end{document}
```

### 报错：
```
! Internal error: bad native font flag in `map_char_to_glyph'
```

TeX Live 2017 可以复现，似乎是 xetex 的 bug，在 TeX Live 2019 中已经修复，可以顺利编译：
<img width="90" alt="Screen Shot 2019-12-12 at 11 53 43 AM" src="https://user-images.githubusercontent.com/12290822/70681352-0f178480-1cd6-11ea-9a21-8f3d427d60d7.png">
