### ISSUE TITLE
参考文献中国著者姓名的汉语拼音的拼写不能缩写

### ISSUE THREAD

**Issue by cgcgbcbc** [xueruini/thuthesis#442]
## 编译环境
编译的系统：macOS 10.15
TeX 发行版：TeX Live 2019
模板版本：v5.5.2
模板类型：doctor

## 描述问题
《研究生学位论文写作指南》第 19页要求中国著者姓名的汉语拼音的拼写执行 GB/T 16159—1996 的规定，名字不能缩写，而模板编译的结果是缩写后的

截图：
<img width="681" alt="Screen Shot 2019-12-12 at 19 07 45" src="https://user-images.githubusercontent.com/3320660/70707262-bc0ff280-1d12-11ea-90ed-dd1993d51ff1.png">

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
\bibliographystyle{thuthesis-numeric} 
\bibliography{ref/refs}
\end{document}
```
其中`ref/refs.bib`的内容为
```
@inproceedings{Li,
	author = {Li, Chi and Zhou, Min and Gu, Zuxing and Chen, Guang and Wang, Yuexing and Wu, Jiecheng and Gu, Ming},
	title = {VBSAC: A Value-based Static Analyzer for C},
	booktitle = {Proceedings of the 28th ACM SIGSOFT International Symposium on Software Testing and Analysis},
	series = {ISSTA 2019},
	year = {2019},
	isbn = {978-1-4503-6224-5},
	location = {Beijing, China},
	pages = {382--385},
	numpages = {4},
	url = {http://doi.acm.org/10.1145/3293882.3338998},
	doi = {10.1145/3293882.3338998},
	acmid = {3338998},
	publisher = {ACM},
	address = {New York, NY, USA},
	keywords = {Bug detection, Static analysis, Value-based analysis},
} 
```

**Comment by zepinglee** [comment]
看得真仔细。

1. 《GB/T 16159—1996 汉语拼音正词法基本规则》中未提到汉语拼音人名的缩写。

2. 根据《[GB/T 16159—2012 汉语拼音正词法基本规则](http://www.moe.gov.cn/ewebeditor/uploadfile/2012/08/21/20120821100233165.pdf)》，人名的拼音是可以缩写的。
<img width="843" alt="Screen Shot 2019-12-13 at 8 23 56 AM" src="https://user-images.githubusercontent.com/12290822/70759605-e947b980-1d81-11ea-97e8-d28eb72e8179.png">

3. 《GB/T 7714—2005 文后参考文献著录规则》未提到用汉语拼音书写的人名。

4. 《GB/T 7714—2015 信息与文献 参考文献著录规则》规定“其名可缩写”：
<img width="826" alt="Screen Shot 2019-12-13 at 8 30 21 AM" src="https://user-images.githubusercontent.com/12290822/70759883-cf5aa680-1d82-11ea-9fe9-906f2ca2592f.png">

5. 《[GB/T 28039—2011 中国人名汉语拼音字母拼写规则](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091249368.pdf)》：
<img width="854" alt="Screen Shot 2019-12-13 at 8 37 40 AM" src="https://user-images.githubusercontent.com/12290822/70760192-d7ffac80-1d83-11ea-8cbf-5abab9779bea.png">

6. 《研究生学位论文写作指南》第 19页的规定“中国著者姓名的汉语拼音的拼写执行 GB/T 16159—1996 的规定，名字不能缩写”，应该理解为基于国标的额外规定。

7. 从 BibTeX 实现的角度，对一个西文字母组成的人名，无法自动区分是西文的人名还是汉语拼音的人名。即便能区分，也无法自动判断该著者是否为中国国籍，比如 “Li Feifei”（这个例子也不完全合适，她的正式名字一般都写作 Li Fei-Fei）。

8. 综上所述，只能采用手工的方式进行标注，我目前找到的唯一一种可行的办法是：
```
@inproceedings{Li,
  author = {Li, {\relax Chi} and Zhou, {\relax Min} and Gu, {\relax Zuxing} and Chen, {\relax Guang} and Wang, {\relax Yuexing} and Wu, {\relax Jiecheng} and Gu, {\relax Ming}},
  ...
```
效果截图：
<img width="797" alt="Screen Shot 2019-12-13 at 9 13 11 AM" src="https://user-images.githubusercontent.com/12290822/70761629-ca98f100-1d88-11ea-97a8-fee556af398e.png">

**Comment by xueruini** [comment]
> 2\. 从 BibTeX 实现的角度，对一个西文字母组成的人名，无法自动区分是西文的人名还是汉语拼音的人名。即便能区分，也无法自动判断该著者是否为中国国籍，比如 “Li Feifei”（这个例子也不完全合适，她的正式名字一般都写作 Li Fei-Fei）。

直接无语了。。。

**Comment by cgcgbcbc** [comment]
论文定稿之后我直接把bib换成生成的bbl include到main.tex里手动调，简单粗暴😂

**Comment by zepinglee** [comment]
嗯，这是最简单的办法

**Comment by roastduck** [comment]
是否考虑一律不缩写？标准中缩写均为可选。
