### ISSUE TITLE
页面布局的问题

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#443]
研究生《写作指南》：

> 页边距:上—3.0 厘米，下—3.0 厘米，左—3.0 厘米，右—3.0 厘米，装 订线 0 厘米;
页码范围:普通;
页眉距边界:2.2 厘米，页脚距边界:2.2 厘米。

本科生《写作指南》：

<img width="652" alt="Screen Shot 2019-12-26 at 1 07 34 PM" src="https://user-images.githubusercontent.com/12290822/71459046-b0c3c900-27e0-11ea-83a4-8e8ab728d893.png">

目前的实现是：

https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx#L1299-L1320

```TeX
\geometry{
  a4paper, % 210 * 297mm
  hcentering,
  ignoreall,
  nomarginpar}
\ifthu@bachelor
  \geometry{
    left=32mm,
    headheight=5mm,
    headsep=5mm,
    textheight=227mm,
    bottom=32mm,
    footskip=12mm}
\else
  \geometry{
    left=30mm,
    headheight=5mm,
    headsep=5mm,
    textheight=237mm,
    bottom=29mm,
    footskip=6mm}
\fi
```

有以下几个问题：

1. 本科生的左、右边距为 32mm，跟要求的 3 厘米不符；
2. 研究生的下边距为 29 mm，跟要求的 3.0 厘米不符；
3. 研究生的上边距为 297 - 237 - 29 = 31 mm，跟要求的 3.0 厘米不符；
4. 研究生的页脚距边界 29 - 6 = 23 mm，跟要求的 2.2 厘米不符；
5. 研究生的页眉距边界 31 - 5 - 5 = 21 mm，跟要求的 2.2 厘米不符；另外 `fancyhdr` 的header 是向下对齐的，实际的页眉距边界距离还有出入。

另外建议代码中的数值、单位最好跟《写作指南》中的尽可能接近，这样比对时一目了然，而不必进行计算或单位换算。

**Comment by zepinglee** [comment]
这个不太准啊，这明明是 bug 不是 feature_request

**Comment by xueruini** [comment]
> 有以下几个问题：
> 
> 1. 本科生的左、右边距为 32mm，跟要求的 3 厘米不符；
> 2. 研究生的下边距为 29 mm，跟要求的 3.0 厘米不符；
> 3. 研究生的下边距为 297 - 237 - 29 = 31 mm，跟要求的 3.0 厘米不符；
> 4. 研究生的页脚距边界 29 - 6 = 23 mm，跟要求的 2.2 厘米不符；
> 5. 研究生的页眉距边界 31 - 5 - 5 = 21 mm，跟要求的 2.2 厘米不符；另外 `fancyhdr` 的header 是向下对齐的，实际的页眉距边界距离还有出入。
> 
> 另外建议代码中的数值、单位最好跟《写作指南》中的尽可能接近，这样比对时一目了然，而不必进行计算或单位换算。

是根据 word 效果比对得到的，直接设置规范的数字会有偏差

**Comment by zepinglee** [comment]
用尺子量出来的？我待会去量一下

**Comment by xueruini** [comment]
转成 PDF，调成相同大小的窗口比对的

**Comment by zepinglee** [comment]
我目前没找到在 Word 中把 layout 输出到 pdf 的办法，下图左边是用 \geometry{showframe} 生成的 pdf，右边是学校的 Word 示例：

**Comment by zepinglee** [comment]
我目前没找到在 Word 中把 layout 输出到 pdf 的办法，下图左边是用 \geometry{showframe} 生成的 pdf，右边是学校的 Word 示例：

![Screen Shot 2019-12-28 at 10 44 11 PM](https://user-images.githubusercontent.com/12290822/71545883-9994ff00-29cb-11ea-91b5-ddf86288594b.png)

**Comment by zepinglee** [comment]
我发现两边版心的上边缘是对齐的，但是第一行文字的基线有明显的差别。TeX 处理的法案似乎是尽可能往上怼，而 Word 中第一行的基线会先预留一段距离。所以原来的设置相当于将版心向下平移 1 毫米，应该就是为了补偿这个差异。

另外请教下 @ RuixiZhang42 Word 这里预留的距离是怎么计算的？假设第一行全是中易宋体的汉字，字号 12bp，行距 20bp。这样似乎就可以通过精确的计算进行补偿了。

**Comment by zepinglee** [comment]
这是本科生版心横向的比较，上下是一致的。

![Uploading Screen Shot 2019-12-29 at 12.05.54 AM.png…]()

原来设置 `left=32mm` 应该是加上了左边装订线的 0.2 cm，但是前面设置了 `hcentering` 导致右边距被错误地设为 32mm。
