### ISSUE TITLE
默认 openany？

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#445]
## 描述问题

《研究生学位论文写作指南》第 3 页要求“从‘中文摘要’开始各部分双面印刷，各部分之间不必留空白页。”
而模板默认的选项是 `openany`。

本科生未作规定，但是示例论文《气候变化对冬小麦产量影响的数值模拟研究》的目录中第 2 章是在偶数页，所以也是 `openany`。
<img width="769" alt="Screen Shot 2019-12-27 at 6 27 27 PM" src="https://user-images.githubusercontent.com/12290822/71513740-99670780-28d6-11ea-95db-37800c44653c.png">

**Comment by zepinglee** [comment]
啊现在的默认确实是 `openany`，但是这里的文档没有即时更新：

https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx#L406

我觉得这段文字可以删掉，因为 `openright` 需要用户自己调用，还面临一定的风险，干脆不提了。

**Comment by xueruini** [comment]
文档的确漏了更新。`openright` 还是可以留着

**Comment by xueruini** [comment]
我看你已经更新了文档
