### ISSUE TITLE
下载MacTex安装后找不到该程序

### ISSUE THREAD

**Issue by LIGHTNINGGG0423** [xueruini/thuthesis#447]
您好，我在https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/mac/mactex/ 的路径下，下载并安装了MaxTex.pkg，安装过程中提示我占用了6.96G的内存，但是之后只能在应用程序中找到BibDesk、LaTeXiT、TeX Live Utility、TexShop这四个程序，而它们加起来才约100M，且除了TeXshop能编译（但是找不到thuthesis包之类的），看不到指导文件中的各种功能。请问是应该有MacTex这个程序吗？怎么下载CTex以编译中文呢？多占用的6.8G是为什么呢？我已经下载了thuthesis的文件，但具体该怎么用呢？谢谢！

**Comment by zepinglee** [comment]
> 安装过程中提示我占用了6.96G的内存
6.96G 是硬盘，不是内存。

> 但是之后只能在应用程序中找到BibDesk、LaTeXiT、TeX Live Utility、TexShop这四个程序，而它们加起来才约100M
MacTeX的核心程序在 `/usr/local/texlive`，而且主要是命令行下使用的，TeXShop 等程序只是附带的编辑器（其实不怎么好用）。

> 请问是应该有MacTex这个程序吗？
MacTeX 是一套东西，不存在叫 MacTeX 的程序。

> 怎么下载CTex以编译中文呢？
不要用 CTeX 套装。

> 我已经下载了thuthesis的文件，但具体该怎么用呢？
看来你是完全的新鸟，建议找实验室用过 LaTeX 的师兄进行指导，或者阅读 [lshort-zh-cn](http://mirrors.ctan.org/info/lshort/chinese/lshort-zh-cn.pdf)。

**Comment by LIGHTNINGGG0423** [comment]
> > 安装过程中提示我占用了6.96G的内存
> 
> 6.96G 是硬盘，不是内存。
> 
> > 但是之后只能在应用程序中找到BibDesk、LaTeXiT、TeX Live Utility、TexShop这四个程序，而它们加起来才约100M
> 
> MacTeX的核心程序在 `/usr/local/texlive`，而且主要是命令行下使用的，TeXShop 等程序只是附带的编辑器（其实不怎么好用）。
> 
> > 请问是应该有MacTex这个程序吗？
> 
> MacTeX 是一套东西，不存在叫 MacTeX 的程序。
> 
> > 怎么下载CTex以编译中文呢？
> 
> 不要用 CTeX 套装。
> 
> > 我已经下载了thuthesis的文件，但具体该怎么用呢？
> 
> 看来你是完全的新鸟，建议找实验室用过 LaTeX 的师兄进行指导，或者阅读 [lshort-zh-cn](http://mirrors.ctan.org/info/lshort/chinese/lshort-zh-cn.pdf)。

谢谢～
