### ISSUE TITLE
至此主要的代码工作已经完成了，后续还需要：

### ISSUE THREAD

**Issue by xueruini** [xueruini/thuthesis#448]
4. 发布 Overleaf 的版本

_Originally posted by @zepinglee in https://github.com/xueruini/thuthesis/pull/434#issuecomment-569234741_

**Comment by zepinglee** [comment]
Overleaf 有 import/sync from GitHub 的功能，不必上传 zip

**Comment by xueruini** [comment]
> Overleaf 有 import/sync from GitHub 的功能，不必上传 zip

这个好像是高级账号才有，昨晚手动传了一个

**Comment by zepinglee** [comment]
> > Overleaf 有 import/sync from GitHub 的功能，不必上传 zip
> 
> 这个好像是高级账号才有，昨晚手动传了一个

不会呀，免费的就有、

<img width="228" alt="Screen Shot 2020-01-05 at 5 42 28 PM" src="https://user-images.githubusercontent.com/12290822/71777997-c6a46b80-2fe2-11ea-815a-076421e7ccfb.png">

**Comment by xueruini** [comment]
你点进去看
