### ISSUE TITLE
目录和书签中的参考文献、致谢、声明、个人简历等链接有问题

### ISSUE THREAD

**Issue by toylsc** [xueruini/thuthesis#453]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
模板版本：v6.0.0
模板类型：doctor

## 描述问题

最新版的模板（v6.0.0）生成的文档中，最后部分的参考文献、致谢、声明、个人简历等目录和书签中对应的链接，都导向了前一个部分的内容了，如截图所示，点击“致谢”跳转到的是“参考文献”部分。v6.0.0 release 默认自带的编译好的 main.pdf 里面就存在这个问题，重新编译还是存在这个问题。

截图：

![image](https://user-images.githubusercontent.com/19552049/72678498-80bacd80-3ae1-11ea-8c90-c42bb4fb8c38.png)

**Comment by zepinglee** [comment]
啊，没错；

上次为了依赖 hyperref 导致的

**Comment by wxsthuee** [comment]
同样的问题

**Comment by zepinglee** [comment]
https://github.com/xueruini/thuthesis/blob/dd5d2b0c3a71b80eecc81180148a5fbd46490c48/thuthesis.dtx#L2062-L2066

@xueruini 这段描述已经过时：

> 本科论文要求所有的章都出现在目录里，比如摘要、Abstract、主要符号表等，所以可以简单的扩展默认\cs{chapter*} 实现这个目的。但是研究生又不要这些出现在目录中……

本科生论文样例《气候变化对冬小麦产量影响的数值模拟研究》的目录中不包含摘要、Abstract。


> 但是研究生……，而且致谢和声明部分的章名、页眉和目录都不同

致谢和声明两部分的章名、页眉和目录是相同的，都是两字之间空一字宽。

**Comment by zepinglee** [comment]
@xueruini 我搞到哪个分支？
