### ISSUE TITLE
生成的PDF文件只有一级目录

### ISSUE THREAD

**Issue by wxsthuee** [xueruini/thuthesis#457]
## 编译环境
编译的系统：macOS 10.15
TeX 发行版：MacTeX 2019
模板版本：v6.0.0
模板类型：doctor

## 描述问题
生成的PDF文件只有一级目录，没有二级目录了。
之前版本的模版是有的。

截图：
<img width="102" alt="Snipaste_2020-02-02_20-47-56" src="https://user-images.githubusercontent.com/6491355/73608389-5434a480-45fd-11ea-8273-5ff2cc5c6572.png">

**Comment by zepinglee** [comment]
可以复现你的问题

**Comment by zepinglee** [comment]
这是因为附录中的节标题不加入目录，需要在附录处将 `tocdepth` 设为 0，然而 `hyperref` 的 pdf 书签也默认使用 `tocdepth`，所以导致全局的书签只有一级。

解决办法：手动设置 `bookmarksdepth = 2`。

**Comment by zepinglee** [comment]
@xueruini 我 push 到 `v6.0.1-dev` 了，建议尽快把两个 hot fix（还有 #453 的）merge 到 `master`。`v6.0.1-dev` 只保留实验性的内容。

**Comment by xueruini** [comment]
看到了。`6.0.1-dev` 其它部分也没什么大改动，就一起合了
