### ISSUE TITLE
正文里，“玥”、“昉”汉字编译之后不显示

### ISSUE THREAD

**Issue by wxsthuee** [xueruini/thuthesis#459]
## 编译环境
编译的系统：macOS 10.15
TeX 发行版：MacTeX 2019
模板版本：v6.0.0
模板类型：doctor

## 描述问题
正文里，“玥”、“昉”汉字编译之后不显示，但是宋体字库里有这两个字。

下面截图是“致谢”章节中，输入“感谢我的朋友张玥、杨昉等，他们”的编译结果：

<img width="222" alt="Snipaste_2020-02-03_13-56-27" src="https://user-images.githubusercontent.com/6491355/73629588-9e199b00-468e-11ea-86a9-94f8a8156255.png">

已安装打包的所有字体，依然没有效果lol

**Comment by wxsthuee** [comment]
> ## 编译环境
> 编译的系统：macOS 10.15
> TeX 发行版：MacTeX 2019
> 模板版本：v6.0.0
> 模板类型：doctor
> 
> ## 描述问题
> 正文里，“玥”、“昉”汉字编译之后不显示，但是宋体字库里有这两个字。
> 
> 下面截图是“致谢”章节中，输入“感谢我的朋友张玥、杨昉等，他们”的编译结果：
> 
> <img alt="Snipaste_2020-02-03_13-56-27" width="222" src="https://user-images.githubusercontent.com/6491355/73629588-9e199b00-468e-11ea-86a9-94f8a8156255.png">

**Comment by zepinglee** [comment]
这是因为 `ctex` 宏包更新不及时，在 macOS 10.15 下将系统检测为 Linux，从而调用 Fandol 字库导致缺字，见 https://github.com/CTeX-org/ctex-kit/issues/455 。

解决办法，在 `\documentclass[]{thuthesis}` 显式设置 `fontset=mac`。

另外，macOS 系统自带的是华文字体，与学校的示例（中易字体）略有区别，建议在提交终稿时在 Windows 字体的环境中编译，并设置 `fontset=windows`。

**Comment by wxsthuee** [comment]
> 这是因为 `ctex` 宏包更新不及时，在 macOS 10.15 下将系统检测为 Linux，从而调用 Fandol 字库导致缺字，见 [CTeX-org/ctex-kit#455](https://github.com/CTeX-org/ctex-kit/issues/455) 。
> 
> 解决办法，在 `\documentclass[]{thuthesis}` 显式设置 `fontset=mac`。
> 
> 另外，macOS 系统自带的是华文字体，与学校的示例（中易字体）略有区别，建议在提交终稿时在 Windows 字体的环境中编译，并设置 `fontset=windows`。

问题解决了！感谢大佬！！！

**Comment by wxsthuee** [comment]
> 这是因为 `ctex` 宏包更新不及时，在 macOS 10.15 下将系统检测为 Linux，从而调用 Fandol 字库导致缺字，见 [CTeX-org/ctex-kit#455](https://github.com/CTeX-org/ctex-kit/issues/455) 。
> 
> 解决办法，在 `\documentclass[]{thuthesis}` 显式设置 `fontset=mac`。
> 
> 另外，macOS 系统自带的是华文字体，与学校的示例（中易字体）略有区别，建议在提交终稿时在 Windows 字体的环境中编译，并设置 `fontset=windows`。

还是想问一下，有没有能在mac下直接解决的方案😂

**Comment by zepinglee** [comment]
> 还是想问一下，有没有能在mac下直接解决的方案😂

`fontset=mac`?

**Comment by stone-zeng** [comment]
如果装了 office，可以手动调用 windows 的中易字库，但会比较麻烦。

**Comment by wxsthuee** [comment]
> > 还是想问一下，有没有能在mac下直接解决的方案😂
> 
> `fontset=mac`?

我试了一下，华文字体的区别还是蛮大的，不知道能不能通过。
怎么调用Windows的字库呢？

**Comment by wxsthuee** [comment]
> 如果装了 office，可以手动调用 windows 的中易字库，但会比较麻烦。

我装了😂求指导调用Windows字库

**Comment by zepinglee** [comment]
@xueruini 要不要绕过 `ctex` 在 `thuthesis` 层面处理 `fontset`？这样可以加个选项 `fontset=macword`

**Comment by xueruini** [comment]
> @xueruini 要不要绕过 `ctex` 在 `thuthesis` 层面处理 `fontset`？这样可以加个选项 `fontset=macword`

刚才 `make dist` 提示说 simsun 找不到，上次清楚的记得用了 `fontset` 是过了的，检查后发现被放到了`/Applications/Microsoft Word.app/Contents/Resources/DFonts`，可能是最近 office 升级文件又挪地方了，只好手动装 sim*.ttf。这样来看 `macword` 也不一定能通用，不能根本解决问题。还是人肉装对应字体稳妥一点。

**Comment by zepinglee** [comment]
> 刚才 `make dist` 提示说 simsun 找不到，上次清楚的记得用了 `fontset` 是过了的，检查后发现被放到了`/Applications/Microsoft Word.app/Contents/Resources/DFonts`，可能是最近 office 升级文件又挪地方了，只好手动装 sim*.ttf。这样来看 `macword` 也不一定能通用，不能根本解决问题。还是人肉装对应字体稳妥一点。

好像没变吧，这篇《[在 LaTeX 中使用 OpenType 字体（二） | stone-zeng.github.io](https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/ )》是写在 2019-07-06。你调用字体是用字体名还是文件名？

**Comment by xueruini** [comment]
> 好像没变吧，这篇《[在 LaTeX 中使用 OpenType 字体（二） | stone-zeng.github.io](https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/)》是写在 2019-07-06。你调用字体是用字体名还是文件名？

```latex
\documentclass[fontset=windows]{thuthesis}
```

这样出来的效果更接近 word。之前  `fc-list`  都找不到 sim*

**Comment by wxsthuee** [comment]
> > 还是想问一下，有没有能在mac下直接解决的方案😂
> 
> `fontset=mac`?

我发现在macOS下可以直接设置 fontset=windows，字体是对的

**Comment by xueruini** [comment]
> 我发现在macOS下可以直接设置 fontset=windows，字体是对的

恩，它找到 office 那些字体了。我前段时间是 OK 的，昨天就报错了。所以有了上面的讨论

**Comment by stone-zeng** [comment]
XeTeX 只能找到字体册里面（需要用**字体名**调用）的字体，依靠 kpathsea 来读取文件（因此要用**文件名**），Office 带的字体应该没办法直接调。

**Comment by zepinglee** [comment]
> 我发现在macOS下可以直接设置 fontset=windows，字体是对的

那是因为你把 Microsoft Office 的字体安装到了字体册

**Comment by xueruini** [comment]
> 那是因为你把 Microsoft Office 的字体安装到了字体册

这个判断我有点犹豫的。我一直是 macos，这几天就遇到了诡异现象。

示例文档里有几个字需要用 simsun 来显示，所以编译 6.0.0 时临时改成了 `fontset=windows`，当时直接就过了，因为装了 office，以为是自动找到了字体，就没太在意。昨天编译 6.0.1 自然又改成了 windows，结果提示找不到字体。这期间升级过 Office

![image](https://user-images.githubusercontent.com/1863/73728612-a0ebbd00-476e-11ea-8d47-33c3efcdbc31.png)

也 `tlmgr update` 过，但从没有主动安装过 sim* 字体，也没有删除过任何字体。

**Comment by zepinglee** [comment]
> 任何

你检查下 `~/Library/Fonts`

**Comment by xueruini** [comment]
> 你检查下 `~/Library/Fonts`

昨天报错的时候检查过，没有这些字体。后来手动装了，就 ok 了。

6.0.0 编译为什么能过，没想通
