### ISSUE TITLE
checkmark不显示

### ISSUE THREAD

**Issue by zjhthu** [xueruini/thuthesis#461]
## 编译环境
编译的系统：Overleaf

在table中使用\checkmark（✔️），但并没有显示出来

截图：
![image](https://user-images.githubusercontent.com/6079234/73826789-55eaac00-4839-11ea-95b0-e94f66cd0b9f.png)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
\begin{table}[]
\begin{center}
\small
\begin{tabular}{c|cc|ccc}
\hline
threshold              & S & L         & mAP{5}(\%)        & mAP{10}(\%)       & mAP{20}(\%)       \\ \hline
0.01                   & \checkmark &            \\ \hline
\multirow{2}{*}{0.001} & \checkmark &  \\
                      &   & \checkmark          \\ \hline
\end{tabular}
\end{center}
\end{table}
\end{document}
```
如果使用包\usepackage{amssymb}，overleaf编译会过不了。

**Comment by zepinglee** [comment]
原始的 `amssymb` 在文本模式和数学模式都可以使用 `\checkmark`。但是 `thuthesis` 使用了 `unicode-math`，该宏包定义的 `\checkmark` 只能用于数学模式。所以临时的解决方案是改成 `$\checkmark$`。

**Comment by zjhthu** [comment]
解决了，谢谢！

**Comment by zepinglee** [comment]
另外 `center` 会导致额外的垂直距离，建议换成 `\centering` 命令，参考示例文档。

**Comment by zjhthu** [comment]
好的，谢谢~

**Comment by zepinglee** [comment]
在模板中可以暂时
```tex
\AtBeginDocument{%
   \renewcommand\checkmark{\ensuremath{✓}}%
 }
```
这样可以在 text mode 中用 `\checkmark` 命令，但是直接用 `✓` 还是不行，因为 TeX Gyre Termes 和 Times New Roman 没有“✓”（U+2713）的字形。

更好的方案是 fallback 到 XITS。

另外 Linux 下的西文衬线字体可以换成 XITS，比 TeX Gyre Termes 字形多一些。

**Comment by zjhthu** [comment]
OK~
