### ISSUE TITLE
参考文献的引用，连续的两个序号是否可以改用逗号连接而不用连字符？

### ISSUE THREAD

**Issue by mindest** [xueruini/thuthesis#463]
参考文献引用的序号，多个连续的文献序号总是以 `-` 连接 (例如 [12-15])，但是当连续的序号只有两个时，好像一般习惯直接用逗号 `,` (如 [12,13])，而不用连字符 (如 [12-13])，请问这种情况应该如何处理？natbib 宏包对仅两个连续序号应该也是用逗号的，不知道模板做了什么改动？

**Comment by zepinglee** [comment]
研究生《写作指南》第 17 页：
<img width="655" alt="Screen Shot 2020-02-11 at 12 03 17 AM" src="https://user-images.githubusercontent.com/12290822/74166705-fdb11100-4c61-11ea-97b2-b963428d5ab7.png">

**Comment by mindest** [comment]
> 研究生《写作指南》第 17 页：
> <img alt="Screen Shot 2020-02-11 at 12 03 17 AM" width="655" src="https://user-images.githubusercontent.com/12290822/74166705-fdb11100-4c61-11ea-97b2-b963428d5ab7.png">

感谢！因为还没收到最新的写作指南，看以往师兄的论文都是用的逗号…我应该找找以往的指南看一下的

**Comment by zepinglee** [comment]
> 感谢！因为还没收到最新的写作指南，看以往师兄的论文都是用的逗号…我应该找找以往的指南看一下的

《写作指南》在研究生院的官网有，http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=001050603&parentColumnId=0010506&itemSeq=5365

**Comment by mindest** [comment]
> > 感谢！因为还没收到最新的写作指南，看以往师兄的论文都是用的逗号…我应该找找以往的指南看一下的
> 
> 《写作指南》在研究生院的官网有，http://yjsy.cic.tsinghua.edu.cn/docinfo/board/boarddetail.jsp?columnId=001050603&parentColumnId=0010506&itemSeq=5365

谢谢~
