### ISSUE TITLE
本科生阅读调研报告的引用不正确

### ISSUE THREAD

**Issue by WhirlFirst** [xueruini/thuthesis#465]
## 编译环境
编译的系统：macOS 10.14 / Overleaf
TeX 发行版：MacTeX 2019
模板版本：v6.0.1
模板类型：bachelor

## 描述问题
无论是在本地或者Overleaf上，本科生调研阅读报告的引用似乎都有问题

截图：
本地：
![image](https://user-images.githubusercontent.com/23123386/74599737-fb312b80-5054-11ea-8384-fbe5748f4ab8.png)
overleaf:
![image](https://user-images.githubusercontent.com/23123386/74599745-11d78280-5055-11ea-8870-874a56c41360.png)

复现上述问题的代码：
```TeX
\input{data/appendix-survey} 


\cite{abrahams99tex,salomon1995advanced}.
```

**Comment by zepinglee** [comment]
后面的 `\cite` 要放到新的 chapter 里

**Comment by zepinglee** [comment]
至少要在 `data/appendix-survey.tex` 里的 `survey` 环境后接一个 `\clearpage`

**Comment by WhirlFirst** [comment]
> 至少要在 `data/appendix-survey.tex` 里的 `survey` 环境后接一个 `\clearpage`

对不起，没有太明白什么意思。可能是我说的有问题，我那2句代码是在两个文件里的，第一句在main.tex里，我相当于取消注释而已。第二句本来就在`data/appendix-survey.tex`里，是在示例文件第一段的最后一句上。

此外，我还发现在overleaf上调研报告只能够编译两页，之后的内容不会在PDF中出现

**Comment by WhirlFirst** [comment]
奇怪的是在`data/appendix-survey.tex`中只有在引用`appendix.bib`时，才会出现引用失败的问题，引用`refs.bib`时是正常的

**Comment by zepinglee** [comment]
> > 至少要在 `data/appendix-survey.tex` 里的 `survey` 环境后接一个 `\clearpage`
> 
> 对不起，没有太明白什么意思。可能是我说的有问题，我那2句代码是在两个文件里的，第一句在main.tex里，我相当于取消注释而已。第二句本来就在`data/appendix-survey.tex`里，是在示例文件第一段的最后一句上。
> 
> 此外，我还发现在overleaf上调研报告只能够编译两页，之后的内容不会在PDF中出现

1. 你的第二个截图里显示编译中断了没有完成，但是截图 1 中并没有报错信息。

2. `main.tex` 里的 `\input{data/appendix}` 要注释掉，这三个 `data/appendix*.tex` 的内容有冲突。

**Comment by zepinglee** [comment]
`survey` 环境中为了处理参考文献使用了非常复杂的机制（`bibunits`）

**Comment by WhirlFirst** [comment]
> 1. 你的第二个截图里显示编译中断了没有完成，但是截图 1 中并没有报错信息。
> 2. `main.tex` 里的 `\input{data/appendix}` 要注释掉，这三个 `data/appendix*.tex` 的内容有冲突。

好的谢谢，是我的问题，我以为'appendix*.tex'文件是可以同时存在的。只启用一个后，问题解决了。谢谢

**Comment by zepinglee** [comment]
ok，我修改一下 `data/appendix.tex` 尽量避免冲突
