### ISSUE TITLE
如何用bibtex添加参考文献

### ISSUE THREAD

**Issue by InitialV** [xueruini/thuthesis#466]
## 编译环境
编译的系统：Windows10
TeX 发行版：TeX Live 2019
模板版本：v6.0.0
模板类型：master

请问应该如何添加参考文献？

我尝试了先在`refs.bib`中添加我需要用到的一个bibtex item (Google scholar生成的):

```
@book{kloeden2013numerical,
  title={Numerical solution of stochastic differential equations},
  author={Kloeden, Peter E and Platen, Eckhard},
  volume={23},
  year={2013},
  publisher={Springer Science \& Business Media},
}
```

在正文的`tex`中，我在相应位置添加了引用`~\cite{kloeden2013numerical}`。然后按照我之前的经验，先编译一遍`tex`，会生成`refs.aux`，再用`BibTeX`编译`refs.bib`，再编译两遍`tex`就好了。但是我编译完第一遍`tex`之后，好像`ref/`目录下并没有出现`refs.aux`，所以就无法用`BibTeX`来编译`refs.bib`。我去查看`main.bbl`，里面也确实没有我刚加的这个参考文献的`\bibitem`。

可能因为我还不太熟悉这个模板，所以有些基本的问题还没搞得清楚。在文档中也还没找到解决方案。希望有哪位能够指点一下如何在这个模板中用BibTeX来添加参考文献。谢谢！

**Comment by InitialV** [comment]
不好意思不好意思。。看来是之前错误尝试太多，搞乱了一些辅助文件。
我刚刚`make clean` + `make thesis`就弄好了。

**Comment by zepinglee** [comment]
1. 通常用 BibTeX 编译的是 `main.aux` 不是 `*.bib`。

2. `thuthesis` 从 v6.0 开始使用 `bibunits` 的机制（为了处理本科生调研报告的参考文献），所以会生成 `bu.aux` 的文件，需要用 BibTeX 编译这个 `bu.aux`。

另外建议用 `latexmk` 编译 `main.tex` 自动调用 BibTeX 编译正确的文件。

**Comment by zepinglee** [comment]
我之前试图把 `bu.aux` 跟 `main.aux` 合并到一起，但是需要魔改很多内容。

记录一下以后再实现吧。
