### ISSUE TITLE
本科生要求的索引无内容

### ISSUE THREAD

**Issue by Ecthelion-F** [xueruini/thuthesis#467]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
模板版本：v6.0.1
模板类型：bachelor

## 描述问题
下载模板后将main.tex中的索引打开后用xe->bib->xe->xe编译，产生的文档仅有三个索引标题而无具体内容

截图：
<img width="483" alt="1" src="https://user-images.githubusercontent.com/60468868/74604509-ad223380-50f9-11ea-9401-f08e5d5624c0.PNG">

复现上述问题的代码：
```TeX
%% 本科生要求的几个索引。
 \listoffigures    % 插图索引
 \listoftables     % 表格索引
 \listofequations  % 公式索引
```

**Comment by xueruini** [comment]
`\tableofcontents` 之后的 `\listof*` 都失效了，正在看

**Comment by xueruini** [comment]
fixed by https://github.com/xueruini/thuthesis/pull/462/commits/1db973f3abcb8bb01dfc794c49f87a7dd035a022

**Comment by Ecthelion-F** [comment]
成功了，感谢

**Comment by xueruini** [comment]
没有类似 `\appendix` 的时机来将临时 `tocdepth` 写入目录文件，只能在读写目录文件前恢复。这个方法的一个问题是如果在 `\appendix` 后面插入 `\listofxxx`，就会破坏 `\appendix` 在目录里的显示。
