### ISSUE TITLE
关于参考文献的标题后缀问题

### ISSUE THREAD

**Issue by hdlxjm** [xueruini/thuthesis#469]
我在之前毕业的师兄的论文中，发现有的论文的参考文献标题后缀会带有[M]或者[J]。我在使用最新版本模板的时候，发现好像没有这个设置，请问这个格式是必要的吗？需要怎么设置？

**Comment by zepinglee** [comment]
《研究生学位论文写作指南》

> 电子文献类型和载体类型标志是必备的著录项目。非电子文献类型可以省略……
学位论文类型的文献必须明确标注。

**Comment by hdlxjm** [comment]
请问这个需要怎么设置，是自己在标题后面加上后缀吗？

**Comment by zepinglee** [comment]
1. 学校官方的《写作指南》和 Word 版示例中都没有加；
2. 我个人认为这个信息比较冗余，所以在新版中故意去掉的。
