### ISSUE TITLE
编译出来的 PDF 字体看起来不协调

### ISSUE THREAD

**Issue by toylsc** [xueruini/thuthesis#474]
## 编译环境
编译的系统： Windows 10
TeX 发行版：TeX Live 2019
模板版本：v6.0.1 和 v6.0.2
模板类型：doctor / master / bachelor

## 描述问题
编译出来的 PDF 文档在 100% 大小模式下看起来有点不协调，个别字看起来有点突兀，哪怕是编译模板自带的 main.tex 出来的 PDF 也有这个问题，没有模板自带的 main.pdf 看起来效果整体统一。
如下截图对比可以看出来，例如“**字子瞻**”、“**嘉佑进士**”等处。v6.0.1 和 v6.0.2 都是这样，不知道是操作系统还是 Tex Live 的问题。

### 重新编译实例 main.tex 效果如下，可以看到许多字好像大小和粗细不协调：

![image](https://user-images.githubusercontent.com/19552049/75251954-9fb22b00-5816-11ea-93b6-093f93f02da2.png)

---

### 模板自带的 main.pdf 效果如下，可以看到效果整体很舒服：

![image](https://user-images.githubusercontent.com/19552049/75251979-af317400-5816-11ea-8bc0-5db050fa453e.png)

**Comment by stone-zeng** [comment]
6.0.2 和 6.0.1 的 `main.pdf` 里面所用字体虽然都是中易，但确实略有区别，貌似是版本号不同？

6.0.1：

![image](https://user-images.githubusercontent.com/18233088/75247514-0df1f000-580d-11ea-94c4-08f976101e13.png)

6.0.2：

![image](https://user-images.githubusercontent.com/18233088/75247517-10ece080-580d-11ea-8a66-8b890d9e63f5.png)

**Comment by toylsc** [comment]
我自己重新编译出来的 pdf 和模板自带的看起来不同，难道是模板自带的 pdf 是在 linux 或 mac 下编译的？
自己编译出来的 pdf 效果差的原因是某些字看起来笔画粗细和大小与其他字不协调。

**Comment by xueruini** [comment]
> 6.0.2 和 6.0.1 的 `main.pdf` 里面所用字体虽然都是中易，但确实略有区别，貌似是版本号不同？

两个电脑上编的，倒是没注意字体版本。眼睛这么犀利，这两个图没看出差别来

**Comment by toylsc** [comment]
> > 6.0.2 和 6.0.1 的 `main.pdf` 里面所用字体虽然都是中易，但确实略有区别，貌似是版本号不同？
> 
> 两个电脑上编的，倒是没注意字体版本。眼睛这么犀利，这两个图没看出差别来

我这个自己编译的 pdf 看起来区别挺大的，在 1080 分辨率 100% 大小下一眼望去感觉不同的字笔画粗细和大小不一样，很不协调，没有模板自带的看起来匀称统一，这是不是我自己的电脑问题而不是模板的问题？

**Comment by stone-zeng** [comment]
Hinting 问题，换个分辨率高的屏幕就好了（误

当然，不会影响打印出来的结果，这点东西无关紧要啦。

**Comment by toylsc** [comment]
> Hinting 问题，换个分辨率高的屏幕就好了（误
> 
> 当然，不会影响打印出来的结果，这点东西无关紧要啦。

想要模板自带的 PDF 那种效果该怎么办，毕竟我自己编译出来的确实看起来花花一片不协调，在电脑上看起来不舒服，送审以后让别人看起来可能也不太好。如果换操作系统或改变设置能解决的话就好了。

**Comment by zepinglee** [comment]
> > 6.0.2 和 6.0.1 的 `main.pdf` 里面所用字体虽然都是中易，但确实略有区别，貌似是版本号不同？
> 
> 两个电脑上编的，倒是没注意字体版本。眼睛这么犀利，这两个图没看出差别来

我也看不出来……LS 是做字体的

**Comment by zepinglee** [comment]
> 想要模板自带的 PDF 那种效果该怎么办，毕竟我自己编译出来的确实看起来花花一片不协调，在电脑上看起来不舒服，送审以后让别人看起来可能也不太好。如果换操作系统或改变设置能解决的话就好了。

你用的是什么 PDF 阅读器？

**Comment by toylsc** [comment]
> 你用的是什么 PDF 阅读器？

Adobe Acrobat XI 11.0.0 破解版的，还可以直接编辑 PDF 文件。我编辑两种 PDF 文件发现都是宋体 12 号，但就是输入文字后显示效果不一样，一个笔画较粗整体显示很匀称，一个不同字粗细看起来不一样不协调。
我对重新编译的 pdf 用 ps2pdf 又做了一次转换“ps2pdf main.pdf main_new.pdf” 发现字体显示也匀称了，只是相比于原版自带的都变成了较细的笔画，如下图所示

![image](https://user-images.githubusercontent.com/19552049/75314578-1a248e80-589b-11ea-9a9f-ba431f0e9ac3.png)

**Comment by stone-zeng** [comment]
（劝你放弃，hinting 的锅基本没什么好解决的办法

**Comment by zepinglee** [comment]
劝你放弃 +1，PDF 渲染的锅。

就算“送审以后让别人看起来可能也不太好”，你也可以打印一份出来。

**Comment by toylsc** [comment]
> 劝你放弃 +1，PDF 渲染的锅。
> 
> 就算“送审以后让别人看起来可能也不太好”，你也可以打印一份出来。

好吧，我再试试其它系统怎么样，如果能知道模板自带的 PDF 是在什么环境下生成的就好了。

**Comment by zepinglee** [comment]
> > 劝你放弃 +1，PDF 渲染的锅。
> > 就算“送审以后让别人看起来可能也不太好”，你也可以打印一份出来。
> 
> 好吧，我再试试其它系统怎么样，如果能知道模板自带的 PDF 是在什么环境下生成的就好了。

附给你一份 macOS 刚编译的： 
[main.pdf](https://github.com/xueruini/thuthesis/files/4253624/main.pdf)

以及截图： 
<img width="660" alt="ScreenShot" src="https://user-images.githubusercontent.com/12290822/75316278-d8e2ad80-589f-11ea-8dc8-0228c3627ea2.png">

以及用 macOS 调用 Windows 字体编译的：
[main.pdf](https://github.com/xueruini/thuthesis/files/4253655/main.pdf)

<img width="656" alt="ScreenShot" src="https://user-images.githubusercontent.com/12290822/75316751-20b60480-58a1-11ea-96db-56b7610c2ab7.png">

**Comment by zepinglee** [comment]
@xueruini 话说示例文档中的隶书和幼圆可以去掉吗？mac 版 ms-office word 没这俩字体，所以每次都得删一遍。

**Comment by toylsc** [comment]
> 附给你一份 macOS 刚编译的：
> 以及截图：
> 以及用 macOS 调用 Windows 字体编译的：

多谢，看来 mac 下面编译的显示没问题

**Comment by stone-zeng** [comment]
主要其实是因为 mac 基本都是 retina，你用 windows 配个好点的屏幕一样就没这么多问题了……

**Comment by toylsc** [comment]
> 主要其实是因为 mac 基本都是 retina，你用 windows 配个好点的屏幕一样就没这么多问题了……

原来屏幕分辨率和生成的 PDF 文件有关系啊？我之前以为程序一样、字体文件一样，生成的 pdf 文件应该一样，看来 1080 的分辨率还是有点小。。。

**Comment by zepinglee** [comment]
> > 主要其实是因为 mac 基本都是 retina，你用 windows 配个好点的屏幕一样就没这么多问题了……
> 
> 原来屏幕分辨率和生成的 PDF 文件有关系啊？我之前以为程序一样、字体文件一样，生成的 pdf 文件应该一样，看来 1080 的分辨率还是有点小。。。

是 PDF 阅读器的问题，不是生成 PDF 时的问题

**Comment by stone-zeng** [comment]
adobe 的软件很多会覆盖系统默认的字体渲染，你换 edge 或者其他啥效果可能都不一样。毕竟不管是什么样的字，最终都是要靠像素显示出来，不同的软件对这一过程的处理也不尽相同。

**Comment by toylsc** [comment]
> 是 PDF 阅读器的问题，不是生成 PDF 时的问题

或者说是系统问题？我用**同一款 PDF 阅读器**看你发的 mac 下编译的 PDF 文件和我在 windows 下 编译的 PDF 文件，在 100% 大小下确实显示效果不一样啊，字体粗细都不一样。mac 下编译的 PDF 看起来和模板自带的 PDF 文件一样。PDF 文件里面都是同样的字体和同样的字号，就是显示不一样。

**Comment by toylsc** [comment]
> adobe 的软件很多会覆盖系统默认的字体渲染，你换 edge 或者其他啥效果可能都不一样。毕竟不管是什么样的字，最终都是要靠像素显示出来，不同的软件对这一过程的处理也不尽相同。

我用的是同一个 PDF 阅读器，在同一个 windows 系统里面分别看模板自带的 main.pdf 和我自己编译的 main.pdf 确实不同。也就是说同一个 adobe 阅读器，处理不同的 PDF 文件，即使两者字体和字号相同，渲染方式可能不同，但这是阅读器的问题，不是编译出来的 PDF 文件本身包含某些不同信息造成的？

**Comment by xueruini** [comment]
> @xueruini 话说示例文档中的隶书和幼圆可以去掉吗？mac 版 ms-office word 没这俩字体，所以每次都得删一遍。

可以删，没啥用。当时凑这些字数也是为了让后面出现跨页表格的例子。论文里应该没人会用这两个字体。
