### ISSUE TITLE
外文资料的调研阅读报告

### ISSUE THREAD

**Issue by Diyorazh** [xueruini/thuthesis#478]
## 编译环境
编译的系统： Overleaf
模板版本：v(我也不清楚，overleaf上面搜的，应该是最新版)
模板类型：bachelor

## 描述问题
我无法在appendix-survey后插入参考文献，有参考文献大字但是出不来。

复现上述问题的代码：
\bibliographystyle{thuthesis-numeric}  
\bibliography{ref/refs}

谢谢！

**Comment by zepinglee** [comment]
描述清楚

**Comment by Diyorazh** [comment]
![image](https://user-images.githubusercontent.com/34129418/75812080-70ce1480-5d42-11ea-90d0-22a09b54a308.png)

已经上传截图

**Comment by zepinglee** [comment]
OverLeaf 的原始示例文档可以编译通过，无法复现你的问题。

<img width="1118" alt="Screen Shot 2020-03-04 at 4 40 58 PM" src="https://user-images.githubusercontent.com/12290822/75860529-efa47980-5e36-11ea-985a-fb754bde852f.png">

**Comment by xueruini** [comment]
楼主是不是没有 `cite` 任何东西？

**Comment by Diyorazh** [comment]
楼上两位：
抱歉回复晚了，我在美国做毕设有点时差。这个问题不止我一个人出现了，我和我的同学是物理系的，我们都遇到了这个问题，他的问题和我的实验的。
首先您本来就有的两个.bib文件我没有改的，如果直接调用，应该是您的默认设置。但是什么都出不来。


![Uploading Screen Shot 2020-03-04 at 2.35.10 PM.png…]()


![Screen Shot 2020-03-04 at 2 32 19 PM](https://user-images.githubusercontent.com/34129418/75929252-06da6b80-5e25-11ea-91cd-e0e6c942868c.png)

**Comment by Diyorazh** [comment]
![Screen Shot 2020-03-04 at 2 37 33 PM](https://user-images.githubusercontent.com/34129418/75929539-b1eb2500-5e25-11ea-86af-c8248047a6f0.png)

**Comment by Diyorazh** [comment]
![Screen Shot 2020-03-04 at 2 38 12 PM](https://user-images.githubusercontent.com/34129418/75929588-c7f8e580-5e25-11ea-99f5-9e83a5592610.png)

**Comment by Diyorazh** [comment]
啊，我破案了，@xueruini 大佬说的对，需要文中cite。我跑了一下overleaf上的原始文件，发现可以出现。因为没有改bib，所以我试了一下在文中\cite{tex} ，发现Knuth的那条就出现了。
因为我draft的时候用的是bibitem，cite的label和template的不一样。所以这个cite一个才会出现一个。妙啊！

解决解决！
P.S. 我把有我论文内容的截图删掉了，大佬们不要介意。
