### ISSUE TITLE
调研阅读报告 survey 环境使用英文

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#479]
由 @Harry-Chen 在 https://t.me/ctexug 提出。

本科生的 survey 是要求用英文写的，这一部分里面的各种对象的名字也该改成英文的（冒出一个 图xxx 过于违和）

目前示例文档的方式是：
```tex
\caption*{Figure~1\quad This is an example ...}
```
<img width="243" alt="Screen Shot 2020-03-05 at 10 58 43 AM" src="https://user-images.githubusercontent.com/12290822/75943567-4d38d480-5ed0-11ea-9d43-33902e847f4b.png">
比较丑陋。

如果用 `\caption{This is an example...}`，效果是
<img width="229" alt="Screen Shot 2020-03-05 at 10 57 51 AM" src="https://user-images.githubusercontent.com/12290822/75943533-35615080-5ed0-11ea-9529-ed51588a3022.png">

**Comment by zepinglee** [comment]
另外关于编号的方式，虽然 survey 是比较独立的部分，但是图表的编号用全文统一的“A.1”更合理

**Comment by Harry-Chen** [comment]
See #483

**Comment by xueruini** [comment]
当时那样做例子，是有学院要求附录要保证跟原文一模一样

**Comment by zepinglee** [comment]
这部分“外文资料的调研阅读报告”应该是自己写的吧？所以也不存在“原文”吧？

**Comment by xueruini** [comment]
翻译原文要贴上来

**Comment by zepinglee** [comment]
> 15. 附录 A:为外文资料的调研阅读报告或书面翻译。调研阅读报告需附参考文献;书面 翻译需注明外文资料原文的索引。标题为“外文资料的调研阅读报告或书面翻译”，用黑体小 三号字，段前 30pt，段后 20pt，行距 20pt。内容部分采用宋体小四号字，行距用固定值 20pt， 段前后 0pt。

**Comment by xueruini** [comment]
可能是规范上没写遇到的实际要求。可以留一个例子，以防万一

**Comment by zepinglee** [comment]
@Harrt-Chen
