### ISSUE TITLE
Mac字体

### ISSUE THREAD

**Issue by WhirlFirst** [xueruini/thuthesis#480]
## 编译环境
编译的系统：macOS 10.14
TeX 发行版：MacTeX 2019
模板版本：v6.0.2
模板类型：doctor / master / bachelor

## 描述问题
说实话mac版本的字体如果需要与win保持一致，设置`footset=windows`后，大概率是要手动下几个字体。我在想能不能直接把学校要求的这几个字体文件放在GitHub上，mac的同学直接安装一下，岂不美哉？

我是从`https://www.wfonts.com/`这个网站上下载的。我不知道这样做是不是比在win上重新编译一遍会更好一点？为什么不在文档里推荐这种方法呢？ 还是这些字体实际上还是与win的中易字库不一样？或者是有什么版权问题？

### **示例文档(win?)：**
![image](https://user-images.githubusercontent.com/23123386/76098058-c438a080-5f96-11ea-93b8-8c6748595d98.png)
### **Mac：**
![image](https://user-images.githubusercontent.com/23123386/76098082-d0246280-5f96-11ea-9fc2-3590b45690dc.png)

但是好像“基本表格”这几个字比示例文档要小？不知道这是不是字体的锅

**Comment by zepinglee** [comment]
> 或者是有什么版权问题？
对

> 大概率是要手动下几个字体
其实可以用 microsoft office for word 的字体

> mac的同学直接安装一下，岂不美哉？
不美，mac 下的自带的华文宋体和黑体有粗体，windows 的中易字体只能用伪粗；只是个别审查老师非要觉得又问题。

> 但是好像“基本表格”这几个字比示例文档要小？
字号是一样的，只是华文和中易的字形不一样，而且中易的是伪粗，所以照成了视觉上大小的差异

**Comment by WhirlFirst** [comment]
对我看了你们之前讨论word的字体，但实际上更新了Word后字体就找不到了，貌似之前有个issue就说了这个问题https://github.com/xueruini/thuthesis/issues/459 。

关于字体小的问题，我用的是自己下载的字体，没用自带字体，毕竟自带的字体的名字和windows字体的名字不一样，这也是我自己下载字体的原因。还是你的意思是我从网站上下载的不是中易？

**Comment by WhirlFirst** [comment]
说实话我也有点好奇因为字体而格式不合格的事情到底是个例还是普遍问题，学校会查的这么严吗？难道用Mac的同学不能用LaTeX写论文？

**Comment by zepinglee** [comment]
> 对我看了你们之前讨论word的字体，但实际上更新了Word后字体就找不到了，貌似之前有个issue就说了这个问题#459 。

我这里并没有出现这个问题，目前还没搞清楚 xueruini 那边是啥情况。
 
> 关于字体小的问题，我用的是自己下载的字体，没用自带字体，毕竟自带的字体的名字和windows字体的名字不一样，这也是我自己下载字体的原因。还是你的意思是我从网站上下载的不是中易？

示例文档用的啥字体我也不知道……总之这里只是字体字形的问题，不存在字号设置错的，你可以放心。

**Comment by WhirlFirst** [comment]
Fine，总怕最后在这种小事情上栽跟头。。谢谢了

**Comment by zepinglee** [comment]
> 说实话我也有点好奇因为字体而格式不合格的事情到底是个例还是普遍问题，学校会查的这么严吗？难道用Mac的同学不能用LaTeX写论文？

不是很多；比如我个人视力不太好（星际打多了），是分辨不出华文和中易的字体的。

然而个别审查老师能辨别出字体（也可能是看了很多份中易字体突然有个不太一样的），而且还要较真（其实学校的写作指南中也没规定“中易字体”）。

这也不算是“栽跟头”，顶多也就改改字体重新提交一份。
