### ISSUE TITLE
thuthesis.pdf疑似一处笔误

### ISSUE THREAD

**Issue by KateZheng** [xueruini/thuthesis#481]
## 编译环境
编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：doctor / master / bachelor

第5页2.3.3节关于xelatex中的代码，bibtex main.tex好像应该改为bibtex main.aux

**Comment by zepinglee** [comment]
已经修复
