### ISSUE TITLE
6.0.2版本出现warning：Option `pdflang' has already been used

### ISSUE THREAD

**Issue by wxsthuee** [xueruini/thuthesis#482]
## 编译环境
编译的系统：macOS 10.15
TeX 发行版：MacTeX 2019
模板版本：v6.0.2
模板类型：doctor

## 描述问题
有一个warning，6.0.1版本没有出现：
```
Option `pdflang' has already been used,
(hyperref) setting the option has no effect.
```
<img width="326" alt="image" src="https://user-images.githubusercontent.com/6491355/76135146-4391a700-605f-11ea-9b5a-4503b350a768.png">

定位到main.tex中的 \begin{document}

<img width="468" alt="image" src="https://user-images.githubusercontent.com/6491355/76135152-5015ff80-605f-11ea-94ba-e6bf160eca29.png">

**Comment by suxpert** [comment]
问题可复现，原因在于
```tex
% Line 1536
\AtBeginDocument{%
```
猜测是某个包设置了 pdflang

**Comment by Harry-Chen** [comment]
这个改动是我引入的，确实好像有问题，无论 language=english 还是 chinese，生成的 pdflang 都是 zh-CN。

**Comment by Harry-Chen** [comment]
See #486
