### ISSUE TITLE
工程硕士中文封面培养单位导师格式

### ISSUE THREAD

**Issue by ychen216** [xueruini/thuthesis#487]
## 编译环境
编译的系统：macOS 10.14
TeX 发行版：MacTeX 2019
模板版本：v6.0.2
模板类型：master

## 描述问题

工程硕士中文封面格式有误

正确的应该是：
![image](https://user-images.githubusercontent.com/32663674/76486118-6a821b80-6459-11ea-8689-0563d5b08616.png)

而现在打印出来的结果其实是学术性硕士的中文封面
![image](https://user-images.githubusercontent.com/32663674/76486162-85ed2680-6459-11ea-9b3a-539cf6c7ae96.png)

**Comment by zepinglee** [comment]
`thusetup.tex` 怎么写的？

**Comment by zepinglee** [comment]
刚没看到图，我去检查一下

**Comment by zepinglee** [comment]
按照 https://github.com/xueruini/thuthesis/blob/master/testfiles/01-cover/master-1-2.tex 的设置没有问题：
<img width="457" alt="Screen Shot 2020-03-12 at 12 17 45 PM" src="https://user-images.githubusercontent.com/12290822/76486830-7f5fae80-645b-11ea-9e4f-1c69448dd7d9.png">

**Comment by ychen216** [comment]
差异在于冒号两侧的缩进

> 好像有些问题

**Comment by zepinglee** [comment]
“01-硕-1-中文3其他专业学位硕士封面”的空白好像也有些问题

**Comment by zepinglee** [comment]
在 29f9c08 修复了封面的格式
