### ISSUE TITLE
ntheorem 宏包的 QED 位置不对

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#488]
由 @ yzq50 在 https://t.me/ctexug 提出。

```TeX
\documentclass{thuthesis}
\usepackage[thmmarks]{ntheorem}
\begin{document}
\begin{proof}
  \begin{equation}
    a = b
  \end{equation}
  Foo \par
\end{proof}

\begin{proof}
  Bar \par
\end{proof}
\end{document}
```

两个示例的问题：
1. 生成的 QED 位置不对，出现在了上一个公式结束的问题；
2. 缺失 QED：
<img width="679" alt="Screen Shot 2020-03-12 at 6 29 12 PM" src="https://user-images.githubusercontent.com/12290822/76512344-712b8580-648f-11ea-98ae-c5eec3721156.png">

这是由于 `ntheorem` 宏包本身的问题，也可以通过
```tex
\usepackage[thmmarks]{ntheorem}
\theoremsymbol{\rule{1em}{1em}}%
\newtheorem*{proof}{Proof}%
```
复现；可能主要是因为 `thmmarks` 选项。

@xueruini 
1. 原来模板中使用 `ntheorem` 的主要原因是什么（似乎可以追溯到 9803f14e59）？
2. 建议将示例文档换成比较稳定的 `amsthm`，用 `filehook` 的方法对其支持，所以也不会造成冲突。

**Comment by xueruini** [comment]
> * 原来模板中使用 `ntheorem` 的主要原因是什么（似乎可以追溯到 [9803f14](https://github.com/xueruini/thuthesis/commit/9803f14e59f4a6cb5a8797da04e6fb6033c7c7ee)）？

隐约记得当时有 QED 的需求，太久了。现在的结构也有点诡异，`ntheorem` 是 `thusetup.tex` 里引入的，配置却在 `cls`。

> * 建议将示例文档换成比较稳定的 `amsthm`，用 `filehook` 的方法对其支持，所以也不会造成冲突。

yes

**Comment by zepinglee** [comment]
> 现在的结构也有点诡异，ntheorem 是 thusetup.tex 里引入的，配置却在 cls。

现在是用了类似 `filehook` 的机制，在 `cls` 里进行配置，但是只有用户 `\usepackage{ntheorem}` 后才会加载这些配置；

这样比在 `cls` 中写死 `\RequirePackage` 更灵活，比如：
1. 用户不需要某些选项；
2. 用户想用其他类似功能的宏包；
3. 不调用该宏包时减少编译的时间；

**Comment by zepinglee** [comment]
另外 `\qedsymbol` 最好使用 `unicode-math` 的 U+0220E ∎ `\QED`，缺点是大部分字体的这个字符是填充黑色的长方块，如果用户不喜欢需要自行修改 `\qedsymbol` 的值。

**Comment by xueruini** [comment]
替换 `ntheorem` 我没问题
