### ISSUE TITLE
附录中的图、表不加入索引

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#490]
目录的二级以上标题不加入目录，同理附录中的图、表不应加入索引。

另外本科生和研究生的《写作指南》似乎都没提到公式索引，感觉不必加到示例中。

**Comment by Diyorazh** [comment]
恕我直言，公式索引感觉没啥用处……

**Comment by Harry-Chen** [comment]
嗯，因为公式不能起名，所以显得比较鸡肋

**Comment by zepinglee** [comment]
嗯，那我把示例的公式索引去掉吧。

**Comment by xueruini** [comment]
其实不用处理什么吧，不用就是了
