### ISSUE TITLE
package kvsetkeys error: thuthesis-master/thusetup.tex .... undefined key 'title'

### ISSUE THREAD

**Issue by liuqingzhe** [xueruini/thuthesis#491]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2019 
模板版本：v5.5.2
模板类型：doctor / master 

## 描述问题
无法生成封面

**Comment by zepinglee** [comment]
试下 v6.0.2 ？

**Comment by liuqingzhe** [comment]
已解决，把v6.0.2的thuthesis.cls文件放入main.tex目录下，可以了。多谢。

**Comment by zepinglee** [comment]
v6.0.2 的 main.tex 的一些命令跟 v5.x 略不同，记得换成新的
