### ISSUE TITLE
是否可以自行扩展个人简历中的列表环境

### ISSUE THREAD

**Issue by yangyz10** [xueruini/thuthesis#492]
目前个人简历中的研究成果部分只有“学术论文”和“研究成果”两个列表。可否自行添加列表的环境，如“参与项目”、“获奖情况”之类，各自进行编号？

**Comment by zepinglee** [comment]
当然可以啊

**Comment by yangyz10** [comment]
请问如何实现？

**Comment by xueruini** [comment]
https://github.com/xueruini/thuthesis/blob/master/thuthesis.dtx#L3351-L3371

可以抄这里的定义，就是个 list
