### ISSUE TITLE
本科生的调研报告 appendix-survey 在本地编译无法出现参考文献

### ISSUE THREAD

**Issue by xpc16** [xueruini/thuthesis#493]
## 编译环境
编译的系统：Windows 10 /Overleaf
TeX 发行版：TeX Live 2019
模板版本：v6.0.2
模板类型：bachelor

## 描述问题
appendix-survey在[overleaf](https://www.overleaf.com/latex/templates/thuthesis-tsinghua-university-thesis-latex-template/tjjttqzttsyv)编译正常。
但从overleaf/GitHub下载本地编译，appendix-survey无法显示参考文献列表（xelatex -> bibtex -> xelatex*2），cite refs.bib 有标号无列表，cite appendix.bib 无标号无列表。正文部分参考文献列表正常。

截图：
overleaf
![批注 2020-03-18 140729](https://user-images.githubusercontent.com/34030203/76931001-bda91200-6922-11ea-9f76-ee57234324f2.jpg)

vs code
![批注 2020-03-18 142012](https://user-images.githubusercontent.com/34030203/76931601-001f1e80-6924-11ea-896b-8863a3b8ddfe.jpg)

**Comment by zepinglee** [comment]
`survey` 环境比较特殊，需要用 `bibtex` 对 `main-survey.aux` 编译一次；

OverLeaf 使用了 `latexmk`，可以自动处理。

建议在本地也使用 `latexmk`。

**Comment by xpc16** [comment]
解决了，谢谢学长！（没有留意那个.vscode）(lll￢ω￢)
