### ISSUE TITLE
下载的zip想打开main.tex会显示 error reading 

### ISSUE THREAD

**Issue by hansha168** [xueruini/thuthesis#494]
## 编译环境
编译的系统：Windows 10Overleaf
TeX 发行版：TeX Live 2019 
模板版本：v5.5.2
模板类型：doctor

**Comment by zepinglee** [comment]
1. 哪个 zip？
2. win10 还是 overleaf？
3. 哪个编辑器？
4. 用最新版

**Comment by Harry-Chen** [comment]
duplicate with #495
