### ISSUE TITLE
用最新版本运行报错

### ISSUE THREAD

**Issue by hansha168** [xueruini/thuthesis#495]
## 编译环境
编译的系统：Windows 10 
TeX 发行版：MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：master 
报错: ! undefined controla sequence.
1.5 \documentclass [degree=master, fontset=windows] {thuthesis}

**Comment by zepinglee** [comment]
1. 最新版本是 v6.0.2
2. 把报错信息写全

**Comment by hansha168** [comment]
我写错了，是用的v6.0.2

**Comment by xueruini** [comment]
错误信息可以贴一下

**Comment by hansha168** [comment]
! undefined controla sequence.
1.5 \documentclass [degree=master, fontset=windows] {thuthesis}

**Comment by hansha168** [comment]
方便留一下邮箱或者微信吗？我感觉我的问题比较多……

**Comment by zepinglee** [comment]
1. `\docmentclass` 没有定义的话，可能是用了 pdftex 或者 xetex 编译，正确的是 xelatex 。
2. 可以把 `main.log` 的内容贴过来；
3. 建议在 GitHub 上交流，可以记录下来方便有相同问题的同学参考。

**Comment by hansha168** [comment]
1. 使用Xelatex,报错 undefined control sequence. \KVS@thu@key@handler...}}}\kvsetkeys@expandafter{thu@choice}{\thu@@choices}
2.main.log是空白

**Comment by zepinglee** [comment]
可能是用了低版本的 kvsetkeys 宏包，miktex 没自动更新；

建议你把编译输出的内容都贴过来

**Comment by hansha168** [comment]
你好，我这个安装的是CTEX full版本，好像console有问题，不能更新

**Comment by zepinglee** [comment]
不支持 CTeX 套装

**Comment by hansha168** [comment]
那我安装什么来编译呢？

**Comment by zepinglee** [comment]
阅读文档？

<img width="791" alt="Screen Shot 2020-03-20 at 8 20 59 PM" src="https://user-images.githubusercontent.com/12290822/77163096-576dec00-6ae8-11ea-8ddb-53eb2443129e.png">

**Comment by hansha168** [comment]
多谢
