### ISSUE TITLE
名字和导师的名字不等宽

### ISSUE THREAD

**Issue by hansha168** [xueruini/thuthesis#496]
## 编译环境
编译的系统： Windows 10 
TeX 发行版： MiKTeX 2.9.6753
模板版本：v6.0.2
模板类型： master

## 描述问题
学校要求封面上自己的名字和导师的名字等宽，但是这个模板编译出来自己的名字占据4个字节，而导师的名字占据了3个字节。

**Comment by zepinglee** [comment]
代码？截图？

**Comment by zepinglee** [comment]
另外区分一下“字节”和“汉字宽度”

**Comment by hansha168** [comment]
抱歉，我想表达的意思是汉字宽度。截图如图所示。[
![清华大学学位论文 LaTeX 模板使用示例文档 v6 0 2](https://user-images.githubusercontent.com/59385456/77221652-c0fdf280-6b08-11ea-9f14-4b706f255346.png)
](url)

**Comment by hansha168** [comment]
抱歉，我想表达的意思是汉字宽度。我这边网络有问题，图片上传不上去。其实就是你们给的模板编译出来的效果，薛瑞尼老师的名字占据了4个汉字宽度，而郑老师的名字是3个汉字宽度。

**Comment by zepinglee** [comment]
中文姓名和职称之间以英文逗号“,”分开；

但是给的示例似乎忘记更新了，稍后修复

**Comment by zepinglee** [comment]
在 4914c13 中修复，效果：

<img width="483" alt="Screen Shot 2020-03-21 at 5 50 46 PM" src="https://user-images.githubusercontent.com/12290822/77224003-804fb900-6b9c-11ea-8291-f5d7530d3c85.png">

**Comment by hansha168** [comment]
哦，是的，这下好了。多谢
