### ISSUE TITLE
overleaf中垚字不显示

### ISSUE THREAD

**Issue by zjhthu** [xueruini/thuthesis#497]
在overleaf中，一些复杂的汉字如“垚”没办法显示

**Comment by zepinglee** [comment]
目前在 overleaf 中配置的中文字体是 fandol，缺这个字形；

后续版本会换成 noto cjk，

**Comment by zjhthu** [comment]
想问一下大概是什么时候？或者我自己弄的话该怎么处理？

**Comment by xueruini** [comment]
mac/windows本地编译就OK了，是字体的事

**Comment by zjhthu** [comment]
好的，我试试

**Comment by zepinglee** [comment]
> 想问一下大概是什么时候？或者我自己弄的话该怎么处理？

这个是在 overleaf 上编译时用的字体缺字，不影响本地编译的效果，你就当没看见好了，不必自己去折腾字体；

时间不确定；

**Comment by zepinglee** [comment]
@xueruini https://github.com/xueruini/thuthesis/tree/fontset

1. 提供 `font`, `cjk-font`, `math-font` 选项设置字体（感谢 [fduthesis](https://github.com/stone-zeng/fduthesis)）；
1. 接管 ctex 的 fontset 选项，避免在 macOS 10.15 的系统检测问题；
1. OverLeaf 上会优先使用 Noto CJK 作为中文字体。

**Comment by zepinglee** [comment]
另外封面的姓名部分用的是楷体，而 Overleaf 上可用的楷体只有 AR PL KaitiM GB 和 FandolKai，两个都缺“垚”这个字形，总之这个问题没办法，你可以选择：
1. 自己上传字体并进行配置；
2. 假装没看到缺字。

**Comment by zjhthu** [comment]
我先在本地编译解决了，感谢~
