### ISSUE TITLE
本科生模板里PDF文件中的书签有错位

### ISSUE THREAD

**Issue by Leeehow** [xueruini/thuthesis#499]
点击PDF里的书签“致谢”，会转到”插图索引“

点击PDF里的书签“声明”，会转到“表格索引”

但是插图索引和表格索引都没有PDF里的书签

**Comment by Leeehow** [comment]
就是这个意思
![微信截图_20200327191144](https://user-images.githubusercontent.com/45907951/77750708-40d31200-705f-11ea-9cb8-35d63cdb18bd.png)

**Comment by zepinglee** [comment]
哪个版本？是不是跟 #499 一样？

**Comment by Leeehow** [comment]
是一样的，从CTAN里下的V6.0.2

**Comment by zepinglee** [comment]
#453 已经解决了，是不是你本地没生成 cls 文件？
