### ISSUE TITLE
如何将积分上下限的位置放到积分号右侧?

### ISSUE THREAD

**Issue by TAOYi92** [xueruini/thuthesis#500]
## 编译环境
编译的系统：macOS 10.12
TeX 发行版：MacTeX 2019
模板版本：v5.5.2
模板类型：doctor

## 描述问题
模板中的积分号是正体，且积分上下限在积分号上下，如何将积分上下限的位置放到积分号右侧（在模板外使用LaTeX的默认编译样式）？
一些尝试：
1. 注释掉`thuthesis.dtx`里的`\unimathsetup`部分和`\removenolimits`部分，但是没有效果。
2. 在`main.tex`中加上`\setmathfont{XITSMath-Regular.otf}`,只是积分号变成斜体但上下限的位置仍然在积分号上下侧

截图：
![sshot](https://user-images.githubusercontent.com/22067392/78155865-9436cd00-7470-11ea-90ac-b3cd98136e57.jpg)

请各位大佬不吝赐教，感谢！！

**Comment by zepinglee** [comment]
国内的习惯一般都是在上下

**Comment by zepinglee** [comment]
研究生写作指南要求的是按照 GB 3102.11-1993 执行，其中对积分号上下限的规定是上下和右方都可以：
<img width="712" alt="Screen Shot 2020-04-02 at 10 12 21 AM" src="https://user-images.githubusercontent.com/12290822/78203777-71d19d80-74ca-11ea-8ea2-a6cb57876158.png">
但是国内的习惯是在上下，所以不建议修改。

**Comment by TAOYi92** [comment]
> 国内的习惯一般都是在上下

感谢回复，由于我的导师是外国人，我的毕业论文主体都是英文写作，所以还是想解决一下这个问题。

**Comment by zepinglee** [comment]
国外的话也有一份 ISO 80000-2:2009 标准：

<img width="764" alt="Screen Shot 2020-04-02 at 10 21 59 AM" src="https://user-images.githubusercontent.com/12290822/78204323-db9e7700-74cb-11ea-9624-e33765e7214e.png">

TeX 传统的样式是按照英美国家的习惯，ISO 的是欧洲大陆国家的习惯，我国的 GB 基本跟 ISO 差不多，只有个别符号不一样，参考 https://github.com/latexstudio/ChinaThesis/wiki/GB-math 。总之不建议在这个问题上纠结，除非你导师有直接要求。

**Comment by TAOYi92** [comment]
> 国外的话也有一份 ISO 80000-2:2009 标准：
> 
> <img alt="Screen Shot 2020-04-02 at 10 21 59 AM" width="764" src="https://user-images.githubusercontent.com/12290822/78204323-db9e7700-74cb-11ea-9624-e33765e7214e.png">
> 
> TeX 传统的样式是按照英美国家的习惯，ISO 的是欧洲大陆国家的习惯，我国的 GB 基本跟 ISO 差不多，只有个别符号不一样，参考 https://github.com/latexstudio/ChinaThesis/wiki/GB-math 。总之不建议在这个问题上纠结，除非你导师有直接要求。

谢谢你的建议，我的导师之一提了一下这个方面

**Comment by zepinglee** [comment]
这也太不给学校官方的《写作指南》面子了吧……建议你跟导师沟通一下，因为 TeX 传统样式跟国标还有其他区别，比如大写希腊字母的正斜体，矢量的正斜体。

另外临时的解决方案是去掉 `dtx` 文件中 `\removenolimits{...}` 的部分，然后重新生成 `cls` 文件。

后续可以给 `\thusetup` 加个选项 `math-style = TeX/ISO/GB` 的选项。

**Comment by TAOYi92** [comment]
> 这也太不给学校官方的《写作指南》面子了吧……建议你跟导师沟通一下，因为 TeX 传统样式跟国标还有其他区别，比如大写希腊字母的正斜体，矢量的正斜体。
> 
> 另外临时的解决方案是去掉 `dtx` 文件中 `\removenolimits{...}` 的部分，然后重新生成 `cls` 文件。
> 
> 后续可以给 `\thusetup` 加个选项 `math-style = TeX/ISO/GB` 的选项。

好的，谢谢你！

**Comment by xueruini** [comment]
导师对这个位置这么在意啊？

感觉这样调整下去，fontspec/unicode-math的选项都得包装一遍
