### ISSUE TITLE
本科生的段落首行缩进 0.8cm

### ISSUE THREAD

**Issue by zepinglee** [xueruini/thuthesis#501]
1. 《研究生写作指南》第 11 页规定了三线表的三条线的粗度，但是 thuthesis 没有实现；（本科生第 3 页要求同样）

2. 本科生要求正文段落“首行缩进 0.8cm”，thuthesis 实现的是 2 个汉字宽度。

**Comment by xueruini** [comment]
> 2\. 本科生要求正文段落“首行缩进 0.8cm”，thuthesis 实现的是 2 个汉字宽度。

2字符是中文约定。不建议改成 0.8cm（大胆怀疑规范写的时候是抄了word的数字，而word并未合适配置为2字符）。

**Comment by xueruini** [comment]
> 1. 《研究生写作指南》第 11 页规定了三线表的三条线的粗度，但是 thuthesis 没有实现；（本科生第 3 页要求同样）

例子里直接用 toprule 指定线粗，对不了解的是有点问题

**Comment by zepinglee** [comment]
有份本科生的《声明》还真是缩进 0.8 cm：
<img width="756" alt="Screen Shot 2020-04-03 at 11 20 32 AM" src="https://user-images.githubusercontent.com/12290822/78320955-5388a200-759d-11ea-9981-922408b27143.png">

**Comment by zepinglee** [comment]
可以通过 `\heavyrulewidth` 和 `\lightrulewidth` 来设置默认的粗度

**Comment by xueruini** [comment]
> 有份本科生的《声明》还真是缩进 0.8 cm：

我就是觉得当时写规范的人可能不知道 by 后面可以写 2 chars

**Comment by zepinglee** [comment]
1. 中文模板就保持这样吧，不过本科英文模板还是采用 0.8cm 的缩进（其实这连个格式问题也是我在检查英文模板的时候发现的）

2. 我觉得尽可能避免在写正文需要过多设置格式（内容与格式分离原则）

**Comment by xueruini** [comment]
> 2\. 我觉得尽可能避免在写正文需要过多设置格式（内容与格式分离原则）

这个的确应该默认配置好，赞同改 heavy/light rule width
