### ISSUE TITLE
从v5.4.5到最新版，公式中无法正确显示一些大写加粗的希腊字母

### ISSUE THREAD

**Issue by po-one** [xueruini/thuthesis#502]
## 编译环境
编译的系统：Windows 10 1809
TeX 发行版：MiKTeX 2.9.7364
模板版本：v6.0.2
模板类型：doctor

## 描述问题

无法显示大写加粗的希腊字母，诸如 $\mathbf \Psi$、$\mathbf \Theta$ 等字符。
奇怪的是使用$\bm \Psi$可以正常显示，但是我不喜欢用斜体，因为论文全篇都不是italic的。

这几天一直被这个问题困扰，而v5.4.5及之前版本试验无此问题。

不知有没有临时的解决方案。

**Comment by zepinglee** [comment]
> 但是我不喜欢用斜体，因为论文全篇都不是italic的。

研究生《写作指南》：
<img width="675" alt="Screen Shot 2020-04-06 at 11 49 45 PM" src="https://user-images.githubusercontent.com/12290822/78577976-721ebf80-7861-11ea-9da6-9b2abb13da96.png">

其中 GB 3102.11-1993 《物理科学和技术中使用的数学符号》（2017 年改为 GB/T）
<img width="733" alt="Screen Shot 2020-04-06 at 11 53 28 PM" src="https://user-images.githubusercontent.com/12290822/78578640-5ff15100-7862-11ea-8f9f-d63f5a151445.png">

> 奇怪的是使用$\bm \Psi$可以正常显示
`thuthesis` 的设置中 `\bm` 等同于 `\symbf`

**Comment by po-one** [comment]
除去这个原因（因为这确实是个bug，毕竟之前的版本是可以显示的），有没有办法使得 \mathbf \Psi 正常显示？现在属于字体库的希腊字母粗体缺失问题。 @zepinglee

**Comment by stone-zeng** [comment]
现在 `thuthesis` 换用了 `unicode-math` 宏包作为数学字体支持，不再支持 `\mathbf` 和 `\bm` 的用法。现在：

- 加粗、直立应该使用 `\symbfup`
- 加粗、倾斜应该使用 `\symbfit` 或者 `\symbf`
- `\mathbf` 会使用**文本字体**，因此可能不支持希腊字母等，所以不建议使用

**Comment by zepinglee** [comment]
> 因为这确实是个bug，毕竟之前的版本是可以显示的

`thuthesis` 从 v5.5.0 开始使用 `unicode-math` 处理数学字体，跟 TeX 传统不一样，不是 bug。

**Comment by po-one** [comment]
> 现在 `thuthesis` 换用了 `unicode-math` 宏包作为数学字体支持，`\mathbf` 和 `\bm` 仅作兼容性保留。现在：
> 
> * 加粗、直立应该使用 `\symbfup`
> * 加粗、倾斜应该使用 `\symbfit` 或者 `\symbf`
> * `\mathbf` 会使用**文本字体**，因此可能不支持希腊字母等，所以不建议使用

使用 \symbfup 后问题解决，多谢。不知有没有办法全局在模板里自动用symbfup代替mathbf渲染，这样可能是一个比较好的解决方案

**Comment by po-one** [comment]
> > 因为这确实是个bug，毕竟之前的版本是可以显示的
> 
> `thuthesis` 从 v5.5.0 开始使用 `unicode-math` 处理数学字体，跟 TeX 传统不一样，不是 bug。

好的，那我把 issue 关了，临时替代方案可用`\symbfup`解决。
