### ISSUE TITLE
关于subequations子公式后的莫名缩进

### ISSUE THREAD

**Issue by yangyz10** [xueruini/thuthesis#503]
在使用\begin{subequations}...\end{subequations}插入子公式环境后，如果不空行继续该段落，则公式后该行文字不顶格，而是有不到四分之一汉字的缩进。不使用subequations公式环境的段落均无此现象。不知是设置问题还是模板问题？

**Comment by zepinglee** [comment]
> 在使用\begin{subequations}...\end{subequations}插入子公式环境后，如果不空行继续该段落，则公式后该行文字不顶格，而是有不到四分之一汉字的缩进。不使用subequations公式环境的段落均无此现象。不知是设置问题还是模板问题？

给个示例代码和截图？

**Comment by zepinglee** [comment]
无法复现你的问题：
```tex
\documentclass[degree=master]{thuthesis}
\usepackage{mwe}
\begin{document}
\lipsum[1]
\begin{subequations}
  \begin{equation}
    Foo
  \end{equation}
  \begin{equation}
    Foo
  \end{equation}
\end{subequations}
\lipsum[1]
\end{document}
```

<img width="677" alt="Screen Shot 2020-04-07 at 9 32 05 PM" src="https://user-images.githubusercontent.com/12290822/78675151-3d6d3f80-7917-11ea-805d-8e51fd37bd7e.png">

**Comment by yangyz10** [comment]
现象好像与\label的位置相关：
```tex
\documentclass[degree=doctor]{thuthesis}
\begin{document}
先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也。然侍卫之臣不懈于内，忠志之士忘身于外者，盖追先帝之殊遇，欲报之于陛下也。诚宜开张圣听，以光先帝遗德，恢弘志士之气，不宜妄自菲薄，引喻失义，以塞忠谏之路也。
\begin{subequations}
    \label{eq}
    \begin{align}
        f_{1} &= 1 \\
        f_{2} &= 2 \\
        f_{3} &= 3
    \end{align}
\end{subequations}
宫中府中，俱为一体，陟罚臧否，不宜异同。若有作奸犯科及为忠善者，宜付有司论其刑赏，以昭陛下平明之理，不宜偏私，使内外异法也。
\end{document}
```
<img width="507" alt="image" src="https://user-images.githubusercontent.com/48130305/78678803-064d5d00-791c-11ea-97a2-72859d08a703.png">

```tex
\documentclass[degree=doctor]{thuthesis}
\begin{document}
先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也。然侍卫之臣不懈于内，忠志之士忘身于外者，盖追先帝之殊遇，欲报之于陛下也。诚宜开张圣听，以光先帝遗德，恢弘志士之气，不宜妄自菲薄，引喻失义，以塞忠谏之路也。
\begin{subequations}
    \begin{align}
        f_{1} &= 1 \\
        f_{2} &= 2 \\
        f_{3} &= 3
    \end{align}
    \label{eq}
\end{subequations}
宫中府中，俱为一体，陟罚臧否，不宜异同。若有作奸犯科及为忠善者，宜付有司论其刑赏，以昭陛下平明之理，不宜偏私，使内外异法也。
\end{document}
```
<img width="501" alt="image" src="https://user-images.githubusercontent.com/48130305/78679040-49a7cb80-791c-11ea-8d0f-18cf101df6a9.png">

**Comment by zepinglee** [comment]
对，`\label` 的问题。

另外 `amsmath` 的文档中提到：
> A `\label` command immediately after `\begin{subequations}` will produce a `\ref` of the parent number 4.9, not 4.9a.

这似乎才是推荐的用法。

**Comment by yangyz10** [comment]
多谢，学习了。
