### ISSUE TITLE
同一文献引用多次是否支持

### ISSUE THREAD

**Issue by xiaoweing** [xueruini/thuthesis#506]
研究生学位论文写作指南3.4.1中提到
3.
同一文献在论著中被引用多次，只编 1 个序号，引文页码放在"[]"外，文献表中不再重复著录页码。例如：张中国 等 [4]15-17 张中国 等 [4]55 认为…… 。
请问该功能是否支持，如果支持的话，能否给个示例，如果不支持的话，有没有一些建议

**Comment by zepinglee** [comment]
`\cite[15-17]{foo}`，参考 `gbt7714` 或者 `natbib` 的文档
