### ISSUE TITLE
个人简历页行距不统一

### ISSUE THREAD

**Issue by yangyz10** [xueruini/thuthesis#507]
在个人简历页“发表的学术论文”部分，publications尚未刊载论文的部分（模板中的[4]）与前后两个部分的publications行距不统一。在模板示例文档中即有此现象。

**Comment by xueruini** [comment]
这是故意的，学校要求将不同类别的分开。注意看例子的写法，有说明

**Comment by yangyz10** [comment]
我指的是每个项目里的行间距：
![image](https://user-images.githubusercontent.com/48130305/78872223-83dbaf00-7a7b-11ea-95db-6fa55528ee4a.png)

**Comment by xueruini** [comment]
明白了，我看看
