### ISSUE TITLE
怎样将书脊编译至封面中

### ISSUE THREAD

**Issue by AllanWlz** [xueruini/thuthesis#509]
直接编译得到的封面中，第二页是空白页。系里要求将书脊放在第二页，不知道该怎样操作？

**Comment by zepinglee** [comment]
1. 最简单的方法是用 pdf 编辑软件插进去，比如像 macOS 的 Preview 这样的轻量级软件；
1. 中英文封面是 `\maketitle` 一个命令生成的，如果要在里面插入书脊的内容必须要重定义。（其中的空白页是用 `\cleardoublepage` 生成的。）
1. 这样也不方便打印（中文封面的背面是书脊），所以不适合作为模板的默认样式。

**Comment by zepinglee** [comment]
我改了一下 `\spine` 允许在正文中使用。但是如果要插到第二页（中文封面和英文封面之间），就必须将，就必须将 `\maketitle` 拆成两个命令。
