### ISSUE TITLE
! LaTeX Error: File `logreq.sty' not found

### ISSUE THREAD

**Issue by DTKx** [xueruini/thuthesis#510]
## 编译环境
编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型：doctor / master / bachelor

## 描述问题
《研究生学位论文写作指南》第 xx 页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
abc
\end{document}
```
Hello, I have tried to compile the Latex file in TexMaker, however the following error appear and I could no figure out why it is not working.
Would you mind sharing your thoughts?
![image](https://user-images.githubusercontent.com/63344441/79031437-ea0d2280-7b9e-11ea-9904-f170b7679c7b.png)

**Comment by zepinglee** [comment]
It seems that you used `logreq` but it's not installed in your distribution.

**Comment by DTKx** [comment]
That's true, thaaank you so much!
