### ISSUE TITLE
请问，thuthesis在哪设置单双面啊，找遍说明文档好像都没有看到？

### ISSUE THREAD

**Issue by luojiujiu** [xueruini/thuthesis#511]
请问，thuthesis在哪设置单双面啊，找遍说明文档好像都没有看到？

**Comment by zepinglee** [comment]
都是双面打印，已经在模板里配置好了

**Comment by luojiujiu** [comment]
谢谢，我找到怎么配置了，修改thuthesis.cls文件的第150行，将
\LoadClass[a4paper,openany,UTF8,zihao=-4,scheme=plain,]{ctexbook}中的openany改成openright就可以了

发件人: Zeping Lee <notifications@github.com>
发送时间: 2020年4月12日 20:43
收件人: xueruini/thuthesis <thuthesis@noreply.github.com>
抄送: luojiujiu <luojiujiu@msn.com>; State change <state_change@noreply.github.com>
主题: Re: [xueruini/thuthesis] 请问，thuthesis在哪设置单双面啊，找遍说明文档好像都没有看到？ (#511)


都是双面打印，已经在模板里配置好了

**Comment by zepinglee** [comment]
目前模板中是先 `\ProcessKeyvalOptions*` 再 `\LoadClass[a4paper,openany,UTF8,zihao=-4,scheme=plain]{ctexbook}[2017/04/01]`，这样用户即便在 `\documentclass` 设置了 `openright` 也会被 `\LoadClass` 的选项覆盖掉。

应该改为在 `\ProcessKeyvalOptions*` 前用 `\ExecuteOptions`

**Comment by zepinglee** [comment]
`\ExecuteOptions` 似乎也不行，应该 `\PassOptionsToClass{openany}{book}`。

**Comment by luojiujiu** [comment]
你好，我用的是Tex Live 2020，将\LoadClass[a4paper,openany,UTF8,zihao=-4,scheme=plain]{ctexbook}中的openany变为openright，确实有变化，每个章节的首页为右开面，并没有被覆盖掉，按照你说的办法，编译报错：
Argument of \KV@def has an extra }. \ProcessKeyvalOptions
Paragraph ended before \KV@def was complete. \ProcessKeyvalOptions
Missing \endcsname inserted. \ProcessKeyvalOptions
Missing \endcsname inserted. \ProcessKeyvalOptions
Missing \begin{document}. \ProcessKeyvalOptions*

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Zeping Lee <notifications@github.com>
发送时间: Tuesday, April 14, 2020 8:26:17 AM
收件人: xueruini/thuthesis <thuthesis@noreply.github.com>
抄送: luojiujiu <luojiujiu@msn.com>; State change <state_change@noreply.github.com>
主题: Re: [xueruini/thuthesis] 请问，thuthesis在哪设置单双面啊，找遍说明文档好像都没有看到？ (#511)


目前模板中是先 \ProcessKeyvalOptions* 再 \LoadClass[a4paper,openany,UTF8,zihao=-4,scheme=plain]{ctexbook}[2017/04/01]，这样用户即便在 \documentclass 设置了 openright 也会被 \LoadClass 的选项覆盖掉。

应该改为在 \ProcessKeyvalOptions* 前用 \ExecuteOptions

―

**Comment by zepinglee** [comment]
> 你好，我用的是Tex Live 2020，将\LoadClass[a4paper,openany,UTF8,zihao=-4,scheme=plain]{ctexbook}中的openany变为openright，确实有变化，每个章节的首页为右开面，并没有被覆盖掉，按照你说的办法，编译报错： Argument of \KV@def has an extra }. \ProcessKeyvalOptions Paragraph ended before \KV@def was complete. \ProcessKeyvalOptions Missing \endcsname inserted. \ProcessKeyvalOptions Missing \endcsname inserted. \ProcessKeyvalOptions Missing \begin{document}. \ProcessKeyvalOptions* 发送自 Windows 10 版邮件<[https://go.microsoft.com/fwlink/?LinkId=550986>应用](https://go.microsoft.com/fwlink/?LinkId=550986>%E5%BA%94%E7%94%A8)
> […](#)

你可以暂且用替换 `\LoadClass` 的方法，忽略后面的讨论。

**Comment by luojiujiu** [comment]
好的，谢谢！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Zeping Lee <notifications@github.com>
发送时间: Tuesday, April 14, 2020 9:39:27 AM
收件人: xueruini/thuthesis <thuthesis@noreply.github.com>
抄送: luojiujiu <luojiujiu@msn.com>; State change <state_change@noreply.github.com>
主题: Re: [xueruini/thuthesis] 请问，thuthesis在哪设置单双面啊，找遍说明文档好像都没有看到？ (#511)


你好，我用的是Tex Live 2020，将\LoadClass[a4paper,openany,UTF8,zihao=-4,scheme=plain]{ctexbook}中的openany变为openright，确实有变化，每个章节的首页为右开面，并没有被覆盖掉，按照你说的办法，编译报错： Argument of \KV@def has an extra }. \ProcessKeyvalOptions Paragraph ended before \KV@def was complete. \ProcessKeyvalOptions Missing \endcsname inserted. \ProcessKeyvalOptions Missing \endcsname inserted. \ProcessKeyvalOptions Missing \begin{document}. \ProcessKeyvalOptions* 发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用<https://go.microsoft.com/fwlink/?LinkId=550986%3E%E5%BA%94%E7%94%A8>
…

你可以暂且用替换 \LoadClass 的方法，忽略后面的讨论。

―

**Comment by xueruini** [comment]
很久之前有opeany openright，后来都是双面，就删了

**Comment by zepinglee** [comment]
> 很久之前有opeany openright，后来都是双面，就删了

其实 `openany` 和 `openright` 都是双面 `twoside`，区别只是在于新的一章开起于偶数页时是否要加一空白页使得在右侧（奇数页）开起。事实上，研究生《写作指南》要求“从“中文摘要”开始各部分双面印刷，各部分之间不必 留空白页。”本科生并要求，但是给的[样](http://www.law.tsinghua.edu.cn/publish/law/7024/20120216153516317135347/1487557620435.pdf)中是 `openany` 的。

有的用户选择自行设置 `openright`：`\documentclass[openright]{thuthesis}`，但是并没有效果，因为会被 cls 文件的 `\LoadClass[a4paper,openany,UTF8,zihao=-4,scheme=plain]{ctexbook}[2017/04/01]` 的 `openany` 覆盖掉。我尝试了一下修复这个问题，但没成功。

**Comment by xueruini** [comment]
这部分不需要灵活支持，有调整的必要么

**Comment by luojiujiu** [comment]
收到，谢谢！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Zeping Lee <notifications@github.com>
发送时间: Monday, May 11, 2020 9:07:41 PM
收件人: xueruini/thuthesis <thuthesis@noreply.github.com>
抄送: luojiujiu <luojiujiu@msn.com>; State change <state_change@noreply.github.com>
主题: Re: [xueruini/thuthesis] 请问，thuthesis在哪设置单双面啊，找遍说明文档好像都没有看到？ (#511)


Closed #511<https://github.com/xueruini/thuthesis/issues/511>.

―
