### ISSUE TITLE
请问如何将参考文献设置成CELL杂志的样式

### ISSUE THREAD

**Issue by lvhailong** [xueruini/thuthesis#513]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v6.0.1
模板类型：doctor 

## 描述问题
生命科学学院的博士毕业论文参考文献样式和学校《研究生学位论文写作指南》中要求的不一致，需要按照CELL杂志的样式，例如：
正文插入样式：Mechanotransduction channels convert mechanical stimuli into neuronal signals (Arnado ́ttir and Chalfie, 2010; Coste et al., 2012; Vollrath et al., 2007). Several models have been proposed regarding how the mechanical force triggers channel opening (Kung, 2005; Lumpkin and Caterina, 2007; Orr et al., 2006). I
 文献列表样式：
Anishkin, A., and Kung, C. (2013). Stiffened lipid platforms at molecular force foci. Proc. Natl. Acad. Sci. USA 110, 4886–4892.
Arnado ́ ttir, J., and Chalfie, M. (2010). Eukaryotic mechanosensitive channels. Annu. Rev. Biophys. 39, 111–137.

我找到了手册里提到的这段内容：
BIBTEX 对自定义样式的支持比较有限，所以用户只能通过修改 bst 文件来修改文献列表的 格式。本宏包提供了一些接口供用户更方便地修改，在 bst 文件开始处的 load.config 函数 中，有一组配置参数用来控制样式。若变量被设为 #1 则表示该项被启用，设为 #0 则不启用。默 认的值是严格遵循学校规定的配置。

但是完全不懂要怎么实现修改成我们学院要求的样式，还望指教，谢谢！

**Comment by zepinglee** [comment]
给份你们学院的官方文档？最好是官方链接

**Comment by lvhailong** [comment]
> 给份你们学院的官方文档？最好是官方链接

官方链接没找到，但是我们的要求是按照[这个表格](https://cloud.tsinghua.edu.cn/f/ae7e1b72d74843388b2b/?dl=1)自查，这个表格没提到的内容以学校的《研究生学位论文写作指南》为准

**Comment by lvhailong** [comment]
补充一下，我找到了elseviers出版社的[官方模版](https://www.latextemplates.com/template/elseviers-elsarticle-document-class)
CELL杂志是其旗下期刊，根据官方提供的[模板列表](http://www.latextemplates.com/templates/academic_journals/1/journal_refstyles.pdf)查询到CELL期刊的样式为model2-names.bst 模板为elsarticle-template-2-harv.tex 可以在[这个包](http://www.latextemplates.com/templates/academic_journals/1/elsarticle.zip)里找到
麻烦看看能不能把这个样式整合到thuthesis模板里？

**Comment by zepinglee** [comment]
> 补充一下，我找到了elseviers出版社的[官方模版](https://www.latextemplates.com/template/elseviers-elsarticle-document-class)
> CELL杂志是其旗下期刊，根据官方提供的[模板列表](http://www.latextemplates.com/templates/academic_journals/1/journal_refstyles.pdf)查询到CELL期刊的样式为model2-names.bst 模板为elsarticle-template-2-harv.tex 可以在[这个包](http://www.latextemplates.com/templates/academic_journals/1/elsarticle.zip)里找到
> 麻烦看看能不能把这个样式整合到thuthesis模板里？

你给的几个链接都是 http://www.latextemplates.com 的，不是 cell 官网也不是 elsevier 官网。

**Comment by lvhailong** [comment]
> > 补充一下，我找到了elseviers出版社的[官方模版](https://www.latextemplates.com/template/elseviers-elsarticle-document-class)
> > CELL杂志是其旗下期刊，根据官方提供的[模板列表](http://www.latextemplates.com/templates/academic_journals/1/journal_refstyles.pdf)查询到CELL期刊的样式为model2-names.bst 模板为elsarticle-template-2-harv.tex 可以在[这个包](http://www.latextemplates.com/templates/academic_journals/1/elsarticle.zip)里找到
> > 麻烦看看能不能把这个样式整合到thuthesis模板里？
> 
> 你给的几个链接都是 http://www.latextemplates.com 的，不是 cell 官网也不是 elsevier 官网。

好吧，虽然不算官网但是确实可用，这个问题我已经解决了。
只需要下载model2-names.bst文件并更改样式调用该文件即可
% 参考文献
\bibliographystyle{model2-names.bst} %CELL 格式

**Comment by zepinglee** [comment]
我找到的官方的要求在 https://www.cell.com/cell/authors 的 References 一节，但是官方并没有提供相应的 bst。

Elsevier 官网 https://www.elsevier.com/authors/author-schemas/latex-instructions 提到了：

1. [elsarticle](http://www.ctan.org/tex-archive/macros/latex/contrib/elsarticle)；
2. [els-cas-templates](https://www.ctan.org/pkg/els-cas-templates/)；
3. Elsevier reference styles: [sample manuscript](https://www.elsevier.com/__data/assets/file/0007/56842/elsarticle-template.zip)；

这些模板中的参考文献格式与 Cell 的比较接近的有 `elsarticle-harv.bst`、`model2-names.bst` 和 `model5-names.bst`，但是跟 Cell 的仍然有所差异。

其他有的实现有 https://ctan.org/pkg/cell ，然而这个质量太低，甚至编译有错误。

**Comment by lvhailong** [comment]
> 我找到的官方的要求在 https://www.cell.com/cell/authors 的 References 一节，但是官方并没有提供相应的 bst。
> 
> Elsevier 官网 https://www.elsevier.com/authors/author-schemas/latex-instructions 提到了：
> 
> 1. [elsarticle](http://www.ctan.org/tex-archive/macros/latex/contrib/elsarticle)；
> 2. [els-cas-templates](https://www.ctan.org/pkg/els-cas-templates/)；
> 3. Elsevier reference styles: [sample manuscript](https://www.elsevier.com/__data/assets/file/0007/56842/elsarticle-template.zip)；
> 
> 这些模板中的参考文献格式与 Cell 的比较接近的有 `elsarticle-harv.bst`、`model2-names.bst` 和 `model5-names.bst`，但是跟 Cell 的仍然有所差异。
> 
> 其他有的实现有 https://ctan.org/pkg/cell ，然而这个质量太低，甚至编译有错误。

好的，辛苦啦！目前来说model2-names.bst已经比较接近了，如果不仔细看应该可以通过格式审查
