### ISSUE TITLE
请问图注（或图解）应该怎么插入

### ISSUE THREAD

**Issue by lvhailong** [xueruini/thuthesis#514]
## 编译环境
编译的系统： Overleaf
TeX 发行版：TeX Live 2019 
模板版本：v6.0.2
模板类型：doctor 

## 描述问题
请问如何正确的插入图注或图解（不是图名）

我看到thuthesis模板示例中的插图都是只有图名而没有图解段落，我们学院给的[范文](https://cloud.tsinghua.edu.cn/f/8396e17b0f8f468ab53f/?dl=1)里几乎每个图都需要加入图名和一段落的图解，我尝试使用\subcaption{}命令插入后发现即便只有一个图也会在图解前加上（a）
![截屏2020-04-15上午11 44 21](https://user-images.githubusercontent.com/9078308/79296971-6db46f80-7f0f-11ea-92ca-898b1fb2da50.jpg)
如果插入两次\subcaption{}命令会出现两段（a）（b）开头的图解
![截屏2020-04-15上午11 55 24](https://user-images.githubusercontent.com/9078308/79297208-1531a200-7f10-11ea-8bce-69ed41eaa9b0.jpg)
那么这种不需要标记（a) 或（b）的怎么实现？
![截屏2020-04-15上午11 34 21](https://user-images.githubusercontent.com/9078308/79296965-6b521580-7f0f-11ea-9453-02918c79f48b.jpg)

即便需要标记（a) 和（b）也是应该像这样连续在一个段落里的
![截屏2020-04-15上午11 33 33](https://user-images.githubusercontent.com/9078308/79296953-655c3480-7f0f-11ea-8ba7-ac91c69d2ef5.jpg)

请问有没有办法不自动加入这个（a）或（b）因为我们在描述图解时有可能前后提及的顺序随机，还有像这种第一句不提（a）（b）而是在后面提及的情况。
![截屏2020-04-15上午11 34 43](https://user-images.githubusercontent.com/9078308/79296969-6c834280-7f0f-11ea-972c-0dbc9184d30f.jpg)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{thuthesis}
\begin{document}
\begin{figure}[H] 
  \centering
  \includegraphics{thu-whole-logo.pdf}
  \caption{利用 Xfig 制图}
  \subcaption{由滋养层干细胞自我更新核心转录因子Cdx2、Eomes和Elf5组成的调控网络共同调控了\textit{Esrrb}、Sox2、Gata3和Fgfr2等其余自我更新标记基因，从而使滋养层干细胞得以维持在稳定的自我更新状态。}
  \label{fig:xfig1}
\end{figure}
\end{document}
```

**Comment by xueruini** [comment]
`\caption[目录里的标题]完整的标题。还有图注。规范里没有图注这个东西，一般都是跟着图名一大段话。`

**Comment by lvhailong** [comment]
> ```
> \caption[目录里的标题]{完整的标题。还有图注。规范里没有图注这个东西，一般都是跟着图名一大段话。}
> ```

如果说像您说的这样将“图注”跟在“图名”后面一大段话。可以让这一大段话另起一行并做首行缩进处理吗？应该怎么实现？谢谢！

**Comment by xueruini** [comment]
可以使用普通的格式化命令

**Comment by lvhailong** [comment]
> 可以使用普通的格式化命令

可以麻烦给一小段示范命令吗？我对LATEX命令不熟

**Comment by xueruini** [comment]
`\par`  `\\`  `\parindent` `\hspace` 基本就够了

**Comment by lvhailong** [comment]
> `\par` `\\` `\parindent` `\hspace` 基本就够了

尝试了这样，会无法编译

> \begin{figure}[H] 
> \centering
> \includegraphics{thu-whole-logo.pdf}
> \caption{这是插图标题\par这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落}
> \label{fig:xfig1}
> \end{figure}

换成下面的命令
> \begin{figure}[H] 
>   \centering
>   \includegraphics{thu-whole-logo.pdf}
>   \caption{这是插图标题\\\这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落这是图注段落}
>   \label{fig:xfig1}
> \end{figure}
编译结果如下
![截屏2020-05-07上午12 31 52](https://user-images.githubusercontent.com/9078308/81203572-b0db9d00-8ffa-11ea-99ad-5a1a90b6ec87.jpg)


虽然换行是成功了，但是又带来了新的问题，原来居中的插图标题变成左端对齐了，怎么才能回到居中呢？另外新段落的缩进还是没有实现。

**Comment by zepinglee** [comment]
可以用
```tex
\begin{figure}[h] % use float package if you want it here
  \centering
  \includegraphics{thu-whole-logo.pdf}
  \caption{利用 Xfig 制图}
  \label{fig:xfig1}
  \begingroup
    \captionsetup{format=plain,font=small}
    \caption*{\hspace{2\ccwd}在胚胎发育的第2.5天-第3.5天，Cdx2基因的表达诱发了第一次细胞分化过程，
      由此产生了滋养层干细胞和胚胎干细胞两种细胞类型。}
  \endgroup
\end{figure}
```

这里自动缩进不能正常使用，只能手动缩进了。

**Comment by lvhailong** [comment]
> 可以用
> 
> ```
> \begin{figure}[h] % use float package if you want it here
>   \centering
>   \includegraphics{thu-whole-logo.pdf}
>   \caption{利用 Xfig 制图}
>   \label{fig:xfig1}
>   \begingroup
>     \captionsetup{format=plain,font=small}
>     \caption*{\hspace{2\ccwd}在胚胎发育的第2.5天-第3.5天，Cdx2基因的表达诱发了第一次细胞分化过程，
>       由此产生了滋养层干细胞和胚胎干细胞两种细胞类型。}
>   \endgroup
> \end{figure}
> ```
> 
> 这里自动缩进不能正常使用，只能手动缩进了。

哇，这个好用，完美的解决了我的困惑。
非常感谢！

**Comment by zepinglee** [comment]
@xueruini 要不要提供个命令或者环境封装一下这里的格式设置？

**Comment by xueruini** [comment]
> @xueruini 要不要提供个命令或者环境封装一下这里的格式设置？

如果模板里太多非“内容指令”，我觉得就有违模板的初衷，而且会增加使用门槛。这个问题目前只有一例，先 hold 吧

**Comment by WangYJ2019** [comment]
您好，我遇到了类似的问题。当figure的caption内容比较短的情况下是居中对齐，但是caption大于1行的情况下，
（1）对齐方式发生了改变，从居中对齐变成了左对齐；
（2）图的编号（e.g. “图1.1”这几个字符）发生了悬挂缩进的现象。
与word排版出来的格式完全不一样。请问有办法处理么？
