### ISSUE TITLE
去除摘要和目录页眉

### ISSUE THREAD

**Issue by upuil** [xueruini/thuthesis#515]
我想将模板目录和摘要的页眉去掉，请问如何实现？

**Comment by zepinglee** [comment]
用 `fancyhdr` 定义 page style 然后调用

**Comment by upuil** [comment]
能说一下具体如何定义吗 ？以及添加的位置，我用thu@plain格式去除不了目录和摘要的页眉，提前谢谢啦！

**Comment by zepinglee** [comment]
哪个专业要求这个格式呀？

**Comment by upuil** [comment]
我是外校的 想用一下

**Comment by zepinglee** [comment]
你需要看懂这一段 https://github.com/xueruini/thuthesis/blob/a86b0824da527268645571cc5fe3096d65a665b3/thuthesis.dtx#L1677
