### ISSUE TITLE
请问我make的时候出现这种错误是怎么回事

### ISSUE THREAD

**Issue by fkx16** [xueruini/thuthesis#516]
D:\毕设\Graduation Thesis>make thesis
latexmk main
latexmk: warning: running with administrator privileges
latexmk: The script engine could not be found.
latexmk: Data: scriptEngine="perl.exe", scriptName="latexmk"
Makefile:40: recipe for target 'main.pdf' failed
make: *** [main.pdf] Error 1

**Comment by fkx16** [comment]
补充一下，我用latexmk编译出现的错误是这样的：
D:\毕设\Graduation Thesis>latexmk main.tex

======================================================================

Unfortunately, the package latexmk could not be installed.
Please check the log file:
C:\Users\fkx16\AppData\Local\MiKTeX\2.9\miktex\log\latexmk.log
======================================================================
latexmk: The script could not be found.
latexmk: Data: scriptEngine="perl", scriptName="latexmk", path="scripts/latexmk/latexmk.pl"

**Comment by zepinglee** [comment]
`make` 会调用 `latexmk` 编译，看来没有安装成功

**Comment by stone-zeng** [comment]
miktex 默认不带 perl，因而也不含 latexmk。

**Comment by xueruini** [comment]
可以自己装个perl

**Comment by xueruini** [comment]
Makefile 有必要对 windows 支持以下

**Comment by zepinglee** [comment]
主要是 windows 下 miktex 的问题。

如果没有 latexmk，在 Makefile 中就只能写三遍 `xelatex`，感觉不是很实用。建议不管

**Comment by xueruini** [comment]
windows 默认也没有 make 吧
