### ISSUE TITLE
三个索引只有标题无内容

### ISSUE THREAD

**Issue by xindubawukong** [xueruini/thuthesis#518]
## 编译环境

编译的系统：macOS 10.14
TeX 发行版：TeX Live 2018
模板版本：v6.0.2
模板类型：bachelor

## 描述问题

插图索引、表格索引和公式索引页，只有标题，无内容。

但将3行代码移至`\tableofcontents`前，即可正常显示索引内容。

截图：

![image](https://user-images.githubusercontent.com/22728970/79529033-2f00ef80-809e-11ea-96b4-ee951bfee81d.png)

复现上述问题的代码：
```TeX
\listoffigures    % 插图索引
\listoftables     % 表格索引
\listofequations  % 公式索引
```

**Comment by xindubawukong** [comment]
#467 

与该问题一样，但我已经使用了最新版的thuthesis，仍然不行

**Comment by xindubawukong** [comment]
不好意思，解决了，thx

**Comment by zepinglee** [comment]
在 dev 分支，还没合并到 master 或发布。
