### ISSUE TITLE
请问我在make thesis的时候显示这些是怎么回事？貌似没有make 成功。

### ISSUE THREAD

**Issue by computational-physcis-2011301020083** [xueruini/thuthesis#519]
xetex thuthesis.ins
This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015/Debian) (preloaded format=xetex)
 restricted \write18 enabled.
entering extended mode
(./thuthesis.ins (/usr/share/texlive/texmf-dist/tex/latex/base/docstrip.tex
Utility: `docstrip' 2.5e <2014/09/29>
English documentation    <2014/09/29>

**********************************************************
* This program converts documented macro-files into fast *
* loadable files by stripping off (nearly) all comments! *
**********************************************************

********************************************************
* No Configuration file found, using default settings. *
********************************************************

)

Generating file(s) thuthesis.cls dtx-style.sty 

Processing file thuthesis.dtx (cls) -> thuthesis.cls
                              (dtx-style) -> dtx-style.sty
File thuthesis.dtx ended by \endinput.
Lines  processed: 3727
Comments removed: 1955
Comments  passed: 0
Codelines passed: 1763

***********************************************************
*
* To finish the installation you have to move the following
* files into a directory searched by TeX:
*
* The recommended directory is TEXMF/tex/latex/thuthesis
*
*   thuthesis.cls
*   thuthesis-author-year.bst
*   thuthesis-numeric.bst
*   thuthesis-bachelor.bst
*   tsinghua.pdf
*
* To produce the documentation run the files ending with
* `.dtx' through LaTeX.
*
* Happy TeXing!
***********************************************************
 )
No pages of output.
Transcript written on thuthesis.log.
latexmk main
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
Latexmk: All targets () are up-to-date

**Comment by zepinglee** [comment]
```
latexmk main
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
Latexmk: All targets () are up-to-date
```

**Comment by zepinglee** [comment]
1. 按道理 thuthesis 要求 TeX Live 2017 以上的版本，2017 下是编译不过的；
2. 你这里显示 latexmk 检查到 main.pdf 已经 up-to-date。这里有个问题是，如果你上一次用 latexmk 编译的过程中，第一遍调用 latex 编译没问题，生成了 pdf（但不完整），但是第二遍 latex 时报错（比如参考文献之类的）；之后再调用 latexmk 时就会误以为这个不完整的 pdf 已经 up-to-date。建议：
    1. 删掉 pdf 重新编译；
    2. 在 latexmkrc 里配置 `$go_mode = 1;`，这个 `go_mode` 就是告诉 latexmk 不管有没有 up-to-date 都至少过一遍 latex。

**Comment by computational-physcis-2011301020083** [comment]
多谢多谢，我下载安装的应该是最新的Latex：
sudo apt-get install texlive-full
sudo apt-get install texmaker
然后我
git clone https://github.com/computational-physcis-2011301020083/thuthesis.git
之后直接进去编译的
make
没有编译成功，也没有上一次的pdf文件，很奇怪？

**Comment by computational-physcis-2011301020083** [comment]
我安装的时候：
sudo apt-get install texlive-full
他显示：
Reading package lists... Done
Building dependency tree       
Reading state information... Done
texlive-full is already the newest version (2015.20160320-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
难道是版本不对吗？

**Comment by zepinglee** [comment]
> 多谢多谢，我下载安装的应该是最新的Latex：
> sudo apt-get install texlive-full
> sudo apt-get install texmaker
> 然后我
> git clone https://github.com/xueruini/thuthesis.git
> 之后直接进去编译的
> make
> 没有编译成功，也没有上一次的pdf文件，就像我报告的那个错误，很奇怪？

你的 ubuntu 版本最新的就是 2015。你可以选择：
1. 使用新的 ubuntu
2. 从 https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/ 安装新版 TeX Live，参考 http://tug.org/texlive/doc/texlive-zh-cn/texlive-zh-cn.pdf

**Comment by computational-physcis-2011301020083** [comment]
我重新装了一下，问题解决了，谢谢
