### ISSUE TITLE
生成的PDF文件的属性不包含关键词信息

### ISSUE THREAD

**Issue by srxiong** [xueruini/thuthesis#520]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
模板版本：v6.0.2
模板类型：bachelor

## 描述问题
在v5.5.2的版本中，生成的PDF文件的属性含有关键词信息，可以在Adobe Acrobat Reader DC的Document Properties中看到。在v6.0.2的版本中，此关键词信息丢失。

截图：
v5.5.2
![image](https://user-images.githubusercontent.com/54189844/79568509-89bf3900-80e8-11ea-83f3-832606d93d36.png)

v6.0.2
![image](https://user-images.githubusercontent.com/54189844/79570385-ea9c4080-80eb-11ea-998a-ad43b7f47141.png)

复现上述问题的代码：
main.tex

## 可能的解决办法
将data/abstract.tex里的
keywords = {TeX, LaTeX, CJK, 模板, 论文}
keywords* = {TeX, LaTeX, CJK, template, thesis}
显式地移入thusetup.tex中即可。

猜测出现问题的原因是写入PDF文件信息的操作
![image](https://user-images.githubusercontent.com/54189844/79571024-0a803400-80ed-11ea-8dd3-16b4d7d9c16f.png)
出现在data/abstract.tex将keywords和keywords*条目放入thusetup之前。

**Comment by Harry-Chen** [comment]
确实是的，在 `\begin{document}` 设置的关键词就不会被用上

**Comment by zepinglee** [comment]
使用 `\hypersetup` 设置关键词只有在输出第一页 pdf 前有效，所以你可以将 `\thusetup{keywords = xxx}` 移到 `\begin{document}` 前，比如 `thusetup.tex` 中。

个人觉得目前示例中在 `abstract` 中设置 `keywords` 在逻辑上更流畅一些，相比之下缺少 pdf meta 信息就不是那么重要了。

**Comment by srxiong** [comment]
> 使用 `\hypersetup` 设置关键词只有在输出第一页 pdf 前有效，所以你可以将 `\thusetup{keywords = xxx}` 移到 `\begin{document}` 前，比如 `thusetup.tex` 中。
> 
> 个人觉得目前示例中在 `abstract` 中设置 `keywords` 在逻辑上更流畅一些，相比之下缺少 pdf meta 信息就不是那么重要了。

同意你的观点！
