### ISSUE TITLE
“main.pdf”中的表1.1中的脚注好像没有生效？

### ISSUE THREAD

**Issue by Leojc** [xueruini/thuthesis#521]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2019
模板版本：v6.0.2
模板类型：bachelor

## 描述问题
main.pdf中的表1.1中的脚注好像没有生效？
![批注 2020-04-24 183046](https://user-images.githubusercontent.com/33376945/80203440-bc71b000-8659-11ea-86d2-4391050af85f.jpg)

**Comment by Leojc** [comment]
改用threeparttable包解决了

**Comment by xueruini** [comment]
的确，得查查看

**Comment by xueruini** [comment]
是 4560a315194a30207d0dc3336ad1f123733eb36b 引入的。只要把 hyperref 早点 Require 进来就 OK 了。具体原因还没查。

**Comment by zepinglee** [comment]
LaTeX 传统的习惯是把表注写到 caption 里，所以经常是很长的一大段 caption。学校要求的格式是，表题在表格上方，表注在下方，所以 LaTeX 传统的用法不太适合这种格式。

我个人不太赞成在 `minipage` 里用 `\footnote`，感觉 `threeparttable` 的方案更舒服一些，似乎也是 TeXFAQ 推荐的（https://texfaq.org/FAQ-footintab）。我觉得基于 `threeparttable` 适配一下格式更好。

**Comment by zepinglee** [comment]
`hyperref` 的文档地 9.1.37 节：
> Linked footnotes are not supported inside environment ‘tabularx’, because they uses the optional argument of \footnotetext, see section ‘Limitations’. Before version 2011/09/28 6.82i hyperref had disabled footnotes entirely by ‘hyperfootnotes=false’.

感觉直接交换顺序有潜在 bug 的风险。

**Comment by zepinglee** [comment]
另外研究生写作指南第 11 页：
> 若图或表中有附注，采用英文小写字母顺序编号，附注写在图或表的下方。

本科生写作指南：
> 若图或表中有附注，对其应采用如：①、②顺序编号；附注写在图或表的下方。

两者要求的编号方式不一样。

目前用 `minipage` + 脚注的实现会多一条脚注线，比较影响美观。
<img width="590" alt="Screen Shot 2020-05-19 at 10 16 55 AM" src="https://user-images.githubusercontent.com/12290822/82277246-f06e9580-99b9-11ea-846d-0c6295bf5a95.png">

`threeparttable` 的方式需要手动编号，其实也没比直接手写（复杂表格示例 1）好多少。
```tex
\begin{table}
  \begin{threeparttable}[b]
    \caption{...}
    \begin{tabular}...% or {tabular*}
      ...42\tnote{1}&....  ...
    \end{tabular}
    \begin{tablenotes}
    \item [1] the first note ...
    \end{tablenotes}
  \end{threeparttable}
\end{table}
```

**Comment by xueruini** [comment]
那就 threepart 吧。hyperref 冲突太多，放在最后妥当
