### ISSUE TITLE
本科生模板，日期与上方内容距离太近怎么办？

### ISSUE THREAD

**Issue by Leojc** [xueruini/thuthesis#522]
## 编译环境
编译的系统： Windows 10 
TeX 发行版：TeX Live 2019 
模板版本：v6.0.2
模板类型：bachelor

## 描述问题
本科生模板，日期与上方内容距离太近

截图：
![批注 2020-04-24 181955](https://user-images.githubusercontent.com/33376945/80202539-5d5f6b80-8658-11ea-82ec-4cc69cb2407b.jpg)

**Comment by zepinglee** [comment]
封面的各部分都是设置的固定位置，但是没考虑“辅导教师”一行，所以日期跟上面距离太近。

可以在日期这里改成相对位置。

**Comment by Leojc** [comment]
> 
> 
> 封面的各部分都是设置的固定位置，但是没考虑“辅导教师”一行，所以日期跟上面距离太近。
> 
> 可以在日期这里改成相对位置。

请问如何改成相对位置呀，是修改thuthesis.cls文件吗？我对这个不太熟

**Comment by zepinglee** [comment]
> > 封面的各部分都是设置的固定位置，但是没考虑“辅导教师”一行，所以日期跟上面距离太近。
> > 可以在日期这里改成相对位置。
> 
> 请问如何改成相对位置呀，是修改thuthesis.cls文件吗？我对这个不太熟

我还没写好，稍后推到 `dev` 分支

**Comment by Leojc** [comment]
> 
> 
> > > 封面的各部分都是设置的固定位置，但是没考虑“辅导教师”一行，所以日期跟上面距离太近。
> > > 可以在日期这里改成相对位置。
> > 
> > 
> > 请问如何改成相对位置呀，是修改thuthesis.cls文件吗？我对这个不太熟
> 
> 我还没写好，稍后推到 `dev` 分支

好的，非常感谢！

**Comment by xueruini** [comment]
跟这个是一回事么？https://github.com/xueruini/thuthesis/pull/434#issuecomment-569396322

**Comment by zepinglee** [comment]
不太一样，这个是本科生的

**Comment by Leojc** [comment]
请问这个问题解决了吗？

**Comment by zepinglee** [comment]
已经写好了，还没推上来
