### ISSUE TITLE
本科生论文关于文献调研部分

### ISSUE THREAD

**Issue by wanzzc** [xueruini/thuthesis#523]
## 编译环境
编译的系统：Windows 10 
TeX 发行版：TeX Live 2019
模板版本：v5.5.2
模板类型：bachelor

## 描述问题
《本科生学位论文写作指南》第 15条要求说明附录需要单独的参考文献部分，而模板编译的结果是和正文整合在一起的

截图：

复现上述问题的代码：
```TeX
\bibliographystyle{thuthesis-bachelor}     % 本科生参考文献的著录格式
\bibliography{ref/appendix}

\end{survey}

```

**Comment by wanzzc** [comment]
我看到thuthesis.pdf说明里面应该是按照标准来设计的，但我运行之后没法生成对应的结果，survey环境里面似乎还是在ref当中寻找参考文献

**Comment by zepinglee** [comment]
“和正文整合在一起”是什么意思？

**Comment by wanzzc** [comment]
就是说appendix部分的参考文献还是到ref.bib里面寻址，而且最后生成在正文后面附的参考文献里面，附录部分没有单独生成参考文献列表

**Comment by wanzzc** [comment]
写作指南里面要求是附录部分有自己的参考文献表和编号

**Comment by wanzzc** [comment]
等于是thuthesis.pdf当中提到的bibunits宏包没起到作用

**Comment by zepinglee** [comment]
复现不出你描述的问题

**Comment by wanzzc** [comment]
您这边运行的话是正常的是吗？

**Comment by zepinglee** [comment]
> 您这边运行的话是正常的是吗？

对，你可以把其他内容删掉后打包发上来

**Comment by wanzzc** [comment]
https://cloud.tsinghua.edu.cn/d/3a367ad370554c9fafb0/
我这边网络有点问题，github传不上来东西，我把压缩包放在清华云盘里面了，跟您这边的发布版本比几乎没什么改动，就是把附录换成了survey，现在运行出来就不正常

**Comment by wanzzc** [comment]
![Snipaste_2020-04-30_19-50-49](https://user-images.githubusercontent.com/39272017/80707077-f6402c00-8b1b-11ea-8579-a9f18c326926.png)

**Comment by wanzzc** [comment]
附录部分运行的效果就是上面那张图的样子

**Comment by zepinglee** [comment]
<img width="702" alt="Screen Shot 2020-04-30 at 7 57 53 PM" src="https://user-images.githubusercontent.com/12290822/80707640-e37a2700-8b1c-11ea-95ff-aa3bf2322379.png">

这没有问题啊

**Comment by wanzzc** [comment]
我这边运行出来不是这个效果

**Comment by wanzzc** [comment]
最后参考文献的这一部分没有出现

**Comment by wanzzc** [comment]
![Snipaste_2020-04-30_20-04-27](https://user-images.githubusercontent.com/39272017/80708192-d3af1280-8b1d-11ea-8690-dc6e2f14927f.png)

**Comment by zepinglee** [comment]
`dev` 分支已经补充了编译说明：
<img width="701" alt="Screen Shot 2020-04-30 at 8 05 29 PM" src="https://user-images.githubusercontent.com/12290822/80708277-01945700-8b1e-11ea-9d9d-6f75366a29f8.png">

建议使用 `latexmk` 编译。

**Comment by wanzzc** [comment]
用这个方法问题解决了，非常感谢，之前是拿texstudio作编译器的

**Comment by thuliu-yt16** [comment]
@wanzzc 同样的问题我重新编译就解决了
