### ISSUE TITLE
main.tex使用\spines生成书脊后，下文格式出现错误

### ISSUE THREAD

**Issue by Hang-Zhang** [xueruini/thuthesis#524]
![屏幕快照 2020-05-01 上午11 26 47](https://user-images.githubusercontent.com/32285641/80779598-b1a9a480-8b9e-11ea-93db-bc8ae5a393b8.png)

**Comment by xueruini** [comment]
`\spine` 要独立使用，不能跟正文混在一起

**Comment by Conanzhou** [comment]
使用{\spine},大括号可以限制环境
