### ISSUE TITLE
运行报错，求助

### ISSUE THREAD

**Issue by weiguoguo** [xueruini/thuthesis#525]
## 编译环境
编译的系统： Windows 10 
TeX 发行版：TeX Live 2019
模板版本：最新版
模板类型： master

## 描述问题
在texwork中编译时中断，显示如下：
<img width="562" alt="error" src="https://user-images.githubusercontent.com/37107336/80793212-1a0d7b80-8bc9-11ea-9ff0-0f7b236632dd.png">
See the kvsetkeys package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.96 }
      
? 

截图

**Comment by zepinglee** [comment]
需要 `xetex thuthesis.ins` 生成 `thuthesis.cls`，否则会找到 texlive 中旧版本的 thuthesis.cls。

**Comment by weiguoguo** [comment]
谢谢作者的回答，问题解决了，再次表示感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeping Lee"<notifications@github.com&gt;; 
发送时间: 2020年5月1日(星期五) 晚上11:11
收件人: "xueruini/thuthesis"<thuthesis@noreply.github.com&gt;; 
抄送: "天苍清落"<615277872@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xueruini/thuthesis] 运行报错，求助 (#525)





 
需要 xetex thuthesis.ins 生成 thuthesis.cls，否则会找到 texlive 中旧版本的 thuthesis.cls。

**Comment by zepinglee** [comment]
@xueruini 我上次跟 @stone-zeng 讨论，感觉不是很有必要使用 `dtx` 这套东西。`dtx` 的优势在于生成文档；但是代码的注释在编辑器中阅读比在 PDF 更方便，而且带来的劣势是给用户升级版本造成了一些麻烦，所以经常有人问关于 dtx 的问题。

**Comment by xueruini** [comment]
还好吧，还是可以有一点小情怀。

升级的确会有不便之处，尤其是不用命令行的，不过这个情况一般出现在非正式发布的版本，正式版本里都会带上 cls

**Comment by Harry-Chen** [comment]
> 还好吧，还是可以有一点小情怀。
> 
> 升级的确会有不便之处，尤其是不用命令行的，不过这个情况一般出现在非正式发布的版本，正式版本里都会带上 cls

这几天被问了很多，80% 的人遇到的错都是因为没有生成 cls 所以用了老版本的模板。我倒是也感觉其实文档放代码可能不是那么必要，直接提供 cls 感觉会更干净一点。
