### ISSUE TITLE
为 survey 和 translation 环境提供独立的目录

### ISSUE THREAD

**Issue by Harry-Chen** [xueruini/thuthesis#526]
和 @zepinglee 讨论了一下，本科生的 `survey` 和 `translation` 环境应该允许生成目录放在相应部分的开头。一些理由可能包括：

1. 要翻译的文献自带目录，尊重原有格式
2. 内容较长，难以定位和检索（未包含于主目录中）

似乎原本 `titletoc` 宏包能够做到这件事情（即独立目录，就像 `bibunit`），但是因为模板里面一些黑魔法，似乎 `titletoc` 无法正确工作。

**Comment by xueruini** [comment]
> 因为模板里面一些黑魔法，似乎 `titletoc` 无法正确工作。

有时候都不知道是哪里踩雷了，比如下午跟了许久也不得其法，最后发现换一下加载顺序就行了 https://github.com/xueruini/thuthesis/pull/527/files#diff-c64e7e4bcc905414850428220f37b1cf

titletoc 也是在操作 starttoc, xxxmark 这些内部函数/变量，冲突了一点都不奇怪。。。

**Comment by zepinglee** [comment]
`titletoc` 跟 LaTeX 原来的 toc 功能肯定是冲突的，所以有两套方案：

1. 基于 `titletoc` 重新实现目前的目录格式，这样可以在 `survey` 里用 `titletoc` 的 partial TOC 功能。

2. 沿用 LaTeX 的 toc 功能，把 `survey` 的目录写到新的文件（类似 `.toc`）中再读取，需要 patch `\section`, `\subsection` 等命令的 `\addcontentsline{toc}`，而且还要考虑跟 `ctex` 和 `hyperref` 的兼容性。

推荐方案 1。

**Comment by Harry-Chen** [comment]
我觉得方案 1 是比较科学的

**Comment by zepinglee** [comment]
> 我觉得方案 1 是比较科学的

我刚试了一下，发现有两条需求要同时实现比较麻烦：

1. 附录的节标题不加入主目录（目前用的方法是在 `.toc` 文件中设置 `tocdepth=0`）；
2. survey 环境的节标题要写入 `.ptc` 文件供 `titletoc` 处理这部分的 partial toc，但是这里会受到 `tocdepth=0` 的影响。

感觉还需要 hack 进 `titletoc` 的代码。

**Comment by zepinglee** [comment]
@Harry-Chen 试下 a18c8ac ？

**Comment by Harry-Chen** [comment]
> @Harry-Chen 试下 [a18c8ac](https://github.com/xueruini/thuthesis/commit/a18c8ac44aee01b031d85f9a9a5e4a09a61aa285) ？

试了一下，感觉没问题。尝试手动 `\addcontentsline` 也是对的。

**Comment by zepinglee** [comment]
图表索引的格式忘记设置了

**Comment by Harry-Chen** [comment]
对了，是不是改一下示例 `latexmkrc` 还有 `.gitignore`，把 `ptc` 都加进去
