### ISSUE TITLE
本科论文写作中附录A书面翻译原文索引失败

### ISSUE THREAD

**Issue by invisiblecloak-slw** [xueruini/thuthesis#528]
## 编译环境
编译的系统：macOS 10.15
TeX 发行版：TeX Live 2019
模板版本：v6.0.2
模板类型：bachelor

## 描述问题
《本科综合论文训练论文写作指南》第 3 页要求附录A书面翻译需注明外文资料原文的索引。

而模板编译的结果是：将外文资料的BibTex文件填写在ref/refs.bib中，在appendix-translation.tex文件中声明\nocite{dorigo1996ant}，按照xelatex->bibtex->xelatex->xelatex的编译顺序进行编译，结果提示Citation '...' Undefined

截图：

https://sbimg.cn/image/m9UCa
https://sbimg.cn/image/m9arM

**Comment by Harry-Chen** [comment]
用 latexmk 编译，新版模板用的 `bibunits` 需要特殊处理。
