### ISSUE TITLE
translation环境中被翻译外文资料的独立references

### ISSUE THREAD

**Issue by invisiblecloak-slw** [xueruini/thuthesis#529]
通过在main.tex中打开\input{data/appendix-translation}命令

并在appendix-translation.tex中加入
```
\nocite{label}
\bibliographystyle{plainnat}
\bibliography{ref/appendix}
```

即可输出被翻译外文资料的原文索引。

请问如何为被翻译的外文资料输出其独立的参考文献，用以在翻译过程中\cite{}呢？

**Comment by Harry-Chen** [comment]
你引用的这段话就是你想做的事情吧？

**Comment by invisiblecloak-slw** [comment]
想要为translate做两件事：

1.输出被翻译外文文献自身的参考文献，用以在翻译过程中cite。

2.按照综合论文训练写作指南的要求，在最后附上被翻译文献的原文索引。

上面的代码成功解决了2中的需求，但是如果在翻译过程中直接\cite{}原文引用的某一文献，1和2的参考文献列表是共享的。

请问如何分别输出被翻译文章的references以及原文索引呢？谢谢！

**Comment by Harry-Chen** [comment]
> 为外文资料的调研阅读报告或书面翻译。调研阅读报告需附参考文献；书面翻译需注明外文资料原文的索引

这句话确实有一点点歧义。如果你想把两个分开的话，你可以参考模板里面 translation 环境的实现，自己模拟它。也就是使用独立的 bibunit 来区分这两个环境

**Comment by Harry-Chen** [comment]
@zepinglee 我感觉确实有这个问题，文献本身有 reference，然后要带一个原文索引，可以理解为两个独立的 bibunit

**Comment by invisiblecloak-slw** [comment]
感谢！期待模版支持这一特性，现在准备学一下bibunit达成这一目标。

**Comment by invisiblecloak-slw** [comment]
```
\newenvironment{translation}{%
  \chapter{外文资料的书面翻译}%
  \thu@setenglish
  \let\title\thu@appendix@title
  \let\maketitle\thu@appendix@maketitle
  \renewcommand\bibname{书面翻译对应的原文索引}%
  \let\bibsection\thu@appendix@bibsection
  \renewcommand\@bibunitname{main-translation}%
  \let\bibliographystyle\defaultbibliographystyle
  \let\bibliography\thu@appendix@bibliography
\begin{bibunit}%
}{%
  \end{bibunit}%
}
```
附录A的标号是以A.x.x开头的，对于外文翻译的references，标号应该是A.x 参考文献。请问应该如何修改translation的环境，来模拟出两个独立的bibunit呢？谢谢！(做了一点尝试，但是没能成功)

**Comment by Harry-Chen** [comment]
> ```
> \newenvironment{translation}{%
>   \chapter{外文资料的书面翻译}%
>   \thu@setenglish
>   \let\title\thu@appendix@title
>   \let\maketitle\thu@appendix@maketitle
>   \renewcommand\bibname{书面翻译对应的原文索引}%
>   \let\bibsection\thu@appendix@bibsection
>   \renewcommand\@bibunitname{main-translation}%
>   \let\bibliographystyle\defaultbibliographystyle
>   \let\bibliography\thu@appendix@bibliography
> \begin{bibunit}%
> }{%
>   \end{bibunit}%
> }
> ```
> 
> 附录A的标号是以A.x.x开头的，对于外文翻译的references，标号应该是A.x 参考文献。请问应该如何修改translation的环境，来模拟出两个独立的bibunit呢？谢谢！(做了一点尝试，但是没能成功)

参考文献一般不会标上章节编号的。其实我有一个比较脏的办法，可以直接拿来用。你把这里的“书面翻译对应的原文索引“改成参考文献。然后在 translation 环境中间起一个 section* 叫”书面翻译对应的原文索引“，直接用 bibitem 手写原文索引。考虑到原文不会有很多篇，这样做应该是最省力的

**Comment by invisiblecloak-slw** [comment]
摸索到一种方式：

在appendix-translation.tex的最后\sectiton{参考文献} (或\section*{参考文献})。

这样会为参考文献分配隶属于附录A的编号，形如A.x 参考文献 (或 参考文献)

之后通过对itemize的格式控制可以手动输出被翻译文献的references，不需要改动translate环境中“书面翻译对应的原文索引”。达到与translate环境相似的输出环境(不足之处是每一条item内部的行间距尚未找到格式控制方法)。

这种方法有一种好处是：可以直接复制被翻译文献的references，劳动量可能也不是很大233

完整代码为：
```
\section{参考文献}
{
  \small
  \begin{itemize}[leftmargin=15pt,parsep=5pt]
      \item [{[1]}] M. Dorigo and L. M. Gambardella, “Ant colony system: a cooperative learning approach to the traveling salesman problem,” IEEE Transactions on evolutionary computation, vol. 1, no. 1, pp. 53–66, 1997.
  \end{itemize}
}
```

**Comment by Harry-Chen** [comment]
> 摸索到一种方式：
> 
> 在appendix-translation.tex的最后\sectiton{参考文献} (或\section*{参考文献})。
> 
> 这样会为参考文献分配隶属于附录A的编号，形如A.x 参考文献 (或 参考文献)
> 
> 之后通过对itemize的格式控制可以手动输出被翻译文献的references，不需要改动translate环境中“书面翻译对应的原文索引”。达到与translate环境相似的输出环境(不足之处是每一条item内部的行间距尚未找到格式控制方法)。
> 
> 这种方法有一种好处是：可以直接复制被翻译文献的references，劳动量可能也不是很大233
> 
> 完整代码为：
> 
> ```
> \section{参考文献}
> {
>   \small
>   \begin{itemize}[leftmargin=15pt,parsep=5pt]
>       \item [{[1]}] M. Dorigo and L. M. Gambardella, “Ant colony system: a cooperative learning approach to the traveling salesman problem,” IEEE Transactions on evolutionary computation, vol. 1, no. 1, pp. 53–66, 1997.
>   \end{itemize}
> }
> ```

无论哪部分手写，我还是建议在 thebibliography 环境中写 bibitem，这种用 itemize 的方法太裸了。

**Comment by robertying** [comment]
不改源代码的 workaround：

```tex
...

  \renewcommand\bibname{参考文献}
  \bibliographystyle{thuthesis-bachelor}
  \bibliography{ref/translation}

  \renewcommand\bibname{书面翻译对应的原文索引}
  \begin{thebibliography}{2}
    \bibitem{abrahams99tex}
    P.~W. Abrahams, K.~Berry, and K.~A. Hargreaves, \emph{{\TeX} for the
      Impatient}.\hskip 1em plus 0.5em minus 0.4em\relax Addison-Wesley, 1990.

    \bibitem{salomon1995advanced}
    D.~Salomon, ``The advanced {\TeX}book.''\hskip 1em plus 0.5em minus 0.4em\relax
    New York: Springer, 1995.
  \end{thebibliography}
```

**Comment by Harry-Chen** [comment]
@zepinglee 有什么想法吗，我觉得可以切成三个 bibunit

**Comment by zepinglee** [comment]
> @zepinglee 有什么想法吗，我觉得可以切成三个 bibunit

感觉可以搞三个 bibunit，但是这里要改接口 `\bibliography`，算是 breaking change，需要跳个稍大一点的版本号。

另外“原文索引”这部分接口怎么命名？（又到了令人难受的起名）

**Comment by Harry-Chen** [comment]
> > @zepinglee 有什么想法吗，我觉得可以切成三个 bibunit
> 
> 感觉可以搞三个 bibunit，但是这里要改接口 `\bibliography`，算是 breaking change，需要跳个稍大一点的版本号。
> 
> 另外“原文索引”这部分接口怎么命名？（又到了令人难受的起名）

诶这个为什么算是 breaking change 了？似乎用法没有改变啊？

**Comment by zepinglee** [comment]
> 诶这个为什么算是 breaking change 了？似乎用法没有改变啊？

原来的是用 `\bibliography` 生成“原文索引”，现在用来生成参考文献。“原文索引”需要另搞个环境。

**Comment by Harry-Chen** [comment]
> > 诶这个为什么算是 breaking change 了？似乎用法没有改变啊？
> 
> 原来的是用 `\bibliography` 生成“原文索引”，现在用来生成参考文献。“原文索引”需要另搞个环境。

我觉得两边都可以用 biblography？相当于增加另一个

**Comment by zepinglee** [comment]
> 我觉得两边都可以用 biblography？相当于增加另一个

```TeX
% 生成参考文献
\cite{abrahams99tex}
\bibliographystyle{plainnat}
\bibliography{ref/appendix}

% 生成原文索引
\begin{bibunit}
  \makeatletter
  \renewcommand\@bibunitname{main-index}%
  \makeatother
  \renewcommand\bibname{书面翻译对应的原文索引}%
  \nocite{salomon1995advanced}
  \bibliographystyle{plainnat}
  \bibliography{ref/appendix}
\end{bibunit}
```
第二部分最好封装起来

**Comment by Harry-Chen** [comment]
> > 我觉得两边都可以用 biblography？相当于增加另一个
> 
> ```
> % 生成参考文献
> \cite{abrahams99tex}
> \bibliographystyle{plainnat}
> \bibliography{ref/appendix}
> 
> % 生成原文索引
> \begin{bibunit}
>   \makeatletter
>   \renewcommand\@bibunitname{main-index}%
>   \makeatother
>   \renewcommand\bibname{书面翻译对应的原文索引}%
>   \nocite{salomon1995advanced}
>   \bibliographystyle{plainnat}
>   \bibliography{ref/appendix}
> \end{bibunit}
> ```
> 
> 第二部分最好封装起来

明白了，我的想法是可以做一个环境，比如叫 `index`，然后允许用户在里面用 `\bibliography` 或者手写 `\bibitem`，是这个意思么

**Comment by zepinglee** [comment]
> 明白了，我的想法是可以做一个环境，比如叫 `index`，然后允许用户在里面用 `\bibliography` 或者手写 `\bibitem`，是这个意思么

不完全是，
```tex
% 生成原文索引
\begin{translation-index}
  \nocite{salomon1995advanced}
  \bibliographystyle{plainnat}
  \bibliography{ref/appendix}
\end{translation-index}
```
主要是模板不应该暴露 `\begin{translation-index}` 和 `\renewcommand\@bibunitname` 这些内容

**Comment by zepinglee** [comment]
现在“书面翻译对应的原文索引”改为用 `translation-index` 环境。

**Comment by Harry-Chen** [comment]
> > 明白了，我的想法是可以做一个环境，比如叫 `index`，然后允许用户在里面用 `\bibliography` 或者手写 `\bibitem`，是这个意思么
> 
> 不完全是，
> 
> ```
> % 生成原文索引
> \begin{translation-index}
>   \nocite{salomon1995advanced}
>   \bibliographystyle{plainnat}
>   \bibliography{ref/appendix}
> \end{translation-index}
> ```
> 
> 主要是模板不应该暴露 `\begin{bibunit}` 和 `\renewcommand\@bibunitname` 这些内容

其实我想说的就是你这段代码的意思，我的意思是如果同学不想用生成的索引还可以手写

**Comment by zepinglee** [comment]
@xueruini `dev` 分支已经积累了不少 commits 啦，感觉需要跳个版本 v6.1 了。

**Comment by xueruini** [comment]
这几天我读一下
