### ISSUE TITLE
引用中文文献会出现“问号”乱码

### ISSUE THREAD

**Issue by wxsthuee** [xueruini/thuthesis#531]
## 编译环境
编译的系统：macOS 10.15
TeX 发行版：MacTeX 2019
模板版本：v6.0.0
模板类型：doctor

## 描述问题
引用中文文献会出现“问号”乱码，如：
[131] ??? ??????? ???????????, 2001.

bib中文献为：
@book{xlong2001information,
  title={应用信息论基础},
  author={朱雪龙},
  year={2001},
  publisher={清华大学出版社有限公司}
}

**Comment by xueruini** [comment]
你的 bib 文件什么编码

**Comment by wxsthuee** [comment]
> 你的 bib 文件什么编码

改成UTF-8之后就可以了！多谢您！
