### ISSUE TITLE
封面日期的字体错误

### ISSUE THREAD

**Issue by Leojc** [xueruini/thuthesis#532]
## 编译环境
编译的系统： Windows 10
TeX 发行版：TeX Live 2020
模板版本：v6.0.2
模板类型：bachelor

## 描述问题
《本科生综合论文训练论文写作指南》要求“论文成文打印的日期用阿拉伯数字，采用小四号宋体。”而模板编译的结果是Times New Roman

**Comment by zepinglee** [comment]
嗯，这个可以改一下
