### ISSUE TITLE
如何正确引用网络电子文献

### ISSUE THREAD

**Issue by namespaceXP** [xueruini/thuthesis#533]
“除此之外的电子 文献的著录格式如下:
[序号]主要责任者. 题名:其他题名信息[文献类型标志/文献载体标志]. 出版地:出版者，出版年(更新或修改日期) [引用日期].获取和 访问路径(联机文献必备).”

**Comment by zepinglee** [comment]
你想表达什么？

**Comment by namespaceXP** [comment]
就是如何以上面说的格式引用电子文献，主要是引用日期这部分。直接调url包好像只能显示出版年，没办法打出[引用日期]。

**Comment by zepinglee** [comment]
> 就是如何以上面说的格式引用电子文献，主要是引用日期这部分。直接调url包好像只能显示出版年，没办法打出[引用日期]。

引用日期在 BibTeX 的域是 `urldate`，参考 https://github.com/CTeX-org/gbt7714-bibtex-style
