### ISSUE TITLE
请问怎么引用本科学位论文？

### ISSUE THREAD

**Issue by Diyorazh** [xueruini/thuthesis#534]
## 编译环境
编译的系统：Overleaf
TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
模板版本：v5.5.2
模板类型： bachelor

## 描述问题
请问怎么引用本科学位论文？
refs.bib里面没有出现bachlorsthesis的格式，只有硕士和博士的。我试图写成bachelorsthesis的格式却告诉我没有定义。

谢谢～

复现上述问题的代码：
`@bachelorsthesis{xyz,
  author =       {xyz},
  title =        {xyzzyx模型的研究},
  school =       {清华大学},
  year =         2018,
  address =      {北京},
}`

**Comment by zepinglee** [comment]
BibTeX 没有 `bachelorsthesis` 的类型，研究生写作指南也没提到引用本科生论文的格式。

一般不会饮用本科生的学位论文吧。

**Comment by Diyorazh** [comment]
可是我需要引用本科生的论文……

**Comment by zepinglee** [comment]
那你直接用 `phdthesis` 吧，学校本科生的参考文献格式要求不区分学位类型。

**Comment by Diyorazh** [comment]
谢谢！不过如果我要cite 硕士论文的话 我用bachelor的版本里面bibtex `masterthesis `里面也会出现[硕士学位论文]的？

**Comment by Diyorazh** [comment]
我碰巧有一个本科论文和一个硕士论文要用……

**Comment by zepinglee** [comment]
> 谢谢！不过如果我要cite 硕士论文的话 我用bachelor的版本里面bibtex `masterthesis `里面也会出现[硕士学位论文]的？

`\bibliographystyle{thuthesis-bachelor}` 会出现“[硕士学位论文]”？不应该呀，你试下最新的 dev 版？

**Comment by Diyorazh** [comment]
啊，好的，我之前用的是Numeric. 谢谢！不过换成了bachelor以后好像所有的格式都变了，作者变成了大写的。所以哪个才是符合本科生要求的格式呢？

**Comment by zepinglee** [comment]
> 啊，好的，我之前用的是Numeric. 谢谢！不过换成了bachelor以后好像所有的格式都变了，作者变成了大写的。所以哪个才是符合本科生要求的格式呢？

见 http://www.law.tsinghua.edu.cn/publish/law/7024/2012/20120216153516317135347/20120216153516317135347_.html 的 2019 年版《参考文献著录格式》

**Comment by Diyorazh** [comment]
非常感谢～！！！
