### ISSUE TITLE
封面格式的问题

### ISSUE THREAD

**Issue by JL-Cheng** [xueruini/thuthesis#535]
您好，我编译之后，封面上“系别、专业、姓名、指导教师”这部分没有居中而且距离标题太远了，我想问一下我应该在哪里修改这个格式？
![image](https://user-images.githubusercontent.com/30789532/82279842-0e3ef900-99c0-11ea-9c45-9faf52fbe878.png)

**Comment by zepinglee** [comment]
你可以跟 [综合论文训练-论文样例.pdf](http://www.law.tsinghua.edu.cn/publish/law/7024/20120216153516317135347/1487557620435.pdf) 对比一下，系别、专业这部分内容的绝对位置是一样的，只是你的题目只有一行，显得之间的空白比较大
