### ISSUE TITLE
本科论文封面允许加入“联合指导教师”

### ISSUE THREAD

**Issue by Harry-Chen** [xueruini/thuthesis#537]
RT，有一些系对此有要求（比如数学系）。目前模板里面对于宽度有限制，如果加入的话，会变成这样：

![image](https://user-images.githubusercontent.com/2819727/82398046-76efa980-9a84-11ea-8a24-79936aa624aa.png)

模板里面 `\thu@info@item` 里定义的 `\thu@fixed@box` 限制了宽度。

**Comment by Harry-Chen** [comment]
不过把这个 size 改成六个字以后感觉有点丑…特别是没有“联合指导教师”的时候

**Comment by zepinglee** [comment]
> 不过把这个 size 改成六个字以后感觉有点丑…特别是没有“联合指导教师”的时候

你这是新加了一行吧？我感觉这个必须用 `\scalebox` 了：
```tex
\scalebox{0.8}[1]{\thu@fixed@box{5em}{联合指导教师}}：\thu@name@title{\thu@joint@supervisor}%
```

感觉效果还可以：
<img width="416" alt="Screen Shot 2020-05-20 at 12 23 25 PM" src="https://user-images.githubusercontent.com/12290822/82404772-b625f680-9a94-11ea-9887-f44eaab1e301.png">

**Comment by Harry-Chen** [comment]
> > 不过把这个 size 改成六个字以后感觉有点丑…特别是没有“联合指导教师”的时候
> 
> 你这是新加了一行吧？我感觉这个必须用 `\scalebox` 了：
> 
> ```
> \scalebox{0.8}[1]{\thu@fixed@box{5em}{联合指导教师}}：\thu@name@title{\thu@joint@supervisor}%
> ```
> 
> 感觉效果还可以：
> <img alt="Screen Shot 2020-05-20 at 12 23 25 PM" width="416" src="https://user-images.githubusercontent.com/12290822/82404772-b625f680-9a94-11ea-9887-f44eaab1e301.png">

我是直接把行宽改成 6em 了，确实不太行。这样看起来好不少

**Comment by zepinglee** [comment]
感觉压缩的字还是不太好看，你还可以考虑这两种方案：

1. 像“01-博-1-中文6学术型封面（有联合导师）.doc”一样用“联合导师”：

<img width="411" alt="Screen Shot 2020-05-20 at 12 49 04 PM" src="https://user-images.githubusercontent.com/12290822/82406081-4b76ba00-9a98-11ea-969f-17de0aa30d44.png">


2. 像”01-硕-1-中文1学术型硕士封面.doc“一样统一用 5.5em 的宽度：

<img width="408" alt="Screen Shot 2020-05-20 at 12 55 50 PM" src="https://user-images.githubusercontent.com/12290822/82406471-4d8d4880-9a99-11ea-85a7-e9a73c43f40f.png">

**Comment by Harry-Chen** [comment]
> 感觉压缩的字还是不太好看，你还可以考虑这两种方案：
> 
> 1. 像“01-博-1-中文6学术型封面（有联合导师）.doc”一样用“联合导师”：
> 
> <img alt="Screen Shot 2020-05-20 at 1 00 08 PM" width="384" src="https://user-images.githubusercontent.com/12290822/82406696-ddcb8d80-9a99-11ea-82bd-5f11c9205fd1.png">
> 
> 1. 像”01-硕-1-中文1学术型硕士封面.doc“一样统一用 5.5em 的宽度：
> 
> <img alt="Screen Shot 2020-05-20 at 12 55 50 PM" width="408" src="https://user-images.githubusercontent.com/12290822/82406471-4d8d4880-9a99-11ea-85a7-e9a73c43f40f.png">

我看了一下和咨询了一下，似乎没有宽度这方面的要求。我倾向于把模板的宽度整个改成 5.5 em，然后加入联合指导教师的这一行。就算没有这么长的一行的话，也还不算丑。你觉得呢？

**Comment by zepinglee** [comment]
> 我看了一下和咨询了一下，似乎没有宽度这方面的要求。我倾向于把模板的宽度整个改成 5.5 em，然后加入联合指导教师的这一行。就算没有这么长的一行的话，也还不算丑。你觉得呢？

可以根据 `\thu@joint@supervisor` 是否为空选择宽度。

**Comment by Harry-Chen** [comment]
> > 我看了一下和咨询了一下，似乎没有宽度这方面的要求。我倾向于把模板的宽度整个改成 5.5 em，然后加入联合指导教师的这一行。就算没有这么长的一行的话，也还不算丑。你觉得呢？
> 
> 可以根据 `\thu@joint@supervisor` 是否为空选择宽度。

嗯，这更好了，我去改一下模板吧

**Comment by zepinglee** [comment]
> 嗯，这更好了，我去改一下模板吧

见 3ca9866 。

**Comment by Harry-Chen** [comment]
有点快，我刚准备 commit。。。
