### ISSUE TITLE
本科生模板的封面姓名那一段文字没有居中，是向左偏的

### ISSUE THREAD

**Issue by Leojc** [xueruini/thuthesis#540]
## 编译环境
编译的系统：Windows 10 
TeX 发行版：TeX Live 2020
模板版本：dev
模板类型：bachelor

## 描述问题
本科生模板的封面姓名那一段文字没有居中，是向左偏的，不知应该如何调节呢，谢谢

**Comment by zepinglee** [comment]
> 本科生模板的封面姓名那一段文字没有居中，是向左偏的，不知应该如何调节呢，谢谢

哪里？给个截图？

**Comment by Leojc** [comment]
![批注 2020-05-25 224420](https://user-images.githubusercontent.com/33376945/82823050-6b174380-9ed9-11ea-8360-4cbad7682a26.jpg)

**Comment by Leojc** [comment]
#535 就是这个问题

**Comment by Leojc** [comment]
原来样例就是偏的吗……我们没给样例

**Comment by zepinglee** [comment]
> 原来样例就是偏的吗……我们没给样例

目前的格式是按照 http://www.law.tsinghua.edu.cn/publish/law/7024/2012/20120216153516317135347/20120216153516317135347_.html 的样例设计的，如果你们没给就按照这个格式吧

**Comment by Leojc** [comment]
> 
> 
> > 原来样例就是偏的吗……我们没给样例
> 
> 目前的格式是按照 http://www.law.tsinghua.edu.cn/publish/law/7024/2012/20120216153516317135347/20120216153516317135347_.html 的样例设计的，如果你们没给就按照这个格式吧

嗯嗯，多谢啦~
