### ISSUE TITLE
本科模板目录中“附录A”的“A”的字体不是非衬线

### ISSUE THREAD

**Issue by zdy023** [xueruini/thuthesis#542]
## 编译环境1

编译的系统：Manjaro 20.0 Lysia
TeX 发行版：TeX Live 2019
模板版本：v6.0.2 (master)
模板类型：bachelor

## 编译环境2

编译的系统：Windows 10
TeX发行版：TeX Live 2019
模板版本：v6.0.2 (release)
模板类型：bachelor

## 描述问题

《本科综合论文训练写作指南》第 2页要求目录中章节名都是非衬线字体，而模板编译出来附录处的字母“A”“B”都是衬线字体。后面的标题字体是没有问题的，只有目录中不对。

虽然法学院网站上17年的样例也是衬线字体，但是昨天格式审查有人这里被指出来了，所以想问一下这里应该如何调整。

截图：

![Screenshot_20200526_114419](https://user-images.githubusercontent.com/24731406/82858386-51601580-9f46-11ea-9543-ce70f4728f0f.png)

![mmexport1590464728898](https://user-images.githubusercontent.com/24731406/82858459-8704fe80-9f46-11ea-8d37-8c4d8bf8ed28.jpg)

**Comment by Harry-Chen** [comment]
@zepinglee 这就是自动化系的了…

**Comment by Harry-Chen** [comment]
对于 dev 分支的代码，把 https://github.com/xueruini/thuthesis/blob/dev/thuthesis.dtx#L2277
这里的 `\heiti` 改成 `\sffamily` 即可。

**Comment by Harry-Chen** [comment]
对于目前的 master 分支，修改下面的代码：
https://github.com/xueruini/thuthesis/blob/a86b0824da527268645571cc5fe3096d65a665b3/thuthesis.dtx#L2152-L2158

直接去掉这一段 if，改成 `\sffamily` 即可

**Comment by zepinglee** [comment]
参考 #431 ，我考虑两种方案：

1. 本科生的目录章标题的西文统一换成 sans serif，然而有可能别的院系老师可能要求 serif；

2. 保留目前的默认值，增加选项 `toc-chapter-style = times/arial` 供用户选择，比如：
```tex
\thusetup{
  toc-chapter-style = arial,
}
```

**Comment by zepinglee** [comment]
我又想了一下，感觉默认设为 Arial 更合理，

1. 虽然本科生《写作指南》关于目录章标题的格式只提到
> 目录从第 1 章开始，每 章标题用黑体小四号字

但是后面关于标题的格式要求：
<img width="658" alt="Screen Shot 2020-05-26 at 12 08 54 PM" src="https://user-images.githubusercontent.com/12290822/82859573-b79a6780-9f49-11ea-8e48-ee7e7647b524.png">

所以目录的内容跟原标题保持一致更合理；

2. 就标题本身而言，无衬线的 Arial 跟黑体的中文更搭配；

**Comment by zepinglee** [comment]
现在默认是 Arial 了

**Comment by xueruini** [comment]
之前加过一堆选项，`tocarialchapter`，就是这么来的。

后来 6.0 都删了。

**Comment by zepinglee** [comment]
> 之前加过一堆选项，`tocarialchapter`，就是这么来的。
> 
> 后来 6.0 都删了。

嗯，但是原来的几个选项不太正确。

**Comment by zdy023** [comment]
问题解决了，感激不尽
