### ISSUE TITLE
“关于学位论文使用授权的声明”和“中文摘要”之间没有预留空白页

### ISSUE THREAD

**Issue by toylsc** [xueruini/thuthesis#543]
## 编译环境
编译的系统：MacOS
TeX 发行版：MacTeX 2020
模板版本：v6.0.2
模板类型：doctor

## 描述问题
《研究生学位论文写作指南》第 3 页要求“中文封面”、“英文封面”、“关于学位论文使用授权的声明”三部分单面印刷，不加页码。从“中文摘要”开始各部分双面印刷，各部分之间不必留空白页。

而模板编译的结果是“关于学位论文使用授权的声明”和“中文摘要”之间没有留空白页，这意味着直接双面打印会导致“中文摘要”打印到“关于学位论文使用授权的声明”的背面，导致之后的内容也错位了。5.3.2 版本反而没有这个问题。

**Comment by zepinglee** [comment]
v6.0.2 确实有这个问题，但是目前 `dev` 分支已经解决了。

**Comment by zepinglee** [comment]
同 #504
