### ISSUE TITLE
英文，Author-year格式下，请问如何让文内引用中的页码不写在上标？

### ISSUE THREAD

**Issue by Revolverrr** [xueruini/thuthesis#544]
也就是说仍然使用natbib默认的格式。

例如`\citep[p. 106, content in square brackets in original]{hor2011}`，希望显示的效果如下（忽略字体）：
![image](https://user-images.githubusercontent.com/56210805/82921400-e98fe600-9faa-11ea-9de0-3b44d11a4cc0.png)

而不是：
![image](https://user-images.githubusercontent.com/56210805/82921593-20fe9280-9fab-11ea-8740-58dff1f32f94.png)

请问应该如何实现呀？谢谢！

**Comment by zepinglee** [comment]
研究生《写作指南》第 18 页：
<img width="669" alt="Screen Shot 2020-05-26 at 11 54 01 PM" src="https://user-images.githubusercontent.com/12290822/82922512-450ea380-9fac-11ea-85d9-36040ce1eece.png">

**Comment by Revolverrr** [comment]
> 研究生《写作指南》第 18 页：
> <img alt="Screen Shot 2020-05-26 at 11 54 01 PM" width="669" src="https://user-images.githubusercontent.com/12290822/82922512-450ea380-9fac-11ea-85d9-36040ce1eece.png">

喔，感谢提醒。不过我是本科生，只是本系允许用英文写。学校发的《写作指南》里只考虑了中文论文，好像仅对numeric格式下的文内引用作了要求（“在论文正文中引用了参考文献的部位，须用上标标注[参考文献序号]”）。在《参考文献著录格式》中的“英文文献著录规范”里，也只是列举了几种常用的格式（APA等等），没有更多要求。然后我使用的是APA格式，于是就觉得文内是不是也按APA来比较好……。

**Comment by Revolverrr** [comment]
啊 我自己会了 打扰了

**Comment by zepinglee** [comment]
APA 格式的参考文献需要 `apacite` 宏包，跟模板可能还有些兼容性问题。另外你是哪个系的？

**Comment by Revolverrr** [comment]
> APA 格式的参考文献需要 `apacite` 宏包，跟模板可能还有些兼容性问题。另外你是哪个系的？

我用的是自己魔改的`apa`宏包，暂时好像没出什么问题！我是哲学系的，允许写英文好像也就是今年的事，也没有提更多的格式要求（可能没怎么考虑这回事），只说得有个中文摘要。所以我就开始乱搞

**Comment by zepinglee** [comment]
这魔改能力也是厉害了！

外文系有自己的一套格式（#435 ），跟中文的有所区别。目前我实现了一半，还没推到 GitHub，其中如果用户设置 `degree=bachelor, language=english` 会按照外文系的格式。如果你们系页允许英文的话，这样似乎就有些不妥。建议你后续询问一下审查老师的详细格式要求，比如是否按照外文系的格式。

另外 author-year 引用的页码是在这里调整的：
https://github.com/xueruini/thuthesis/blob/dev/thuthesis.dtx#L3451-L3467

**Comment by Revolverrr** [comment]
1、啊，是因为apa太旧了，就改了一下文献列表的格式，应该没什么实质改动。我猜可能是因为用`\bibliographystyle{apa}`不需要调用额外的宏包，所以问题不大？

2、感谢提醒！我回头问一下老师。

3、哈哈谢谢，我就是把这里注释掉了，看来没搞错。
