### ISSUE TITLE
章与节间的间距有问题

### ISSUE THREAD

**Issue by shenyp09** [xueruini/thuthesis#57]
当在章标题下面没有文字直接开始本章第一节的时候，会出现间距变大的问题，如您给出的示例的第二章。

**Comment by alick9188** [comment]
@xueruini 之前研究有结果没？有没解决方案？

**Comment by xueruini** [comment]
sorry，没再研究这个问题了。。。

**Comment by thuFangZhang** [comment]
试了一下，写成以下代码就存在间距不对的问题：

\chapter{结论} % (fold)
\label{cha:conc}

部分结论（其实这个地方不想写内容）

\section{结论1} % (fold)
\label{sec:conc_conc}

而写成以下代码就没有间距问题：

\chapter{结论} % (fold)
\section{结论1} % (fold)
\label{sec:conc_conc}

也就是说，\chapter 后面不跟着label就没有问题，这样一个弱弱的解决方案就是 遇到这种情况 就不加 label 了...

**Comment by alick** [comment]
感谢 @thuFangZhang 启发！经过测试发现应该是 `\@chapter` 重定义时忘了 `\@afterheading` 的缘故。请测试 #102 中的修正版本。

**Comment by alick** [comment]
@shenyp09 
> 在仔细检查后发现，似乎每一级节标题见如果之间相连没有文字都存在间距过大的问题

是这样吗？我没感觉到……如果真有的话，我也不知道是什么缘故了……

**Comment by thuFangZhang** [comment]
@alick  经过测试 Texlive 2014 + xelatex / pdflatex ，章与节之间的距离改过来了。

同时，各级标题之间都没问题，没有前面说的 “似乎每一级节标题见如果之间相连没有文字都存在间距过大的问题”。

**Comment by xueruini** [comment]
👍
