### ISSUE TITLE
为什么Latex的1.5倍行距与word的1.5倍行距差别很大？

### ISSUE THREAD

**Issue by ewtahn** [xueruini/thuthesis#83]
thuthesis.cls中，  \@setfontsize\normalsize{12bp}{20bp} 是调整正文字体大小和行距的吧？按照1.5倍行距的定义，这里的20bp应该改成12+1.5*(12/2)=21bp 。结果发现比word中设置1.5倍行距要窄的多，是我理解有误么？

**Comment by fefe982** [comment]
是不是在 word 里打开了“对齐到网格线”? 这个选项默认是打开的。好像在段落属性里。

**Comment by ewtahn** [comment]
@fefe982 我设置了没什么效果。。问题是现在我不知道1.5倍应该是什么样子的了。。

**Comment by xueruini** [comment]
打印成pdf，比对实际效果。这两个系统的度量衡不是一一对应的。

**Comment by alick9188** [comment]
参考以下链接：

https://tex.stackexchange.com/questions/65849/confusion-onehalfspacing-vs-spacing-vs-word-vs-the-world
http://bbs.ctex.org/forum.php?mod=viewthread&tid=43334
http://yinguobing.com/latex-%E4%B8%AD%E7%9A%84%E8%A1%8C%E9%97%B4%E8%B7%9D/
https://tex.stackexchange.com/questions/13742/what-does-double-spacing-mean

**Comment by ewtahn** [comment]
@xueruini thank you

**Comment by ewtahn** [comment]
@alick9188 thank you,it helps
