### ISSUE TITLE
允许URL在横杠处折行

### ISSUE THREAD

**Issue by salviati6** [xueruini/thuthesis#84]
参考文献的URL太长且带大量横杠时，折行很难看（默认选项只在"/"和"."处折行），建议把
```latex
\RequirePackage{hyperref}
```
改成
```latex
\PassOptionsToPackage{hyphens}{url}\RequirePackage{hyperref}
```
允许在横杠处折行。

TeX.SX的相关问题：
http://tex.stackexchange.com/questions/3033/forcing-linebreaks-in-url

**Comment by alick9188** [comment]
嗯。不过我不确信这个应该写到缺省设置里。一个疑虑是连字符(hyphen)处断行会产生歧义（URL里有连字符，还是为断行而加的连字符）。另外，对于 URL 里一长串字母数字的情况也没有帮助，是不是对它也要特殊处理？

我个人的做法一般是尽量避免出现很长的 URL。当没有太多信息量时干脆不写，或者考虑 URL 缩短服务。

**Comment by salviati6** [comment]
由于URL中不能出现空格（只能用丑陋的%20表示），在网站URL用横杠代替空格还是蛮常见的。我也不想加EB/OL啊，但总是有些内容实在找不到纸质出处……不加入默认设置也有道理，也许在说明文档里面提一下就行了。

另外想问一下有没有让电子资源自动加[EB/OL]的方法？这个好像一直没有在thuthesis里实现，派生出来的seuthesis之类的倒是可以。

**Comment by alick9188** [comment]
On 03/03/2015 08:37 PM, Fang Zhang wrote:
> 由于URL中不能出现空格（只能用丑陋的%20表示），在网站URL用横杠代替空格还是蛮常见的。我也不想加EB/OL啊，但总是有些内容实在找不到纸质出处……不加入默认设置也有道理，也许在说明文档里面提一下就行了。
> 

嗯，有空时我在文档里加上说明。

> 另外想问一下有没有让电子资源自动加[EB/OL]的方法？这个好像一直没有在thuthesis里实现，派生出来的seuthesis之类的倒是可以。
> 

应该不难通过定制 thubib.bst 实现。或许可以从 seuthesis backport 过来。
新问题最好新开一个issue，方便追踪。

**Comment by alick9188** [comment]
自动加 [EB/OL] 在新issue里讨论吧
