### ISSUE TITLE
应使用 geometry 包重构有关页面尺寸的代码

### ISSUE THREAD

**Issue by leo-liu** [xueruini/thuthesis#85]
目前这部分代码很乱不说，对纸张大小的设置是直接用 `\special` 命令完成的：
```latex
\AtBeginDvi{\special{papersize=\the\paperwidth,\the\paperheight}}
\AtBeginDvi{\special{!%
      \@percentchar\@percentchar BeginPaperSize: a4
      ^^Ja4^^J\@percentchar\@percentchar EndPaperSize}}
```
而把几个输出后端的代码挤在一起，又不顾场合的用法，会造成混乱和错误。

例如[这里](http://www.newsmth.net/bbscon.php?bid=460&id=323314)报告的关于 tikz external 库出错的问题。

geometry 包能有效简化代码并处理这类问题。

**Comment by salviati6** [comment]
我是水木上的 bug reporter, 非常感谢 @Leo-Liu 老师的快速解答！

在问题解决之前，我还是老实关掉 \tikzexternalize 或者切回 pdflatex 好了。

**Comment by xueruini** [comment]
最开始是用geometry，后来由于某种原因（已经想不起来了），改成了目前的实现，由于一般不会遇到这里的问题，所以也一直没优化。理应改进。

2015-03-05 15:47 GMT+08:00 Leo-Liu <notifications@github.com>:

**Comment by Leo-Liu** [comment]
> 最开始是用geometry，后来由于某种原因（已经想不起来了），改成了目前的实现，由于一般不会遇到这里的问题，所以也一直没优化。理应改进。

日志清楚的话，看一下当时的 git 修改日志就行。看 geometry 当时出什么问题了——应该是没问题。

**Comment by alick9188** [comment]
git bisect 找到了移除 geometry 的提交：
{{{
3d5f581ab31a3735d0299dd13d99790c55a76af2 is the first bad commit
commit 3d5f581ab31a3735d0299dd13d99790c55a76af2
Author: Edward L. Fox <edyfox@gmail.com>
Date:   Sun Mar 12 12:56:44 2006 +0000

    Sync with separately commited files.
}}}
不过里面看不到为什么删除了...

**Comment by alick9188** [comment]
看了代码，感觉当时是为了加入对本科论文的支持，而当时本科/硕士的页面设置差别较小，因而可能直接写原始的 `\setlength` 比写两遍 `\RequirePackge` 经济。以上纯属猜测，如有雷同纯属巧合。

不过那些 `AtBeginDvi`语句是在 geometry 移除之后加上的，二者不是一回事。

**Comment by Leo-Liu** [comment]
无所谓了。
大概看了一下那次提交，改动非常大，\changes 记录就有，从 2006/06/27 到 2006/03/03，明显不是一次修改，只是合并提交了。
edyfox <https://github.com/edyfox> 在这次提交中把
fancyhdr、geometry、footmisc 的依赖都去掉了，也可能单纯是不喜欢多依赖项。
<https://github.com/edyfox>

在 2015年3月9日 下午9:16，Alick Zhao <notifications@github.com>写道：

**Comment by alick9188** [comment]
照我理解 dvips 编译方式已经不提供支持了，所以干脆移除引起问题的这几行好了。参见 #87 

@salviati6 请协助测试

**Comment by salviati6** [comment]
在 OS X Yosemite 10.10.2 + MacTeX + XeTeX 0.99991 环境下测试通过！

下午测试一下 Windows 环境，应该没问题。

**Comment by salviati6** [comment]
Windows 7 SP1 64-bit + MiKTeX 2.9 64-bit + XeTeX 0.99991 环境下测试通过。

**Comment by alick9188** [comment]
已合并修改到master分支。

@salviati6 可能的话，帮忙测一下非xelatex引擎下是否有什么问题。

**Comment by salviati6** [comment]
dvips 已经不支持了, 目前应该只支持 pdflatex 与 xelatex 了吧？ 我刚刚换到 xelatex, 之前一直都在用 pdflatex, 没有什么问题。 lualatex 从来没有用过……

**Comment by alick9188** [comment]
@salviati6 还有一个 latex+dvipdfmx 的方式。lualatex 没试过.

**Comment by Leo-Liu** [comment]
你们不打算测试 latex+dvipdfmx 了么？这个用的人可不少。

lualatex 目前的 ctex 版本还不支持，我打算在 TL2015 前发布 2.0 版本。

Fang Zhang <notifications@github.com>于2015年3月12日星期四写道：
> dvips 已经不支持了, 目前应该只支持 pdflatex 与 xelatex 了吧？ 我刚刚换到 xelatex, 之前一直都在用
pdflatex, 没有什么问题。 lualatex 从来没有用过……
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/w-19R3acG_BfbSdYFYD1eyhXiBB_6o6Mekp-rVB_JgaL8oCCQIRO_eAv9rTi2te0iBO-6dcOSJEcWvqxzzu7EoVhZaBsBBrKy0lGODh0Ocmxp2Dli3HEe3-yuf89vIAPOOAUEHHwNLc8uqGetI5h0c-YpICOJQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAi086D9ftgEu-7SCqPMWEz5JOZJAEW3ks5n0WfGgaJpZM4Dp3OX.gif
>

**Comment by Leo-Liu** [comment]
建议可以测试一下新版本的 ctex 宏包。
  https://ctex-kit.googlecode.com/svn/branches/ctex/
不过我这几天一直在写文档和整理代码。等文档大致写完了大概会在论坛上发个 RC 版本。

**Comment by Leo-Liu** [comment]
如果删掉相应的 \special 命令，有很少量的可能会因为安装 TeX 发行版时的设置不同，造成输出的 PDF 文件不是 A4 纸大小，而是大一些美国的 letterpaper，造成问题。但如果自己加 special 命令，则很不容易写正确。
用 geometry 是比较省力的做法，我不大清楚现在的顾虑是什么。还是说纯粹的多一事不如少一事？

**Comment by alick9188** [comment]
@Leo-Liu 目前支持 latex+dvipdfmx。刚测了一下工作正常。

ctex 有新 RC 版本时会尽量测一下。

我印象中 MikTeX, TeX Live 都可以比较方便的全局设置 A4 或 letter 纸张。

改用 geometry 的话，还是需要为本科/非本科设置两套参数，所以似乎简化不了多少代码...

**Comment by xueruini** [comment]
当前版本不少code都很丑陋，是有必要清理清理。

**Comment by alick9188** [comment]
reopen 了，geometry 的确可以让代码更易读和便于维护。

**Comment by alick** [comment]
:+1:

On Mon, Dec 14, 2015 at 2:37 AM, Ruini Xue <notifications@github.com> wrote:

> Closed #85 <https://github.com/xueruini/thuthesis/issues/85> via ddebf0c
> <https://github.com/xueruini/thuthesis/commit/ddebf0cfe00a3af7d09c34a524ebfdb449e414c2>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xueruini/thuthesis/issues/85#event-490724084>.
>



-- 
Regards,
Alick
