### ISSUE TITLE
xetex编译时数学模式字体中混有Computer Modern

### ISSUE THREAD

**Issue by salviati6** [xueruini/thuthesis#86]
为了解决中英文间的自动空格，从 pdflatex 尝试切换到了 xelatex, 然后就出现了一堆问题……xelatex 编译出来的 pdf 里面很多数学模式字体都是 Computer Modern 而不是 Times New Roman, 包括但不限于以下位置：
* 数学模式上下标中的数字、运算符与大写希腊字母
* \si (siunitx)中的\$
* pgfplots 图中的 tick label (可以通过设置 `/pgf/number format/assume math mode` 绕开数学模式检查)

用 Acrobat 查看 pdf 中的字体就能发现以上位置的字体全都是 CMR, 而用 pdflatex 编译时就都是 Nimbus Roman No9 L.

MWE:
```latex
% !TeX program = xelatex
\documentclass[doctor]{thuthesis}
\usepackage{siunitx}
\begin{document}
\begin{equation}
c_1^2 = a_1^2 + b_1^2
\end{equation}
$\Delta f (\xi), \Omega (\ell)$, \si{\$/MW}
\end{document}
```

**Comment by salviati6** [comment]
这个问题之前已经有人在 [Google Groups](http://permalink.gmane.org/gmane.comp.tex.thuthesis/292) 中提出来了，但是没有得到回应：

> **[thuthesis: 1041] 有没有方法把论文中所有数字都改为Times New Roman字体**
> 用的是最新的thuthesis模板，xelatex在Win 7下编译，正文中数字0-9的字体默认为Times New Roman, 但是公式中似乎不是，为了统一，有没有方法把论文中所有数字都改为Times New Roman字体啊，包括公式中的数字？

**Comment by alick9188** [comment]
请尝试在 thuthesis.cls 里引用 ctexbook 之前，给 fontspec 宏包指定  no-math 选项试试：
```
\PassOptionsToPackage{no-math}{fontspec}
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{ctexbook}}
```

也试下编译 main.tex 的输出是否正常。

**Comment by salviati6** [comment]
在 Windows 7 SP1 64-bit + MiKTeX 2.9 64-bit + XeTeX 0.99991 环境下用上面的 MWE 与我自己的 main.tex 均测试通过，用 Acrobat 查看字体，发现已经没有任何 CMR 了。

非常感谢您，现在总算可以安心切到 XeTeX 了！

**Comment by alick9188** [comment]
已经合并到master分支。如仍有问题或出现其它问题，请告知～
