### ISSUE TITLE
如何插入源代码呢？

### ISSUE THREAD

**Issue by ninjadq** [xueruini/thuthesis#88]
请问如何在thuthethis里面插入程序的源代码？

要可以引用写caption，还要能ref。

直接用verbatim的话不能达到效果

**Comment by alick9188** [comment]
On 03/16/2015 08:28 PM, Qian Deng wrote:
> 请问如何在thuthethis里面插入程序的源代码？
> 
> 要可以引用写caption，还要能ref。
> 
> 直接用verbatim的话不能达到效果
> 

使用 listings 宏包。

**Comment by ninjadq** [comment]
已用，非常好用，谢谢啦！
