### ISSUE TITLE
请测试 ctex 宏包第 2 版兼容性

### ISSUE THREAD

**Issue by leo-liu** [xueruini/thuthesis#92]
第 2 版的 `ctex` 宏包改动较多，且包含少量不兼容的变化，请测试 `thuthesis` 能否方便地迁移到新版本。以及文档说明是否清晰。

可以到[CTeX 论坛发布页](http://bbs.ctex.org/forum.php?mod=viewthread&tid=79955)下载并反馈意见。当然，欢迎直接到 [ctex-kit](https://github.com/CTeX-org/ctex-kit) 项目提出问题。

单目录测试包也可以从[百度云](http://pan.baidu.com/s/1i35p6XR)下载。

**Comment by alick9188** [comment]
我用水木上的 ctex-20150327-c69b3e9.test.zip 测试了一下，Linux 下会遇到不兼容，问题在于字体设置方面 ctex 没有了 `\ifCTEX@nofonts`，thuthesis 之前检测到它会加载示例的自定义字体配置文件`thufonts.def`。可以通过将 nofonts 选项设成 thuthesis 的选项，在加载 ctexbook 时做个判断实现兼容。

另外一点是 ctex 2.0 的 windows 字库带上了隶书和幼圆（还有雅黑），意味着 Windows 下用 thuthesis 排版本科论文（需要隶书字体）时不需要 nofonts 选项自定义字体了。

**Comment by leo-liu** [comment]
你们不要用 `ctex` 内部实现的宏，这种明摆着是往不兼容写的。
`thuthesis` 这种非常专门的文档类，还不如直接固定字体设置呢。

**Comment by alick9188** [comment]
我是支持固定字体设置的。不过不排除有人想用 Adobe 字体、方正字体啊。

**Comment by salviati6** [comment]
有人用Adobe字体通过格式审查么？预答辩时印的论文用了adobefonts, 被眼尖的老师直接指出“你这个字体不太对啊”，后来乖乖改回来了

**Comment by leo-liu** [comment]
固定设置，想用 Adobe 字体、方正字体的同学自己修改 `thufonts.def` 算了。
Adobe 字体和中易字体也要纠结，贵校要求也够无聊的。

**Comment by alick** [comment]
前面提到的引用ctex内部宏导致的不兼容问题，已经随着 #94 解决了。
