### ISSUE TITLE
xelatex与1.5版本的pdf兼容性问题

### ISSUE THREAD

**Issue by msmummy** [xueruini/thuthesis#93]
具体表现是当includegraphic使用的pdf图版本大于等于1.5时，会发生错误，不能正确显示图。

需要加入以下参数：

xe[la]tex -output-driver="xdvipdfmx -V 5" filename.tex

更多可参见http://tug.org/pipermail/xetex/2007-November/007883.html

**Comment by alick9188** [comment]
你的 TeX 发行版 (TeX Live? CTeX? MikTeX?)是什么版本？我在用的 TeX Live 2014 默认输出的 PDF 就是 1.5 版本的，应该没有这个问题。

**Comment by msmummy** [comment]
嗯，我看了一下，也是v5的。但是编译1.5版本确实会出错，我把pdf都转成1.4就好了。

**Comment by alick9188** [comment]
什么也是 v5 的？v5=PDF 1.5?

请提供你的 TeX 发行版版本信息，xelatex 版本信息 (`xelatex -v`)，最好也提供下出错的最小示例tex文件和图片。

**Comment by alick** [comment]
我测试了自己的一个 PDF 1.5 的图片，没有重现问题。
