### ISSUE TITLE
固定字体设置

### ISSUE THREAD

**Issue by alick** [xueruini/thuthesis#94]
承接 #92 中的讨论，开个issue专门讨论是否固定thuthesis中的字体设置。具体说来，就是默认只支持使用中易六种字体，对adobe字体等不再默认支持。有需要的用户，仍可通过手工修改 thufonts.def 文件来实现。

如果没人（三天内）提出反对意见，那么就认为是同意这个提议了。

**Comment by salviati6** [comment]
预答辩时老师提出的我用的Adobe字体“看上去不大对劲，可能无法通过格式审查”，但是这位老师并不是系里和图书馆负责审查格式的老师，也不知道用Adobe字体是否能在后者过审

**Comment by alick9188** [comment]
这个因人而异...

在 2015年4月1日 下午9:52，Fang Zhang <notifications@github.com>写道：

**Comment by xueruini** [comment]
就学位论文而言，基本上定死在sim系列了。

2015-04-01 22:01 GMT+08:00 Alick Zhao <notifications@github.com>:

**Comment by alick9188** [comment]
考虑实现吧。代码改动不多，主要是文档更新。
